### PR TITLE
fix(dx12): map composite alpha mode

### LINKED ISSUE #7108: DX12 with DirectComposition transparency not working
**Description**

Using DX12 backend to render into a DirectComposition Visual, alpha channel doesn't affect the render.

**Repro steps**

The repro can be found here, https://github.com/amrbashir/wgpu-dcomp-repro/blob/master/src/main.rs

It is adapted from a wgpu basic example and windows-rs DirectComposition example https://github.com/microsoft/windows-rs/blob/master/crates/samples/windows/dcomp/src/main.rs 

**Expected vs observed behavior**

I expected to be able to create semi-transparent colors using DirectComposition + wpgu but instead, I only get `Opaque` composite alpha mode.

**Extra materials**

This is DirectComposition FillRectangle

Image

This is wgpu rendering to same visual, using the same color and alpha

Image

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
OS: Windows 11
wpgu: 24
wgpu-backend: DX12
windows-rs: 0.58

### PR DESCRIPTION
**Pull request by amrbashir**
**Connections**
_Link to the issues addressed by this PR, or dependent PRs in other repositories_

closes #7108

**Description**
_Describe what problem this is solving, and how it's solved._

Fix wgpu alpha modes when using it with windows DirectComposition.

**Testing**
_Explain how this change is tested._

This PR was tested using the repro at https://github.com/microsoft/windows-rs/blob/91cfd289eeae05fa0bb6bdbe37a8426061f77c6e/crates/samples/windows/dcomp/src/main.rs

**Checklist**

- [X] Run `cargo fmt`.
- [X] Run `taplo format`.
- [X] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [X] Run `cargo xtask test` to run tests.
- [X] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu-hal/src/dx12/adapter.rs [hunk 1]
```diff
@@ -863,7 +863,13 @@ impl crate::Adapter for super::Adapter {
                 | wgt::TextureUses::COPY_SRC
                 | wgt::TextureUses::COPY_DST,
             present_modes,
-            composite_alpha_modes: vec![wgt::CompositeAlphaMode::Opaque],
+            composite_alpha_modes: vec![
+                wgt::CompositeAlphaMode::Auto,
+                wgt::CompositeAlphaMode::Inherit,
+                wgt::CompositeAlphaMode::Opaque,
+                wgt::CompositeAlphaMode::PostMultiplied,
+                wgt::CompositeAlphaMode::PreMultiplied,
```
Comment (cwfitzgerald) [inline wgpu-hal/src/dx12/adapter.rs]: This needs to be conditional on rendering to a DComp swapchain. Regular swapchains should only have `Opaque`

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]

**Review by cwfitzgerald — APPROVED** [review]
Nice, thanks!

**Comment by amrbashir** [comment]
apologies, had a missing `in` in change log entry
