### PR TITLE
[Naga msl-out] Add padding to end of structs. And run some textureSample CTS tests that now pass

### LINKED ISSUE #7803: textureSample CTS execution tests fail on Macos
**Description**
Running `textureSample` CTS execution tests fails on my M2 Macbook Pro

**Repro steps**

```
cargo xtask cts 'webgpu:shader,execution,expression,call,builtin,textureSample:*'
```

Same result in Firefox.

**Expected vs observed behavior**

The tests fail. With the `--debug` flag passed to the CTS runner, we can see that the incorrect samples have the values as if they were sampled from pixel 0,0

**Platform**
Current trunk. M2 Macbook pro. Sequoia 15.4.1

### PR DESCRIPTION
**Pull request by jamienicol**
**Connections**
Fixes #7803
Depends on #7807 

The deno changes are copied from #7709. If this lands first I'll remove the changes from that PR.

**Description**
See #7803 

Note I've only enabled the 1d tests to run. In higher dimensions we use more exotic texture formats, some of which fail. They also take a very long time to run, so there's probably a discussion to be had about whether that's desirable.

**Testing**
Added CTS test to run

**Squash or Rebase?**

Rebase

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by jamienicol** [comment]
Marking as draft until I fix the test failures

File: tests/tests/wgpu-gpu/shader/struct_layout.rs [hunk 1]
```diff
@@ -238,8 +238,7 @@ fn create_struct_layout_tests(storage_type: InputStorageType) -> Vec<ShaderTest>
                 &input_values,
                 &[0, 1, 2, 3, 4, 8, 9, 10, 11, 12],
             )
-            .header(header)
-            .failures(Backends::METAL),
```
Comment (jamienicol) [inline tests/tests/wgpu-gpu/shader/struct_layout.rs:242]: @cwfitzgerald This PR seems to fix these tests. Since you added them, thought you might have opinions on whether this fix is correct? It doesn't really seem the same as described in #5262

File: naga/tests/out/msl/spv-quad-vert.msl [hunk 2]
```diff
@@ -12,10 +12,12 @@ struct gl_PerVertex {
     float gl_PointSize;
     type_3 gl_ClipDistance;
     type_3 gl_CullDistance;
+    char _pad4[4];
 };
 struct VertexOutput {
     metal::float2 member;
     metal::float4 gl_Position;
+    char _pad2[65519];
```
Comment (jamienicol) [inline naga/tests/out/msl/spv-quad-vert.msl]: This seems incorrect and needs further investigation

Comment (jimblandy) [reply naga/tests/out/msl/spv-quad-vert.msl]: This is probably coming from [here](https://github.com/gfx-rs/wgpu/blob/65337894f609b536d0016fbabfea6324c5b98faf/naga/src/front/spv/function.rs#L543-L552):

```
                let ty = module.types.insert(
                    crate::Type {
                        name: None,
                        inner: crate::TypeInner::Struct {
                            members,
                            span: 0xFFFF, // shouldn't matter
                        },
                    },
                    span,
                );
```

Comment (jimblandy) [reply naga/tests/out/msl/spv-quad-vert.msl]: This "shouldn't matter" was introduced in 604e10e1 (2021-4-6):

```
commit 604e10e19b1f8ce284b5da14ce72d47b670f8832
Author: Dzmitry Malyshau <kvarkus@gmail.com>
Date:   Tue Apr 6 23:40:11 2021 -0400

    Rewrite IR to have member offsets, full structure span and alignment
```

Comment (jimblandy) [reply naga/tests/out/msl/spv-quad-vert.msl]: I filed #7807 to make the SPIR-V front end compute struct sizes and member offsets correctly.

Comment (jamienicol) [reply naga/tests/out/msl/spv-quad-vert.msl]: After rebasing on 7807 this is now a sensible number

**Comment by jamienicol** [comment]
Ready for review now

**Review by jimblandy — APPROVED** [review]

**Comment by jamienicol** [comment]
@crowlKats approved the exact same deno changes in #7709 , so I think we can go ahead and land this
