### PR TITLE
Gate DX12 mesh shader command signature initialization on device support.

### LINKED ISSUE #8296: STATUS_ACCESS_VIOLATION when requesting device for Intel iGPU on wgpu 27.0.1
**Description**
#8110 introduces a regression which produces a STATUS_ACCESS_VIOLATION crash when requesting a device for an Intel(R) Iris(R) Xe Graphics integrated graphics adapter.  The crash does not reproduce at 1f10d0ce8a25e69d2c5f7c4b45bb47d5a744c291, but does at 05cc6dca82fe5f5890299abf7cde6f1cd2907a26.

**Repro steps**
I can reproduce this by running `cargo run --bin wgpu-examples hello_triangle` with `WGPU_BACKEND` set to `dx12`.

**Expected vs observed behavior**
Should be able to request device without any crash (as worked in the previous commit on trunk).

**Extra materials**

Screenshot of relevant stack trace from windbg:

image

**Platform**

* Windows 11 (10.0.26100)
* Intel i9-13900H CPU
* Intel(R) Iris(R) Xe Graphics (driver version 32.0.101.6913)
    * This is the device that is having issues.
* NVIDIA RTX 2000 Ada Generation Laptop GPU
    * This continues to work without issues.

### PR DESCRIPTION
**Pull request by vorporeal**
**Connections**

Fixes #8296.

**Description**

Addresses crashes when initializing a DX12 device that lacks support for mesh shaders.

This conditions creation of the command signatures for indirect mesh shader dispatch on the device supporting mesh shaders.  The code here generally follows the patterns used in other backends (e.g.: Vulkan).

**Testing**

- Manually tested using `cargo run --bin wgpu-examples hello_triangle` (with `WGPU_ADAPTER_NAME` set to my Intel iGPU) that the `hello_triangle` example now runs properly.
- Manually tested using the `mesh_shader` example that mesh shaders still work with supported devices - set `WGPU_ADAPTER_NAME` to my dedicated GPU (which worked), and set it to my integrated GPU, which failed with `Adapter does not support required features for this example: Features { features_wgpu: FeaturesWGPU(EXPERIMENTAL_MESH_SHADER), features_webgpu: FeaturesWebGPU(0x0) }`.

**Squash or Rebase?**

Squash - will want to add a commit with changelog updates once we agree on impl.

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Review by inner-daemons — APPROVED** [review]
I've looked it over and it looks good to me. Just FYI you will probably have to create a PR to backport this to 27.0.

File: wgpu-hal/src/dx12/device.rs [hunk 1]
```diff
@@ -1371,47 +1380,54 @@ impl crate::Device for super::Device {
                     };
                     size_of_val(&first_vertex) + size_of_val(&first_instance) + size_of_val(&other)
                 };
-                Some(super::CommandSignatures {
-                    draw: Self::create_command_signature(
+
+                let draw_mesh = if desc.flags.contains(crate::PipelineLayoutFlags::MESH_SHADER) {
```
Comment (cwfitzgerald) [inline wgpu-hal/src/dx12/device.rs]: Instead of needing to pass this down as a flag, we should be able to check the wgpu-hal device for the currently enabled features

File: wgpu-hal/src/dx12/command.rs [hunk 2]
```diff
@@ -1401,9 +1404,12 @@ impl crate::CommandEncoder for super::CommandEncoder {
         self.prepare_dispatch([0; 3]);
         let cmd_list6: Direct3D12::ID3D12GraphicsCommandList6 =
             self.list.as_ref().unwrap().cast().unwrap();
+        let Some(command_signature) = self.shared.cmd_signatures.draw_mesh.as_ref() else {
```
Comment (cwfitzgerald) [inline wgpu-hal/src/dx12/command.rs]:
```suggestion
        let Some(ref command_signature) = self.shared.cmd_signatures.draw_mesh else {
```
Nit to keep this pattern in line with the rest of the codebase

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Thanks for taking this on! Some notes.

File: wgpu-hal/src/dx12/device.rs (hunk 1 above)
Comment (vorporeal) [reply wgpu-hal/src/dx12/device.rs]: Yes of course; I somehow missed (despite looking for it explicitly) that this function received `&self`.  Done.

**Comment by vorporeal** [comment]
PTAL - addressed comments and added changelog entry.

**Review by cwfitzgerald — APPROVED** [review]
Amazing, will backport and get this out
