### PR TITLE
[core] Make `poll(Wait)` not hang after bad command submission.

### LINKED ISSUE #5969: `Device::poll(Wait)` hangs after failed command submission
The test below hangs on Vulkan backends, waiting for a submission index of `1` No commands have been successfully submitted to the queue, so this fence value will never be signaled.

Speculation: We assign submission indexes before we know whether the submission will succeed, because we need to (or used to need to) mark each wgpu_core resource with its submission index before hal submission. We implement `Maintain::Wait` by getting the current fence value and then waiting for it to be signalled. I speculate that, when submission fails, we increment the fence value, but then never submit any commands that would signal that value, so a subsequent `Wait` will wait for a value that cannot be signalled unless some other thread submits work to that queue.

```rust
/// Submit a command buffer to the wrong device. A wait poll shouldn't hang.
#[gpu_test]
static WAIT_AFTER_BAD_SUBMISSION: GpuTestConfiguration =
    GpuTestConfiguration::new().run_async(wait_after_bad_submission);

async fn wait_after_bad_submission(ctx: TestingContext) {
    let (device2, queue2) =
        wgpu_test::initialize_device(&ctx.adapter, ctx.device_features, ctx.device_limits.clone())
            .await;

    let command_buffer1 = ctx.device.create_command_encoder(&<_>::default()).finish();
    // This should fail, since the command buffer belongs to the wrong
    // device.
    wgpu_test::fail(
        &device2,
        || {
            queue2.submit([command_buffer1]);
        },
        Some("doesn't match Device"),
    );

    // This should not hang.
    //
    // Specifically, the failed submission should not cause a new fence value to
    // be allocated that will not be signalled until further work is
    // successfully submitted, causing a greater fence value to be signalled.
    device2.poll(wgpu::Maintain::Wait);
}
```

### PR DESCRIPTION
**Pull request by jimblandy**
Add `wgpu_core::device::Device::last_successful_submission_index`,
which records the fence value that `Maintain::Wait` should actually
wait for. See comments for details.

Fixes #5969.

### CODE REVIEW

File: tests/tests/poll.rs [hunk 1]
```diff
@@ -125,3 +125,30 @@ static WAIT_OUT_OF_ORDER: GpuTestConfiguration =
...
+#[gpu_test]
+static WAIT_AFTER_BAD_SUBMISSION: GpuTestConfiguration =
+    GpuTestConfiguration::new().run_async(wait_after_bad_submission);
+
+async fn wait_after_bad_submission(ctx: TestingContext) {
+    let (device2, queue2) =
+        wgpu_test::initialize_device(&ctx.adapter, ctx.device_features, ctx.device_limits.clone())
+            .await;
+
+    let command_buffer1 = ctx.device.create_command_encoder(&<_>::default()).finish();
```
Comment (cwfitzgerald) [inline tests/tests/poll.rs]: Could we spell this type out

File: wgpu-core/src/device/queue.rs [hunk 2]
```diff
@@ -1062,7 +1062,7 @@ impl Global {
             let fence = fence_guard.as_mut().unwrap();
             let submit_index = device
                 .active_submission_index
-                .fetch_add(1, Ordering::Relaxed)
+                .fetch_add(1, Ordering::SeqCst)
```
Comment (cwfitzgerald) [inline wgpu-core/src/device/queue.rs:1072]: I still don't think this is any more correct, but not with thinking about the cost, so we can leave the change

**Review by cwfitzgerald — APPROVED** [review]
Nice cleanups in here, small nits

File: wgpu-core/src/device/queue.rs (hunk 2 above)
Comment (jimblandy) [reply wgpu-core/src/device/queue.rs:1072]: You're right, we need to make sure that submissions occur in order of increasing index, which means we need a lock on this entire thing. Using `SeqCst` here isn't good enough.

Comment (jimblandy) [reply wgpu-core/src/device/queue.rs:1072]: Filed as #5978
