### PR TITLE
hal/vulkan: Replace gpu-alloc by gpu-allocator

### LINKED ISSUE #5925: Switch the Vulkan backend from `gpu_alloc` to `gpu_allocator`.
It's what we use in the D3D12 backend.

Ideally, implement https://github.com/Traverse-Research/gpu-allocator/issues/235 before doing the switch to avoid changing the behavior too much.

### LINKED ISSUE #8533: Current GPU allocator for vulkan blocks transient textures and causes crash
As I've been testing on mobile devices, I've found that app would crash when using a `TextureUsages::TRANSIENT` texture with Vulkan.
Later investigations lead to the `gpu-alloc` crate [marking the `LAZILY_ALLOCATED` memory type as incompatible for everything](https://github.com/zakarumych/gpu-alloc/blob/649ca44f9d403f65b450185ca23627cd7da817f9/gpu-alloc/src/usage.rs#L127).
Despite it having a comment that saids `// Unsupported`, removing the if condition allows it to just work.

I would just like to know if we still intend to use this allocator for the next release or if #8158 can get in by then.

### PR DESCRIPTION
**Pull request by DeltaEvo**
**Connections**

Closes https://github.com/gfx-rs/wgpu/issues/5925
Closes https://github.com/gfx-rs/wgpu/issues/8533

**Description**

This is the allocator that is used for the dx12 backend and has
a simpler configuration than gpu-alloc.

This also brings the Device::generate_allocator_report feature to
the vulkan backend.

**Testing**

This has been running in productions since a few month on a
server doing offscreen rendering without any issues.
    
The AccelerationStructure part was not tested.

**Squash or Rebase?**

Rebase

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-hal/src/vulkan/device.rs [hunk 1]
```diff
@@ -1095,59 +1007,54 @@ impl crate::Device for super::Device {
...
+                linear: true, // Buffers are always linear
+                allocation_scheme: gpu_allocator::vulkan::AllocationScheme::GpuAllocatorManaged,
+            })
+            .inspect_err(|_| {
+                unsafe { self.shared.raw.destroy_buffer(raw, None) };
+            })?;
+
+        // FIXME: Remove this
+        if let Some(slice) = allocation.mapped_slice_mut() {
+            slice.fill(0);
```
Comment (DeltaEvo) [inline wgpu-hal/src/vulkan/device.rs]: Currently without this, some `webgpu:api,operation,command_buffer,copyTextureToTexture:copy_depth_stencil:format="stencil8"` [subcases fails](https://github.com/DeltaEvo/wgpu/actions/runs/16834892534/job/47691784286), it seems to tell me that there is either an issue with the BufferInitTracker machinery, or `vkMapMemory` has a side effect that I don't understand

Comment (DeltaEvo) [reply wgpu-hal/src/vulkan/device.rs]: Needs https://github.com/gfx-rs/wgpu/pull/8099, removing this hack and resolving for now

File: wgpu-hal/src/vulkan/adapter.rs [hunk 2]
```diff
@@ -2355,87 +2355,42 @@ impl super::Adapter {
...
+            } => {
+                // TODO: Would it be useful to expose the host size in memory hints
+                // instead of always using half of the device size?
+                let device_size = suballocated_device_memory_block_size;
+                let host_size = device_size.start / 2..device_size.end / 2;
+
+                gpu_allocator::AllocationSizes::new(device_size.start, host_size.start)
+                    .with_max_device_memblock_size(device_size.end)
+                    .with_max_host_memblock_size(host_size.end)
+            }
```
Comment (Wumpf) [inline wgpu-hal/src/vulkan/adapter.rs]: let's move this out and share the exact same allocator creation code with DX12. No reason not to as far as I can tell. That way we have less backend differences and/or make them more visibile

**Review by Wumpf — COMMENTED** [review]
Looking great! Should add a changelog entry for that.

I'd also like to have a brief check with the revised [benchmark framework](https://github.com/gfx-rs/wgpu/pull/8511). But we don't have to hold it up on that, eager to finally land this so we have less variance in that area. Since that's a pretty consequential change I'd also like to check with at least one more maintainer :)

File: wgpu-hal/src/vulkan/adapter.rs [hunk 3]
```diff
@@ -2355,87 +2355,42 @@ impl super::Adapter {
...
+        // TODO: the allocator's configuration should take hardware capability into
+        // account.
+        const MB: u64 = 1024 * 1024;
+        let allocation_sizes = match memory_hints {
+            wgt::MemoryHints::Performance => gpu_allocator::AllocationSizes::new(128 * MB, 64 * MB)
+                .with_max_device_memblock_size(256 * MB)
+                .with_max_host_memblock_size(128 * MB),
+            wgt::MemoryHints::MemoryUsage => gpu_allocator::AllocationSizes::new(8 * MB, 4 * MB)
+                .with_max_device_memblock_size(64 * MB)
+                .with_max_host_memblock_size(32 * MB),
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/adapter.rs]: Lets give these constants names, so the readers of this code can clearly wee what each number means, without needing to read gpu-allocator's documentation

File: wgpu-hal/src/vulkan/adapter.rs [hunk 4]
```diff
@@ -2355,87 +2355,42 @@ impl super::Adapter {
...
+            wgt::MemoryHints::Manual {
+                suballocated_device_memory_block_size,
+            } => {
+                // TODO: Would it be useful to expose the host size in memory hints
+                // instead of always using half of the device size?
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/adapter.rs]: Could you file a followup issue about this and link it in the comment?

File: wgpu-hal/src/vulkan/adapter.rs (hunk 2 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/adapter.rs]: +1

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Some small comments, but then lets do this!

File: wgpu-hal/src/vulkan/adapter.rs (hunk 2 above)
Comment (DeltaEvo) [reply wgpu-hal/src/vulkan/adapter.rs]: Done

File: wgpu-hal/src/vulkan/adapter.rs (hunk 3 above)
Comment (DeltaEvo) [reply wgpu-hal/src/vulkan/adapter.rs]: Didn't do it, deduplicating this code with the dx12 backend required me to create a type and those are now assigned to named fields.

Let me know if you still think I should create constants for those.

File: wgpu-hal/src/vulkan/adapter.rs (hunk 4 above)
Comment (DeltaEvo) [reply wgpu-hal/src/vulkan/adapter.rs]: Done https://github.com/gfx-rs/wgpu/issues/8625

File: wgpu-hal/src/lib.rs [hunk 5]
```diff
@@ -381,6 +381,107 @@ pub enum DeviceError {
...
+            }
+        }
+    }
+}
+
+// A copy of gpu_allocator::AllocationSizes, allowing to read the configured value for
+// the dx12 backend, we should instead add getters to gpu_allocator::AllocationSizes
+// and remove this type.
+// https://github.com/Traverse-Research/gpu-allocator/issues/295
+#[allow(dead_code)] // may be unused on some platforms
```
Comment (cwfitzgerald) [inline wgpu-hal/src/lib.rs]: Could this be `#[cfg_attr(not(any(dx12, vulkan)), expect(dead_code))]`

**Review by cwfitzgerald — APPROVED** [review]
I've got a nit and this needs to be rebased/merged with main to pick up the new CI, but this is G2G otherwise!

File: wgpu-hal/src/lib.rs (hunk 5 above)
Comment (DeltaEvo) [reply wgpu-hal/src/lib.rs]: Done !
