### PR TITLE
Simplify features

### LINKED ISSUE #1390: Unexpected validation warnings
I keep getting these two validation warnings for even the simplest of shaders. The code does run (no crash or panic).

This is on Win10 with Intel Graphics (things crash if enable the NVida GPU, but that's a different issue). Using wgpu-native from master (naga 25). LunarSDK 1.2.176.1 (05-May-2021). Shaders are provided to wgpu in WGSL.

ImageMSArray capability:
```
VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-01091 (0xa7bb8db6)] : Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x14f78a6dfe8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (ImageMSArray) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
object info: (type: DEVICE, hndl: 0x14f78a6dfe8)
```

InterpolationFunction capability:
```
VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-01091 (0xa7bb8db6)] : Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x14f78a6dfe8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (InterpolationFunction) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
object info: (type: DEVICE, hndl: 0x14f78a6dfe8)
```

Also seeing this from time to time (poolSizeCount must be greater than 0):
```
VALIDATION [VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength (0x8e5726c)] : Validation Error: [ VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength ] Object 0: handle = 0x1fb7749e588, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8e5726c | vkCreateDescriptorPool: parameter pCreateInfo->poolSizeCount must be greater than 0. The Vulkan spec states: poolSizeCount must be greater than 0 (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength)
object info: (type: DEVICE, hndl: 0x1fb7749e588)
```

### PR DESCRIPTION
**Pull request by kvark**
**Connections**
Fixes #1390
Makes vertex writable storage optional (native-only for now)
Fixes the follow-up to #891 

**Description**
Refactors the code so that adding new features and maintaining current ones is much easier.
Refactors the way missing features are checked and reported, DRY way.

**Testing**
Not really tested

### CODE REVIEW

File: wgpu-core/src/device/mod.rs [hunk 1]
```diff
@@ -342,7 +342,6 @@ impl<B: GfxBackend> Device<B> {
                         spv::Capability::Image1D,
                         spv::Capability::SampledCubeArray,
                         spv::Capability::ImageCubeArray,
-                        spv::Capability::ImageMSArray,
```
Comment (kvark) [inline wgpu-core/src/device/mod.rs:345]: this turns out to be multisampled storage textures, we don't need them (at least right now)

File: wgpu-types/src/lib.rs [hunk 2]
```diff
@@ -526,6 +526,15 @@ bitflags::bitflags! {
...
         const STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING = 0x0000_0010_0000_0000;
+        /// Enables bindings of writable storage buffers and textures visible to fragment shaders.
+        ///
+        /// Note: some (tiled-based) platforms do not support fragment shaders with any side-effects.
+        ///
+        /// Supported Platforms:
+        /// - All
+        ///
+        /// This is a native-only feature.
+        const FRAGMENT_WRITABLE_STORAGE = 0x0000_0020_0000_0000;
```
Comment (cwfitzgerald) [inline wgpu-types/src/lib.rs:537]: While we're here we should also add VERTEX_WRITABLE_STORAGE.

File: wgpu-core/src/instance.rs [hunk 3]
```diff
@@ -453,11 +458,11 @@ impl<B: GfxBackend> Adapter<B> {
         // Check features that are always needed
         let wishful_features = hal::Features::ROBUST_BUFFER_ACCESS
             | hal::Features::VERTEX_STORES_AND_ATOMICS
```
Comment (cwfitzgerald) [inline wgpu-core/src/instance.rs:460]: I thought webgpu vert shaders had to be pure (see my other comment)

File: wgpu-core/src/instance.rs [hunk 4]
```diff
@@ -453,11 +458,11 @@ impl<B: GfxBackend> Adapter<B> {
...
-            | hal::Features::FRAGMENT_STORES_AND_ATOMICS
             | hal::Features::NDC_Y_UP
             | hal::Features::INDEPENDENT_BLENDING
             | hal::Features::SAMPLER_ANISOTROPY
-            | hal::Features::IMAGE_CUBE_ARRAY;
+            | hal::Features::IMAGE_CUBE_ARRAY
+            | hal::Features::SAMPLE_RATE_SHADING;
```
Comment (cwfitzgerald) [inline wgpu-core/src/instance.rs:465]: These all should likely be candidates for downlevel features. Don't need to do anything about these now, I'll file an issue to follow up.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]

File: wgpu-core/src/resource.rs [hunk 5]
```diff
@@ -266,8 +266,8 @@ pub enum CreateTextureError {
     InvalidMipLevelCount(u32),
     #[error("The texture usages {0:?} are not allowed on a texture of type {1:?}")]
     InvalidUsages(wgt::TextureUsage, wgt::TextureFormat),
-    #[error("Feature {0:?} must be enabled to create a texture of type {1:?}")]
-    MissingFeature(wgt::Features, wgt::TextureFormat),
+    #[error("Texture format {0:?} can't be used")]
```
Comment (cwfitzgerald) [inline wgpu-core/src/resource.rs:269]: nit:
```suggestion
    #[error("Texture format {0:?} can't be used due to a missing feature")]
```

**Review by cwfitzgerald — APPROVED** [review]
One nit, but otherwise LGTM

File: wgpu-core/src/resource.rs (hunk 5 above)
Comment (kvark) [reply wgpu-core/src/resource.rs:269]: Since the actual `MissingFeatures` is the source for this, it should already say that a feature is missing. I haven't double-checked the final look of this, but we can follow-up and fix it.

**Comment by kvark** [comment]
Thank you for rocket-fast reviews!
bors r=cwfitzgerald
