### PR TITLE
naga: Add support for textureQueryLevels to GLSL parser

### LINKED ISSUE #6393: Naga doesn't recognize GLSL 'textureQueryLevels' function
When processing a GLSL shader that calls `textureQueryLevels`, Naga fails.

```glsl
// test.glsl
#version 460

layout (set = 1, binding = 1) uniform texture2D some_texture;

void main() {
    int levels = textureQueryLevels(some_texture);
}
```

Command:
`naga test.frag --input-kind glsl --shader-stage frag`

Result:
```
error: Unknown function 'textureQueryLevels'
  ┌─ test.frag:6:18
  │
6 │     int levels = textureQueryLevels(some_texture);
  │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The same error is present when using Naga as a Rust crate.

Adding `#extension GL_ARB_texture_query_levels : enable` to the source doesn't make a difference.

### PR DESCRIPTION
**Pull request by magcius**
**Connections**
Fixes #6393.

**Description**
Adds support for the textureQueryLevels function.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: naga/src/front/glsl/builtins.rs [hunk 1]
```diff
@@ -292,6 +292,29 @@ pub fn inject_builtin(
...
+                    class,
+                };
+
+                declaration
+                    .overloads
+                    .push(module.add_builtin(vec![image], MacroCall::TextureQueryLevels))
+            };
+
+            texture_args_generator(
+                TextureArgsOptions::SHADOW | TextureArgsOptions::MULTI | variations.into(),
```
Comment (teoxoy) [inline naga/src/front/glsl/builtins.rs]: There don't seem to be overloads for multisampled textures.

Comment (magcius) [reply naga/src/front/glsl/builtins.rs]: Nice catch. I indeed copied this from above and didn't realize that MULTI here referred to multi-sampled textures.

**Review by teoxoy — APPROVED** [review]
LGTM, thanks!
