### PR TITLE
[metal] arm64_32 (ILP32/watchOS) support

### LINKED ISSUE #9406: Support arm64_32 (ILP32) target — watchOS on Apple Watch6/7/8/SE2
**Description**
wgpu-native on watchOS arm64_32 (ILP32 — `sizeof(long) == sizeof(void*) == 4`). We have the full WebGPU pipeline working: WGSL compilation via naga, compute dispatch, render pipeline, 8 indirect draws, and texture-to-buffer readback — validated on both Apple Watch Series 10 (arm64/S9) and Apple Watch SE2 (arm64_32/S6).

After rebasing to **wgpu-native v29** (which uses `objc2-metal`), the original enum representation and ObjC caching issues from v27's `metal-rs`/`objc` crates are eliminated. Three wgpu-hal patches remain.

arm64_32 is Apple's unique ABI: ARM64 instruction set with 32-bit pointers/long/size_t. Used by Apple Watch Series 4–9, SE1–SE2, and Ultra 1 (~100M devices).

**Repro steps**

Build wgpu-native v29 for `arm64_32-apple-watchos` and run any WebGPU workload that uses texture-to-buffer copies:

1. `cargo +nightly build -Z build-std=std,panic_abort --target arm64_32-apple-watchos --release --features "wgsl,metal"`
2. Create a render pipeline, render to a texture, copy texture to buffer via `wgpuCommandEncoderCopyTextureToBuffer`
3. Call `wgpuCommandEncoderFinish`

**Expected vs observed behavior**

*Expected*: The WebGPU pipeline runs identically to arm64 (LP64).

*Observed* (on wgpu v29 with `objc2-metal`): Three issues remain after the v27→v29 migration resolved the enum/ObjC problems:

1. **`KERN_INVALID_ADDRESS at 0x50` in AGXMetalS4 during `copyFromTexture:toBuffer:`** — The A13/S6 GPU driver crashes when blitting from `MTLStorageMode::Private` textures on ILP32. All arguments are valid (verified with crash-address-encoded probes — encoder, texture, buffer all non-null; origin, extent, bytesPerRow all correct). The native Swift Metal implementation that works on the same hardware uses `MTLStorageMode::Shared`. Fix: use Shared storage on `target_pointer_width = "32"` — Apple's unified memory architecture makes this equally performant.

2. **Driver instability with `MTLMutability` hints** — After the Shared storage fix, setting mutability hints on pipeline buffer descriptors causes intermittent driver instability on the S6 GPU. Conservative fix: disable `supports_mutability` on `target_pointer_width = "32"`.

3. **`CGFloat` is `f32` on ILP32** — `objc2-metal`'s `CGSize::new()` expects `CGFloat`, which is `f32` on arm64_32 (not `f64`). One call site in `wgpu-hal/src/metal/surface.rs` passes `f64`. Fix: `as _` instead of `as f64`.

4. **`Metal.framework` not in watchOS SDK** — `objc2-metal` uses `#[link(name = "Metal", kind = "framework")]` but the watchOS SDK doesn't ship Metal.framework stubs (Metal is available at runtime only). Workaround: `-undefined dynamic_lookup` linker flag. Proper fix would be in `objc2-metal` (weak linking or runtime loading on watchOS).

**Extra materials**

Patches needed (against wgpu v29 / `objc2-metal`):

| # | Repo | Change | Status |
|---|------|--------|--------|
| 1 | ~~gfx-rs/metal-rs~~ | ~~`#[repr(u64)]` → `#[repr(usize)]`~~ | **Not needed on v29** — `objc2-metal` handles this correctly |
| 2 | ~~SSheldon/rust-objc~~ | ~~`AtomicUsize` → `AtomicPtr`~~ | **Not needed on v29** — `objc2` handles this correctly |
| 3 | gfx-rs/wgpu | `MTLStorageMode::Shared` for textures on `target_pointer_width = "32"` | [PR #9411](https://github.com/gfx-rs/wgpu/pull/9411) |
| 4 | gfx-rs/wgpu | Disable `supports_mutability` on `target_pointer_width = "32"` | [PR #9411](https://github.com/gfx-rs/wgpu/pull/9411) |
| 5 | gfx-rs/wgpu | `CGFloat` fix in `surface.rs` (`as f64` → `as _`) | [PR #9411](https://github.com/gfx-rs/wgpu/pull/9411) |
| 6 | madsmtm/objc2 | `Metal.framework` linking on watchOS (no SDK stubs) | [Issue #835](https://github.com/madsmtm/objc2/issues/835) |

Additionally, `wgpu-native` itself needs watchOS target support (bindgen SDK paths in `build.rs`, `target_os = "watchos"` cfg gates) — these are wgpu-native patches, not wgpu-core/hal.

**Testing**

Validated on physical hardware with wgpu-native v29 + `objc2-metal`:
- Apple Watch SE2 (arm64_32, S6/A13, watchOS 11.6): all probes pass, 0 crashes ✅
- Apple Watch Series 10 (arm64, S9/A15, watchOS 26.4): all probes pass, 0 crashes ✅

**Platform**
Building on macOS 26.4 with Rust nightly, Xcode 26, targeting watchOS 11+ (Apple Watch 6/SE2, A13 equivalent) and watchOS 26 (Apple Watch 10, A15 equivalent). Cross-checked on iPhone XS, iPhone 12, macOS 26.4, and tvOS 26.4.

### PR DESCRIPTION
**Pull request by matthargett**
## Connections
Closes https://github.com/gfx-rs/wgpu/issues/9406

## Description

Three fixes to make the Metal backend work on arm64_32 (Apple Watch watchOS, ILP32 ABI where `sizeof(long) == sizeof(void*) == 4`).

### 1. Use `MTLStorageMode::Shared` for textures on arm64_32
The AGXMetalS4 driver (A13/S6 GPU) crashes with `KERN_INVALID_ADDRESS at 0x50` during `copyFromTexture:toBuffer:` on `MTLStorageMode::Private` textures on ILP32. The native Swift Metal implementation that works on the same hardware uses Shared storage for render textures. Apple's unified memory architecture makes Shared equally performant for GPU access.

Gated behind `cfg!(target_pointer_width = "32")` — zero effect on 64-bit.

### 2. Disable buffer mutability hints on arm64_32
The AGXMetalS4 driver exhibits instability when `MTLMutability` hints are combined with Shared storage mode. Conservative disable on 32-bit targets. Can be re-enabled per-device with broader test coverage.

### 3. Fix `CGFloat` type in `surface.rs`
`CGFloat` is `f64` on LP64 but `f32` on ILP32. `CGSize::new()` was hardcoded to `as f64`, which fails to compile on arm64_32. Changed to `as _` to infer the correct type.

## Testing

Validated on physical hardware with wgpu-native v29:
- Apple Watch SE2 (arm64_32, S6/A13, watchOS 11.6): full pipeline passes — WGSL→MSL via naga, compute dispatch, render pipeline, 8 indirect draws, texture-to-buffer readback ✅
- Apple Watch Series 10 (arm64, S9/A15, watchOS 26.4): no regressions ✅

### CODE REVIEW

**Comment by matthargett** [comment]
CI fail looks unrelated:
error: failed to load source for dependency `libtest-mimic`

Caused by:
  Unable to update https://github.com/cwfitzgerald/libtest-mimic.git?rev=9979b3c

Caused by:
  revspec '9979b3c' not found; class=Reference (4); code=NotFound (-3)

**Comment by inner-daemons** [comment]
Related article since I was interested in this:
<https://www.phoronix.com/news/GCC-May-Deprecate-ARM64-ILP32>

At the end of that it mentions that GCC later deprecated this.

Also, it looks like this is an architecture used exclusively for Apple Watches where the registers are 64bit but the pointers are 32bit. I also think that newer apple watches moved away from this, since [there is a aarch64 watchos target triple](https://doc.rust-lang.org/nightly/rustc/platform-support.html), and this target is tier 2 whereas arm64_32 is tier 3.

**Comment by matthargett** [comment]
> Related article since I was interested in this: https://www.phoronix.com/news/GCC-May-Deprecate-ARM64-ILP32
> 
> At the end of that it mentions that GCC later deprecated this.

I can understand why: Apple ecosystem almost exclusively uses LLVM/clang/swift, so it would make sense for GCC to drop the maintenance overhead.

> Also, it looks like this is an architecture used exclusively for Apple Watches where the registers are 64bit but the pointers are 32bit. I also think that newer apple watches moved away from this, since [there is a aarch64 watchos target triple](https://doc.rust-lang.org/nightly/rustc/platform-support.html), and this target is tier 2 whereas arm64_32 is tier 3.

yes, Apple Watch 9 (Ultra 2, SE 3) and newer are now on pure arm64, and Apple Watch 6/7/8/SE2 are the arm64_32 ABI which are still supported in watchOS 26. as I mentioned in the issue text, I was testing on Apple Watch SE2 (arm64_32 / A12) and Apple Watch 10 (arm64 / A15). That's still ~100 million devices, but also some of these issues I've supplied patches that should affect *any* Apple 32-bit platform. I personally want my WebGPU-oriented app to reach more of the majority of the ~170M active devices, including users who have hand-me-down devices. 

FWIW, the A12-derived GPU (and it's Metal) in the arm64_32 watchOS 26 watches is surprisingly capable. Happy to include a demo video, if that's helpful.

**Comment by inner-daemons** [comment]
Oh, I'm not at all trying to argue that this is bad. Just throwing this out there. And yeah, I figured people were using clang anyway.

File: wgpu-hal/src/metal/device.rs [hunk 1]
```diff
@@ -521,6 +521,14 @@ impl crate::Device for super::Device {
...
             {
                 MTLStorageMode::Memoryless
+            } else if cfg!(target_pointer_width = "32") {
+                // On arm64_32 (watchOS ILP32), the AGXMetalS4 driver (A13/S6 GPU)
+                // crashes in copyFromTexture:toBuffer: on Private textures — null
+                // deref at offset 0x50 in the driver's internal texture state. Use
+                // Shared storage which works correctly on Apple's unified memory
+                // architecture and matches what native Swift Metal code uses on
+                // these devices.
+                MTLStorageMode::Shared
```
Comment (inner-daemons) [inline wgpu-hal/src/metal/device.rs:531]: This is an interesting bug, is it documented anywhere?

**Review by inner-daemons — APPROVED** [review]
LGTM, nothing too controversial here.

File: wgpu-hal/src/metal/device.rs (hunk 1 above)
Comment (matthargett) [reply wgpu-hal/src/metal/device.rs:531]: Not that I'm aware of. There's a couple of reasons this amazing capability of these Apple Watch devices are shrouded:
* the feature/capability flags will say a feature isn't available, but the MSL will actually just work. before I ported wgpu, I tested Metal exhaustively to figure out what *actually* works. This was kicked off by seeing the Memoji app on my child's Apple Watch 9 and realizing the functionality it implied.
* if you try to do some of these MSL features in the simulator, you'll get a hard abort or it just won't work. I'm guessing most people (very reasonably) give up.
* some features, like ASTC HDR textures, work intermittently (shows magenta sometimes) on Apple Watch 6/SE2, but works fine on Apple Watch 9 and later. I haven't pinned down why, but again I'm assuming this would ward off most mildly curious app/3D developers.

This is probably a good conference/meetup talk to commoditize this hard-won knowledge, happy to apply if anyone has suggestions on a good venue!

File: wgpu-hal/src/metal/device.rs [hunk 2]
```diff
@@ -521,6 +521,14 @@ impl crate::Device for super::Device {
                 && self.shared.private_caps.supports_memoryless_storage
             {
                 MTLStorageMode::Memoryless
+            } else if cfg!(target_pointer_width = "32") {
+                // On arm64_32 (watchOS ILP32), the AGXMetalS4 driver (A13/S6 GPU)
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/device.rs:525]:
```suggestion
                // There are no Apple OSes that support both 32bit applications and Metal,
                // so this branch is guaranteed to be just be ILP32 devices.
                //
                // On arm64_32 (watchOS ILP32), the AGXMetalS4 driver (A13/S6 GPU)
```

Comment (cwfitzgerald) [reply wgpu-hal/src/metal/device.rs:525]: Lets actually give `cfg!(target_pointer_width = "32")` a useful name like `let is_watchos_isp32` or something and use it everywhere here.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
As this PR is small and self-justifying, we can go forward with this.

However I can tell that the description, originating issue, comments, and changes themselves are LLM generated. While we do not ban LLM contributions, we do expect that we're talking to a person not an LLM. Please in the future disclose what parts of comments and descriptions etc are being generated with an LLM. This will help us communicate better and will help you learn more.

**Comment by matthargett** [comment]
> As this PR is small and self-justifying, we can go forward with this.

yay!

> However I can tell that the description, originating issue, comments, and changes themselves are LLM generated. While we do not ban LLM contributions, we do expect that we're talking to a person not an LLM. Please in the future disclose what parts of comments and descriptions etc are being generated with an LLM. This will help us communicate better and will help you learn more.

While I did use Claude to help format the issue and PR description based on project norms, all of my comment replies in this PR were written by me (usually in the GitHub app on my phone) like this one. check my other OSS  contributions from the last ~30 years and you'll probably see the consistency. I know that OSS maintainership can be challenging, and there may be tribal knowledge I'm not aware of, so I try to have a positive tone and an open mind when wading into a new project/ecosystem :) 

I'm happy to hop on a video call (or meet folks in the SF Bay Area) if that's helpful. I am a real person who has been programming for over 40 years since the TI-99, and have been a Principal Engineer for the last 10 years of my career. I understand the concern and hesitancy, and appreciate the reasons behind the push back :)

File: wgpu-hal/src/metal/device.rs (hunk 2 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/metal/device.rs]: This isn't hasn't been addressed

**Review by cwfitzgerald — APPROVED** [review]
Thanks!
