### PR TITLE
[hal/vk] Rework Submission and Surface Synchronization

### LINKED ISSUE #5559: Vulkan Swapchain and Submit Synchronization Incorrect
We are currently using a single ping-pong semaphore (I'm calling this set of two semaphores a "relay semaphore") for all of our synchronization between acquire/present and between submissions. This is wrong for multiple reasons.

First using the same relay semaphore for both the submit -> present barrier and the submit -> submit barrier means that a single semaphore is being waited on twice. The act of waiting on a semaphore also resets the semaphore, so waiting on a single semaphore twice results in undefined behavior.

Second we are using the same relay semaphore for all acquire -> submit -> present cycles. This would be fine if we could guarantee that the previously used submit had finished its wait and the semaphore was reset by the time we scheduled the following acquire, but we can't. We need to have N relay semaphores, one per acquire cycle, until we can prove that the least-recently-used semaphore is finished being used.

I have provided the diagram of how submission synchronization needs to work with lines. Blue lines are swapchain relay semaphores (one set per frame). Orange lines are submit -> submit relay semaphore (a single one on the device.

```mermaid
flowchart LR
    A1[Acquire 1] --> S1[Submit 1]
    S1 --> P1[Present 1]
    S1 --> S21

    A2[Acquire 2] --> S21[Submit 2]
    S21 --> S22[Submit 3]
    S22 --> P2[Present 2]
    S22 --> S3[Submit 4]
    S3 --> S4
    
    A3[Acquire 3] --> S4[Submit 5]
    S4 --> P3[Present 3]

    subgraph Frame 3
        A3
        S4
        P3
    end

    subgraph Free Submission
        S3
    end

    subgraph Frame 2
        A2
        S21
        S22
        P2
    end

    subgraph Frame 1
        A1
        S1
        P1
    end

    linkStyle 2,4,6,7 stroke:#ffa600,whoops;
    linkStyle 0,1,3,5,8,9 stroke:#019297,whoops;
```

Possibly related:
- #5491 
- #5374
- #4919 
- #3452

### LINKED ISSUE #5693: Submitting multiple command encoders per frame causes hang on Vulkan
**Description**
Frames hanging for 5-10 seconds (presumably until timeout).
I bisected the issue and found it was introduced in #4967.

Possibly related to https://github.com/gfx-rs/wgpu/issues/5662

**Repro steps**
It only happens for me when submitting multiple command encoders with render passes in a single frame. 
I don't have a minimal reproduction yet, but I wanted to share in case anyone else has encountered the same issue. 

**Platform**
Ubuntu 22.04, nvidia 4090 - 535.86.10

### LINKED ISSUE #5828: FIFO on Vulkan showing old frames on high refresh rate monitors
**Description**
FIFO and FIFO_RELAXED for Vulkan are displaying old frames out of order, causing jitter. This happens if my monitor is set to 144hz, but if I lock it to 60 in windows it doesn't happen. I found this while working on my Bevy game, and was able to reproduce it in the Boids example. The Bevy reproduction even shows the frame count rendered on screen and you can see it go 3317, 3319, 3321, 3320. In the Boids gif attached below, it goes 1,2,3,4,3,5, no skipping a frame outright. 

**Repro steps**
Run Boids example. 
It can be harder to tell vs normal frame pacing issue, so it can make it easier to record and review to footage frame by frame

**Expected vs observed behavior**
Expected: To not see a frame repeated after a newer one has been shown.
Observed: Frames going backwards.

**Extra materials**
Old_frame
Old_frame_3
Trying to find other people running into this issue and I found this. https://forums.blurbusters.com/viewtopic.php?t=13358. 0 idea if it's useful.

**Platform**
Windows 11 build 22631, Nvidia 4090 running 555.99. Found on wgpu 0.17.2 and 0.20.1

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

* Closes #5559
* Closes #5693 
* Maybe #4919
* Maybe #5374
* Maybe #5491
* Probably not #3452.

**Description**

As described in #5559, our submission and surface synchronization was totally messed up. I've revamped it, made smarter classes to help keep all the bookkeeping straight, and generally make the code cleaner and easier to understand.

**Testing**

works on my machine lel

### CODE REVIEW

**Comment by JMS55** [comment]
Works fine for me running the cube example with VK validation layers enabled
```
[2024-05-09T06:03:33Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "Intel(R) Arc(TM) Graphics", vendor: 32902, device: 32085, device_type: IntegratedGpu, driver: "Intel Corporation", driver_info: "101.5382", backend: Vulkan }
```

**Comment by Vecvec** [comment]
This fixes an annoying access violation termination (that I thought was a driver bug) on program exit after a present.

**Comment by hecrj** [comment]
Unfortunately, it does not fix #5644 for me. Same constant validation error on presentation:

```
[2024-05-09T08:16:24Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkAcquireNextImageKHR-semaphore-01779 (0x5717e75b)]
        Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xba7514000000002a, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
[2024-05-09T08:16:24Z ERROR wgpu_hal::vulkan::instance]         objects: (type: SEMAPHORE, hndl: 0xba7514000000002a, name: ?)
```

The actual validation error only happens with a `debug` build, although `release` feels much slower than `0.19` as well. I believe something is very slow and the errors actually only show up in `debug` mode.

Flamegraph of `cube` seems to indicate this—with `present` taking a huge amount of time:

flamegraph

For comparison, same drivers with `0.19`:

flamegraph

Even if I enable `Immediate` present mode, frames seem to take twice as much time to be rendered with `0.20`.

**Comment by cwfitzgerald** [comment]
@hecrj could you try again with these latest commits, someone else who can reproduce the validation error says that this fixed it.

**Comment by hecrj** [comment]
@cwfitzgerald Yep! The latest changes fix the validation errors. Thanks!

I'm still noticing a bit of worse performance in `debug` mode, but it doesn't seem to be there in `release` mode anymore. Flamegraphs look the same as before, but I imagine it's expected since now synchronization works properly and there may be more waiting. No errors in any case!

File: wgpu-hal/src/lib.rs [hunk 1]
```diff
@@ -486,9 +486,15 @@ pub trait Surface: WasmNotSendSync {
     /// the timeout will be ignored.
     ///
     /// Returns `None` on timing out.
+    ///
+    /// # Safety
+    ///
+    /// - The fence must be the same fence passed to all [`Queue::submit`]s
+    ///   that used textures acquired from this surface.
```
Comment (jimblandy) [inline wgpu-hal/src/lib.rs]: This is unclear. I'm using textures acquired from this surface all the time, with many different submissions.

File: wgpu-hal/src/vulkan/mod.rs [hunk 2]
```diff
@@ -149,6 +140,103 @@ pub struct Instance {
     shared: Arc<InstanceShared>,
 }
 
+/// The semaphores used to synchronize the swapchain image acquisition.
+///
+/// One of these is created per swapchain image and is used for the swapchain
```
Comment (jimblandy) [inline wgpu-hal/src/vulkan/mod.rs]: This is unclear. A swapchain has several images. Each has its own `SwapchainSemaphores`. What does it mean for all of them to be "used for the swapchain"?

**Comment by jimblandy** [comment]
I'm actually rewriting these comments as I review so if you're not attached to them then don't worry too much about fixing anything.

**Comment by cwfitzgerald** [comment]
Yeah that's fine - I was just trying to get something there.

File: wgpu-hal/src/lib.rs [hunk 3]
```diff
@@ -675,7 +681,7 @@ pub trait Queue: WasmNotSendSync {
 
     /// Submit `command_buffers` for execution on GPU.
     ///
-    /// If `signal_fence` is `Some(fence, value)`, update `fence` to `value`
+    /// If `signal_fence` is `(fence, value)`, update `fence` to `value`
     /// when the operation is complete. See [`Fence`] for details.
```
Comment (Wumpf) [inline wgpu-hal/src/lib.rs]:
```suggestion
    /// Will update `fence` to `value` when the operation is complete.
    /// See [`Fence`] for details.
```

File: wgpu-hal/src/vulkan/mod.rs [hunk 4]
```diff
@@ -359,18 +463,70 @@ pub struct Device {
     render_doc: crate::auxil::renderdoc::RenderDoc,
 }
 
+/// Semaphores that a given submission should wait on and signal.
+struct RelaySemaphoreState {
+    wait: Option<vk::Semaphore>,
+    signal: vk::Semaphore,
```
Comment (jimblandy) [inline wgpu-hal/src/vulkan/mod.rs]: My reading is that you can actually just use one semaphore to order submits, for both the signal and wait operations.

The rules I can find about signaling and waiting just say they have to happen in the natural order, and a submission will definitely wait before signalling. So the semaphore will always be in the right state for the next operation.

It's not a problem just to enqueue multiple operations that will wait and signal the same semaphore - if it were, then you couldn't handle an arbitrary number of submissions just by swapping two semaphores back and forth. Certainly when you're doing that, half the submissions are waiting on the same semaphore. So if that's permitted, you might as well just use one semaphore for everything.

The text of `VUID-VkSubmitInfo2-semaphore-03881` explicitly mentions the possibility of semaphores appearing in both lists on the same submit:

> If the same semaphore is used as the semaphore member of both an element of `pSignalSemaphoreInfos` and `pWaitSemaphoreInfos`, and that semaphore is a timeline semaphore, the value member of the `pSignalSemaphoreInfos` element must be greater than the value member of the `pWaitSemaphoreInfos` element

That's describing timeline semaphores, but it shows that the authors are expecting this possibility. And there's no VUID saying that the same semaphore can't appear in both lists.

**Comment by jimblandy** [comment]
@cwfitzgerald What do you think of this? https://github.com/gfx-rs/wgpu/commit/da543fb51

My hope was that this would make the states of `RelaySemaphores` a bit clearer to a new reader. If people should not use `wait` unless `should_wait` is true, then let's actually force people to check that condition before they can even get at the value: classic `Option`. But it does make `advance` fallible and require us to pass the device.

[edit: made this a little nicer still: `RelaySemaphoreState` is no longer necessary]

**Comment by jimblandy** [comment]
@cwfitzgerald Here's an even more radical suggestion: https://github.com/gfx-rs/wgpu/commit/b5d52fed45e4f89213e6fe5870e99126865711aa

Just use a single semaphore for all queue ordering.

**Comment by cwfitzgerald** [comment]
@jimblandy i think we can go for it, the only question is if we want to still avoid this deadlock in anv mentioned in the old code, it if we consider that old enough to ignore.    

```
/// It would be correct to use a single semaphore there, but 
/// [Intel hangs in `anv_queue_finish`](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5508).
```

I should have perseved that comment somehow.

**Comment by jimblandy** [comment]
@cwfitzgerald:

> I should have perseved that comment somehow.

Ahh, yes, I was reviewing by checking out the branch and just wandering around with rust-analyzer, so I didn't notice that the patch removed the comment. If that's the sole rationale for the entire semaphore-swapping doohickey then we had definitely better have the comment.

Kvark filed that bug in Oct 2021. That's not that long ago, so I think we'd better keep it. It sounds like a bear to debug, and I'd rather not have to debug it again.

**Comment by jimblandy** [comment]
So I guess the remaining question is what you think of [this one](https://github.com/gfx-rs/wgpu/pull/5681#issuecomment-2118327977).

**Comment by jimblandy** [comment]
So here's the latest version of my suggestion:
https://github.com/jimblandy/wgpu/compare/hal-vk-wait-semaphore-is-option%7E2...jimblandy:wgpu:hal-vk-wait-semaphore-is-option

**Comment by cwfitzgerald** [comment]
Looks fine to me, could you either PR to my fork or just push to it?

**Comment by jimblandy** [comment]
I still want to get a handle on the swapchain semaphores. I've got some work-in-progress docs for those too. I'll take care of this tomorrow morning.

File: wgpu-hal/src/vulkan/mod.rs [hunk 5]
```diff
@@ -149,6 +140,99 @@ pub struct Instance {
...
+/// One of these is created per swapchain image and is used for the swapchain
+///
+/// The `acquire` semaphore is used to signal from the acquire operation to the first submit
+/// that uses the image.
+///
+/// The `present` semaphores are used to signal from each submit that uses the image to the
+/// present operation. We need use one per submit as we don't know at submit time which
+/// submission will be the last to use the image, so we add semaphores to them all.
+#[derive(Debug)]
+struct SwapchainSemaphores {
```
Comment (jimblandy) [inline wgpu-hal/src/vulkan/mod.rs]: Could we rename this `SwapchainImageSemaphores`, since it's per image, not per swapchain?

File: wgpu-hal/src/vulkan/mod.rs [hunk 6]
```diff
@@ -702,58 +871,85 @@ impl crate::Queue for Queue {
...
+                }
+                check.len() == surface_textures.len()
+            },
+            "More than one surface texture is being used from the same swapchain. This will cause a deadlock in release."
+        );
 
-        for &surface_texture in surface_textures {
-            wait_stage_masks.push(vk::PipelineStageFlags::TOP_OF_PIPE);
-            wait_semaphores.push(surface_texture.wait_semaphore);
+        // We lock access to all of the semaphores. This may block if two submissions are in flight at the same time.
```
Comment (jimblandy) [inline wgpu-hal/src/vulkan/mod.rs]: Please check my understanding, but I think this can't actually block. All submissions using any given `SurfaceTexture` are required to use the same `Fence`, and as explained in the docs for `wgpu_hal::Queue::submit`, all submissions using the same `Fence` must be synchronized to occur in a particular order.

File: wgpu-hal/src/vulkan/instance.rs [hunk 7]
```diff
@@ -1011,12 +1016,28 @@ impl crate::Surface for super::Surface {
...
+        let locked_swapchain_semaphores = swapchain_semaphores_arc
+            .try_lock()
+            .expect("Failed to lock a SwapchainSemaphores.");
+
+        // Wait for the previously acquired image used by the semaphore to be available.
+        swapchain.device.wait_for_fence(
+            fence,
+            locked_swapchain_semaphores.previously_used_submission_index,
+            timeout_ns,
+        )?;
```
Comment (jimblandy) [inline wgpu-hal/src/vulkan/instance.rs]: What does this actually accomplish? Aren't we going to wait for the `acquire` semaphore anyway?

**Comment by jimblandy** [comment]
@cwfitzgerald I just pushed two doc commits. Could you look them over for accuracy?

File: wgpu-hal/src/vulkan/instance.rs (hunk 7 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/instance.rs]: We must wait until the cpu timeline is sure that the semaphore has been signaled and reset. Otherwise there will be two acquire operations that could signal the same semaphore.

File: wgpu-hal/src/vulkan/mod.rs (hunk 5 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/mod.rs]: Sure

File: wgpu-hal/src/vulkan/mod.rs [hunk 8]
```diff
@@ -793,19 +1058,20 @@ impl crate::Queue for Queue {
     ) -> Result<(), crate::SurfaceError> {
         let mut swapchain = surface.swapchain.write();
         let ssc = swapchain.as_mut().unwrap();
+        let mut swapchain_semaphores = texture.surface_semaphores.lock();
+
+        // debug_assert_eq!(
+        //     Arc::as_ptr(&texture.surface_semaphores),
+        //     Arc::as_ptr(&ssc.surface_semaphores[ssc.next_semaphore_index]),
+        //     "Trying to use a surface texture that does not belong to the current swapchain."
+        // );
```
Comment (jimblandy) [inline wgpu-hal/src/vulkan/mod.rs]: This should either be uncommented or removed, but we shouldn't leave it in limbo like this.

File: wgpu-hal/src/vulkan/instance.rs (hunk 7 above)
Comment (jimblandy) [reply wgpu-hal/src/vulkan/instance.rs]: So, in other words:

If we were to remove this wait, then acquisition, command submission, and presentation would all set stuff in motion in the presentation engine or on the GPU, but as far as the CPU is concerned, they'd all return without blocking, so the CPU could just run the process full speed ahead, blow through the entire swapchain, come around to the front of the ring buffer again, and make a fresh call to `vkAcquireNextImage` passing the same semaphore as last time. This wait is the only thing that rate-limits that process to match actual presentation speed.

Is that correct?

File: wgpu-hal/src/vulkan/mod.rs (hunk 4 above)
Comment (jimblandy) [reply wgpu-hal/src/vulkan/mod.rs]: As discussed in Matrix (my bad), technically what I said above is correct, but we want to keep the semaphore-swapping code for the time being because of https://gitlab.freedesktop.org/mesa/mesa/-/issues/5508 .

File: wgpu-hal/src/vulkan/instance.rs (hunk 7 above)
Comment (jimblandy) [reply wgpu-hal/src/vulkan/instance.rs]: I've pushed another commit documenting this. If my explanation is correct, please mark this as resolved.

File: wgpu-hal/src/lib.rs (hunk 1 above)
Comment (jimblandy) [reply wgpu-hal/src/lib.rs]: This makes more sense to me now. Resolving.

File: wgpu-hal/src/lib.rs (hunk 3 above)
Comment (jimblandy) [reply wgpu-hal/src/lib.rs]: I've incorporated a change similar to this, so I'm going to resolve this.

**Comment by jimblandy** [comment]
rebased on current trunk

File: wgpu-hal/src/vulkan/mod.rs (hunk 8 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/mod.rs]: Lets remove it.

File: wgpu-hal/src/vulkan/instance.rs (hunk 7 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/instance.rs]: > This wait is the only thing that rate-limits that process to match actual presentation speed.

Yes this is correct.

File: wgpu-hal/src/vulkan/mod.rs (hunk 6 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/mod.rs]: Ah yes, good point, then lets move these all to try_lock.

**Review by jimblandy — APPROVED** [review]
