### PR TITLE
Setup and use new benchmarking harness

### LINKED ISSUE #8508: wgpu benchmark does not work very well on Mac
There is something (that I believe was said to be a known issue, but I can't remember the details) that causes the benchmark to run very slowly on Mac. It is possible to get the benchmark to run in a reasonable amount of time by adjusting the iteration counts, but if one very slow path masks performance changes on other codepaths that would be material on other platforms or in certain use cases, then that limits the usefulness of the benchmark.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Closes #8508?

**Description**

This completely redoes our benchmarking to use a custom interface. This provides a number of benefits enumerated in the lib.rs file. Importantly it improves output to be easier to understand, makes the test code much simpler, and allows us to do test selection more intelligently. 

image

**Testing**

Manual testing with CLI and it is part of the test suite.

**Squash or Rebase?**

Izza.

### CODE REVIEW

**Comment by Wumpf** [comment]
Haven't checked if it's unrelated to your changes, but when trying to run `cargo bench --bench wgpu-benchmark` I get a panic for unknown instruction 🤔 
```
Running benchmark: naga::front

thread 'main' panicked at benches\benches\wgpu-benchmark\shader.rs:254:32:
called `Result::unwrap()` on an `Err` value: UnknownInstruction(2573)
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:697
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\panicking.rs:75
   2: core::result::unwrap_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\result.rs:1732
   3: wgpu_benchmark::shader::frontends::closure$4
             at .\benches\wgpu-benchmark\shader.rs:254
   4: wgpu_benchmark::iter::iter_auto::closure$0
             at .\src\iter.rs:51
   5: wgpu_benchmark::iter::iter
             at .\src\iter.rs:24
   6: wgpu_benchmark::iter::iter_auto<wgpu_benchmark::shader::frontends::closure_env$4>
             at .\src\iter.rs:44
   7: wgpu_benchmark::shader::frontends
             at .\benches\wgpu-benchmark\shader.rs:234
   8: wgpu_benchmark::main
             at .\src\lib.rs:231
   9: wgpu_benchmark::main
             at .\benches\wgpu-benchmark\main.rs:101
  10: core::ops::function::FnOnce::call_once
             at C:\Users\Andreas\.rustup\toolchains\1.88-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

File: benches/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,256 @@
+#![cfg(not(target_arch = "wasm32"))]
+#![expect(clippy::disallowed_types)] // We're outside of the main wgpu codebase
+
+//! Benchmarking framework for `wgpu`.
+//!
+//! This crate a basic framework for benchmarking. Its design is guided
```
Comment (Wumpf) [inline benches/src/lib.rs]:
```suggestion
//! This crate is a basic framework for benchmarking. Its design is guided
```

File: benches/src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,256 @@
...
+    let mut color: ColorChoice = args
+        .opt_value_from_str("--color")
+        .unwrap_or(None)
+        .unwrap_or(ColorChoice::Auto);
+    if color == ColorChoice::Auto && !std::io::stdin().is_terminal() {
+        color = ColorChoice::Never;
+    }
+
+    let exact = args.contains("--exact");
+    let _no_capture = args.contains("--no-capture");
```
Comment (Wumpf) [inline benches/src/lib.rs:135]: what's this for?

File: benches/src/lib.rs [hunk 3]
```diff
@@ -0,0 +1,256 @@
...
+    let is_list = args.contains("--list");
+    let is_test = !is_bench && !is_list;
+
+    let format: Option<String> = args.opt_value_from_str("--format").unwrap();
+
+    if let Some(fmt) = format {
+        assert_eq!(fmt, "terse", "Only 'terse' format is supported.");
+    }
+    if let Some(ref baseline) = baseline_name {
+        if baseline == "previous" {
```
Comment (Wumpf) [inline benches/src/lib.rs]: nit: there's a constant for that in `context.rs`

File: benches/src/lib.rs [hunk 4]
```diff
@@ -0,0 +1,256 @@
...
+            eprintln!("Cannot use 'previous' as a baseline name.");
+            return;
+        }
+    }
+    if let Some(ref write_baseline) = write_baseline {
+        if write_baseline == "previous" {
```
Comment (Wumpf) [inline benches/src/lib.rs]: as above

File: benches/src/print.rs [hunk 5]
```diff
@@ -0,0 +1,205 @@
...
+            time_change: delta_time,
+        }
+    }
+}
+
+/// Get a color spec for the given change value.
+///
+/// Positive changes are red (regression), negative changes are green (improvement).
+/// This represents changes for time durations. For throughput changes, the sign should be inverted.
+fn get_change_color(change: f64) -> ColorSpec {
```
Comment (Wumpf) [inline benches/src/print.rs]: those are changes in percent? why not documented or named like that

File: benches/src/iter.rs [hunk 6]
```diff
@@ -0,0 +1,95 @@
+use std::time::Duration;
+
```
Comment (Wumpf) [inline benches/src/iter.rs:2]: authoring a benchmark I'd expect those to be on those on `BenchmarkContext`'s `impl`.
Also, some doc string on when to use what would be good for that

File: benches/src/iter.rs [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+    let mut iterations = 0_u32;
+    let mut durations = vec![Duration::ZERO; names.len()];
+
+    let control = if let Some(override_control) = ctx.override_iters {
+        override_control
+    } else {
+        LoopControl::Time(Duration::from_secs(1))
+    };
+
+    while !control.finished(iterations, *durations.first().unwrap_or(&Duration::ZERO)) {
```
Comment (Wumpf) [inline benches/src/iter.rs]: the duration picking behavior is a bit strange and needs documentation!

File: benches/src/iter.rs (hunk 6 above)
Comment (Wumpf) [reply benches/src/iter.rs:2]: while we're on the topic if benchmark structure: I find it also a lil bit odd that every benchmark has to build up its own `Vec` of results and not have that being managed by the benchmark context. Not a big deal ofc, but makes this feel a bit raw 🤷

**Review by Wumpf — APPROVED** [review]
some minor stylistic notes but lgtm, makes sense and the output looks really nice!
Would be good though to figure out what the crash is about, I can poke a bit more later

File: benches/src/lib.rs (hunk 2 above)
Comment (cwfitzgerald) [reply benches/src/lib.rs:135]: cargo-nextest passes us this flag when we execute - I'll add a comment.

File: benches/src/print.rs (hunk 5 above)
Comment (cwfitzgerald) [reply benches/src/print.rs]: Yeah - wasn't that way before

File: benches/src/iter.rs (hunk 6 above)
Comment (cwfitzgerald) [reply benches/src/iter.rs:2]: Sounds reasonable - I'll look at this in a followup.
