### PR TITLE
don't panic if naga parsing of shader source fails

### LINKED ISSUE #2545: ShaderSource::Glsl panics if shader has syntax error
**Description**
I'm trying to port an existing application using GLSL to `wgpu`, so I have existing complex shaders I want to modify to be compatible. While trying to get them working, I have found that if the shader has (something which `naga` considers) a syntax error, `wgpu` will panic via `.unwrap()`:

https://github.com/gfx-rs/wgpu/blob/326af60df8623e93b47a0de090e6cb449c8507f5/wgpu/src/backend/direct.rs#L1054

This has the following problems:

1. The application cannot recover from the error (e.g. in case it is allowing the shaders to be edited and reloaded) without using `catch_unwind()`.
2. The error message is presented in `Debug` formatting, which is not ideal for readability.
3. The error message provides only character (byte?), not line, positions (let alone line positions respecting GLSL `#line` directives), so it is difficult to correlate with a line in one's editor.

The last is presumably `naga`'s problem, but I propose that `wgpu` should report shader parsing errors in a `Result::Err()` instead of a panic.

(The `ShaderSource::SpirV` path also has an `.unwrap()` which could be improved the same way, but presumably that's less of a routine occurrence.)

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: [Error { kind: NotImplemented("variable qualifier"), meta: Span { start: 571, end: 580 } }]', /Users/kpreid/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:1037:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3a06854129d1ff7cb1e8a7fb62671782fe2513ba/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/3a06854129d1ff7cb1e8a7fb62671782fe2513ba/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/3a06854129d1ff7cb1e8a7fb62671782fe2513ba/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/3a06854129d1ff7cb1e8a7fb62671782fe2513ba/library/core/src/result.rs:1018:23
   4: <wgpu::backend::direct::Context as wgpu::Context>::device_create_shader_module
             at /Users/kpreid/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:1037:30
   5: wgpu::Device::create_shader_module
             at /Users/kpreid/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/lib.rs:1705:17
   6: all_is_cubes_gpu::in_wgpu::EverythingRenderer::new
             at ./all-is-cubes-gpu/src/in_wgpu.rs:144:29
```

**Platform**
macOS 12.3, `wgpu` 0.12

### PR DESCRIPTION
**Pull request by waynr**
**Connections**
https://github.com/gfx-rs/wgpu/issues/5019

fixes https://github.com/gfx-rs/wgpu/issues/2545

**Description**
In my application shaders are meant to be hot-reloaded on filesystem changes.
If there is a syntax issue with the newly-updated shader source `naga` parsing
of the file can fail. In current trunk, the `Result` returned by `naga` parsing
is simply unwrapped.

This PR removes the `naga` parse unwrap and instead bubbles the `Result` up
through the call stack so to be handled by the calling code.

I am opening this PR prior to updating the changelog and getting `cargo xtask
test` to run just to start discussion (should have commits addressing those
shortly after opening it).

**Testing**
I've updated the examples and test cases that were already calling
`Device.create_shader_module`.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu/src/backend/direct.rs [hunk 1]
```diff
@@ -927,7 +927,7 @@ impl crate::Context for Context {
                     defines: defines.clone(),
                 };
                 let mut parser = naga::front::glsl::Frontend::default();
-                let module = parser.parse(&options, shader).unwrap();
```
Comment (nical) [inline wgpu/src/backend/direct.rs]: wgpu's error handling story is a tad unusual because it implements WebGPU's error handling API and has to work in a completely asynchronous environment. So `create_shader_module` cannot return a `Result`.

Instead of unwrapping here, the error should be put into an error scope the same way it is done a few lines belowe with `handle_error`.

**Review by nical — CHANGES_REQUESTED** [review]

File: wgpu/src/backend/direct.rs (hunk 1 above)
Comment (waynr) [reply wgpu/src/backend/direct.rs]: Oh, I wondered why no `Result`s were being returned anywhere. I'll come back to this later today and make this change!

File: wgpu/src/backend/direct.rs [hunk 2]
```diff
@@ -912,8 +913,19 @@ impl crate::Context for Context {
...
+                    Ok(m) => wgc::pipeline::ShaderModuleSource::Naga(Owned(m)),
+                    Err(cause) => {
+                        self.handle_error(
+                            &device_data.error_sink,
+                            cause,
+                            LABEL,
+                            desc.label,
+                            "Device::create_shader_module",
+                        );
+                        wgc::pipeline::ShaderModuleSource::Dummy(PhantomData)
```
Comment (waynr) [inline wgpu/src/backend/direct.rs]: @nical thanks for the quick review earlier today!

Here is my second attempt. Because this function must always return something but we can't build a `ShaderModuleSource` from invalid shader source, the least disruptive approach here seemed to me like using `ShaderModuleSource::Dummy`, but it also seems less than ideal. It feels to me like the `Dummy` source is never supposed to be used at runtime (maybe it's for tests or something?) given the fact that there were explicit panics set for match arms matching it.

This in combination with `Device.on_uncaptured_error` seems to work for me. I chose not to use `push_error_scope` and `pop_error_scope` because multiple errors can and do get captured but `pop_error_scope` only returns a single error; if `pop_error_scope` could return multiple errors this would be a better approach.

Other possibilities I am considering for solving my own immediate problem:

* Assuming it's not a horrible solution in general for this PR, I could treat `ShaderModuleSource::Dummy` as a kind of error state indicator
* I could just import naga directly, attempt the GLSL parsing before attempting to call `create_shader_module`, and simply handle naga errors at that point

Comment (nical) [reply wgpu/src/backend/direct.rs]: Lets add a `ShaderModuleSource::Invalid` variant instead of using the `Dummy` one here. I think that you are otherwise on the right track.

Error scopes capturing a single error looks like a shortcoming of wgpu. It would be a valuable thing to improve, I filed #5041.

**Review by nical — CHANGES_REQUESTED** [review]

File: wgpu/src/backend/direct.rs (hunk 2 above)
Comment (waynr) [reply wgpu/src/backend/direct.rs]: Hey! I looked into adding `ShaderModuleSource::Invalid` as you suggested, but realized that this (and my use of `ShaderModuleSource::Dummy`) ends up leading to duplicate errors being reported which seems to be why I ended up with multiple errors on parse failure during `Device.on_uncaptured_error` -- I would get one error from the parse error handled using `handle_error` in `wgpu/src/backend/wgpu_core.rs` then another when handling the `ShaderModuleSource::Dummy` variant in `wgpu-core/src/device/resource.rs` (which previously just resulted in a panic).

So I tried a couple different approaches involving `ShaderModuleSource::Invalid` that didn't feel right, but then I realized why none of the approaches up to this point felt right...because in `wgpu/src/backend/wgpu_core.rs` there is no parsing of `wgsl` and hence no handling of parse errors at that level. This led me to the eventual conclusion that the cleanest way to improve error handling for `glsl` is to add `ShaderModuleSource::Glsl` and `ShaderModuleSource::SpirV` (the latter isn't necessary for me, but I figured i would make the change to both as long as I was working on the glsl variant), return that from `ContextWgpuCore.device_create_shader_module` and do the parsing for `glsl` and `spirv` in the same place it's done for wgsl.

This required adding a couple more variants to `CreateShaderModuleError` specific to `glsl` and `spirv` as well as the updating `naga::front::glsl::Frontend.parse` to return a `Result<_, naga::front::glsl::error::ParseError>` where `naga::front::glsl::error::ParseError` is a type I've introduced to encapsulate the `Vec<naga::front::glsl::error::Error>` that was being returned before (i gave up trying to use a vec in `CreateShaderModuleError::ParsingGlsl` after fighting with trait bounds somewhere).

Let me know if this makes sense!

Comment (waynr) [reply wgpu/src/backend/direct.rs]: Oh yeah, just in case you don't get pinged automatically by new messages: @nical

Comment (nical) [reply wgpu/src/backend/direct.rs]: Since this approach involves larger naga changes I'll deffer to @teoxoy or @jimblandy

**Comment by teoxoy** [comment]
@waynr could you rebase the PR on latest trunk? so the new CI jobs can run.

**Comment by teoxoy** [comment]
Ah, nvm, they didn't run because the clippy jobs are failing.

File: naga/src/front/spv/error.rs [hunk 3]
```diff
@@ -127,3 +131,24 @@ pub enum Error {
     )]
     NonBindingArrayOfImageOrSamplers,
 }
+
+impl Error {
+    pub fn emit_to_writer(&self, writer: &mut impl WriteColor, source: &str) {
+        self.emit_to_writer_with_path(writer, source, "glsl");
```
Comment (teoxoy) [inline naga/src/front/spv/error.rs:137]:
```suggestion
        self.emit_to_writer_with_path(writer, source, "spv");
```

**Review by teoxoy — APPROVED** [review]
This PR looks good to me, it's consistent with how we deal with WGSL shaders as well.

**Comment by teoxoy** [comment]
@nical do you want to take another look?

File: wgpu-core/Cargo.toml [hunk 4]
```diff
@@ -106,6 +112,7 @@ rustc-hash = "1.1"
 serde = { version = "1", features = ["serde_derive"], optional = true }
 smallvec = "1"
 thiserror = "1"
+zerocopy = { version = "0.7", optional = true }
```
Comment (cwfitzgerald) [inline wgpu-core/Cargo.toml]: I would prefer ~~if we didn't take a dependency for this,~~ we used bytemuck.

This code doesn't show up in Mozilla's build, but neither bytemuck or zerocopy are used there.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]

File: wgpu-core/src/device/global.rs [hunk 5]
```diff
@@ -1197,7 +1197,7 @@ impl<G: GlobalIdentityHandlerFactory> Global<G> {
                     }
                     #[cfg(feature = "spirv")]
                     pipeline::ShaderModuleSource::SpirV(ref code, _) => {
-                        trace.make_binary("spirv", code.as_bytes())
+                        trace.make_binary("spirv", cast_slice::<u32, u8>(code.borrow()))
```
Comment (cwfitzgerald) [inline wgpu-core/src/device/global.rs]: Nit:

```suggestion
                        trace.make_binary("spirv", bytemuck::cast_slice::<u32, u8>(&code))
```

Should work and remove the need for any imports at all.

Comment (waynr) [reply wgpu-core/src/device/global.rs]: Thanks for catching that! I pushed the change in a different commit to also remove the imports as suggested.

File: wgpu/src/backend/wgpu_core.rs [hunk 6]
```diff
@@ -844,22 +844,19 @@ impl crate::Context for ContextWgpuCore {
...
-                // Parse the given shader code and store its representation.
-                let options = naga::front::glsl::Options { stage, defines };
-                let mut parser = naga::front::glsl::Frontend::default();
-                let module = parser.parse(&options, shader).unwrap();
-
-                wgc::pipeline::ShaderModuleSource::Naga(Owned(module))
+                let options = naga::front::glsl::Options {
+                    stage,
+                    defines: defines.clone(),
+                };
```
Comment (a1phyr) [inline wgpu/src/backend/wgpu_core.rs]:
```suggestion
                let options = naga::front::glsl::Options { stage, defines };
```
This probably shouldn't change.

**Comment by teoxoy** [comment]
This should be ready to go. Pinging @nical & @cwfitzgerald for pending reviews.

**Review by nical — APPROVED** [review]

**Review by cwfitzgerald — APPROVED** [review]

**Comment by waynr** [comment]
Thanks for working through this with me!
