### PR TITLE
hal/vulkan: Accurately map all formats except fp16 to use the non-linear sRGB color space

### LINKED ISSUE #8076: No surface formats available
**Description**
Running an example in wgpu or bevy shows that no surface formats are found:
`[wgpu-hal/examples/ray-traced-triangle/main.rs:285:9] &surface_caps.formats = []`

**Repro steps**

```
 techn0@IO  ~/source/wgpu   trunk  RUST_BACKTRACE=1 cargo run --example ray-traced-triangle
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/examples/ray-traced-triangle`
[wgpu-hal/examples/ray-traced-triangle/main.rs:267:13] exposed.features = Features {
    features_wgpu: FeaturesWGPU(
        SHADER_FLOAT32_ATOMIC | TEXTURE_FORMAT_16BIT_NORM | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_ENCODERS | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | PUSH_CONSTANTS | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | TEXTURE_ATOMIC | TEXTURE_FORMAT_NV12 | EXPERIMENTAL_RAY_QUERY | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX | SHADER_EARLY_DEPTH_TEST | SHADER_INT64 | SUBGROUP | SUBGROUP_VERTEX | SUBGROUP_BARRIER | PIPELINE_CACHE | SHADER_INT64_ATOMIC_MIN_MAX | SHADER_INT64_ATOMIC_ALL_OPS | TEXTURE_INT64_ATOMIC | EXPERIMENTAL_MESH_SHADER | EXPERIMENTAL_RAY_HIT_VERTEX_RETURN | EXPERIMENTAL_MESH_SHADER_MULTIVIEW | EXTENDED_ACCELERATION_STRUCTURE_VERTEX_FORMATS,
    ),
    features_webgpu: FeaturesWebGPU(
        DEPTH_CLIP_CONTROL | DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_BC_SLICED_3D | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | RG11B10UFLOAT_RENDERABLE | BGRA8UNORM_STORAGE | FLOAT32_FILTERABLE | DUAL_SOURCE_BLENDING | CLIP_DISTANCES,
    ),
}
[wgpu-hal/examples/ray-traced-triangle/main.rs:285:9] &surface_caps.formats = []

thread 'main' panicked at wgpu-hal/examples/ray-traced-triangle/main.rs:292:43:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:145:5
   3: core::option::unwrap_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/option.rs:2040:5
   4: core::option::Option<T>::unwrap
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/option.rs:1003:21
   5: ray_traced_triangle::Example<A>::init
             at ./wgpu-hal/examples/ray-traced-triangle/main.rs:292:14
   6: ray_traced_triangle::main
             at ./wgpu-hal/examples/ray-traced-triangle/main.rs:1156:26
   7: core::ops::function::FnOnce::call_once
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected vs observed behavior**
Expected the example to work. Note that it does work if I force it to use the surface format hardcoded in the other if branch.

**Extra materials**
https://github.com/bevyengine/bevy/issues/20481

**Platform**
```
SystemInfo { os: "Linux (Pop!_OS 22.04)", kernel: "6.12.10-76061203-generic", cpu: "AMD Ryzen 9 7950X 16-Core Processor", core_count: "16", memory: "61.9 GiB" }
AdapterInfo { name: "NVIDIA GeForce RTX 3070", vendor: 4318, device: 9348, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "575.57.08", backend: Vulkan }
```

### PR DESCRIPTION
**Pull request by MarijnS95**
**Connections**
Fixes #8076

**Description**

In a quest to deduplicate reported texture formats in #3227 this was hacked in to be based on color spaces (having the same format listed for multiple color spaces is how duplicates exist to begin with), following [a link to some swapchain code] that forcibly uses linear scRGB (extended sRGB) for a surface configuration with fp16 texture format.  By accident it seems also 16-bit UNORM/SNORM formats and even the `A2R10G10B10_UNORM_PACK32` format were placed inside the linear scRGB match arm.  Besides mismatching with the forced color space used at swapchain creation, this disallows using higher bit-depth in regular non-linear sRGB output.  In particular 10-bit is popular for modern monitors, which remain in (non-linear) sRGB while HDR output is disabled.

According to the **linked** Vulkan reports database the existing format pairs with `EXTENDED_SRGB_LINEAR_EXT` have *barely any coverage*, to the point where `R16G16B16A16_SNORM` doesn't seem to be supported at all with anything other than `SRGB_NONLINEAR_KHR`.

[a link to some swapchain code]: https://github.com/gfx-rs/wgpu/blob/f41a1c294bf09c4ab7e523f6c9aff5119044a097/wgpu-hal/src/vulkan/device.rs#L542-L548

**Testing**
No testing yet.

**Squash or Rebase?**

Rebase

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [ ] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-hal/src/vulkan/conv.rs [hunk 1]
```diff
@@ -169,13 +169,22 @@ pub fn map_vk_surface_formats(sf: vk::SurfaceFormatKHR) -> Option<wgt::TextureFo
...
             F::R8G8B8A8_SRGB => Tf::Rgba8UnormSrgb,
+            F::R16G16B16A16_SNORM => Tf::Rgba16Snorm,
+            F::R16G16B16A16_UNORM => Tf::Rgba16Unorm,
+            F::A2B10G10R10_UNORM_PACK32 => Tf::Rgb10a2Unorm,
             _ => return None,
         },
         vk::ColorSpaceKHR::EXTENDED_SRGB_LINEAR_EXT => match sf.format {
+            // TODO: This is almost twice as popular in nonlinear sRGB than linear scRGB,
+            // according to the database linked above.
             F::R16G16B16A16_SFLOAT => Tf::Rgba16Float,
```
Comment (MarijnS95) [inline wgpu-hal/src/vulkan/conv.rs]: In an ideal world users of `wgpu` are allowed to choose a format and color space combination, but I assume simply no API exists for that yet which is why this is hardcoded to force linear scRGB on fp16?

https://github.com/gfx-rs/wgpu/blob/04a34016384963bf26353fad472b5d2c5ecdc359/wgpu-hal/src/vulkan/device.rs#L505-L511

Comment (Wumpf) [reply wgpu-hal/src/vulkan/conv.rs]: Yeah I think the surface APIs should expose color spaces on surfaces similar to how Vulkan does, i.e. first allow the adapter to advertise which format+space pairs are available and then allow surfaces to be created in a way that spells out what space (& encoding) + format the compositor will expect values to be that end up in the surface.

See also:
* https://github.com/gfx-rs/wgpu/issues/2920

What makes this tricky is that WebGPU exposes the color space of a surface/canvas: https://www.w3.org/TR/webgpu/#canvas-configuration
As [per definition](https://www.w3.org/TR/webgpu/#color-spaces) all color spaces are extended range. But while [surface configuration](https://www.w3.org/TR/webgpu/#canvas-configuration) allow specifying the color space, it doesn't seem to specify the encoding/transfer function. That part confuses me a bit since that means that an important puzzle piece seems to be missing: in the example here we'd want color space to be `srgb` in either case, but sometimes in linear and sometimes with the OETF applied (i.e. `SRGB_NONLINEAR`).
Digging a bit deeper, CSS defines linear srgb as a separate color space: https://drafts.csswg.org/css-color/#predefined-sRGB-linear. And as I understand this is the same property that WebGPU is referring to in its canvas configuration.
Therefore I think we'd have to assume that RGBA16F on the web with the surface set to `srgb` is actually `vk::ColorSpaceKHR::EXTENDED_SRGB_NONLINEAR_EXT `, meaning that the linked code makes it inconsistent with WebGPU 😱

**Comment by Wumpf** [comment]
Might be related to
* https://github.com/gfx-rs/wgpu/issues/4842

@valaphee also made the observation that the hardcoded "I guess float means linear extended srgb, everything else non-linear srgb": https://github.com/gfx-rs/wgpu/issues/4842#issuecomment-2075641322

File: wgpu-hal/src/vulkan/conv.rs (hunk 1 above)
Comment (Wumpf) [reply wgpu-hal/src/vulkan/conv.rs]: in other words if we want to start by mirroring WebGPU (and we absolutely should, to make things portable at least), then https://github.com/gfx-rs/wgpu/blob/04a34016384963bf26353fad472b5d2c5ecdc359/wgpu-hal/src/vulkan/device.rs#L505-L511 is actually wrong and it should use `EXTENDED_SRGB_NONLINEAR_EXT` if available.

Comment (Wumpf) [reply wgpu-hal/src/vulkan/conv.rs]: Addendum / looking at the sources step by step:

WebGPU points to https://html.spec.whatwg.org/multipage/canvas.html#predefinedcolorspace
Which in turn points to https://drafts.csswg.org/css-color/#valdef-color-srgb
Which explicitly states the transfer function per color space (depending who you ask color space is independent of transfer function since that's just an encoding detail, but they bundle that here!)

Therefore, https://github.com/gfx-rs/wgpu/blob/3efd640178a6dca4bd00f1c199e2a4f3dfc5fd20/wgpu-types/src/lib.rs#L7461 should strictly imply non-linear encoding (we can add a linear variant for native only!), should really doc & link that up better.
Therefore, we should use `vk::ColorSpaceKHR::EXTENDED_SRGB_NONLINEAR_EXT` as previously stated :)

**Review by Wumpf — APPROVED** [review]
despite lengthy comments above I think this change is a strict improvement and is correct to point to the (imho even more wrong) hardcoded color space bit.

Changelog entry would be nice either way and I'd like to hear your thoughts on what I diged up :)

**Comment by jimblandy** [comment]
This presentation, made to the W3C WebGPU committee in August, was great background on HDR: 

https://docs.google.com/presentation/d/13Gu_ZhNdMzKu285VLP3CNSjRlheo0bZsCHGml6FzlKY/edit?slide=id.p#slide=id.p

**Review by cwfitzgerald — APPROVED** [review]
Yeah lets just get a changelog entry and we can land. This is better than before.

File: wgpu-hal/src/vulkan/conv.rs (hunk 1 above)
Comment (MarijnS95) [reply wgpu-hal/src/vulkan/conv.rs]: Sounds good, thanks for the detailed dive. Can I leave the honors to you to update the formats based on your dissection after we first merge this regression-fix?

**Review by cwfitzgerald — APPROVED** [review]
