### PR TITLE
[wgpu-core] Make `CommandEncoder.is_open` accurate

### LINKED ISSUE #6795: `CommandEncoder.is_open` can't be relied on
`CommandEncoder.is_open` is not accurately reflecting the encoder state because we sometimes reach for the raw encoder and call `begin_encoding` directly on it without setting the `is_open` flag.

https://github.com/gfx-rs/wgpu/blob/53f40794f275329a48efc7d1c637c91b8e51327d/wgpu-core/src/device/queue.rs#L1167-L1191

This was not an issue prior to https://github.com/gfx-rs/wgpu/commit/5e1fbd7176ffacbb6b4ccf29f999e12c2c9421bf because we had to call `.destroy()` on the encoder manually which we weren't doing in all cases (causing leaks).

Since 5e1fbd7176ffacbb6b4ccf29f999e12c2c9421bf we've started to see the following errors in some CTS tests [Bug 1937600](https://bugzilla.mozilla.org/show_bug.cgi?id=1937600).

```
[ERROR wgpu_hal::dx12::command] ID3D12CommandAllocator::Reset() failed with Unspecified error (0x80004005)
[ERROR wgpu_hal::auxil::dxgi::result] Create command list failed: The parameter is incorrect. (0x80070057)
```

We fail to reset the allocator because we didn't discard (see comment in image):

image

### PR DESCRIPTION
**Pull request by teoxoy**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/6795.

**Description**
See https://github.com/gfx-rs/wgpu/issues/6795
This also makes the methods more fail-proof by panicking if we misuse the API.
The last commit is cleanup.

**Testing**
Existing tests & made sure that the tests from [Bug 1937600](https://bugzilla.mozilla.org/show_bug.cgi?id=1937600) work now.

### CODE REVIEW

File: wgpu-core/src/command/mod.rs [hunk 1]
```diff
@@ -337,15 +379,12 @@ impl CommandEncoder {
     /// Begin recording a new command buffer, if we haven't already.
     ///
     /// The underlying hal encoder is put in the "recording" state.
-    pub(crate) fn open(
-        &mut self,
-        device: &Device,
-    ) -> Result<&mut dyn hal::DynCommandEncoder, DeviceError> {
+    pub(crate) fn open(&mut self) -> Result<&mut dyn hal::DynCommandEncoder, DeviceError> {
```
Comment (ErichDonGubler) [inline wgpu-core/src/command/mod.rs:382]: praise: It's a nice win to eliminate arguments like this. 😀

File: wgpu-core/src/device/queue.rs [hunk 2]
```diff
@@ -1165,14 +1165,10 @@ impl Queue {
...
                         // execute resource transitions
-                        if let Err(e) = unsafe {
-                            baked.encoder.raw.begin_encoding(hal_label(
-                                Some("(wgpu internal) Transit"),
-                                self.device.instance_flags,
-                            ))
-                        }
-                        .map_err(|e| self.device.handle_hal_error(e))
-                        {
+                        if let Err(e) = baked.encoder.open_pass(
```
Comment (ErichDonGubler) [inline wgpu-core/src/device/queue.rs]: thought: The term `pass` here is confusing to me, because it's ambiguous. Method documentation states that this refers to a render pass. It'd be nice to present that detail in the naming, IMO.

I know this terminology existed from before, so I don't think it needs to block this review, but if you agree, I'd be happy to do some follow-up work here.

File: wgpu-core/src/command/compute.rs [hunk 3]
```diff
@@ -415,7 +415,9 @@ impl Global {
         // We automatically keep extending command buffers over time, and because
         // we want to insert a command buffer _before_ what we're about to record,
         // we need to make sure to close the previous one.
-        encoder.close(&cmd_buf.device).map_pass_err(pass_scope)?;
+        encoder
+            .close_if_open(&cmd_buf.device)
```
Comment (ErichDonGubler) [inline wgpu-core/src/command/compute.rs]: question: Shouldn't we panic here if the encoder is not in an open state?

This question also applies to the render pass correspondent to this method.

**Review by ErichDonGubler — APPROVED** [review]
LGTM! Had some questions, but nothing that I see as blocking.

File: wgpu-core/src/command/compute.rs (hunk 3 above)
Comment (teoxoy) [reply wgpu-core/src/command/compute.rs]: We shouldn't because it can be either open or closed at this point, depending on what other commands users of the API issued.

File: wgpu-core/src/device/queue.rs (hunk 2 above)
Comment (teoxoy) [reply wgpu-core/src/device/queue.rs]: Yeah, I was thinking to rename it to `open` and rename the current `open` method to `open_if_closed`. If you are up for a PR I can give it a ✅.
