### PR TITLE
Properly Deal with Timeouts

### LINKED ISSUE #3601: Timeout on `Device::maintain` with `Maintain::WaitForSubmissionIndex` is ignored
Whenever `Device::maintain` with `Maintain::WaitForSubmissionIndex` times out, wgpu assumes that the specified submission index is done and initiates cleanup as-if the frame was done. This can cause crashes down the line as buffers may be freed too early (haven't confirmed this part, but seems shaky!).
There is a `StuckGpu` (on `WaitIdleError` and `QueueSubmitError`) but it is unused currently.

Wgpu needs to react to timeouts by *not* assuming the passed submission index is done and instead query the actual done frame.

---

The situation is particularly weird on WebGL where the max timeout is browser defined (and usually much lower than our hardcoded 5 seconds), see https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/clientWaitSync, `MAX_CLIENT_WAIT_TIMEOUT_WEBGL`. Instead, we pass a timeout of zero, meaning that any `WaitForSubmissionIndex` call will pretend the frame is done. However, since freeing gl buffers that are still in use has no practical repercussions, this does not cause any crashes etc..
To make matters worse, on WebGL we can't actually block on this by calling it repeatedly, since [clientWaitSync](https://registry.khronos.org/webgl/specs/latest/2.0/#3.7.14) will not finish unless control is given back to the browser. Effectively meaning that we can't actually block on any particular event. 

Worth noting here that blocking in this manner isn't possible at all either on WebGPU either where `poll` does not exist. 

---

Given that `poll` is a pure Rust space method and not covered by the WebGPU spec I propose to return an enum for all these different failure modes and avoid any panic on `StuckGpu`, i.e. as far as possible not treating hitting the timeout as a crash but rather as an expected error state.

### LINKED ISSUE #4589: Device::poll with Maintain::Wait returns early and with an incorrect value when a 5-second timeout is reached
We're using wgpu to do some computing tasks where individual compute passes will take more than CLEANUP_WAIT_MS.  In the case of a long running compute pass, waiting on the submission index with a Maintain::Wait or Maintain::WaitForSubmissionIndex will return after the timeout is exceeded, even if the task is not complete.  It will also return true indicating the queue is empty if there's nothing else in the queue.  

This timeout should be configurable.  If that's hard, in the meantime, if this timeout is reached, device::poll call should return false to indicate there is still an item in the queue.  Regardless, this behavior should be documented.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Close #3601 
Close #4589

**Description**
_Describe what problem this is solving, and how it's solved._

**Testing**
_Explain how this change is tested._

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by teoxoy** [comment]
I looked at the `wgpu-core` changes and they looked good to me. 👍

File: tests/src/init.rs [hunk 1]
```diff
@@ -42,7 +42,15 @@ pub fn initialize_instance(backends: wgpu::Backends, force_fxc: bool) -> Instanc
             dx12: wgpu::Dx12BackendOptions {
                 shader_compiler: dx12_shader_compiler,
             },
-            gl: wgpu::GlBackendOptions::from_env_or_default(),
+            gl: wgpu::GlBackendOptions {
+                fence_behavior: if cfg!(target_family = "wasm") {
+                    wgpu::GlFenceBehavior::AutoFinish
```
Comment (Wumpf) [inline tests/src/init.rs:52]: where in the tests are we relying on this, what would break if we use `Normal`. Plz add comment

File: wgpu-core/src/device/global.rs [hunk 2]
```diff
@@ -1869,9 +1869,20 @@ impl Global {
...
+                let maintain_result;
+                (user_callbacks, maintain_result) =
+                    device.maintain(fence, wgt::PollType::Wait, snatch_guard);
+
+                match maintain_result {
+                    // We're happy
+                    Ok(wgt::PollStatus::QueueEmpty) => {}
+                    Ok(wgt::PollStatus::WaitSucceeded) => {
+                        // After the wait, the queue should be empty.
+                        break 'error E::GpuWaitTimeout;
```
Comment (Wumpf) [inline wgpu-core/src/device/global.rs]: worth a debug assert since this would be an implementation error, no?

File: wgpu-core/src/device/resource.rs [hunk 3]
```diff
@@ -370,73 +370,133 @@ impl Device {
...
+                user_closures.mappings,
+                queue_empty,
+            ) = queue_result
+        };
+
+        // Based on the queue empty status, and the current finished submission index, determine the result of the poll.
+        let result = if queue_empty {
+            if let Some(wait_submission_index) = wait_submission_index {
+                // Assert to ensure that if we received a queue empty status, the fence shows the correct value.
+                // This is defencive, as this should never be hit.
```
Comment (Wumpf) [inline wgpu-core/src/device/resource.rs]:
```suggestion
                // This is defensive, as this should never be hit.
```

File: wgpu-core/src/device/resource.rs [hunk 4]
```diff
@@ -370,73 +370,133 @@ impl Device {
         assert!(self.queue.set(Arc::downgrade(queue)).is_ok());
     }
```
Comment (Wumpf) [inline wgpu-core/src/device/resource.rs:381]: added comments in this file help a lot, thanks!

File: wgpu-types/src/lib.rs [hunk 5]
```diff
@@ -3991,39 +3991,57 @@ impl<T> Maintain<T> {
...
+            Self::WaitForSubmissionIndex(i) => PollType::WaitForSubmissionIndex(func(i)),
+            Self::Wait => PollType::Wait,
+            Self::Poll => PollType::Poll,
         }
     }
 }
 
-/// Result of a maintain operation.
-pub enum MaintainResult {
+/// Error states after a poll
```
Comment (Wumpf) [inline wgpu-types/src/lib.rs]:
```suggestion
/// Error states after a device poll
```

File: wgpu-types/src/lib.rs [hunk 6]
```diff
@@ -3991,39 +3991,57 @@ impl<T> Maintain<T> {
...
+pub enum PollError {
+    /// The requested Wait timed out before the submission was completed.
+    #[cfg_attr(
+        feature = "std",
+        error("The requested Wait timed out before the submission was completed.")
+    )]
+    Timeout,
+}
+
+/// Status of poll operation.
```
Comment (Wumpf) [inline wgpu-types/src/lib.rs]:
```suggestion
/// Status of device poll operation.
```

File: wgpu-types/src/lib.rs [hunk 7]
```diff
@@ -3991,39 +3991,57 @@ impl<T> Maintain<T> {
...
+    pub fn map_index<U, F>(self, func: F) -> PollType<U>
     where
         F: FnOnce(T) -> U,
     {
         match self {
-            Self::WaitForSubmissionIndex(i) => Maintain::WaitForSubmissionIndex(func(i)),
-            Self::Wait => Maintain::Wait,
-            Self::Poll => Maintain::Poll,
+            Self::WaitForSubmissionIndex(i) => PollType::WaitForSubmissionIndex(func(i)),
+            Self::Wait => PollType::Wait,
```
Comment (Wumpf) [inline wgpu-types/src/lib.rs:4038]: I'm kinda tempted to take the opportunity and bake the "non-webgpu-ness" of those wait operations into the names, but I don't know how to do so without making things worse 🤷

**Review by Wumpf — APPROVED** [review]
marvelous! <3

File: wgpu-core/src/device/global.rs (hunk 2 above)
Comment (cwfitzgerald) [reply wgpu-core/src/device/global.rs]: No, it's possible for another thread to submit in that time. Will add comments.

File: wgpu-types/src/lib.rs (hunk 7 above)
Comment (cwfitzgerald) [reply wgpu-types/src/lib.rs:4038]: Yeah... the behavior on webgpu has always been a bit cheeky...

Idk :)
