### PR TITLE
Work Around Fastclear Bug for Web and Native GL

### LINKED ISSUE #1627: Fastclear Bug With Intel Mesa Adapters on the GL Backend
**Description**
When using the OpenGL backend on Linux the clear color seems to behaving strangely. For one, the color itself is lighter than it should be. For two, the borders around any objects drawn on top of the clear color have an even lighter, pixelated version of the clear color.

I'm currently troubleshooting but I opened the issue to start the discussion. With my experimentation so far it seems completely related to the act of clearing the draw framebuffer. All other rendering and examples seem to work fine, and if you have an example where you can't see the clear color, such as the skybox example, everything looks great.

Also I've noticed some weird related behavior in my Renderdoc captures:

When I launch the example with Renderdoc it has the same problem as running it without Renderdoc ( which makes sense ):

image

And when I view the renderbuffer contents after the initial clear in renderdoc, it shows the clear color like it shows in the render, lighter than it should be:

image

The clear color shows the same in the draw step, all the way until the final framebuffer blit, where it is dark enough ( but still with pixelated edges ):

image

Yet, when I hover over the pixels in the image, the little thumbnail at the bottom shows the wrong ligher color:

image

Very strange.

I found that I could get rid of the pixelated edges by forcing the renderbuffer pixel format to be `RGBA8`, but the color was still off. I think thats the closest lead I have and I'm going to look into how different pixel formats efffect it, and maybe try binding the framebuffer storage to a texture instead of a renderbuffer and see if that makes any difference.

---

**PS:** Very excited that the new GL backend on `wgpu-hal` is working for all the examples! This is the first time I've tried it that the `shadow`, `boids`,  and `skybox` examples have worked. I might try to tackle #1617, but I figured I'd try to get this one out of the way first. :)

**Repro steps**
Run the `cube` or `shadow` example with the OpenGL backend.

**Expected vs observed behavior**
There should be no pixelated edges around objects and the clear color should be darker.

**Expected:**
image

**Actual ( I think it's fine if the lines for the trangles aren't there, the issue is the background color ) :**
image

**Extra materials**

**Shadow example:**
image

**Platform**
Running WGPU `cube` or `shadow` examples on Linux Pop!_OS ( Ubuntu ) 20.04. Adapter info:

```
[2021-07-10T16:54:11Z INFO  wgpu_hal::gles::adapter] Vendor: Intel
[2021-07-10T16:54:11Z INFO  wgpu_hal::gles::adapter] Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
[2021-07-10T16:54:11Z INFO  wgpu_hal::gles::adapter] Version: OpenGL ES 3.2 Mesa 20.0.8
[2021-07-10T16:54:11Z INFO  wgpu_hal::gles::adapter] SL version: OpenGL ES GLSL ES 3.20
```

### PR DESCRIPTION
**Pull request by zicklag**
**Connections**
Resolves #1627 

**Description**
Works around Mesa fastclear bug by doing a manual shader clear on effected platforms

**Testing**
Tested on Mesa Intel(R) UHD Graphics (CML GT2) (Gl)

### CODE REVIEW

File: wgpu-hal/src/gles/queue.rs [hunk 1]
```diff
@@ -560,7 +655,15 @@ impl super::Queue {
                 }
             }
             C::ClearColorF(draw_buffer, ref color) => {
-                gl.clear_buffer_f32_slice(glow::COLOR, draw_buffer, color);
+                if self
+                    .shared
+                    .private_caps
+                    .contains(super::PrivateCapabilities::REQUIRES_SHADER_CLEAR)
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/queue.rs:661]: This check is too general, we should only be doing this if we are clearing to an SRGB buffer.

File: wgpu-hal/src/gles/queue.rs [hunk 2]
```diff
@@ -25,17 +25,112 @@ fn is_3d_target(target: super::BindTarget) -> bool {
...
+        current_stencil_test_enabled,
+        STENCIL_TEST
+    );
+    gl_modes_set_enabled_fn!(
+        set_scissor_test_enabled,
+        current_scissor_test_enabled,
+        SCISSOR_TEST
+    );
+    gl_modes_set_enabled_fn!(set_blend_enabled, current_blend_enabled, BLEND);
+    gl_modes_set_enabled_fn!(set_cull_face_enabled, current_cull_face_enabled, CULL_FACE);
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/queue.rs:65]: If we're keeping all this state around anyway, we should be using it to deduplicate state changes.

File: wgpu-hal/src/gles/adapter.rs [hunk 3]
```diff
@@ -349,6 +393,29 @@ impl crate::Adapter<super::Api> for super::Adapter {
...
+            gl.compile_shader(fragment);
+            gl.attach_shader(program, vertex);
+            gl.attach_shader(program, fragment);
+            gl.link_program(program);
+            let color_uniform_loc = gl
+                .get_uniform_location(program, "color")
+                .expect("Could not find color uniform in shader clear shader");
+
+            Ok((program, color_uniform_loc))
+        })()
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/adapter.rs:416]: Should probably factor this out into a function.

File: wgpu-hal/src/gles/device.rs [hunk 4]
```diff
@@ -248,8 +248,10 @@ impl super::Device {
                         return Err(crate::DeviceError::Lost.into());
                     }
                     super::BindingRegister::Textures | super::BindingRegister::Images => {
-                        let loc = gl.get_uniform_location(program, name).unwrap();
-                        gl.uniform_1_i32(Some(&loc), slot as _);
+                        // The location could be none if the uniform isn't used in the shader
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/device.rs:251]: `gl.uniform_1_i32` can accept a None. In addition, glow is already performing this check for us, so we shouldn't bother.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Some comments, but in general looks good

File: wgpu-hal/src/gles/adapter.rs [hunk 5]
```diff
@@ -293,6 +321,22 @@ impl super::Adapter {
...
+        // (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4972/diffs?diff_id=75888#22f5d1004713c9bbf857988c7efb81631ab88f99_323_327)
+        // seems to indicate all skylake models are effected, so we check for renderer models that
+        // have their 3 letter code ending with `L`
+        let r = renderer.to_lowercase();
+        if r.contains("mesa")
+            && r.contains("intel")
+            && r.split(&[' ', '(', ')'][..])
+                .any(|substr| substr.len() == 3 && substr.chars().nth(2) == Some('l'))
+        {
+            private_caps.set(super::PrivateCapabilities::REQUIRES_SHADER_CLEAR, true);
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/adapter.rs:337]: We should also issue a log::warn when we enable this. Something like:

"Detected skylake derivative running on mesa i915. Clears to srgb framebuffers will use manual shader clears."

File: wgpu-hal/src/gles/adapter.rs [hunk 6]
```diff
@@ -293,6 +321,22 @@ impl super::Adapter {
...
+        // Check platforms effected by mesa bug:
+        // https://gitlab.freedesktop.org/mesa/mesa/-/issues/2565.
+        //
+        // This comment
+        // (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4972/diffs?diff_id=75888#22f5d1004713c9bbf857988c7efb81631ab88f99_323_327)
+        // seems to indicate all skylake models are effected, so we check for renderer models that
+        // have their 3 letter code ending with `L`
+        let r = renderer.to_lowercase();
+        if r.contains("mesa")
+            && r.contains("intel")
```
Comment (kvark) [inline wgpu-hal/src/gles/adapter.rs:333]: is it possible to check for Vendor ID here instead of a string? or would WebGL not give us the vendor id?

File: wgpu-hal/src/gles/adapter.rs [hunk 7]
```diff
@@ -349,6 +393,29 @@ impl crate::Adapter<super::Api> for super::Adapter {
         let zeroes = vec![0u8; super::ZERO_BUFFER_SIZE];
         gl.buffer_data_u8_slice(glow::COPY_READ_BUFFER, &zeroes, glow::STATIC_DRAW);
 
+        // Compile the shader program we use for doing manual clears to work around Mesa fastclear
+        // bug.
+        //
+        // Compile in a closure so we can use `?` to unwrap the errors and handle them all once
+        let (shader_clear_program, shader_clear_program_color_uniform_location) = (|| {
```
Comment (kvark) [inline wgpu-hal/src/gles/adapter.rs:400]: honestly, I'd rather see `unwrap()` here without any closures. Debugging closures is inconvenient, and handling failures here specifically isn't very actionable for the user anyway

File: wgpu-hal/src/gles/adapter.rs [hunk 8]
```diff
@@ -349,6 +393,29 @@ impl crate::Adapter<super::Api> for super::Adapter {
...
+            gl.shader_source(fragment, include_str!("./shader_clear.frag"));
+            gl.compile_shader(fragment);
+            gl.attach_shader(program, vertex);
+            gl.attach_shader(program, fragment);
+            gl.link_program(program);
+            let color_uniform_loc = gl
+                .get_uniform_location(program, "color")
+                .expect("Could not find color uniform in shader clear shader");
+
+            Ok((program, color_uniform_loc))
```
Comment (kvark) [inline wgpu-hal/src/gles/adapter.rs:415]: we should also delete the shaders here

File: wgpu-hal/src/gles/adapter.rs [hunk 9]
```diff
@@ -365,8 +432,19 @@ impl crate::Adapter<super::Api> for super::Adapter {
                 copy_fbo: gl
                     .create_framebuffer()
                     .map_err(|_| crate::DeviceError::OutOfMemory)?,
+                shader_clear_program,
+                shader_clear_program_color_uniform_location,
                 zero_buffer,
                 temp_query_results: Vec::new(),
+                state: Mutex::new(super::QueueState {
```
Comment (kvark) [inline wgpu-hal/src/gles/adapter.rs:439]: is this necessary to be a part of the fastclear workaround? I'd like to discuss this separately

**Review by kvark — CHANGES_REQUESTED** [review]

File: wgpu-hal/src/gles/adapter.rs (hunk 6 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/gles/adapter.rs:333]: Unfortunately it seems to have no concept of a vendor ID :(

File: wgpu-hal/src/gles/queue.rs (hunk 1 above)
Comment (zicklag) [reply wgpu-hal/src/gles/queue.rs:661]: How would I know whether or not the buffer is sRGB?

File: wgpu-hal/src/gles/adapter.rs (hunk 9 above)
Comment (zicklag) [reply wgpu-hal/src/gles/adapter.rs:439]: The mutex made it possible to modify the state ( mutable access ) while also having a reference to `self.shared.context` ( immutable access ), which rust didn't like without the mutex. There might be another way to get around that. I'll see if there's an alternative I could get working. We might just need to not do `let gl = &self.shared.context` at the top of everything so that we can still mutably access our internal state.

Comment (kvark) [reply wgpu-hal/src/gles/adapter.rs:439]: Why does the queue state need to be shared with anything?

Comment (zicklag) [reply wgpu-hal/src/gles/adapter.rs]: Ah, nevermind, it doesn't, I had just written the helper methods on `Queue` which took `&mut self` to the entire queue, when it only needed mutable access to the queue state. Moving the helper methods to the `QueueState` struct and adding an argument for the gl context fixed the borrowing issues without needing a mutex.

I pushed an update without the mutex.

File: wgpu-hal/src/gles/queue.rs (hunk 2 above)
Comment (zicklag) [reply wgpu-hal/src/gles/queue.rs]: When trying to deduplicate the changes, interestingly things stop working. Like the depth or blending not getting set correctly. I think that means our tracked state is somehow getting out of sync with the actual GL state. :/

There's not a way to query the actual GL state is there? That would be better than us tracking it outselves probably.

**Comment by kvark** [comment]
I think we don't actually need to track the GL state here. Correct me if that's wrong.
We may want to do it anyway at some point later, but right now it's not the time and place to do. We need correctness first, complexity later.

The reason why I don't think it's needed is because the clears are only done at the beginning of a render pass. This is where all the state is reset from WebGPU point of view, so the GL backend doesn't need to worry about restoring any states if it does the draw.

**Comment by zicklag** [comment]
OK, I think I addressed all of the review points with the latest push.

File: wgpu-hal/src/gles/adapter.rs [hunk 10]
```diff
@@ -349,6 +394,30 @@ impl crate::Adapter<super::Api> for super::Adapter {
...
+        gl.shader_source(fragment, include_str!("./shader_clear.frag"));
+        gl.compile_shader(fragment);
+        gl.attach_shader(shader_clear_program, vertex);
+        gl.attach_shader(shader_clear_program, fragment);
+        gl.link_program(shader_clear_program);
+        let shader_clear_program_color_uniform_location = gl
+            .get_uniform_location(shader_clear_program, "color")
+            .expect("Could not find color uniform in shader clear shader");
+        gl.delete_shader(vertex);
+        gl.delete_shader(fragment);
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/adapter.rs:419]: This should still be its own function.

File: wgpu-hal/src/gles/mod.rs [hunk 11]
```diff
@@ -562,7 +572,7 @@ enum Command {
     },
     InvalidateAttachments(InvalidatedAttachments),
     SetDrawColorBuffers(u8),
-    ClearColorF(u32, [f32; 4]),
+    ClearColorF(u32, [f32; 4], bool /* is sRGB */),
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/mod.rs:575]: Could we give these names instead of being a tuple

File: wgpu-hal/src/gles/mod.rs [hunk 12]
```diff
@@ -113,13 +115,16 @@ bitflags::bitflags! {
...
+        const SHADER_TEXTURE_SHADOW_LOD = 1 << 1;
         /// Support memory barriers.
-        const MEMORY_BARRIERS = 0x0004;
+        const MEMORY_BARRIERS = 1 << 2;
         /// Vertex buffer layouts separate from the data.
-        const VERTEX_BUFFER_LAYOUT = 0x0008;
+        const VERTEX_BUFFER_LAYOUT = 1 << 3;
+        /// Indicates that we must do a manual shader clear instead of using `gl.clear_buffer` to
+        /// workaround Mesa fastclear bugs.
+        const REQUIRES_SHADER_CLEAR = 1 << 4;
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/mod.rs:127]:
```suggestion
        const DRIVER_WORKAROUND_SRGB_SHADER_CLEAR = 1 << 4;
```

open to bikesheding (@kvark)

I want to see which of these are a problem with the driver and which are a device limitation.

File: wgpu-hal/src/gles/mod.rs [hunk 13]
```diff
@@ -113,13 +115,16 @@ bitflags::bitflags! {
...
         /// Support extended shadow sampling instructions.
-        const SHADER_TEXTURE_SHADOW_LOD = 0x0002;
+        const SHADER_TEXTURE_SHADOW_LOD = 1 << 1;
         /// Support memory barriers.
-        const MEMORY_BARRIERS = 0x0004;
+        const MEMORY_BARRIERS = 1 << 2;
         /// Vertex buffer layouts separate from the data.
-        const VERTEX_BUFFER_LAYOUT = 0x0008;
+        const VERTEX_BUFFER_LAYOUT = 1 << 3;
+        /// Indicates that we must do a manual shader clear instead of using `gl.clear_buffer` to
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/mod.rs:125]: Could we get all the information about the bug here. Then the documentation for the workaround can point to the documentation of this flag.

This way we can have all driver bugs shown off in one place.

File: wgpu-hal/src/gles/shader_clear.vert [hunk 14]
```diff
@@ -0,0 +1,11 @@
+#version 300 es
+precision lowp float;
+// A triangle that fills the whole screen
+const vec2[3] TRIANGLE_POS = vec2[](
+  vec2( 0., -3.),
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/shader_clear.vert:5]: I have a small personal vendetta against omitting the trailing `0` from floats. Could you add them back :)

File: wgpu-hal/src/gles/adapter.rs [hunk 15]
```diff
@@ -161,17 +161,42 @@ impl super::Adapter {
...
+        let (vendor, renderer) = {
+            let vendor = gl.get_parameter_string(glow::VENDOR);
+            let renderer = gl.get_parameter_string(glow::RENDERER);
+
+            (vendor, renderer)
+        };
+        #[cfg(target_arch = "wasm32")]
+        let (vendor, renderer) = {
+            let vendor_const = if extensions.contains("WEBGL_debug_renderer_info") {
+                0x9245 // UNMASKED_VENDOR_WEBGL
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/adapter.rs:176]: Could we get these magic numbers as constants

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
A few more minor things, but this looks good.

File: wgpu-hal/src/gles/mod.rs (hunk 12 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/gles/mod.rs:127]: A few other options: `WORKAROUND_MESA_I915_SRGB_SHADER_CLEAR`, `WORKAROUND_MESA_SRGB_SHADER_CLEAR`

**Comment by zicklag** [comment]
There you go! I went with the most specific `PrivateCapabilities` flag name: `WORKAROUND_MESA_I915_SRGB_SHADER_CLEAR`. I don't care what we go with final, just let me know if you want to change it.

**Comment by zicklag** [comment]
Oh, wait! The shadow example is only clearing half the screen for some reason. Got to check that out.

**Comment by zicklag** [comment]
OK, fixed it, had to set the viewport and scissor before clearing.

File: wgpu-hal/src/gles/adapter.rs [hunk 16]
```diff
@@ -293,6 +323,24 @@ impl super::Adapter {
             ver >= (3, 1),
         );
 
+        let r = renderer.to_lowercase();
+        // Check for Mesa sRGB clear bug. See
+        // [`super::PrivateCapabilities::WORKAROUND_MESA_SRGB_SHADER_CLEAR`].
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/adapter.rs:328]: This link is wrong, and it's concerning that this wasn't caught.

**Review by cwfitzgerald — APPROVED** [review]

File: wgpu-hal/src/gles/adapter.rs (hunk 16 above)
Comment (zicklag) [reply wgpu-hal/src/gles/adapter.rs:328]: Ah, yeah, it's not actually a doc comment, so it's not checked by the doc tools or anything. I just used the same style. I'll fix it.

File: wgpu-hal/src/gles/command.rs [hunk 17]
```diff
@@ -421,10 +421,7 @@ impl crate::CommandEncoder<super::Api> for super::CommandEncoder {
             }
         }
 
-        // set the draw buffers and states
-        self.cmd_buffer
```
Comment (kvark) [inline wgpu-hal/src/gles/command.rs:425]: I don't think we can do this, since the draw targets are required for the clears on the normal path

File: wgpu-hal/src/gles/queue.rs [hunk 18]
```diff
@@ -559,8 +581,21 @@ impl super::Queue {
...
+                ref color,
+                is_srgb,
+            } => {
+                if self
+                    .shared
+                    .private_caps
+                    .contains(super::PrivateCapabilities::WORKAROUND_MESA_I915_SRGB_SHADER_CLEAR)
+                    && is_srgb
+                {
+                    self.perform_shader_clear(draw_buffer, *color);
```
Comment (kvark) [inline wgpu-hal/src/gles/queue.rs:595]: I mentioned that we can't postpone `SetDrawBuffers`. My suggestion is the following:
The queue would have the "draw_buffer_count: u32" field as a part of the state, setup by `SetDrawBuffers` in addition to what it does today. Then `fn perform_shader_clear` can reset to this mask after it's done.

**Comment by zicklag** [comment]
Pushed another update. :+1:

File: wgpu-hal/src/gles/adapter.rs [hunk 19]
```diff
@@ -161,17 +166,42 @@ impl super::Adapter {
...
+        #[cfg(not(target_arch = "wasm32"))]
+        let (vendor, renderer) = {
+            let vendor = gl.get_parameter_string(glow::VENDOR);
+            let renderer = gl.get_parameter_string(glow::RENDERER);
+
+            (vendor, renderer)
+        };
+        #[cfg(target_arch = "wasm32")]
+        let (vendor, renderer) = {
+            let vendor_const = if extensions.contains("WEBGL_debug_renderer_info") {
```
[the remark this answers is not in the document]
Comment (cwfitzgerald) [reply wgpu-hal/src/gles/adapter.rs:170]: I think what he meant was

```
let (vendor, renderer) = if extensions.contains("WEBGL_debug_renderer_info") {
     (GL_UNMASKED_VENDOR_WEBGL, GL_UNMASKED_RENDERER_WEBGL)
else {
     (glow::VENDOR, glow::RENDERER)
}
```

File: wgpu-hal/src/gles/mod.rs [hunk 20]
```diff
@@ -113,13 +115,26 @@ bitflags::bitflags! {
...
+bitflags::bitflags! {
+    /// Flags that indicate necessary workarounds for specific devices or driver bugs
+    struct Workarounds: u32 {
+        // Needs workaround for Intel Mesa bug:
+        // https://gitlab.freedesktop.org/mesa/mesa/-/issues/2565.
+        //
+        // This comment
+        // (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4972/diffs?diff_id=75888#22f5d1004713c9bbf857988c7efb81631ab88f99_323_327)
+        // seems to indicate all skylake models are effected.
+        const WORKAROUND_MESA_I915_SRGB_SHADER_CLEAR = 1 << 0;
```
Comment (cwfitzgerald) [inline wgpu-hal/src/gles/mod.rs:137]: Now that this is in a workarounds struct, the individual const shouldn't be prefixed with WORKAROUND

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
This has had a lot of iterations, thanks for sticking with us! We're getting close.

File: wgpu-hal/src/gles/adapter.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (zicklag) [reply wgpu-hal/src/gles/adapter.rs]: Ah, that makes more sense. :) Pushed an update.

File: wgpu-hal/src/gles/mod.rs (hunk 20 above)
Comment (zicklag) [reply wgpu-hal/src/gles/mod.rs]: That makes sense. Fixed!

**Review by cwfitzgerald — APPROVED** [review]
Looks good from my end. Just want kvark to take one last look. Does this make all the GL tests pass on your machine?

**Comment by zicklag** [comment]
One of the skybox tests is the only failing one, and that one fails on master so I think it's unrelated.

**Comment by cwfitzgerald** [comment]
Alright, sounds fine.

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
bors r=cwfitzgerald,kvark
