### PR TITLE
Ignore maxFragmentCombinedOutputResources for Mesa's Honeykrisp driver

### LINKED ISSUE #9391: Limits exceeded error using wgpu 29 on Asahi Linux on MacBook m2
**Description**
Using Asahi Linux on an M2 MacBook Pro, I can no longer request a device using default limits. I suspect this is related to (or at least in the same ballpark as) [9287](https://github.com/gfx-rs/wgpu/issues/9287), but because the render backend isn't actually Metal in this case any fixes or workarounds in the Metal adapter wouldn't apply.

**Repro steps**
Try to request a device with default limits, like below:
```
    let instance = wgpu::Instance::default();

    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions::default())
        .await?;

    let _ = adapter
        .request_device(&wgpu::DeviceDescriptor {
            required_limits: wgpu::Limits::defaults(),
            ..Default::default()
        })
        .await?;
```

**Expected vs observed behavior**
On 28.0.0 and before the code above works, but on 29.0.0 and 29.0.1 I get
`Error: RequestDeviceError { inner: Core(LimitsExceeded(FailedLimit { name: "max_color_attachments", requested: 8, allowed: 5 })) }`

**Platform**
Asahi Linux on M2 Macbook Pro J493

### PR DESCRIPTION
**Pull request by im-0**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/9391

**Description**

Currently, many wgpu apps that request the device with Limits::defaults() fail to start on Asahi Linux with following error message:

	Limit 'max_color_attachments' value 8 is better than allowed 5

This includes wgpu's own `wgpu-example-02-hello-window`.

Value of '5' looked weirdly non-power-of-two and thus hightly sus, so I tried to investigate where exactly wgpu gets it. It looks like this was recently added by f06431f6de9a7d28fde1dd727c3cfebb5305f0c2: new code divides maxFragmentCombinedOutputResources by 3 for all GPU vendors except of those who produce known to be wrong maxFragmentCombinedOutputResources.

I am not 100% sure that Honeykrisp driver should also be exempt from this, but glxinfo reports GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES=248 on the same Apple M2 Max laptop with Asahi's OpenGL driver. If I understand correctly, GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES is a closest analog for maxFragmentCombinedOutputResources. It seems that `max_combined_shader_output_resources` is never set by OpenGL driver[1] and instead calculated by adding underlying limits by some "defaults" handling code. Also, as the same wgpu allows the same limits just fine on macOS with Metal backend on the same hardware, underlying hardware seems to support those limits.

If you are interested, maxFragmentCombinedOutputResources=16 for Honeykrisp was added by initial commit[2] and never changed since.

[1] https://gitlab.freedesktop.org/mesa/mesa/-/tree/main/src/gallium/drivers/asahi
[2] https://gitlab.freedesktop.org/mesa/mesa/-/commit/5bc828481630147575348b66677edaade9e891e6#line_ed3b525e6_A660

**Testing**
No idea about what is the right way to test this. I just ran `cargo xtask test` before and after the patch.

**Checklist**

- [X] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [X] Run `cargo clippy --tests`.
- [X] Run `cargo xtask test` to run tests. Same amount of failed tests with and without this patch (llvmpipe seems unrelated):
```text
     Summary [  20.284s] 1551 tests run: 1511 passed, 40 failed, 18 skipped
        FAIL [   0.003s] naga::naga snapshots::convert_snapshots_spv
        FAIL [   0.165s] player::player test_api
        FAIL [   1.174s] wgpu-examples [Executed Failure: BACKEND] [Vulkan/Apple M2 Max (G14C B1)/0] water
        FAIL [   1.231s] wgpu-examples [Executed Failure: BACKEND] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] water
     SIGSEGV [   0.255s] wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] ray_aabb_compute
     SIGSEGV [   0.258s] wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] ray_cube_compute
     SIGSEGV [   0.320s] wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] ray_cube_fragment
     SIGSEGV [   0.209s] wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] ray_cube_normals
     SIGSEGV [   0.208s] wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] ray_scene
     SIGSEGV [   0.322s] wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] ray_shadows
     SIGSEGV [   0.345s] wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] ray_traced_triangle
        FAIL [   0.074s] wgpu-test::wgpu-gpu [Executed Failure: BACKEND] [Vulkan/Apple M2 Max (G14C B1)/0] wgpu_gpu::regression::issue_5231_9343::read_only_depth_with_sampled_binding
        FAIL [   0.090s] wgpu-test::wgpu-gpu [Executed Failure: BACKEND] [Vulkan/Apple M2 Max (G14C B1)/0] wgpu_gpu::regression::issue_5231_9343::read_only_depth_without_texture_binding
        FAIL [   0.118s] wgpu-test::wgpu-gpu [Executed Failure: BACKEND] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::regression::issue_5231_9343::read_only_depth_with_sampled_binding
        FAIL [   0.101s] wgpu-test::wgpu-gpu [Executed Failure: BACKEND] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::regression::issue_5231_9343::read_only_depth_without_texture_binding
        FAIL [   0.058s] wgpu-test::wgpu-gpu [Executed] [Vulkan/Apple M2 Max (G14C B1)/0] wgpu_gpu::multiview::draw_multiview_noncontiguous
        FAIL [   0.071s] wgpu-test::wgpu-gpu [Executed] [Vulkan/Apple M2 Max (G14C B1)/0] wgpu_gpu::passthrough::all_passthrough_shaders_binary
        FAIL [   0.047s] wgpu-test::wgpu-gpu [Executed] [Vulkan/Apple M2 Max (G14C B1)/0] wgpu_gpu::passthrough::all_passthrough_shaders_source
        FAIL [   0.054s] wgpu-test::wgpu-gpu [Executed] [Vulkan/Apple M2 Max (G14C B1)/0] wgpu_gpu::passthrough::spirv_passthrough_shader
        FAIL [   0.080s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::binding_array::samplers::binding_array_samplers
        FAIL [   0.039s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::binding_array::samplers::partial_binding_array_samplers
     SIGSEGV [   0.201s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::binding_array::tlas::binding_array_tlas
        FAIL [   0.080s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::passthrough::all_passthrough_shaders_binary
        FAIL [   0.068s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::passthrough::all_passthrough_shaders_source
        FAIL [   0.065s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::passthrough::spirv_passthrough_shader
     SIGSEGV [   0.270s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_aabb::aabb_blas_build_and_trace
     SIGSEGV [   0.317s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::blas_compaction
     SIGSEGV [   0.305s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::blas_compaction_without_flags
     SIGSEGV [   0.288s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::blas_first_vertex
     SIGSEGV [   0.276s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::build_with_transform
     SIGSEGV [   0.224s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::extra_format_build
     SIGSEGV [   0.291s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::only_blas_vertex_return
     SIGSEGV [   0.200s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::out_of_order_as_build
     SIGSEGV [   0.296s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::out_of_order_as_build_use
     SIGSEGV [   0.234s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_build::unprepared_blas_compaction
     SIGSEGV [   0.267s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::as_use_after_free::acceleration_structure_use_after_free
     SIGSEGV [   0.240s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::scene::acceleration_structure_build_no_index
     SIGSEGV [   0.323s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::scene::acceleration_structure_build_with_index
     SIGSEGV [   0.195s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::shader::access_all_struct_members
     SIGSEGV [   0.204s] wgpu-test::wgpu-gpu [Executed] [Vulkan/llvmpipe (LLVM 21.1.8, 128 bits)/1] wgpu_gpu::ray_tracing::shader::prevent_invalid_ray_query_calls
```
- [X] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by im-0** [comment]
Created new issue in Mesa: https://gitlab.freedesktop.org/mesa/mesa/-/work_items/15249

File: wgpu-hal/src/vulkan/adapter.rs [hunk 1]
```diff
@@ -1484,7 +1484,15 @@ impl PhysicalDeviceProperties {
...
-        .contains(&self.properties.vendor_id);
+        .contains(&self.properties.vendor_id)
+            || self
+                .driver
+                .map(|driver| {
+                    // Honeykrisp uses Mesa's default vendor_id, so we check driver_id instead.
+                    self.properties.vendor_id == crate::auxil::db::mesa::VENDOR
+                        && driver.driver_id.as_raw() == 26 // VK_DRIVER_ID_MESA_HONEYKRISP
+                })
+                .unwrap_or(false);
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/adapter.rs]: Style thing, can we split this into two expressions, one for vendor, one for driver, then we can form `ignore_max_fragment_combined_output_resources` from the OR of it.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
LGTM minus some nits, this is a mesa bug, but we will need to ignore it on older driver versions anyway. Per the upstream bug we should also ignore it on mvk,

**Comment by im-0** [comment]
> Per the upstream bug we should also ignore it on mvk,

You mean nvk? Existing code already catches that by vendor_id == crate::auxil::db::nvidia::VENDOR. And now, when I am thinking about it, this feels like wrong thing to do. maxFragmentCombinedOutputResources is reported by driver, but there are multiple independent driver implementations for at least NV, AMD and Intel GPUs.

**Comment by marysaka** [comment]
> LGTM minus some nits, this is a mesa bug, but we will need to ignore it on older driver versions anyway. Per the upstream bug we should also ignore it on mvk,

For reference, I just tested on NVK and https://github.com/gfx-rs/wgpu/issues/9391https://github.com/gfx-rs/wgpu/issues/9391 does not reproduce (but it reproduce as expected on Honeykrisp)
In any cases, I will push a fix for maxFragmentCombinedOutputResources limit on NVK side.

EDIT: Seems that I missed the vendorID ignore... this should really match on the driver ID and not the vendorID.

File: wgpu-hal/src/vulkan/adapter.rs (hunk 1 above)
Comment (im-0) [reply wgpu-hal/src/vulkan/adapter.rs]: I split it and made look more like existing code, so it is easier to add more drivers. Also found that DriverId already has the right constant.

File: wgpu-hal/src/vulkan/adapter.rs [hunk 2]
```diff
@@ -1493,13 +1493,20 @@ impl PhysicalDeviceProperties {
...
+        let ignore_max_fragment_combined_output_resources_by_device = [
             crate::auxil::db::intel::VENDOR,
             crate::auxil::db::nvidia::VENDOR,
             crate::auxil::db::amd::VENDOR,
             crate::auxil::db::imgtec::VENDOR,
         ]
         .contains(&self.properties.vendor_id);
+        let ignore_max_fragment_combined_output_resources_by_driver = self
+            .driver
+            .map(|driver| [vk::DriverId::MESA_AGXV].contains(&driver.driver_id))
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/adapter.rs:1505]: Unrelated: What does AGXV stand for?

**Review by cwfitzgerald — APPROVED** [review]
Thanks!

File: wgpu-hal/src/vulkan/adapter.rs (hunk 2 above)
Comment (im-0) [reply wgpu-hal/src/vulkan/adapter.rs:1505]: AGX is Apple GPU - https://asahilinux.org/docs/hw/soc/agx/
V is for Vulkan, I suppose.

Comment (marysaka) [reply wgpu-hal/src/vulkan/adapter.rs:1505]: Apple GPU (AGX) Vulkan probably? It was renamed a while ago to Honeykrisp so I suppose the Vulkan bindings you are using are a bit older.
