### PR TITLE
fix(core): Flush pending writes before mapAsync, if needed

### LINKED ISSUE #5173: Read-mapped buffer content incorrect unless a submission happens between write and read
**Description**

This is visible during CTS runs, but it was already filed against wgpu-native a while back in https://github.com/gfx-rs/wgpu-native/issues/305.

See the test below. It creates a mapped buffer, writes data into it, unmaps it, maps it again and checks that the content matches what was written. 

**Repro steps**

```rust
#[gpu_test]
static MAP_WITHOUT_SUBMIT: GpuTestConfiguration = GpuTestConfiguration::new().run_async(|ctx| async move {
    let buffer = ctx.device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: 12,
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: true,
    });

    {
        let mut mapped = buffer.slice(0..12).get_mapped_range_mut();
        assert!(mapped.len() == 12);
        for (i, elt) in mapped.iter_mut().enumerate() {
            *elt = (i %255) as u8;
        }    
    }

    buffer.unmap();

    // Uncommenting this makes the test pass
    //ctx.queue.submit([]);

    buffer.slice(0..12).map_async(wgpu::MapMode::Read, Result::unwrap);

    ctx.async_poll(wgpu::Maintain::wait())
        .await
        .panic_on_timeout();

    {
        let mapped = buffer.slice(0..12).get_mapped_range();
        assert!(mapped.len() == 12);
        for (i, elt) in mapped.iter().enumerate() {
            assert_eq!(*elt, (i %255) as u8); // Boom.
        }
    }

    buffer.unmap();
});
```

**Expected vs observed behavior**

The above test should pass but currently doesn't unless the submit call is uncommented.

**Extra materials**

The failing cts test is `webgpu:api,operation,buffers,map:mapAsync,read:mapAsyncRegionLeft="default-expand";mapAsyncRegionRight="default-expand"`

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.

### PR DESCRIPTION
**Pull request by andyleiserson**
Fixes #5173. Also fixes an open TODO to flush pending writes in `on_submitted_work_done`.

Based on top of #9439 and #9444. The changes for this PR are the commits after the merge commit.

This implements the strategy @teoxoy suggested in [bug 1994733, comment 6](https://bugzilla.mozilla.org/show_bug.cgi?id=1994733#c6): if `mapAsync` finds that `PendingWrites` holds writes for the buffer being mapped, then `PendingWrites` is flushed/submitted before mapping the buffer.

This strategy never makes `Queue::writeBuffer` or `unmap` perform a submission. A submission only happens if/when `mapAsync` is called for a buffer with pending writes. This has the nice property that `mapAsync` was already an operation that might have to wait on the queue, although this change broadens the circumstances when that will happen and may increase the amount of queued work that `mapAsync` has to wait on. (More sophisticated approaches would be to only flush the pending writes for the buffer in question, rather than all of them, or to proactively flush pending writes if the queue is idle, to reduce the chance that `mapAsync` ends up waiting on them.)

There is a [long-standing TODO in `mapAsync` about possibly needing a barrier](https://github.com/gfx-rs/wgpu/issues/9306). I briefly considered trying to address that as part of that change, but I think it's a separable concern, and comes with its own set of performance risks that it is better not to lump together with this change.

**Testing**
Adds a directed test and some CTS tests.

**Squash or Rebase?** Rebase

**Checklist**

- [x] Need to add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-core/src/resource.rs [hunk 1]
```diff
@@ -654,50 +658,72 @@ impl Buffer {
...
-                }
-                BufferMapState::Idle => BufferMapState::Waiting(BufferPendingMapping {
-                    range: offset..end_offset,
-                    op,
-                    _parent_buffer: self.clone(),
-                }),
-            };
-        }
+            // Review note: the code previously dropped the snatch lock here. I don't see how
+            // that was correct, if we drop it then the buffer could be destroyed.
```
Comment (teoxoy) [inline wgpu-core/src/resource.rs:672]: I think it was ok because we were not using the raw hal buffer for any operation but we were chaning state on the core buffer so, maybe we could have gotten into an unexpected situation.

File: wgpu-core/src/resource.rs [hunk 2]
```diff
@@ -329,6 +331,8 @@ impl WebGpuError for BufferAccessError {
             Self::InvalidResource(e) => e.webgpu_error_type(),
             Self::DestroyedResource(e) => e.webgpu_error_type(),
 
+            Self::QueueSubmit(_) => ErrorType::Internal,
```
Comment (teoxoy) [inline wgpu-core/src/resource.rs:334]: The spec allows the internal variant to only be returned by pipeline creation.

File: wgpu-core/src/device/queue.rs [hunk 3]
```diff
@@ -1159,6 +1160,40 @@ impl Queue {
...
+            Err((
+                _,
+                e @ E::BufferStillMapped(_)
+                | e @ E::CommandEncoder(_)
+                | e @ E::ValidateAsActionsError(_),
+            )) => {
+                // These errors are not expected. Encode them as a string, because
+                // some of them are not serializable, while `BufferAccessError` is.
+                log::debug!("Unexpected error flushing writes for buffer: {e}");
+                Err(BufferAccessError::QueueSubmit(e.to_string()))
```
Comment (teoxoy) [inline wgpu-core/src/device/queue.rs:1192]: I think we should either panic here or add a new submit function to make it impossible for these variants to be returned.

Comment (teoxoy) [reply wgpu-core/src/device/queue.rs:1192]: Refactoring the submit function to be used by a new submit function that doesn't return these variants seems a lot more tricky.

Comment (teoxoy) [reply wgpu-core/src/device/queue.rs:1192]: Maybe it's possible to take out this block and call it from `map_async`.

https://github.com/gfx-rs/wgpu/blob/a58f51a2568b0ec52717f79f8f23140c3d8968af/wgpu-core/src/device/queue.rs#L1375-L1470

Below it we call `device.maintain` to cleanup resources of previous submissions but I don't think we should do that in `map_async`.

**Review by teoxoy — COMMENTED** [review]
Good stuff!

**Review by jimblandy — CHANGES_REQUESTED** [review]
If I understand correctly, this patch could invoke user callbacks from `Buffer::map_async`. This is new user-visible behavior (potentially unexpected, but I bet it'll be okay). There are a few places in the wgpu documentation that explain when callbacks get invoked that should be updated. For example:
- the docs for `Buffer::map_async`
- the module-level documentation for `Buffer` 
- the docs for `Queue::on_submitted_work_done`

There may be other spots. i'd look for references to `poll`.

**Comment by jimblandy** [comment]
Oh, and obviously, the change in callback behavior needs prominent mention in the CHANGELOG.

**Review by jimblandy — CHANGES_REQUESTED** [review]
It is not correct to hoist the snatch lock acquisition outside `Queue::submit`. The user's callbacks must always be invoked while wgpu-core is holding no locks, but this change lets `submit_inner` invoke them while its caller holds the Device's snatch lock.

**Comment by andyleiserson** [comment]
> It is not correct to hoist the snatch lock acquisition outside `Queue::submit`. The user's callbacks must always be invoked while wgpu-core is holding no locks, but this change lets `submit_inner` invoke them while its caller holds the Device's snatch lock.

It doesn't hold the snatch lock while calling callbacks -- the guard is moved into `device.maintain`, which drops it. (That was the case before I made any changes, but I did have to study it, since at first glance the lock does appear to be released due to going out of scope.) I added a comment about this on line 1528, but probably a comment on `fn submit` itself would be appropriate, assuming we don't undertake a bigger refactoring of `submit`.

**Comment by jimblandy** [comment]
> It doesn't hold the snatch lock while calling callbacks -- the guard is moved into device.maintain, which drops it. 

Okay, I was misreading the code. Yes, this isn't a problem after all.

File: wgpu-core/src/device/queue.rs (hunk 3 above)
Comment (teoxoy) [reply wgpu-core/src/device/queue.rs:1192]: A heads-up: @atlv24 has pulled this out in https://github.com/gfx-rs/wgpu/pull/9361.

**Comment by andyleiserson** [comment]
I have a version of this updated based on #9361, but it has a new test failure in `webgpu:api,operation,buffers,map:mapAsync,write,*` that was not present with the original version.

**Comment by teoxoy** [comment]
What is the new test failure?

File: wgpu-core/src/device/queue.rs (hunk 3 above)
Comment (andyleiserson) [reply wgpu-core/src/device/queue.rs]: Updated this PR with a slightly more general version of `submit_with_pending_writes`.

**Comment by andyleiserson** [comment]
> What is the new test failure?

The new test failure was a silly mistake in the refactoring I did of `submit_with_pending_writes` where I wasn't actually submitting the things I intended to submit 🤦.

**Comment by andyleiserson** [comment]
In the latest version I've also added a flush of pending writes in `on_submitted_work_done` (which was noted in a TODO).

File: wgpu-core/src/device/queue.rs [hunk 4]
```diff
@@ -1487,22 +1495,88 @@ impl Queue {
...
-        submit_index: SubmissionIndex,
-        snatch_guard: &SnatchGuard,
-    ) -> Result<(), DeviceError> {
+        prepared: PendingSubmission<'a>,
+    ) -> Result<SubmissionResult<'a>, DeviceError> {
+        let PendingSubmission {
+            queue: _,
+            snatch_guard,
+            mut fence,
+            command_index_guard: _,
```
Comment (teoxoy) [inline wgpu-core/src/device/queue.rs:1570]: Does the `command_index_guard: _,` syntax drop the lock immediately?

Prior to #9361 `command_index_guard` was being dropped right after `self.raw().submit(` and before `self.lock_life()`.

https://github.com/gfx-rs/wgpu/blob/7143bbe882bf0bd01dbfb1d5a43e5004f7bf854a/wgpu-core/src/device/queue.rs#L1454-L1479

I think it has to be dropped after `self.raw().submit(` due to https://github.com/gfx-rs/wgpu/issues/5978.

File: wgpu-core/src/resource.rs [hunk 5]
```diff
@@ -693,50 +692,82 @@ impl Buffer {
...
 
-        // TODO: we are ignoring the transition here, I think we need to add a barrier
-        // at the end of the submission
+        // At this point, `submit_index` is:
+        // - `Some(index)`, if there is a submission the mapping operation must wait for.
+        // - `Some(0)`, if we have a queue and there is no submission to wait for.
+        // - `None`, if we don't have a queue.
+        //
+        // TODO: Is it okay to unlock the snatch lock and lifetime tracker before updating
+        // the tracker?
```
Comment (teoxoy) [inline wgpu-core/src/resource.rs:750]: I think so, the snatch lock is meant to protect access to some HAL resources and the lifetime tracker tracks the queue's state.

I can imagine us renaming the `LifetimeTracker` to be `QueueState` and moving the `DeviceTracker` to be a field of `QueueState` especially with the multi queue requirements where the states of resources are different on each queue.

**Review by teoxoy — APPROVED** [review]
Looks good, I only have one last concern.

File: wgpu-core/src/device/queue.rs [hunk 6]
```diff
@@ -211,23 +209,13 @@ impl Queue {
         pending_writes.insert_texture(texture);
 
         // Flush pending writes through the standard submission path.
-        let mut surface_textures = FastHashMap::default();
-        surface_textures.insert(Arc::as_ptr(texture), texture.clone());
+        submission
+            .surface_textures
+            .insert(Arc::as_ptr(texture), texture.clone());
```
Comment (andyleiserson) [inline wgpu-core/src/device/queue.rs:215]: I'm not sure if this is actually needed here. We've added the texture to `pending_writes`, and submission already scans for surface textures in pending writes.

I'm actually not sure whether we need to have `submission.surface_textures` at all. Instead of collecting surface textures in `validate_command_buffer` and transitioning them in `submit`, we could combine that with the texture transition logic for pending writes in `submit_pending_submission`. But that would be a bigger refactoring.

Comment (teoxoy) [reply wgpu-core/src/device/queue.rs:215]: That does sound right, `pending_writes.insert_texture(texture);` was added in a later revision of https://github.com/gfx-rs/wgpu/pull/9361, so I think we can simplify things now.

File: wgpu-core/src/device/queue.rs (hunk 4 above)
Comment (andyleiserson) [reply wgpu-core/src/device/queue.rs]: > Does the `command_index_guard: _,` syntax drop the lock immediately?

It does, this is a great catch, thank you.

Comment (kpreid) [reply wgpu-core/src/device/queue.rs]: This isn’t true. An `_` pattern does not drop what it matches; it *leaves it alone*, not dropping, moving, or borrowing it. After this line executes, `command_index_guard` is still owned by the variable `prepared` (the `PendingSubmission` is *partially moved*).

<details><summary>Demo</summary>

```rust
struct Noisy(&'static str);

impl Drop for Noisy {
    fn drop(&mut self) {
        println!("dropped Noisy({})", self.0);
    }
}

struct Container {
    a: Noisy,
    b: Noisy,
}

#[test]
fn test() {
    let c = Container {
        a: Noisy("a"),
        b: Noisy("b"),
    };

    println!("destructuring container, ignoring b");
    let Container { a, b: _ } = c;

    println!("dropping a");
    drop(a);

    // Uncomment this if you like; b is dropped after a in either case.
    // println!("dropping b");
    // drop(c.b);

    println!("end of function");
}
```

</details>

That said, dropping it explicitly might be better for clarity regardless.

Comment (andyleiserson) [reply wgpu-core/src/device/queue.rs]: Welp, you're right, I made the mistake of trusting Claude on this. And worse, after you flagged this, I went back and asked if it was sure to see what it would say, and it said yes and offered a bogus test case that destructured a temporary. And then when I pointed that out it said (emphasis added):

> My original conclusion holds — `_` does drop the guard at the end of the statement — but _**the mechanism is more precise than I initially described**_. It's not that `_` "receives and discards" the value. It's that `_` doesn't move the value at all, so the value stays in the temporary, which is dropped at statement end. The distinction matters conceptually even if the observable behavior is the same.

Yikes. I had not seen Claude do this as much as ChatGPT.

But I do think the confusion here supports dropping it explicitly for clarity.

File: wgpu-core/src/device/queue.rs (hunk 6 above)
Comment (andyleiserson) [reply wgpu-core/src/device/queue.rs:215]: I am going to address this in #9473.
