### PR TITLE
fix Metal leaking resources 

### LINKED ISSUE #8018: Metal resources appear to be leaking in fuzzing runs
Metal resources appear to be leaking in my fuzzing runs. The runs reliably crash with an OOM error after running ~700k-800k cases. This is the write_texture_v2 fuzzer at SHA `0dc6ae7f5` (which is on my local branch and therefore only useful for myself). I haven't seen a similar problem in my runs with `vulkan-portability`, although I don't consider that conclusive evidence that the problem is with the metal backend, since lots of factors could affect whether and when the OOM happens.

I have not ruled out that there's something missing in the fuzzing harness that is causing this, but at first glance it seems to me like dropping the `Global` should drop the `Hub` it contains and in doing so release all of the resources.

<details><summary>Allocation details</summary>

```
==13340== ERROR: libFuzzer: out-of-memory (used: 2055Mb; limit: 2048Mb)
   To change the out-of-memory limit use -rss_limit_mb=<N>

Live Heap Allocations: 841622062 bytes in 15360005 chunks; quarantined: 32734401 bytes in 95680 chunks; 427615 other chunks; total chunks: 15883300; showing top 95% (at most 8 unique contexts)
89539744 byte(s) (10%) in 799462 allocation(s)
    #0 0x000106312b98 in calloc+0x74 (librustc-nightly_rt.asan.dylib:arm64+0x52b98)
    #1 0x00018d70faf8 in _malloc_type_calloc_outlined+0x64 (libsystem_malloc.dylib:arm64+0x1daf8)
    #2 0x00018d505ef4 in _objc_rootAllocWithZone+0x30 (libobjc.A.dylib:arm64+0xdef4)
    #3 0x000198ceca64 in +[MTLCommandQueueDescriptor allocWithZone:]+0x4c (Metal:arm64+0x9a64)
    #4 0x00018d538d00 in objc_alloc_init+0x4c (libobjc.A.dylib:arm64+0x40d00)
    #5 0x000198dcf590 in -[_MTLDevice newCommandQueueWithMaxCommandBufferCount:]+0x24 (Metal:arm64+0xec590)
    #6 0x0001041c1d60 in wgpu_hal::metal::adapter::_$LT$impl$u20$wgpu_hal..Adapter$u20$for$u20$wgpu_hal..metal..Adapter$GT$::open::h2cc953a2f29e2d85 adapter.rs:54
    #7 0x000103733420 in _$LT$A$u20$as$u20$wgpu_hal..dynamic..adapter..DynAdapter$GT$::open::h19b7903c78d12d16 adapter.rs:48
    #8 0x000103cfccb0 in wgpu_core::instance::Adapter::create_device_and_queue::h19c8411351e7f159 instance.rs:826
    #9 0x000103d0677c in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::adapter_request_device::h8e7cbad23166498a instance.rs:1114
    #10 0x000104302174 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:66
    #11 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #12 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #13 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #14 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #15 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #16 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #17 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #18 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #19 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #20 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #21 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

63956960 byte(s) (7%) in 799462 allocation(s)
    #0 0x000106313058 in __sanitizer_mz_calloc+0xd0 (librustc-nightly_rt.asan.dylib:arm64+0x53058)
    #1 0x00018d725318 in _malloc_zone_calloc_instrumented_or_legacy+0x80 (libsystem_malloc.dylib:arm64+0x33318)
    #2 0x00018d70fccc in _malloc_type_zone_calloc_outlined+0x44 (libsystem_malloc.dylib:arm64+0x1dccc)
    #3 0x00018d964ca8 in _CFRuntimeCreateInstance+0x1ec (CoreFoundation:arm64+0x3ca8)
    #4 0x00018da6cd38 in __CFDataInit+0xa8 (CoreFoundation:arm64+0x10bd38)
    #5 0x00018ef73ef4 in bytesInEncoding+0xb0 (Foundation:arm64+0x22ef4)
    #6 0x00018d9b8f6c in -[__NSCFString UTF8String]+0x48 (CoreFoundation:arm64+0x57f6c)
    #7 0x000102c81340 in metal::nsstring_as_str::h4cf7879c713e6d9e lib.rs:65
    #8 0x0001041c1e0c in wgpu_hal::metal::adapter::_$LT$impl$u20$wgpu_hal..Adapter$u20$for$u20$wgpu_hal..metal..Adapter$GT$::open::h2cc953a2f29e2d85 adapter.rs:75
    #9 0x000103733420 in _$LT$A$u20$as$u20$wgpu_hal..dynamic..adapter..DynAdapter$GT$::open::h19b7903c78d12d16 adapter.rs:48
    #10 0x000103cfccb0 in wgpu_core::instance::Adapter::create_device_and_queue::h19c8411351e7f159 instance.rs:826
    #11 0x000103d0677c in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::adapter_request_device::h8e7cbad23166498a instance.rs:1114
    #12 0x000104302174 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:66
    #13 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #14 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #15 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #16 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #17 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #18 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #19 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #20 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #21 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #22 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #23 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

63956960 byte(s) (7%) in 799462 allocation(s)
    #0 0x000106313058 in __sanitizer_mz_calloc+0xd0 (librustc-nightly_rt.asan.dylib:arm64+0x53058)
    #1 0x00018d725318 in _malloc_zone_calloc_instrumented_or_legacy+0x80 (libsystem_malloc.dylib:arm64+0x33318)
    #2 0x00018d70fccc in _malloc_type_zone_calloc_outlined+0x44 (libsystem_malloc.dylib:arm64+0x1dccc)
    #3 0x00018d964ca8 in _CFRuntimeCreateInstance+0x1ec (CoreFoundation:arm64+0x3ca8)
    #4 0x00018da6cd38 in __CFDataInit+0xa8 (CoreFoundation:arm64+0x10bd38)
    #5 0x00018ef73ef4 in bytesInEncoding+0xb0 (Foundation:arm64+0x22ef4)
    #6 0x00018d9b8f6c in -[__NSCFString UTF8String]+0x48 (CoreFoundation:arm64+0x57f6c)
    #7 0x000102c81340 in metal::nsstring_as_str::h4cf7879c713e6d9e lib.rs:65
    #8 0x000104213e48 in _$LT$wgpu_hal..metal..Instance$u20$as$u20$wgpu_hal..Instance$GT$::enumerate_adapters::h4a26210a79881df5 mod.rs:168
    #9 0x000103737f48 in _$LT$I$u20$as$u20$wgpu_hal..dynamic..instance..DynInstance$GT$::enumerate_adapters::h92bdcafcb2ab3596 instance.rs:60
    #10 0x000103ce9960 in wgpu_core::instance::Instance::request_adapter::hdea37510747de0d9 instance.rs:451
    #11 0x000103d02a80 in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::request_adapter::h59822a2b4755a3a9 instance.rs:1029
    #12 0x000104302060 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:55
    #13 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #14 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #15 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #16 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #17 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #18 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #19 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #20 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #21 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #22 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #23 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

63956960 byte(s) (7%) in 799462 allocation(s)
    #0 0x000106313058 in __sanitizer_mz_calloc+0xd0 (librustc-nightly_rt.asan.dylib:arm64+0x53058)
    #1 0x00018d725318 in _malloc_zone_calloc_instrumented_or_legacy+0x80 (libsystem_malloc.dylib:arm64+0x33318)
    #2 0x00018d70fccc in _malloc_type_zone_calloc_outlined+0x44 (libsystem_malloc.dylib:arm64+0x1dccc)
    #3 0x00018d964ca8 in _CFRuntimeCreateInstance+0x1ec (CoreFoundation:arm64+0x3ca8)
    #4 0x00018da6cd38 in __CFDataInit+0xa8 (CoreFoundation:arm64+0x10bd38)
    #5 0x00018ef73ef4 in bytesInEncoding+0xb0 (Foundation:arm64+0x22ef4)
    #6 0x00018d9b8f6c in -[__NSCFString UTF8String]+0x48 (CoreFoundation:arm64+0x57f6c)
    #7 0x000102c81340 in metal::nsstring_as_str::h4cf7879c713e6d9e lib.rs:65
    #8 0x000104219a08 in wgpu_hal::metal::AdapterShared::new::hb0cc838443308a86 mod.rs:344
    #9 0x000104213f0c in _$LT$wgpu_hal..metal..Instance$u20$as$u20$wgpu_hal..Instance$GT$::enumerate_adapters::h4a26210a79881df5 mod.rs:168
    #10 0x000103737f48 in _$LT$I$u20$as$u20$wgpu_hal..dynamic..instance..DynInstance$GT$::enumerate_adapters::h92bdcafcb2ab3596 instance.rs:60
    #11 0x000103ce9960 in wgpu_core::instance::Instance::request_adapter::hdea37510747de0d9 instance.rs:451
    #12 0x000103d02a80 in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::request_adapter::h59822a2b4755a3a9 instance.rs:1029
    #13 0x000104302060 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:55
    #14 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #15 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #16 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #17 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #18 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #19 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #20 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #21 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #22 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #23 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #24 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

38374176 byte(s) (4%) in 799462 allocation(s)
    #0 0x000106313058 in __sanitizer_mz_calloc+0xd0 (librustc-nightly_rt.asan.dylib:arm64+0x53058)
    #1 0x00018d725318 in _malloc_zone_calloc_instrumented_or_legacy+0x80 (libsystem_malloc.dylib:arm64+0x33318)
    #2 0x00018d70fccc in _malloc_type_zone_calloc_outlined+0x44 (libsystem_malloc.dylib:arm64+0x1dccc)
    #3 0x00018d964ca8 in _CFRuntimeCreateInstance+0x1ec (CoreFoundation:arm64+0x3ca8)
    #4 0x00018d972380 in CFStringCreateMutable+0x4c (CoreFoundation:arm64+0x11380)
    #5 0x00018d9cc370 in -[NSArray componentsJoinedByString:]+0x8c (CoreFoundation:arm64+0x6b370)
    #6 0x000198cfeb6c in -[_MTLDevice name]+0x128 (Metal:arm64+0x1bb6c)
    #7 0x000102cab630 in metal::device::DeviceRef::name::ha86d6c3279fd560f device.rs:1558
    #8 0x0001041c1e0c in wgpu_hal::metal::adapter::_$LT$impl$u20$wgpu_hal..Adapter$u20$for$u20$wgpu_hal..metal..Adapter$GT$::open::h2cc953a2f29e2d85 adapter.rs:75
    #9 0x000103733420 in _$LT$A$u20$as$u20$wgpu_hal..dynamic..adapter..DynAdapter$GT$::open::h19b7903c78d12d16 adapter.rs:48
    #10 0x000103cfccb0 in wgpu_core::instance::Adapter::create_device_and_queue::h19c8411351e7f159 instance.rs:826
    #11 0x000103d0677c in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::adapter_request_device::h8e7cbad23166498a instance.rs:1114
    #12 0x000104302174 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:66
    #13 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #14 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #15 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #16 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #17 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #18 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #19 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #20 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #21 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #22 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #23 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

38374176 byte(s) (4%) in 799462 allocation(s)
    #0 0x000106313058 in __sanitizer_mz_calloc+0xd0 (librustc-nightly_rt.asan.dylib:arm64+0x53058)
    #1 0x00018d725318 in _malloc_zone_calloc_instrumented_or_legacy+0x80 (libsystem_malloc.dylib:arm64+0x33318)
    #2 0x00018d70fccc in _malloc_type_zone_calloc_outlined+0x44 (libsystem_malloc.dylib:arm64+0x1dccc)
    #3 0x00018d964ca8 in _CFRuntimeCreateInstance+0x1ec (CoreFoundation:arm64+0x3ca8)
    #4 0x00018d972380 in CFStringCreateMutable+0x4c (CoreFoundation:arm64+0x11380)
    #5 0x00018d9cc370 in -[NSArray componentsJoinedByString:]+0x8c (CoreFoundation:arm64+0x6b370)
    #6 0x000198cfeb6c in -[_MTLDevice name]+0x128 (Metal:arm64+0x1bb6c)
    #7 0x000102cab630 in metal::device::DeviceRef::name::ha86d6c3279fd560f device.rs:1558
    #8 0x000104219a08 in wgpu_hal::metal::AdapterShared::new::hb0cc838443308a86 mod.rs:344
    #9 0x000104213f0c in _$LT$wgpu_hal..metal..Instance$u20$as$u20$wgpu_hal..Instance$GT$::enumerate_adapters::h4a26210a79881df5 mod.rs:168
    #10 0x000103737f48 in _$LT$I$u20$as$u20$wgpu_hal..dynamic..instance..DynInstance$GT$::enumerate_adapters::h92bdcafcb2ab3596 instance.rs:60
    #11 0x000103ce9960 in wgpu_core::instance::Instance::request_adapter::hdea37510747de0d9 instance.rs:451
    #12 0x000103d02a80 in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::request_adapter::h59822a2b4755a3a9 instance.rs:1029
    #13 0x000104302060 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:55
    #14 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #15 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #16 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #17 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #18 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #19 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #20 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #21 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #22 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #23 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #24 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

38374176 byte(s) (4%) in 799462 allocation(s)
    #0 0x000106313058 in __sanitizer_mz_calloc+0xd0 (librustc-nightly_rt.asan.dylib:arm64+0x53058)
    #1 0x00018d725318 in _malloc_zone_calloc_instrumented_or_legacy+0x80 (libsystem_malloc.dylib:arm64+0x33318)
    #2 0x00018d70fccc in _malloc_type_zone_calloc_outlined+0x44 (libsystem_malloc.dylib:arm64+0x1dccc)
    #3 0x00018d964ca8 in _CFRuntimeCreateInstance+0x1ec (CoreFoundation:arm64+0x3ca8)
    #4 0x00018d972380 in CFStringCreateMutable+0x4c (CoreFoundation:arm64+0x11380)
    #5 0x00018d9cc370 in -[NSArray componentsJoinedByString:]+0x8c (CoreFoundation:arm64+0x6b370)
    #6 0x000198cfebdc in -[_MTLDevice name]+0x198 (Metal:arm64+0x1bbdc)
    #7 0x000102cab630 in metal::device::DeviceRef::name::ha86d6c3279fd560f device.rs:1558
    #8 0x000104219a08 in wgpu_hal::metal::AdapterShared::new::hb0cc838443308a86 mod.rs:344
    #9 0x000104213f0c in _$LT$wgpu_hal..metal..Instance$u20$as$u20$wgpu_hal..Instance$GT$::enumerate_adapters::h4a26210a79881df5 mod.rs:168
    #10 0x000103737f48 in _$LT$I$u20$as$u20$wgpu_hal..dynamic..instance..DynInstance$GT$::enumerate_adapters::h92bdcafcb2ab3596 instance.rs:60
    #11 0x000103ce9960 in wgpu_core::instance::Instance::request_adapter::hdea37510747de0d9 instance.rs:451
    #12 0x000103d02a80 in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::request_adapter::h59822a2b4755a3a9 instance.rs:1029
    #13 0x000104302060 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:55
    #14 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #15 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #16 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #17 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #18 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #19 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #20 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #21 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #22 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #23 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #24 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

38374176 byte(s) (4%) in 799462 allocation(s)
    #0 0x000106313058 in __sanitizer_mz_calloc+0xd0 (librustc-nightly_rt.asan.dylib:arm64+0x53058)
    #1 0x00018d725318 in _malloc_zone_calloc_instrumented_or_legacy+0x80 (libsystem_malloc.dylib:arm64+0x33318)
    #2 0x00018d70fccc in _malloc_type_zone_calloc_outlined+0x44 (libsystem_malloc.dylib:arm64+0x1dccc)
    #3 0x00018d964ca8 in _CFRuntimeCreateInstance+0x1ec (CoreFoundation:arm64+0x3ca8)
    #4 0x00018d972380 in CFStringCreateMutable+0x4c (CoreFoundation:arm64+0x11380)
    #5 0x00018d9cc370 in -[NSArray componentsJoinedByString:]+0x8c (CoreFoundation:arm64+0x6b370)
    #6 0x000198cfeb6c in -[_MTLDevice name]+0x128 (Metal:arm64+0x1bb6c)
    #7 0x000102cab630 in metal::device::DeviceRef::name::ha86d6c3279fd560f device.rs:1558
    #8 0x000104213e48 in _$LT$wgpu_hal..metal..Instance$u20$as$u20$wgpu_hal..Instance$GT$::enumerate_adapters::h4a26210a79881df5 mod.rs:168
    #9 0x000103737f48 in _$LT$I$u20$as$u20$wgpu_hal..dynamic..instance..DynInstance$GT$::enumerate_adapters::h92bdcafcb2ab3596 instance.rs:60
    #10 0x000103ce9960 in wgpu_core::instance::Instance::request_adapter::hdea37510747de0d9 instance.rs:451
    #11 0x000103d02a80 in wgpu_core::instance::_$LT$impl$u20$wgpu_core..global..Global$GT$::request_adapter::h59822a2b4755a3a9 instance.rs:1029
    #12 0x000104302060 in write_texture_v2::_::__libfuzzer_sys_run::h0085a9e1ea4360b6 write_texture_v2.rs:55
    #13 0x000104300dec in rust_fuzzer_test_input lib.rs:363
    #14 0x000102c4358c in std::panicking::catch_unwind::do_call::h688b48b9486e3488 panicking.rs:589
    #15 0x000102c44e70 in __rust_try+0x18 (write_texture_v2:arm64+0x10009ce70)
    #16 0x000102c44878 in LLVMFuzzerTestOneInput lib.rs:60
    #17 0x000104305cc8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x158 (write_texture_v2:arm64+0x10175dcc8)
    #18 0x000104305358 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (write_texture_v2:arm64+0x10175d358)
    #19 0x000104306c18 in fuzzer::Fuzzer::MutateAndTestOne()+0x22c (write_texture_v2:arm64+0x10175ec18)
    #20 0x0001043079a0 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x360 (write_texture_v2:arm64+0x10175f9a0)
    #21 0x0001043260b0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1ac8 (write_texture_v2:arm64+0x10177e0b0)
    #22 0x000104332a50 in main+0x24 (write_texture_v2:arm64+0x10178aa50)
    #23 0x00018d552b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)
```

</details>

### PR DESCRIPTION
**Pull request by 39ali**
**Connections**
Fixes #8018 

**Description**
metal is leaking some strings and gpu device because metal resources hold a strong reference back to the MTLDevice

**Testing**
ran some custom tests that would keep creating/deleting resources 

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
@andyleiserson, could you please take this on, since you measured the original problem?

@39ali: You have merge conflicts, and need to rebase.

File: wgpu-hal/src/metal/device.rs [hunk 1]
```diff
@@ -449,8 +449,11 @@ impl crate::Device for super::Device {
             })
         })
     }
-    unsafe fn destroy_buffer(&self, _buffer: super::Buffer) {
+    unsafe fn destroy_buffer(&self, buffer: super::Buffer) {
         self.counters.buffers.sub(1);
+        autoreleasepool(|_| {
+            drop(buffer);
+        });
```
Comment (andyleiserson) [inline wgpu-hal/src/metal/device.rs:456]: Can you explain in more detail how you found this (and the similar handling for `QueueShared`) to be necessary? Is the idea that releasing these objects transfers ownership of some member(s) to the autorelease pool, rather than directly releasing them?

Comment (39ali) [reply wgpu-hal/src/metal/device.rs:456]: from my testings, it doesn't directly release them since there's no main release pool  and that's because the code is not running inside Cocoa event loop so you have to manually autoreleasepool by yourself , there's probably a lot of places like this in the metal backend but this is what i currently found to be leaking

**Review by andyleiserson — CHANGES_REQUESTED** [review]
I would prefer to omit creating `autoreleasepool`s in `Drop` / `destroy`, unless there's compelling evidence it is necessary.

(For what it's worth, I tried running the fuzzing test case from #8018 with just the added `autoreleasepool`s on non-destructor paths, and it did seem like the leak was resolved.)

**Review by andyleiserson — APPROVED** [review]

**Comment by andyleiserson** [comment]
I'm going to merge this without the changes in drop/destroy. I'm not opposed to adding pools in drop and destroy if there's evidence they're necessary, but I don't want to do it if it's just to be conservative/speculative.

The most conservative position is that any time we call ObjC, we could get autorelease objects, so either an autorelease pool needs to be opened every time the application calls into wgpu, or there needs to be a top-level autorelease pool. The latter is less likely to have a performance impact.

I haven't tested it, but presumably adding a top-level autorelease pool in the fuzzing harness in #8018 would also resolve the leaks observed there.

Possibly we could add some sort of sanity-check in wgpu that will detect if autorelease objects are being leaked, and generate a warning suggesting to add a top-level pool.
