### PR TITLE
[naga] anonymous overrides for array-size expressions

### LINKED ISSUE #6722: [naga] panic when array override value already in arena
**Description**
First reported in https://github.com/gfx-rs/wgpu/pull/6635#issuecomment-2540949233, naga panic when array override value already in arena.

backtrace:
```
assertion failed: added && index == self.set.len() - 1 (thread WGPU, at /home/user/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/8f82992/naga/src/arena/unique_arena.rs:153)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: naga::arena::unique_arena::UniqueArena<T>::replace
   9: naga::back::pipeline_constants::process_overrides
  10: wgpu_hal::vulkan::device::<impl wgpu_hal::vulkan::Device>::compile_stage
  11: <D as wgpu_hal::dynamic::device::DynDevice>::create_compute_pipeline
  12: webgpu::wgpu_thread::WGPU::run
```

**Repro steps**

Observed when running [webgpu:shader,execution,limits:workgroup_array_byte_size_override:*](https://gpuweb.github.io/cts/standalone/?runnow=1&q=webgpu:shader,execution,limits:workgroup_array_byte_size_override:*) in servo, but one can also patch wgpu test to expose this behaviour:
```patch
diff --git a/tests/tests/shader/array_size_overrides.rs b/tests/tests/shader/array_size_overrides.rs
index 7f1d32425..476e414c7 100644
--- a/tests/tests/shader/array_size_overrides.rs
+++ b/tests/tests/shader/array_size_overrides.rs
@@ -9,7 +9,7 @@ const SHADER: &str = r#"
     var<workgroup> arr: array<u32, n - 2>;
 
     @group(0) @binding(0)
-    var<storage, read_write> output: array<u32>;
+    var<storage, read_write> output: array<u32, 14 - 2>;

     @compute @workgroup_size(1) fn main() {
         // 1d spiral
@@ -34,9 +34,9 @@ const SHADER: &str = r#"
 static ARRAY_SIZE_OVERRIDES: GpuTestConfiguration = GpuTestConfiguration::new()
     .parameters(TestParameters::default().limits(wgpu::Limits::default()))
     .run_async(move |ctx| async move {
-        array_size_overrides(&ctx, None, &[534], false).await;
+        //array_size_overrides(&ctx, None, &[534], false).await;
         array_size_overrides(&ctx, Some(14), &[286480122], false).await;
-        array_size_overrides(&ctx, Some(1), &[0], true).await;
+        //array_size_overrides(&ctx, Some(1), &[0], true).await;
     });

 async fn array_size_overrides(

```

### PR DESCRIPTION
**Pull request by kentslaney**
**Connections**
Closes #6722 

**Description**
When 2 arrays are sized with different overrides initialized from the same expression, naga panics because the type arena now contains a duplicate. This resolves the issue by creating an anonymous override for each override-sized array.

**Testing**
This change is tested by adding the [test case that prompted it](https://github.com/gfx-rs/wgpu/pull/6787#pullrequestreview-2576905294)

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by kentslaney** [comment]
In the writers, the check for unresolved overrides gets moved from the beginning into the expression processing functions. Unfortunately, unresolved overrides can manifest as non-constant statements being assigned to global variables, so any unresolved expressions get marked as a sign of unresolved overrides:
```rust
            _ => {
                return Err(Error::Override);
            }
```
This is valid since the code is unreachable otherwise, but it still seems like an overgeneralization if you don't know that context going in.

**Comment by jimblandy** [comment]
@kentslaney I'm confused about the relationship between `ResolvedSize` and `IndexableLength`. Their definitions are almost identical. Why do we have both types, instead of just using `IndexableLength`?

File: naga/src/valid/type.rs [hunk 1]
```diff
@@ -533,6 +533,7 @@ impl super::Validator {
                             | TypeFlags::COPY
                             | TypeFlags::HOST_SHAREABLE
                             | TypeFlags::ARGUMENT
+                            | TypeFlags::CONSTRUCTIBLE
```
Comment (jimblandy) [inline naga/src/valid/type.rs:538]: I think [the spec](https://gpuweb.github.io/gpuweb/wgsl/#constructible-types) says that override-sized arrays are not actually "constructible", since they need to have creation-fixed footprint.

I'll push a commit that reverts this addition, but since you went out of your way to add it, I wanted to run it by you to make sure.

Edit: I pushed such a commit, but then I removed it; see subsequent comments.

Comment (jimblandy) [reply naga/src/valid/type.rs:538]: Okay, I see that `CREATION_RESOLVED` is what corresponds to WGSL's "constructible". This is unfortunate naming.

Comment (jimblandy) [reply naga/src/valid/type.rs:538]: Filed #7227 for my confusion.

Comment (jimblandy) [reply naga/src/valid/type.rs:538]: So the remaining question is: why is this added in this PR? Shouldn't it have been there since #6654?

File: wgpu-hal/src/metal/command.rs [hunk 2]
```diff
@@ -1257,8 +1257,7 @@ impl crate::CommandEncoder for super::CommandEncoder {
             .zip(pipeline.work_group_memory_sizes.iter())
             .enumerate()
         {
-            const ALIGN_MASK: u32 = 0xF; // must be a multiple of 16 bytes
-            let size = ((*pipeline_size - 1) | ALIGN_MASK) + 1;
+            let size = pipeline_size.next_multiple_of(16);
```
Comment (jimblandy) [inline wgpu-hal/src/metal/command.rs]: Does this change belong in this PR?

**Review by jimblandy — CHANGES_REQUESTED** [review]
This looks great. The simplification in `naga::back::pipeline_constants` was the kind of thing I was hoping for.

As a follow-up, I actually think it would be fine to go even further and not bother changing `Override` expressions to `Constant` expressions, since the backends can just use the same code to handle both of them. But I wonder what @teoxoy thinks.

Marking this "changes requested" until the comments get addressed. Also, please look over the commits I pushed to make sure they seem okay.

**Comment by teoxoy** [comment]
> This looks great. The simplification in `naga::back::pipeline_constants` was the kind of thing I was hoping for.

This looks nice indeed!

> As a follow-up, I actually think it would be fine to go even further and not bother changing `Override` expressions to `Constant` expressions, since the backends can just use the same code to handle both of them.

This would probably be troublesome since the backends expect fully evaluated constant expressions.

**Comment by jimblandy** [comment]
> This would probably be troublesome since the backends expect fully evaluated constant expressions.

The idea is that `process_overrides` would go ahead and rewrite all overrides to have fully-evaluated constant expressions as their initializers, but otherwise leave things alone. So you'd have global expression handles change due to constant evaluation, but no new entries in `Module::constants`. Backends could handle `Expression::Override` just by writing out its `init` expression.

**Comment by teoxoy** [comment]
Oh, yeah - that would work.

File: naga/src/valid/type.rs (hunk 1 above)
Comment (kentslaney) [reply naga/src/valid/type.rs:538]: Yes, it should have been there initially. I don't remember what prompted me noticing it. Other than the naming issue, would you like it changed somehow?

**Comment by kentslaney** [comment]
It seems like the `process_overrides` change belongs in a separate PR. Do the changes address your concerns @jimblandy?

File: naga/src/valid/type.rs (hunk 1 above)
Comment (teoxoy) [reply naga/src/valid/type.rs:538]: I left a comment in https://github.com/gfx-rs/wgpu/issues/7227#issuecomment-2704418237.

Override-sized arrays are not constructible, so we shouldn't add this flag here.

File: naga/src/valid/mod.rs [hunk 3]
```diff
@@ -565,6 +568,13 @@ impl Validator {
             if !decl_ty.equivalent(init_ty, gctx.types) {
                 return Err(OverrideError::InvalidType);
             }
+            self.validate_const_expression(init, gctx, mod_info, global_expr_kind)
+                .map_err(|err| OverrideError::ConstExpression {
+                    handle: init,
+                    source: err,
+                })?;
```
Comment (teoxoy) [inline naga/src/valid/mod.rs]: Checking the initializer here is not needed since we already check all expressions of `global_expressions`.

File: naga/src/valid/expression.rs [hunk 4]
```diff
@@ -224,7 +224,7 @@ impl super::Validator {
                 crate::TypeInner::Scalar { .. } => {}
                 _ => return Err(ConstExpressionError::InvalidSplatType(value)),
             },
-            _ if global_expr_kind.is_const(handle) || !self.allow_overrides => {
```
Comment (teoxoy) [inline naga/src/valid/expression.rs:226]: Removing this will allow override-expressions through. `allow_overrides` didn't only mean "allow override variables" but also override-expressions.

I think we can rename the bool to `fully_evaluated_global_expressions`. If it's true, we check that all expressions in `global_expressions` have been fully evaluated (it would be a superset of the current `overrides_resolved`).

**Review by teoxoy — DISMISSED** [review]
Looks good overall - left comments about validation.

File: naga/src/valid/mod.rs (hunk 3 above)
Comment (jimblandy) [reply naga/src/valid/mod.rs]: I removed this check.

File: naga/src/valid/expression.rs (hunk 4 above)
Comment (jimblandy) [reply naga/src/valid/expression.rs:226]: I added this back, with the appropriate polarity change.

**Comment by jimblandy** [comment]
I need this change for other work, so I've addressed the review comments, rebased, and squashed.

**Review by jimblandy — APPROVED** [review]
Comments addressed.

**Comment by kentslaney** [comment]
wait, what about https://github.com/gfx-rs/wgpu/pull/7082#discussion_r1970746546

**Comment by jimblandy** [comment]
> wait, what about [#7082 (comment)](https://github.com/gfx-rs/wgpu/pull/7082#discussion_r1970746546)

Oh, good catch - I just didn't see that one. I'm probably not able to fix it today.

**Comment by kentslaney** [comment]
Now that the more immediate problem has been resolved, I'll look into https://github.com/gfx-rs/wgpu/pull/7082#pullrequestreview-2642806918 over the next couple days.

**Comment by kentslaney** [comment]
This is proving more complex than expected because, after refactoring, `ConstantEvaluator` needs to know whether the overrides have already been processed, whereas currently it can just expand the constant expressions both before and after processing overrides. Is the refactoring worth an extra `WgslRestrictions` variant @jimblandy? I'm putting development on hold unless you give me the go-ahead.

You can see the current progress at https://github.com/gfx-rs/wgpu/compare/trunk...kentslaney:wgpu:retry-constant-evaluator
