### PR TITLE
fix STATUS_HEAP_CORRUPTION crash in create_sampler

### LINKED ISSUE #20379: STATUS_HEAP_CORRUPTION on startup during `RenderStartup`.
## Bevy version

main (commit: ff40a6aefcb2ef6d5666971409577116322e0529)

## Relevant system information

Windows 11.

```
AdapterInfo { name: "NVIDIA GeForce RTX 3080", vendor: 4318, device: 8714, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "576.88", backend: Vulkan }
```

## What you did

Repeatedly run the clear_color example.

## What went wrong

Crash during `RenderStartup` with STATUS_HEAP_CORRUPTION.

## Additional information

So far there doesn't seem to be a reliable way to reproduce it. The best I've got is this: first, apply the following patch:

```
From e5027d20bd714f2c11e1db3077ce4f3e2a4debf8 Mon Sep 17 00:00:00 2001
From: andriyDev <andriydzikh@gmail.com>
Date: Fri, 1 Aug 2025 22:20:29 -0700
Subject: [PATCH] dbg

---
 crates/bevy_render/src/lib.rs  | 3 +++
 examples/window/clear_color.rs | 7 +++++++
 2 files changed, 10 insertions(+)

diff --git a/crates/bevy_render/src/lib.rs b/crates/bevy_render/src/lib.rs
index 994bc35bb..a0b69a4fd 100644
--- a/crates/bevy_render/src/lib.rs
+++ b/crates/bevy_render/src/lib.rs
@@ -586,8 +586,11 @@ unsafe fn initialize_render_app(app: &mut App) {
             // Run the `RenderStartup` if it hasn't run yet. This does mean `RenderStartup` blocks
             // the rest of the app extraction, but this is necessary since extraction itself can
             // depend on resources initialized in `RenderStartup`.
+            println!("Started RenderStartup");
             render_world.run_schedule(RenderStartup);
             should_run_startup = false;
+            println!("Finished RenderStartup");
+            std::process::exit(0);
         }
 
         {
diff --git a/examples/window/clear_color.rs b/examples/window/clear_color.rs
index 1933c4e7c..427234d1f 100644
--- a/examples/window/clear_color.rs
+++ b/examples/window/clear_color.rs
@@ -10,6 +10,7 @@ fn main() {
         .add_plugins(DefaultPlugins)
         .add_systems(Startup, setup)
         .add_systems(Update, change_clear_color)
+        .add_systems(Update, exit)
         .run();
 }
 
@@ -22,3 +23,9 @@ fn change_clear_color(input: Res<ButtonInput<KeyCode>>, mut clear_color: ResMut<
         clear_color.0 = PURPLE.into();
     }
 }
+
+fn exit(frame: Res<bevy::diagnostic::FrameCount>, mut app_exit: EventWriter<AppExit>) {
+    if frame.0 > 100 {
+        app_exit.write(AppExit::Success);
+    }
+}
-- 
2.49.0.windows.1
```

Next, run the following bash script (e.g., in Git Bash):

```bash
i=0; while cargo r --example clear_color ; do echo $i; i=$((i + 1)); done
```

Go grab a coffee... this can take a while to fail. I've gotten the heap corruption at iteration 389, though it usually happens sooner than that.

I suspect some operation we are doing isn't actually thread-safe under the hood. Making `RenderStartup` use the single-threaded executor seems to fix it (I got to iteration 750). I went through and listed out all the rendering operations I could find in every RenderStartup usage on main. [Here is the resulting table](https://docs.google.com/spreadsheets/d/10K7ayKowVf2Bg1uAzsFMZuTR8l6Xwut3IOOn4pAM_T0/edit?usp=sharing). None of these scream "not multithread safe", especially since we do these at runtime all the time.

### PR DESCRIPTION
**Pull request by atlv24**
**Connections**
Fixes https://github.com/bevyengine/bevy/issues/20379

**Description**
The unsafe in hal vk `create_sampler` is unsound.

**Testing**
Reproduction case:
```rs
use std::thread;
struct Example {}
impl crate::framework::Example for Example {
    fn init(
        _config: &wgpu::SurfaceConfiguration,
        _adapter: &wgpu::Adapter,
        device: &wgpu::Device,
        _queue: &wgpu::Queue,
    ) -> Self {
        thread::scope(move |s| {
            for i in 0..100 {
                s.spawn(|| {
                    for i in 0..100000 {
                        let _ = device.create_sampler(&wgpu::SamplerDescriptor {
                            label: Some("My Label"),
                            ..Default::default()
                        });
                    }
                });
            }
        });
        Self {}
    }
    fn resize(
        &mut self,
        _config: &wgpu::SurfaceConfiguration,
        _device: &wgpu::Device,
        _queue: &wgpu::Queue,
    ) {
    }
    fn update(&mut self, _event: winit::event::WindowEvent) {}
    fn render(&mut self, _view: &wgpu::TextureView, _device: &wgpu::Device, _queue: &wgpu::Queue) {}
}
```

**Squash or Rebase?**

squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-hal/src/vulkan/device.rs [hunk 1]
```diff
@@ -1414,7 +1414,11 @@ impl crate::Device for super::Device {
         //
         // https://github.com/gfx-rs/wgpu/issues/6867
         if let Some(label) = desc.label {
+            let l = self.shared.sampler_cache.lock();
+            // SAFETY: we are holding a lock on the sampler cache,
+            // so we can only be setting the name from one thread.
             unsafe { self.shared.set_object_name(raw, label) };
+            drop(l);
```
Comment (james7132) [inline wgpu-hal/src/vulkan/device.rs]: Is this explicit drop here necessary? The lock will be dropped there anyway as it goes out of scope once the if-block exits. Or would `l` otherwise go unused?

Comment (atlv24) [reply wgpu-hal/src/vulkan/device.rs]: id rather be explicit, the drop shows that `l` is alive at least until the end of the scope: otherwise, the lock may be immediately discarded. Im not sure how NLL play with this, it might be fine, but i'd rather not rely on implicit behaviors if possible

File: wgpu-hal/src/vulkan/device.rs [hunk 2]
```diff
@@ -1414,7 +1414,11 @@ impl crate::Device for super::Device {
         //
         // https://github.com/gfx-rs/wgpu/issues/6867
         if let Some(label) = desc.label {
+            let l = self.shared.sampler_cache.lock();
```
Comment (ErichDonGubler) [inline wgpu-hal/src/vulkan/device.rs]: nitpick: I think we should use the first `lock` call's guard from immediately above, and extend its scope, so we don't have two lock regions for the same lock in series. Otherwise, I think this commit can mostly be the same?

Will push a `fixup!` for this shortly.

**Review by ErichDonGubler — APPROVED** [review]
LGTM, minus a nit I'm going to fix right now.

File: wgpu-hal/src/vulkan/device.rs (hunk 2 above)
Comment (ErichDonGubler) [reply wgpu-hal/src/vulkan/device.rs]: Pushed [65c9f0e](https://github.com/gfx-rs/wgpu/pull/8043/commits/65c9f0e51be18acda21d9526e350b7ad468a0067).

Comment (atlv24) [reply wgpu-hal/src/vulkan/device.rs]: Makes sense, thanks!

**Comment by atlv24** [comment]
One more note is `set_object_name` currently has a safety comment that says "must be valid to call set_object_name" and that's like... very undescriptive? It would be good to elaborate on when its valid to call, like no concurrent access (and any other requirements)

File: CHANGELOG.md
Comment (ErichDonGubler) [inline CHANGELOG.md:1]: style: We order `Bug Fixes` after `Changes` in our `CHANGELOG`. Fixed with 35002740.

**Comment by ErichDonGubler** [comment]
@atlv24: Just filed https://github.com/gfx-rs/wgpu/pull/8055.
