### PR TITLE
Fix initialization tracking for the destination of `copyTextureToBuffer`

### LINKED ISSUE #8021: CTS `render_pass:storeOp` tests fail on Vulkan and DX12 if run together, but pass if run separately
On Vulkan and DX12, if run in a single run (i.e. with the test selector `webgpu:api,operation,render_pass,storeOp:*`), these tests [fail with errors like](https://github.com/gfx-rs/wgpu/actions/runs/16585816351/job/46910659890):

```
** Failures **
[fail] webgpu:api,operation,render_pass,storeOp:render_pass_store_op,multiple_color_attachments:storeOperation1="discard";storeOperation2="discard" (46ms). Log:
  - (in subcase: colorAttachments=1) EXPECTATION FAILED: Array had unexpected contents at indices 10 through 127.
     Starting at index 9:
       actual == 0x: 00 80 3f 00 00 80 3f a6 03 1d 70 a6 03 1d 70 a6 03 1d 70 a6 03 1d 70 cd cc 4c 3f 00 00 40 3f cd cc 4c 3f ...
       failed ->        xx xx       xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx       xx xx xx xx xx xx ...
     expected ==     00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ...
    Error
        at AllFeaturesMaxLimitsGPUTest.eventualAsyncExpectation (file:///D:/a/wgpu/wgpu/cts/out/common/framework/fixture.js:258:24)
        at AllFeaturesMaxLimitsGPUTest.expectGPUBufferValuesPassCheck (file:///D:/a/wgpu/wgpu/cts/out/webgpu/gpu_test.js:695:10)
        at AllFeaturesMaxLimitsGPUTest.expectGPUBufferValuesEqual (file:///D:/a/wgpu/wgpu/cts/out/webgpu/gpu_test.js:711:10)
        at AllFeaturesMaxLimitsGPUTest.expectGPUBufferRepeatsSingleValue (file:///D:/a/wgpu/wgpu/cts/out/webgpu/gpu_test.js:755:12)
        at AllFeaturesMaxLimitsGPUTest.expectSingleColor (file:///D:/a/wgpu/wgpu/cts/out/webgpu/gpu_test.js:924:10)
        at RunCaseSpecific.fn (file:///D:/a/wgpu/wgpu/cts/out/webgpu/api/operation/render_pass/storeOp.spec.js:299:7)
  - (in subcase: colorAttachments=1) INFO: subcase ran
  - (in subcase: colorAttachments=2) INFO: subcase ran
  - (in subcase: colorAttachments=3) INFO: subcase ran
  - (in subcase: colorAttachments=4) INFO: subcase ran
```

If run separately, they pass. They are also passing in Firefox CTS runs.

### PR DESCRIPTION
**Pull request by andyleiserson**
The main goal of this PR was to fix initialization tracking for buffers that are the destination of a copyT2B operation (#8097). This fixes some CTS tests whose intermittent failure was causing false positives with other changes. I believe it will fix #8021. There is a risk of performance regressions from this change. It would be more performant to use a shader to initialize only the padding areas instead of unnecessarily initializing the entire destination range, but this would be a more involved change.

It was easy to fix the problem with non-4B-aligned initializations (#7947) at the same time, so I did.

There is one additional tweak to the 256B alignment check `bytes_per_row` that was needed to get the `offset_and_bytesPerRow` test fully passing, at least on Linux.

**Testing**
Enables some CTS tests. A directed test might be reasonable too, but I wanted to go ahead and open this so I can see what CI thinks.

**Squash or Rebase?** Rebase

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-core/src/command/transfer.rs [hunk 1]
```diff
@@ -271,9 +271,11 @@ pub(crate) fn extract_texture_selector<T>(
 ///
 /// Copied with some modifications from WebGPU standard.
 ///
-/// If successful, returns a pair `(bytes, stride)`, where:
+/// If successful, returns a pair `(bytes, stride, is_contiguous)`, where:
```
Comment (andyleiserson) [inline wgpu-core/src/command/transfer.rs]:
```suggestion
/// If successful, returns a tuple `(bytes, stride, is_contiguous)`, where:
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -76,6 +76,7 @@ By @Vecvec in [#7913](https://github.com/gfx-rs/wgpu/pull/7913).
 - The function you pass to `Device::on_uncaptured_error()` must now implement `Sync` in addition to `Send`, and be wrapped in `Arc` instead of `Box`.
   In exchange for this, it is no longer possible for calling `wgpu` functions while in that callback to cause a deadlock (not that we encourage you to actually do that).
   By @kpreid in [#8011](https://github.com/gfx-rs/wgpu/pull/8011).
+- `wgpu` now tracks the initialization status of buffer memory correctly when `copy_texture_to_buffer` skips over padding space between rows or layers, or when the start/end of a texture-buffer transfer is not 4B aligned. By @andyleiserson in [#8099](https://github.com/gfx-rs/wgpu/pull/8099).
```
Comment (ErichDonGubler) [inline CHANGELOG.md]: suggestion: It's odd to mention `wgpu` explicitly, because the premise of this `CHANGELOG` is that changes almost always apply to `wgpu`. It seems like we should elide that detail entirely; this would be consistent with other `CHANGELOG` items.

**Review by ErichDonGubler — COMMENTED** [review]
Got all the way up to the last commit, but IDK if I'm returning to this today. Submitting my feedback so far.

File: CHANGELOG.md (hunk 2 above)
Comment (andyleiserson) [reply CHANGELOG.md]: I was perhaps too committed to complete sentences and avoiding passive voice. I've changed it to just say "Track the initialization status..."

**Review by nical — APPROVED** [review]
