### PR TITLE
Additional validation of buffer-texture copies

### LINKED ISSUE #7936: Missing validation for buffer<->texture copies
This was recently added to the CTS and the test (`api,validation,image_copy,buffer_texture_copies:offset_and_bytesPerRow`) is failing with a panic:

```
thread 'main' panicked at wgpu-core/src/command/memory_init.rs:233:17:
Buffer Buffer { raw: <AGXG13XFamilyBuffer: 0x145617980>
    label = buffer(66)
    length = 68
    cpuCacheMode = MTLCPUCacheModeDefaultCache
    storageMode = MTLStorageModePrivate
    hazardTrackingMode = MTLHazardTrackingModeTracked
    resourceOptions = MTLResourceCPUCacheModeDefaultCache MTLResourceStorageModePrivate MTLResourceHazardTrackingModeTracked
    purgeableState = MTLPurgeableStateNonVolatile, size: 68 } has an uninitialized range with a start not aligned to 4 (start was 2)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:76:14
   2: wgpu_core::command::memory_init::<impl wgpu_core::command::BakedCommands>::initialize_buffer_memory
             at /Users/Andy/Development/wgpu/wgpu-core/src/command/memory_init.rs:233:17
   3: wgpu_core::device::queue::Queue::submit
             at /Users/Andy/Development/wgpu/wgpu-core/src/device/queue.rs:1227:41
   4: wgpu_core::device::queue::<impl wgpu_core::global::Global>::queue_submit
             at /Users/Andy/Development/wgpu/wgpu-core/src/device/queue.rs:1651:9
```

### PR DESCRIPTION
**Pull request by andyleiserson**
Adds some more buffer-texture copy validation. I am declaring that this fixes #7936, although there are still problems with buffer-texture copies, see #7946 and #7947.

This PR enforces:
* Offset for copies to/from compressed formats must be aligned to the block size
* Offset for copies to/from depth stencil formats must be 4B aligned.
* Temporarily enforces that all buffer-texture copies be 4B aligned, pending a fix for #7947.
* Disallows multisampled textures for both T2B and B2T (previously only one checked for multisampled textures)

**Testing**
Enables a sampling of relevant CTS tests, but some of the tests still have a mix of passing and failing variants and I didn't try to exhaustively list every passing case in `test.lst`.

**Squash or Rebase?** Squash

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by andyleiserson** [comment]
This comment previously noted which commits belonged to this PR vs. #7935, but that no longer applies since the other PR has been merged and this one rebased.

File: wgpu-core/src/command/transfer.rs [hunk 1]
```diff
@@ -926,19 +983,40 @@ impl Global {
...
+                        let mut buffer_layout = source.layout;
+                        buffer_layout.offset += rel_array_layer as u64 * bytes_per_array_layer;
+                        hal::BufferTextureCopy {
+                            buffer_layout,
+                            texture_base,
+                            size: hal_copy_size,
+                        }
+                    })
+                    .collect()
+            };
```
Comment (teoxoy) [inline wgpu-core/src/command/transfer.rs]: It looks like this change is still in this PR.

File: wgpu-core/src/command/transfer.rs [hunk 2]
```diff
@@ -363,6 +363,59 @@ pub(crate) fn validate_linear_texture_data(
...
+    if !aspect.is_one() {
+        return Err(TransferError::CopyAspectNotOne);
+    }
+
+    let mut offset_alignment = if desc.format.is_depth_stencil_format() {
+        4
+    } else {
+        desc.format
+            .block_copy_size(Some(texture_copy_view.aspect))
+            .unwrap_or(1)
```
Comment (teoxoy) [inline wgpu-core/src/command/transfer.rs]: I think we need to error if we get back a `None` since we don't check anywhere else that the `format-aspect` combination is copyable.

`guaranteed_format_features` also seems to report that `Depth24Plus` is copyable which isn't right but that's a different (though related) issue.

Comment (andyleiserson) [reply wgpu-core/src/command/transfer.rs]: There is a [note in the spec](https://www.w3.org/TR/webgpu/#depth-formats) that:

> All [depth-or-stencil formats](https://www.w3.org/TR/webgpu/#depth-or-stencil-format) support the [COPY_SRC](https://www.w3.org/TR/webgpu/#dom-gputextureusage-copy_src), [COPY_DST](https://www.w3.org/TR/webgpu/#dom-gputextureusage-copy_dst), [TEXTURE_BINDING](https://www.w3.org/TR/webgpu/#dom-gputextureusage-texture_binding), and [RENDER_ATTACHMENT](https://www.w3.org/TR/webgpu/#dom-gputextureusage-render_attachment) usages. [...] However, certain copy operations also restrict the source and destination formats [...].

I interpreted this to mean that it is correct for `guaranteed_format_features` to report that `COPY_DST` and `COPY_SRC` usage are legal with these formats.

The restriction on non-copyable depth and stencil formats is checked using the `conv::is_valid_copy_{src,dst}_texture_format` helpers, which are called adjacent to the calls to `validate_texture_buffer_copy`. I wouldn't be opposed to moving these checks inside `validate_texture_buffer_copy`, since it always seems like a good thing to have implementations that parallel the spec. I left them alone because it didn't seem like a clearly justified refactoring, in part because those checks differ for source/destination, while the stuff in the current `validate_texture_buffer_copy` does not. (I can at least make the comments on `validate_texture_buffer_copy` more explicit about this situation.)

I think the `unwrap_or(1)` could actually be an `expect()` -- I was thinking that there were cases where no alignment requirement came back as `None`, but looking again I don't see any.

File: wgpu-core/src/command/transfer.rs (hunk 1 above)
Comment (andyleiserson) [reply wgpu-core/src/command/transfer.rs]: I pushed a rebase that drops all the other commits and it seems okay now. Not sure why git didn't do the right thing before though.

File: wgpu-core/src/command/transfer.rs (hunk 2 above)
Comment (andyleiserson) [reply wgpu-core/src/command/transfer.rs]: Let me know if you still think there are invalid copies that aren't getting flagged, or if you'd prefer to move the special checks for non-copyable depth/stencil into this function.

Comment (teoxoy) [reply wgpu-core/src/command/transfer.rs]: Oh yeah, the last change looks good! I forgot we had `conv::is_valid_copy_{src,dst}_texture_format`.

**Review by teoxoy — APPROVED** [review]
