### PR TITLE
Deduplicate submitted surfaces to avoid a vulkan deadlock/crash

### LINKED ISSUE #5774: Crash on vulkan when multiple command encoders are used after #5681.
**Description**
Since https://github.com/gfx-rs/wgpu/pull/5681, wgpu now crashes with "More than one surface texture is being used from the same swapchain. This will cause a deadlock in release." if more than 1 command encoder (with a renderpass that has a texture view of your `Surface` texture) is used.

**Repro steps**
Create and submit a 2nd command encoder with a renderpass that uses a view of your surface texture (can create a new texture view or just re-use an existing one) when running on Vulkan.
Run https://github.com/Elabajaba/wgpu-vk-surface-crash

**Expected vs observed behavior**
Expected: Doesn't crash
Observed: 
```
thread 'main' panicked at E:\temp\wgpu\wgpu-hal\src\vulkan\mod.rs:966:9:
More than one surface texture is being used from the same swapchain. This will cause a deadlock in release.
```

**Platform**
Happens on both Windows 11 + AMD gpu and Linux+Mesa RADV (amd) + Wayland.

### PR DESCRIPTION
**Pull request by Elabajaba**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/5774

**Description**
wgpu-hal's vulkan implementataion requires that we only submit each used surface texture once. If we submit the same surface texture multiple times, it'll deadlock.

To fix this, use a hashmap keyed on the surface texture arc's raw pointers instead of a smallvec to deduplicate the surface textures before we submit them.

**Testing**
Tested against https://github.com/Elabajaba/wgpu-vk-surface-crash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu-core/src/device/queue.rs [hunk 1]
```diff
@@ -1263,7 +1265,9 @@ impl Global {
                                         Some(TextureInner::Native { .. }) => false,
                                         Some(TextureInner::Surface { ref raw, .. }) => {
                                             if raw.is_some() {
-                                                submit_surface_textures_owned.push(texture.clone());
+                                                // Compare the Arcs by pointer as Textures don't implement Eq.
+                                                submit_surface_textures_owned
+                                                    .insert(Arc::as_ptr(&texture), texture.clone());
```
Comment (cwfitzgerald) [inline wgpu-core/src/device/queue.rs:1270]: Good thought on Arcs, just wondering if we should use the indexes already built into the texture.info.index or something like that.

File: wgpu-core/src/device/queue.rs [hunk 2]
```diff
@@ -1172,7 +1172,9 @@ impl Global {
 
             let mut used_surface_textures = track::TextureUsageScope::default();
 
-            let mut submit_surface_textures_owned = SmallVec::<[_; 2]>::new();
+            // Use a hashmap here to deduplicate the surface textures that are used in the command buffers.
+            // This avoids vulkan deadlocking from the same surface texture being submitted multiple times.
+            let mut submit_surface_textures_owned = FastHashMap::default();
```
Comment (Elabajaba) [inline wgpu-core/src/device/queue.rs:1177]: Should this be an IndexMap instead? I'm not sure if the ordering matters for it.

File: wgpu-core/src/device/queue.rs (hunk 1 above)
Comment (Elabajaba) [reply wgpu-core/src/device/queue.rs:1270]: > Good thought on Arcs

I copied what you did in vulkan hal's `Queue::submit` lol

> just wondering if we should use the indexes already built into the texture.info.index

Isn't wgpu trying to remove all those indices and move to just using Arcs?

Comment (cwfitzgerald) [reply wgpu-core/src/device/queue.rs:1270]: Those indices are staying

File: wgpu-core/src/device/queue.rs (hunk 2 above)
Comment (cwfitzgerald) [reply wgpu-core/src/device/queue.rs:1177]: No ordering doesn't matter, just uniqueness.

File: wgpu-core/src/device/queue.rs (hunk 1 above)
Comment (cwfitzgerald) [reply wgpu-core/src/device/queue.rs:1270]: Let's leave this for now, for the sake of expediency.

**Review by cwfitzgerald — APPROVED** [review]
Thanks!
