### PR TITLE
chore(cts): Enable test fixed by objc2

### LINKED ISSUE #7357: Returns from metal API calls are transmuted to `NonNull` pointers, but they may be null
The `objc` crate [transmutes the return from the API call into the specified return type](https://github.com/SSheldon/rust-objc/blob/c8696b0cd1932fdf1b5b22c03af86f32a934f42f/src/message/mod.rs#L128). In the case of Metal APIs, this type is a [`NonNull` pointer](https://github.com/sfackler/foreign-types/blob/393f6ab5a5dc66b8a8e2d6d880b1ff80b6a7edc2/foreign-types-macros/src/build.rs#L64). However, the returns from metal API calls may be null (e.g. https://developer.apple.com/documentation/metal/mtldevice/maketexture(descriptor:): "Return Value: A new [MTLTexture](https://developer.apple.com/documentation/metal/mtltexture) instance if the method completed successfully; otherwise nil.").

I observed a few strange behaviors resulting from the null value in the `NonNull` pointer:
* It appears that the compiler optimizes the value of calling `.as_ptr().is_null()` on a `NonNull` pointer as a constant. So the following check is not effective: https://github.com/gfx-rs/wgpu/blob/3e4d24ea9830b65b5fe7d30265e51632db937b6c/wgpu-hal/src/metal/device.rs#L435
* The compiler can use the fact that a `NonNull` pointer must not be null to more compactly represent enums. Most commonly, `Option<NonNull<T>>` can be represented in the same memory as `NonNull<T>`. But it is also clever enough to represent `Result<super::TextureView, DeviceError>` using the same memory as `TextureView`. This resulted in what was supposed to be `Ok(TextureView { raw: <null>, aspects: FormatAspects::COLOR })` having the same memory representation as `Err(DeviceError::Lost)`, and a device lost error appearing seemingly out of nowhere.

I found this while looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1914934. This isn't the core issue there (the core issue is the lack of support for a particular format in `copyExternalImageToTexture`), and once that core issue is resolved, it will no longer be a good test case here. But it ought to be possible to reproduce this issue with any case that exhausts GPU resources.

### PR DESCRIPTION
**Pull request by andyleiserson**
Closes #7357

**Squash or Rebase?** Squash

### CODE REVIEW

File: cts_runner/tests/integration.rs [hunk 1]
```diff
@@ -84,12 +84,12 @@ fn uncaptured_error() {
             const device = await adapter.requestDevice();
             device.createShaderModule({ code })
         "#,
-        "cts_runner caught WebGPU error:
+        "cts_runner caught WebGPU error:\x20
```
Comment (cwfitzgerald) [inline cts_runner/tests/integration.rs:87]: What?

**Review by cwfitzgerald — APPROVED** [review]

File: cts_runner/tests/integration.rs (hunk 1 above)
Comment (ErichDonGubler) [reply cts_runner/tests/integration.rs:87]: I'm not the author, but I think I can answer this: When we have snapshot output with trailing whitespace, capturing that in string literals is tricky, because it's often difficult-to-notice and automatically trimmed by contributors' various text editing environments. This solves both of those issues, though it's not obvious to somebody who doesn't know what U+20 is. 😅

Also: We already do this in `naga/tests/naga/wgsl_errors.rs`, so there's some precedent here.

**Review by ErichDonGubler — APPROVED** [review]
