### PR TITLE
Test And Normalize Vertex Behavior on All Backends

### LINKED ISSUE #4256: Missing test coverage for draw_indirect
This was something noticed by @cwfitzgerald on matrix when I was asking about it

### LINKED ISSUE #4276: `draw_instanced_offset` fails on GL
The `draw_instanced_offset` test is failing in GL, suggesting the workaround translating gl_InstanceIndex into gl_InstanceID + offset isn't functioning properly.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Closes #4256 
Closes #4276

**Description**

This adds the necessary logic so that `@builtin(instance_index)` works correctly against all supported calls, both direct and indirect.

**Testing**

Completely re-implemented the tests to cover many permutations.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [x] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu/src/util/mod.rs [hunk 1]
```diff
@@ -19,9 +18,8 @@ use std::{
 pub use belt::StagingBelt;
 pub use device::{BufferInitDescriptor, DeviceExt};
 pub use encoder::RenderEncoder;
-pub use indirect::*;
 pub use init::*;
-pub use wgt::math::*;
+pub use wgt::{math::*, DispatchIndirectArgs, DrawIndexedIndirectArgs, DrawIndirectArgs};
```
Comment (i509VCB) [inline wgpu/src/util/mod.rs:22]: Technically a breaking change due to type name changes (`Arg` was added to each type name)

Comment (cwfitzgerald) [reply wgpu/src/util/mod.rs:22]: Yeah, I should probably switch it back, was trying not to touch `core` though, but this obviously isn't going to land before arcinization :)

Comment (cwfitzgerald) [reply wgpu/src/util/mod.rs:22]: Decided to keep the change, but mention it

File: tests/tests/vertex_indices/mod.rs [hunk 2]
```diff
@@ -1,14 +1,237 @@
...
+            self.instance.start
+        } else {
+            0
+        };
+
+        if let Some(vertex_offset) = self.vertex_offset {
+            bytes.extend_from_slice(
+                wgpu::util::DrawIndexedIndirectArgs {
+                    vertex_count: self.vertex.end - self.vertex.start,
+                    instance_count: self.instance.end - self.instance.start,
```
Comment (teoxoy) [inline tests/tests/vertex_indices/mod.rs:44]:
```suggestion
                    instance_count: self.instance.end - first_instance,
```

File: tests/tests/vertex_indices/mod.rs [hunk 3]
```diff
@@ -1,14 +1,237 @@
...
+                    first_index: self.vertex.start,
+                    first_instance,
+                }
+                .as_bytes(),
+            )
+        } else {
+            bytes.extend_from_slice(
+                wgpu::util::DrawIndirectArgs {
+                    vertex_count: self.vertex.end - self.vertex.start,
+                    instance_count: self.instance.end - self.instance.start,
```
Comment (teoxoy) [inline tests/tests/vertex_indices/mod.rs:55]:
```suggestion
                    instance_count: self.instance.end - first_instance,
```

File: tests/tests/vertex_indices/mod.rs [hunk 4]
```diff
@@ -1,14 +1,237 @@
...
+
+    /// Add the draw call to the given indirect buffer
+    fn add_to_buffer(&self, bytes: &mut Vec<u8>, features: wgpu::Features) {
+        // The behavior of non-zero first_instance in indirect draw calls in currently undefined if INDIRECT_FIRST_INSTANCE is not supported.
+        let supports_first_instance = features.contains(wgpu::Features::INDIRECT_FIRST_INSTANCE);
+        let first_instance = if supports_first_instance {
+            self.instance.start
+        } else {
+            0
+        };
```
Comment (teoxoy) [inline tests/tests/vertex_indices/mod.rs:38]: Or would it make sense to turn this into an assert instead and make sure we don't call this fn with params that are not supported?

File: tests/tests/vertex_indices/mod.rs [hunk 5]
```diff
@@ -1,14 +1,237 @@
...
+                    instance: 0..1,
+                    vertex_offset: None,
+                },
+                Draw {
+                    vertex: 3..6,
+                    instance: 0..1,
+                    vertex_offset: None,
+                },
+            ],
+            TestCase::DrawBaseVertex => &[Draw {
```
Comment (teoxoy) [inline tests/tests/vertex_indices/mod.rs:124]: I find the names for `DrawVertexOffset`, `DrawBaseVertex` and `DrawInstancedOffset` to be a bit confusing.

`DrawVertexOffset` doesn't specify a `vertex_offset` but `DrawBaseVertex` does.

It might be better to rename `vertex_offset` to `base_vertex` (that's also what the spec calls it).

File: wgpu-types/src/lib.rs [hunk 6]
```diff
@@ -6507,44 +6553,83 @@ impl_bitflags!(PipelineStatisticsTypes);
...
 pub struct DrawIndexedIndirectArgs {
-    /// The number of indices to draw.
-    pub index_count: u32,
+    /// The number of vertices to draw.
+    pub vertex_count: u32,
     /// The number of instances to draw.
     pub instance_count: u32,
-    /// Offset into the index buffer, in indices, begin drawing from.
+    /// The first index within the index buffer.
     pub first_index: u32,
```
Comment (teoxoy) [inline wgpu-types/src/lib.rs:6591]:
```suggestion
    pub first_vertex: u32,
```

File: wgpu-types/src/lib.rs [hunk 7]
```diff
@@ -6507,44 +6553,83 @@ impl_bitflags!(PipelineStatisticsTypes);
...
-    /// Added to each index value before indexing into the vertex buffers.
-    pub base_vertex: i32,
-    /// First instance to draw.
+    /// The value added to the vertex index before indexing into the vertex buffer.
+    pub vertex_offset: i32,
```
Comment (teoxoy) [inline wgpu-types/src/lib.rs]:
```suggestion
    pub base_vertex: i32,
```

File: wgpu-hal/src/vulkan/adapter.rs [hunk 8]
```diff
@@ -991,12 +992,19 @@ impl super::Instance {
         };
 
         if let Some(driver) = phd_capabilities.driver {
+            #[allow(clippy::unnecessary_cast, trivial_numeric_casts)]
+            // False positive on the `as u8` cast on Linux/Android aarch64
```
Comment (teoxoy) [inline wgpu-hal/src/vulkan/adapter.rs]:
```suggestion
            #[cfg(not(any(target_os = "macos", target_os = "ios")))]
```

I was thinking of silently ignoring the check but if the message has value, we can go with that.

File: wgpu-hal/src/vulkan/adapter.rs [hunk 9]
```diff
@@ -991,12 +992,19 @@ impl super::Instance {
...
             if driver.conformance_version.major == 0 {
-                log::warn!(
-                    "Adapter is not Vulkan compliant, hiding adapter: {}",
-                    info.name
-                );
-                return None;
+                let driver_name_unsigned = driver.driver_name.map(|i| i as u8);
+                if !driver_name_unsigned.starts_with(b"MoltenVK") {
```
Comment (teoxoy) [inline wgpu-hal/src/vulkan/adapter.rs]:
```suggestion
                if driver.driver_id != ash::vk::DriverId::MOLTENVK {
```

File: naga/src/back/glsl/mod.rs [hunk 10]
```diff
@@ -4308,29 +4356,32 @@ const fn glsl_scalar(scalar: crate::Scalar) -> Result<ScalarString<'static>, Err
...
         Bi::ViewIndex => "gl_ViewIndex",
         // vertex
         Bi::BaseInstance => "uint(gl_BaseInstance)",
         Bi::BaseVertex => "uint(gl_BaseVertex)",
         Bi::ClipDistance => "gl_ClipDistance",
         Bi::CullDistance => "gl_CullDistance",
-        Bi::InstanceIndex => "uint(gl_InstanceID)",
+        Bi::InstanceIndex => {
+            if options.draw_parameters {
+                "(uint(gl_InstanceID) + uint(gl_BaseInstanceARB))"
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs:4369]: `gl_BaseInstance` seems to also be available in GLSL 4.6

File: naga/src/back/glsl/mod.rs [hunk 11]
```diff
@@ -76,6 +76,9 @@ const CLAMPED_LOD_SUFFIX: &str = "_clamped_lod";
 pub(crate) const MODF_FUNCTION: &str = "naga_modf";
 pub(crate) const FREXP_FUNCTION: &str = "naga_frexp";
 
+// Must match code in glsl_built_in
+pub const BASE_INSTANCE_BINDING: &str = "naga_vs_base_instance";
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs]:
```suggestion
pub const FIRST_INSTANCE_BINDING: &str = "naga_vs_first_instance";
```

File: naga/src/back/glsl/mod.rs [hunk 12]
```diff
@@ -652,6 +686,16 @@ impl<'a, W: Write> Writer<'a, W> {
             writeln!(self.out)?;
         }
 
+        if self.entry_point.stage == ShaderStage::Vertex
+            && !self
+                .options
+                .writer_flags
+                .contains(WriterFlags::DRAW_PARAMETERS)
+        {
+            writeln!(self.out, "uniform uint {BASE_INSTANCE_BINDING};")?;
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs]: Can we make this conditional on the presence of the builtin? I'd recommend looking at `Features::MULTI_VIEW`.

File: wgpu-hal/src/gles/command.rs [hunk 13]
```diff
@@ -1004,38 +1019,44 @@ impl crate::CommandEncoder<super::Api> for super::CommandEncoder {
         &mut self,
         start_vertex: u32,
         vertex_count: u32,
-        start_instance: u32,
+        base_instance: u32,
```
Comment (teoxoy) [inline wgpu-hal/src/gles/command.rs]: Can we keep the name as it was before? Or rename both to `first_vertex`/`first_instance` everywhere?

File: naga/src/back/glsl/mod.rs (hunk 10 above)
Comment (teoxoy) [reply naga/src/back/glsl/mod.rs:4369]: But it seems all 4.6 implementations also support the extension, I guess this is fine then.

https://opengl.gpuinfo.org/listreports.php?extension=GL_ARB_shader_draw_parameters&option=not

**Review by teoxoy — CHANGES_REQUESTED** [review]

**Comment by teoxoy** [comment]
These are all great changes btw!

File: wgpu-hal/src/gles/command.rs (hunk 13 above)
Comment (teoxoy) [reply wgpu-hal/src/gles/command.rs]: The naming across APIs looks to be a mess as well but we should at least try to keep it consistent with the WebGPU and Vulkan specs (both using `first_vertex`/`first_instance`).

File: tests/tests/vertex_indices/mod.rs (hunk 4 above)
Comment (cwfitzgerald) [reply tests/tests/vertex_indices/mod.rs:38]: This is what's actually doing the "sanitizing" - as some tests are speced to use a non-zero first_instance, and we need them to behave deterministically.

File: tests/tests/vertex_indices/mod.rs (hunk 3 above)
Comment (cwfitzgerald) [reply tests/tests/vertex_indices/mod.rs:55]: What it was is actually the indended behavior, we want it to "malfunction"

File: wgpu-types/src/lib.rs (hunk 6 above)
Comment (cwfitzgerald) [reply wgpu-types/src/lib.rs:6591]: Spec has this as first_index

File: wgpu-hal/src/vulkan/adapter.rs (hunk 8 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/adapter.rs]: Just so that our adapter choosing behavior is clear from the logs.

File: tests/tests/vertex_indices/mod.rs (hunk 4 above)
Comment (teoxoy) [reply tests/tests/vertex_indices/mod.rs:38]: I see, I guess it's fine then.

File: wgpu-types/src/lib.rs (hunk 6 above)
Comment (teoxoy) [reply wgpu-types/src/lib.rs:6591]: Ah, right.

File: wgpu-types/src/lib.rs [hunk 14]
```diff
@@ -6507,44 +6553,83 @@ impl_bitflags!(PipelineStatisticsTypes);
...
+
 /// Argument buffer layout for draw_indexed_indirect commands.
 #[repr(C)]
-#[derive(Clone, Copy, Debug)]
+#[derive(Copy, Clone, Debug, Default)]
 pub struct DrawIndexedIndirectArgs {
-    /// The number of indices to draw.
-    pub index_count: u32,
+    /// The number of vertices to draw.
+    pub vertex_count: u32,
```
Comment (teoxoy) [inline wgpu-types/src/lib.rs]: This was correct previously.

File: tests/tests/vertex_indices/mod.rs (hunk 5 above)
Comment (cwfitzgerald) [reply tests/tests/vertex_indices/mod.rs:124]: Alright, tried some new names

**Comment by teoxoy** [comment]
@cwfitzgerald I got a few more renames / small fixes, can I just push a commit? It's easier than pointing out all the places through github's UI.

**Comment by cwfitzgerald** [comment]
@teoxoy Yeah, always just go ahead :)

**Review by teoxoy — APPROVED** [review]

**Comment by teoxoy** [comment]
Pushed, if the changes look good, feel free to land it.

On a related note, I noticed we don't seem to validate `DownlevelFlags::BASE_VERTEX`.

**Review by cwfitzgerald — COMMENTED** [review]
Nice stuff

> On a related note, I noticed we don't seem to validate DownlevelFlags::BASE_VERTEX.

Biiiiig spooky, willfix.
