### PR TITLE
[wgpu] correct doc for resolve query set

### LINKED ISSUE #4838: Incorrect docs for resolve_query_set
I was reading about occlusion culling and looking at the `wgpu` documentation for relevant features, and noticed something odd in  [the docs for `CommandEncoder::resolve_query_set()` and its `impl`](https://docs.rs/wgpu/0.18.0/wgpu/struct.CommandEncoder.html#impl-CommandEncoder-2) ([source](https://docs.rs/wgpu/0.18.0/src/wgpu/lib.rs.html#3604-3628)).

* The function documentation says "See `PipelineStatisticsTypes` for more information." Surely this should be `QueryType`?
* The `impl` block documentation says “`Features::TIMESTAMP_QUERY` or `Features::PIPELINE_STATISTICS_QUERY` must be enabled on the device in order to call these functions.” But occlusion queries are neither of those, and there's only one function in the `impl` block.

I suspect these are both left over from a previous WebGPU API revision, but I have no experience with queries so I can't be confident that I'm right or what the correct statement is. Happy to send a PR if the intent can be clarified.

### PR DESCRIPTION
**Pull request by valaphee**
**Connections**
Closes https://github.com/gfx-rs/wgpu/issues/4838

**Description**
Moved `resolve_query_set` to the general command encoder impl, as it technically doesn't require any feature, is not meaningful to the end user, and it's not possible to create a query set with an unsupported type anyway.

And added info about how many bytes to expect.

**Testing**

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu/src/lib.rs [hunk 1]
```diff
@@ -3671,34 +3671,11 @@ impl CommandEncoder {
...
-    }
-}
 
-/// [`Features::TIMESTAMP_QUERY`] or [`Features::PIPELINE_STATISTICS_QUERY`] must be enabled on the device in order to call these functions.
-impl CommandEncoder {
-    /// Resolve a query set, writing the results into the supplied destination buffer.
+    /// Resolves a query set, writing the results into the supplied destination buffer.
     ///
-    /// Queries may be between 8 and 40 bytes each. See [`PipelineStatisticsTypes`] for more information.
+    /// Occlusion and timestamp queries are 8 bytes each. For pipeline statistics queries,
```
Comment (Wumpf) [inline wgpu/src/lib.rs]:
```suggestion
    /// Occlusion and timestamp queries are 8 bytes each (see [`wgpu::QUERY_SIZE`]). For pipeline statistics queries,
```

**Review by Wumpf — APPROVED** [review]
nice, thank you!

**Comment by cwfitzgerald** [comment]
CI is failing

**Comment by Wumpf** [comment]
oops, my fault!
