### PR TITLE
metal: prevent command buffer exhaustion deadlocks

### LINKED ISSUE #3084: Hitting the `MAX_COMMAND_BUFFERS` limit for Metal
**Description**
The Metal backend enforces a backend of 2048 pending command buffers here: https://github.com/gfx-rs/wgpu/blob/6451d31b7a0a1ce6dbcaf8cc7e6536ac06587f6d/wgpu-hal/src/metal/adapter.rs#L8

I am creating mipmaps for a very large (> 200 layers) texture array. My code is basically equivalent to this loop in the mipmap example (except I have to fill `m x n` mipmaps for `m` mipmap levels and `n` array layers): https://github.com/gfx-rs/wgpu/blob/6451d31b7a0a1ce6dbcaf8cc7e6536ac06587f6d/wgpu/examples/mipmap/main.rs#L136

Apparently, the loop hits the limit of 2048 command buffers. My code deadlocks when trying to drop the current render pass inside the loop.

**Repro steps**
Just reduce `MAX_COMMAND_BUFFERS` to something like 10 and try the mipmap example, this has the same effect.

**Expected vs observed behavior**
The root problem seems to be the fact that each render pass starts a new command buffer. Maybe multiple render passes can be batched into one? Or maybe wgpu can at least notify me when the limit is reached by making `begin_render_pass()` fallible?

**Platform**
wgpu 0.14, metal backend on macOS / iOS

### PR DESCRIPTION
**Pull request by waywardmonkeys**
**Connections**
Fixes #3084, #8047.

**Description**
- Track outstanding Metal command buffers per queue and gate begin_encoding against the hard MAX_COMMAND_BUFFERS, returning device-lost with an actionable warning instead of letting new_command_buffer hang when encoders are leaked.
- Share the counter across queue/encoders and decrement on submit or discard after clearing the raw command buffer so drop happens before the bookkeeping update.

**Testing**
Tests pass. I've run the test from #8047 and this code triggers.

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Using the test from #8047 with the minimal changes to compile against `trunk`, this code does pick up the issue at a count where it used to hang.

The example for the problem now shows this instead of deadlocking:

```
[2025-11-26T14:41:43Z WARN  wgpu_hal::metal::command] metal: refusing to create new command buffer; 4097 outstanding command buffers exceeds the limit of 4096. Treating this as device lost. Ensure command encoders are submitted or dropped rather than kept alive to avoid exhausting Metal's command buffer budget.

thread 'main' (58364203) panicked at /Users/bruce/Development/custodian/wgpu/wgpu/src/backend/wgpu_core.rs:2187:18:
Error in Buffer::get_mapped_range: Validation Error

Caused by:
  Buffer with '' label has been destroyed

stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/panicking.rs:75:14
   2: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_fatal
             at /Users/bruce/Development/custodian/wgpu/wgpu/src/backend/wgpu_core.rs:348:9
   3: <wgpu::backend::wgpu_core::CoreBuffer as wgpu::dispatch::BufferInterface>::get_mapped_range
             at /Users/bruce/Development/custodian/wgpu/wgpu/src/backend/wgpu_core.rs:2187:18
   4: wgpu::api::buffer::BufferSlice::get_mapped_range
             at /Users/bruce/Development/custodian/wgpu/wgpu/src/api/buffer.rs:606:39
   5: TestEncoderTooManyCpasses::main
             at ./src/main.rs:258:29
```

So you don't get a clear indication of what happened unless you have the logs on...

File: wgpu-hal/src/metal/mod.rs [hunk 1]
```diff
@@ -362,6 +362,10 @@ pub struct Adapter {
 
 pub struct Queue {
     raw: Arc<Mutex<metal::CommandQueue>>,
+    // Tracks command buffers created via `CommandEncoder::begin_encoding` that
+    // have not yet been submitted or discarded. Used to proactively fail
+    // before hitting Metal's `maxCommandBufferCount`.
+    command_buffer_created_not_submitted: Arc<atomic::AtomicU64>,
```
Comment (andyleiserson) [inline wgpu-hal/src/metal/mod.rs]: An observation, but not important: it might be possible to use `Arc<()>` and rely on `Arc::strong_count` to indicate the number of outstanding command buffers. Although there is an issue of the difference between when the command encoder is created and when `begin_encoding` is called.

**Review by andyleiserson — APPROVED** [review]
Thanks for this, Firefox has the same concern.

Another test case is `cargo xtask cts 'webgpu:api,validation,resource_usages,texture,in_render_common:*'`.

**Comment by inner-daemons** [comment]
@waywardmonkeys Do you plan on coming back to this PR

**Comment by andyleiserson** [comment]
[1e677f2](https://github.com/gfx-rs/wgpu/commit/1e677f234ac4c109821a44a0804fc95c0f8a95cd) resolves conflicts with the objc2 changes, primarily the command buffer count changing from u64 to usize.

[c206f68](https://github.com/gfx-rs/wgpu/commit/c206f68d8025f3f34de1212df543609d6392aadc) rebases onto #9217 and puts the command buffer count in the new `QueueShared` struct so there doesn't need to be an `Arc` solely for the command buffer count.

[Comparing those two SHAs](https://github.com/gfx-rs/wgpu/compare/1e677f234ac4c109821a44a0804fc95c0f8a95cd..c206f68d8025f3f34de1212df543609d6392aadc) shows the substantive changes I have made to this PR combined with the diff from #9217.

**Comment by ErichDonGubler** [comment]
@andyleiserson: Looks like CI has a quibble with your changes.

**Comment by waywardmonkeys** [comment]
Thanks for landing this! I am weeks behind on email so just saw the one from three days ago by chance!
