### PR TITLE
Cast ptr to Device not Surface

### LINKED ISSUE #5637: STATUS_ACCESS_VIOLATION on exit
**Description**
Since I have updated from 0.19 to 0.20, I am facing an issue similar to #1377.

When my program exits after the first use of the device, in a call `surface.configure(&device, &config)`, the program exits with STATUS_ACCESS_VIOLATION when exiting through an anyhow error bubbled up to pollster or a regular exit with an `Ok(())` result.

When I use the `panic!()` macro, it seems fine. See the various exit scenarios commented in the snippet below.

**Repro steps**

Extracted minimal reproduction from my Main Project in which I am using pollster, anyhow and winit.

```rust
use anyhow::{Context, Result};
use std::sync::Arc;
use wgpu::Features;
use winit::event_loop::{EventLoop};
use winit::window::WindowBuilder;


#[pollster::main]
async fn main() -> Result<()> {
    let event_loop = EventLoop::new()
        .context("Failed to create event loop")?;

    let window = Arc::new(WindowBuilder::new()
        .with_title("Panic! at the disco")
        .build(&event_loop)
        .context("Failed to create window")?);

    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
        backends: wgpu::Backends::all(),
        ..Default::default()
    });

    let surface = instance.create_surface(window.clone())
        .context("Failed to create surface")?;

    let adapter = instance.request_adapter(
        &wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            force_fallback_adapter: false,
            compatible_surface: Some(&surface),
        })
        .await
        .context("Failed to find an appropriate adapter")?;

    let (device, _queue) = adapter
        .request_device(
            &wgpu::DeviceDescriptor {
                label: None,
                required_features: Features::default(),
                required_limits: Default::default(),
            },
            None,
        )
        .await
        .context("Failed to create device / queue")?;

    let surface_caps = surface.get_capabilities(&adapter);
    let surface_format = surface_caps.formats.iter()
        .filter(|format| format.is_srgb())
        .next()
        .unwrap_or(surface_caps.formats.first().context("No surface formats found")?);

    let config = wgpu::SurfaceConfiguration {
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
        format: *surface_format,
        width: window.inner_size().width,
        height: window.inner_size().height,
        present_mode: surface_caps.present_modes[0],
        alpha_mode: surface_caps.alpha_modes[0],
        view_formats: vec![],
        desired_maximum_frame_latency: 2,
    };

    // error before call to surface.configure, will exit as expected
    // return Err(anyhow::anyhow!("Disco"));

    surface.configure(&device, &config);

    // panic exits with code 101, as expected
    // panic!();

    // this will exit with exit code: 0xc0000005, STATUS_ACCESS_VIOLATION, unexpected
    return Err(anyhow::anyhow!("Disco"));

    // when forgetting the device first, will exit as expected
    // std::mem::forget(device);
    // return Err(anyhow::anyhow!("Disco"));

    // also without a panic, the program will exit with exit code: 0xc0000005, STATUS_ACCESS_VIOLATION, unexpected
    Ok(())
}
```

**Expected vs observed behavior**
Running the above code results in the program exiting with STATUS_ACCESS_VIOLATION, but I expect it to exit with code 1 and a message printed:

```
Error: Disco

Stack backtrace:
<followed by backtrace>
```

Specifying `0.19.4` for version in the dependencies does indeed show this expected behavior, where with `0.20.0` the access violation is seen.

Expected behavior with `0.20.0` is seen when specifying `wgpu::Backends::GL` as opposed to `VULKAN`, `DX12` or `all()`.

**Platform**
```toml
[dependencies]
anyhow = "1.0.82"
pollster = { version = "0.3.0", features = ["macro"] }
wgpu = { version = "0.20.0" }
winit = { version = "0.29.15", features = ["rwh_06"] }
```

reproduced on:
 * windows 11 [Version 10.0.22631.3527]: rustc 1.76.0 (07dca489a 2024-02-04)
 * windows 11 [Version 10.0.22631.3527]: rustc 1.78.0-nightly (2d24fe591 2024-03-09)
 * in CI using docker.io/rustlang/rust:nightly: rustc 1.79.0-nightly (aed2187d5 2024-04-27)
   * cross compiled using `cargo build --target=x86_64-pc-windows-gnu` and ran on the same windows 11

adapter, driver and other info, from log from Main Project, that has `env_logger` output:

```
[2024-04-30T00:47:47Z WARN  wgpu_hal::vulkan::instance] InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation
[2024-04-30T00:47:47Z INFO  wgpu_hal::vulkan::instance] Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw
[2024-04-30T00:47:47Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 4080 SUPER", vendor: 4318, device: 9986, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "551.61", backend: Vulkan }
[2024-04-30T00:47:47Z INFO  wgpu_core::instance] Adapter Dx12 AdapterInfo { name: "NVIDIA GeForce RTX 4080 SUPER", vendor: 4318, device: 9986, device_type: DiscreteGpu, driver: "", driver_info: "", backend: Dx12 }
[2024-04-30T00:47:47Z INFO  wgpu_core::instance] Adapter Dx12 AdapterInfo { name: "Microsoft Basic Render Driver", vendor: 5140, device: 140, device_type: Cpu, driver: "", driver_info: "", backend: Dx12 }
[2024-04-30T00:47:47Z INFO  wgpu_core::instance] Adapter Gl AdapterInfo { name: "NVIDIA GeForce RTX 4080 SUPER/PCIe/SSE2", vendor: 4318, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
[2024-04-30T00:47:47Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 4080 SUPER", vendor: 4318, device: 9986, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "551.61", backend: Vulkan }
```

### PR DESCRIPTION
**Pull request by sagudev**
Arc has device stored inside not surface.

fixes https://github.com/gfx-rs/wgpu/issues/5637

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [x] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu-core/src/device/any_device.rs [hunk 1]
```diff
@@ -34,7 +34,7 @@ impl AnyDevice {
         unsafe fn drop_glue<A: HalApi>(ptr: *mut ()) {
             // Drop the arc this instance is holding.
             unsafe {
-                _ = Arc::from_raw(ptr.cast::<A::Surface>());
+                _ = Arc::from_raw(ptr.cast::<A::Device>());
```
Comment (ErichDonGubler) [inline wgpu-core/src/device/any_device.rs:37]: This looks like a copy-paste error introduced in https://github.com/gfx-rs/wgpu/pull/5081 (CC @udoprog, the author, as an FYI, no action items I can see).

**Review by cwfitzgerald — APPROVED** [review]
Well, that's a doozy

**Review by ErichDonGubler — APPROVED** [review]
Oof, seems pretty clear!

**Comment by Wumpf** [comment]
this fix here has a little whoopsie in there, fixed here:
* https://github.com/gfx-rs/wgpu/pull/6052

(noticed only now after merging that these are related)

**Comment by sagudev** [comment]
Unsafe code is hard :pensive:.
