### PR TITLE
Query support fixes

### LINKED ISSUE #1374: Query values all zero in mipmap example with wgpu 0.8
I noticed that when I run the mipmap example with the new wgpu version 0.8 all the query values are zero:
```
Generating mip level 1 took 0.0000000000 μs and called the fragment shader 0 times
Generating mip level 2 took 0.0000000000 μs and called the fragment shader 0 times
Generating mip level 3 took 0.0000000000 μs and called the fragment shader 0 times
Generating mip level 4 took 0.0000000000 μs and called the fragment shader 0 times
Generating mip level 5 took 0.0000000000 μs and called the fragment shader 0 times
Generating mip level 6 took 0.0000000000 μs and called the fragment shader 0 times
Generating mip level 7 took 0.0000000000 μs and called the fragment shader 0 times
Generating mip level 8 took 0.0000000000 μs and called the fragment shader 0 times
```
With wgpu 0.7 I get values:
```
Generating mip level 1 took 9920.0000000000 μs and called the fragment shader 65536 times
Generating mip level 2 took 5184.0000000000 μs and called the fragment shader 16384 times
Generating mip level 3 took 4192.0000000000 μs and called the fragment shader 4096 times
Generating mip level 4 took 3904.0000000000 μs and called the fragment shader 1024 times
Generating mip level 5 took 3968.0000000000 μs and called the fragment shader 256 times
Generating mip level 6 took 3776.0000000000 μs and called the fragment shader 64 times
Generating mip level 7 took 3648.0000000000 μs and called the fragment shader 16 times
Generating mip level 8 took 2688.0000000000 μs and called the fragment shader 4 times
```

### PR DESCRIPTION
**Pull request by Wumpf**
**Connections**
Fixes #1374 for master
If PR is accepted,I already have a fix for 0.9 which came out as a sideproduct: https://github.com/Wumpf/wgpu/tree/v0.9-fix-buffer-init-on-query-resolve

**Description**
Fixes:
* (affects master, v0.8, v0.9) query resolve operation not marking buffers as initialized
* (affects master) Broken query stride handling for Vulkan
* (affects master) Vulkan not advertising query support

**Testing**
* added new test
* mipmap sample

### CODE REVIEW

File: wgpu-hal/src/metal/command.rs [hunk 1]
```diff
@@ -296,6 +296,7 @@ impl crate::CommandEncoder<super::Api> for super::CommandEncoder {
         range: Range<u32>,
         buffer: &super::Buffer,
         offset: wgt::BufferAddress,
+        _: wgt::BufferSize, // Metal doesn't support queries that are bigger than a single element are not supported
```
Comment (kvark) [inline wgpu-hal/src/metal/command.rs:299]: comment needs to be adjusted a bit, it says "not supported" twice

**Review by kvark — APPROVED** [review]
Looks great, thank you for addressing this!
I specifically didn't want to include the `stride` parameter in the `copy_query_results`, since it's not portable, but it appears to be required for pipeline statistics, so oh well :)
bors r+

File: wgpu-hal/src/metal/command.rs (hunk 1 above)
Comment (Wumpf) [reply wgpu-hal/src/metal/command.rs:299]: Oops
