### PR TITLE
[WebGPU] validate polygon mode

### LINKED ISSUE #4194: [WebGPU] Error if any required feature is not available
**Description**
When requesting POLYGON_MODE_LINE in webgpu it doesn't give an error despite it not working. Webgl correctly gives an error.

A similar issue also happen when using `PolygonMode::Line` without requesting the feature. In webgl it will give an error while in webgpu it gives no error but doesn't render correctly.

**Repro steps**
I discovered this with bevy. I tried making a simple reproduction but I couldn't figure out how to build a simple repro and build it for wasm, I kept getting unrelated errors, I was probably doing something wrong. Is there a simple template somewhere that I could use?

**Expected vs observed behavior**
Expected: All platform that do not support `POLYGON_MODE_LINE` to raise an error if the feature is requested
Observed: Some platform that do not support `POLYGON_MODE_LINE`  do not raise an error if the feature is requested

**Platform**
I was using windows, but I don't think this is OS related.
This was found with bevy 0.12-dev which is still on wgpu 0.16

### PR DESCRIPTION
**Pull request by teoxoy**
**Checklist**

- [x] Run `cargo clippy`.
- [ ] Run `cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
fixes https://github.com/gfx-rs/wgpu/issues/4194

### CODE REVIEW

File: wgpu/src/backend/web.rs [hunk 1]
```diff
@@ -340,6 +340,18 @@ fn map_primitive_state(primitive: &wgt::PrimitiveState) -> web_sys::GpuPrimitive
     //TODO:
     //mapped.unclipped_depth(primitive.unclipped_depth);
 
+    match primitive.polygon_mode {
+        wgt::PolygonMode::Fill => {}
```
Comment (ErichDonGubler) [inline wgpu/src/backend/web.rs:344]: nitpick: I think `()` is generally preferable over `{}`; it's more direct.

Pushed as 48f701bb.

File: wgpu/src/backend/web.rs [hunk 2]
```diff
@@ -340,6 +340,18 @@ fn map_primitive_state(primitive: &wgt::PrimitiveState) -> web_sys::GpuPrimitive
...
+        wgt::PolygonMode::Line => panic!(
+            "{:?} is not enabled for this backend",
+            wgt::Features::POLYGON_MODE_LINE
+        ),
+        wgt::PolygonMode::Point => panic!(
+            "{:?} is not enabled for this backend",
+            wgt::Features::POLYGON_MODE_POINT
+        ),
```
Comment (ErichDonGubler) [inline wgpu/src/backend/web.rs:352]: nitpick: Pushed this suggestion as 16ff4df1:

```suggestion
        mode @ (wgt::PolygonMode::Line | wgt::PolygonMode::Point) => {
            panic!("{mode:?} is not enabled for this backend",)
        }
```

**Review by ErichDonGubler — APPROVED** [review]
Pushed up my nitpicks as `fixup!` commits, so you can autosquash. If you disagree, feel free to drop the relevant commits instead. 🙂

Non-blocking, but: Is there a way we can meaningfully test for this? Not sure what appetite we have for backend-specific tests, but it'd be nice to not regress later.

File: wgpu/src/backend/web.rs (hunk 2 above)
Comment (teoxoy) [reply wgpu/src/backend/web.rs:352]: I think the panic should mention the feature rather than the mode itself. There is precedent for this, if we want to use the mode instead we should discuss about it and do it everywhere.

File: wgpu/src/backend/web.rs (hunk 1 above)
Comment (teoxoy) [reply wgpu/src/backend/web.rs:344]: It's not very often I see `()` over `{}` in this case. I personally prefer `{}` but don't care much as long as we consistently use one of them, the only reliable way of doing that being through rustfmt. However, there seems to be no such rule we could enable (https://rust-lang.github.io/rustfmt).

Comment (cwfitzgerald) [reply wgpu/src/backend/web.rs:344]: I also prefer {}.  It's standard for "empty block" == do nothing, as opposed "returns the empty tuple" == do something by returning a nothing.

File: wgpu/src/backend/web.rs (hunk 2 above)
Comment (cwfitzgerald) [reply wgpu/src/backend/web.rs:352]: Yeah, the feature is the error you get elsewhere as well. We should keep this consistant.

**Review by cwfitzgerald — COMMENTED** [review]
Going to respectfully veto @ErichDonGubler's changes, and this is good to go once they're reverted.

**Comment by ErichDonGubler** [comment]
> Going to respectfully veto @ErichDonGubler's changes, and this is good to go once they're reverted.

🤔 Huh, I didn't expect these to be controversial. Why's that?

**Comment by cwfitzgerald** [comment]
I responded individually in each subthread :)

File: wgpu/src/backend/web.rs (hunk 2 above)
Comment (ErichDonGubler) [reply wgpu/src/backend/web.rs:352]: Ah, I see how this refactor was incorrect. Sorry about that!
