### PR TITLE
Validation fixes for dual-source blending, depth bias, and `frag_depth`

### LINKED ISSUE #6071: Point and line primitives must not have depth bias
<https://github.com/gpuweb/gpuweb/pull/4743> introduced new validation that we do not yet support. We should do that!

### LINKED ISSUE #8592: dual source blending is forced if enabled (wgpu being overly strict?)
**Description**
creating a render pipeline with a shader module that uses dual source blending but not using the dual source as one of the blend factors in one of the components of the blend state yields the following validation error:
`Shader entry point expects the pipeline to make use of dual-source blending`.

**Repro steps**
just create a render pipeline using a shader with dual source blending enabled and `wgpu::BlendState::REPLACE` for the pipeline and it will fail.

**Expected vs observed behavior**
the pipeline creation fails, but it doesn't seem like it needs to. it makes sense to fail to create a pipeline if the blend state uses dual source blending and the shader does not, but failling to create a pipeline if it does not necessarily use the dual source in the blending might be overly strict. for example, this behaviour makes it impossible to use `wgpu::BlendState::REPLACE`.

i'm not a gpu expert or anything close to that, but i couldn't find anywhere on the WebGPU spec that this should be the case. in fact, all i could find is that the `dual-source-blending` feature being enabled _allows_ the usage of `Src1`, `OneMinusSrc1`, `Src1Alpha` and `OneMinusSrc1Alpha` blend factors (but does not _require_ it).

**Extra materials**
WebGPU spec on the `dual-source-blending` feature: https://www.w3.org/TR/webgpu/#dom-gpufeaturename-dual-source-blending

the code responsible for this behaviour is this one:
https://github.com/gfx-rs/wgpu/blob/75188a7fe1c7826a8122f6c80292ac73a5e8ae09/wgpu-core/src/device/resource.rs#L4405-L4414

more specifically, the first `if` expression.

### PR DESCRIPTION
**Pull request by andyleiserson**
Several validation fixes. The only reason the dual-source blending fix is related is that both it and the `frag_depth` fix add fields to `ShaderStageForValidation::Fragment` that @ErichDonGubler added recently.

* If the pipeline uses dual-source blending, then the shader must configure appropriate I/O, but it is not an error to use a shader that defines the I/O in a pipeline that only uses one blend source. Fixes #8592.
* Depth bias is only supported with triangle topologies. Fixes #6071.
* If the shader outputs `frag_depth`, then the pipeline must have a depth attachment. (No bug.)

This change will conflict with #8840, which needs more discussion, so I expect #8840 will be rebased on this one. Whichever lands second should enable the entire `depth_stencil_state` suite.

**Testing**
Enables relevant CTS tests.

**Squash or Rebase?** Rebase

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [ ] Run `cargo xtask test` to run tests.
- [x] Add `CHANGELOG.md` entries.

### CODE REVIEW

**Comment by dhardy** [comment]
This doesn't solve my issue (should have been an issue not a discussion): https://github.com/gfx-rs/wgpu/discussions/8798
```
wgpu error: Validation Error

Caused by:
  In Device::create_render_pipeline, label = 'text subpixel mask pipe'
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
      Pipeline uses dual-source blending, but the shader does not support it
```
This is using a GLSL shader which works correctly if I hack wgpu to disable this validation completely.

**Comment by andyleiserson** [comment]
> This doesn't solve my issue (should have been an issue not a discussion): #8798

It's not related to this change, but I filed #8864 from your discussion, and opened #8865 and https://github.com/kas-gui/kas/pull/635.

File: wgpu-core/src/validation.rs [hunk 1]
```diff
@@ -1644,6 +1648,15 @@ impl Interface {
                 if dual_source_blending && !entry_point.dual_source_blending {
                     return Err(StageError::InvalidDualSourceBlending);
                 }
+
+                if entry_point
+                    .outputs
+                    .iter()
+                    .any(|varying| matches!(varying, Varying::BuiltIn(naga::BuiltIn::FragDepth)))
```
Comment (Wumpf) [inline wgpu-core/src/validation.rs]: would be nice if those types would be `Eq` so we could just do a `contains`, any reason why not?

**Review by Wumpf — APPROVED** [review]
very nice, thanks for the logical commit split

**Comment by andyleiserson** [comment]
The push of https://github.com/gfx-rs/wgpu/commit/c20c23a4d7b602bb9d7df6b1739806d6a07695a0 is a rebase plus a new commit to implement (and use) `Eq` for `Varying`.

The push of https://github.com/gfx-rs/wgpu/commit/bc4b44ec536004aa5d5427df5054fb9e55fc081c was an incorrect (partial) attempt to squash the new commit, and the push of https://github.com/gfx-rs/wgpu/commit/75180c34082c9225e49804224f676a922d42fe8f actually squashes the commit.

Sorry for the noise.

File: wgpu-core/src/validation.rs (hunk 1 above)
Comment (andyleiserson) [reply wgpu-core/src/validation.rs]: I don't see why not. Depending on how tightly the enums get packed, the `Varying::Local { location: u32, iv: InterfaceVar }` variant could be one or two words, or could be a handful more than that, but it's not so much that it seems inappropriate to implement `Eq`.
