### PR TITLE
Validate Dynamic Bindings are In-Bounds

### LINKED ISSUE #756: Overstepping buffer range with dynamic offsets results in vulkan validation error (CoreValidation-DrawState-DescriptorSetNotUpdated)
I'm using wgpu master on linux.

If a buffer slice with a dynamic offset is bound a vulkan validation error is triggered if `buffer_range_start+dynamic_offset+buffer_range_length` exceeds the length of the underlying buffer.
Example:
```
// setup
    let geometry_bind_group_layout =
        device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: None,
            bindings: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStage::VERTEX,
                ty: wgpu::BindingType::UniformBuffer {
                    dynamic: true,  // <-!!!
                    min_binding_size: None,
                },
                count: None,
                _non_exhaustive: Default::default(),
            }],
        });
    let geometry_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: None,
        layout: &geometry_bind_group_layout,
        bindings: &[wgpu::Binding {
            binding: 0,
            resource: wgpu::BindingResource::Buffer(uniform_buffer.slice(buffer_range_start..buffer_range_end)), // <-!!!
        }],
    });
....
// before draw call
    rpass.set_bind_group(0, &geometry_pass.bind, &[dynamic_offset]);  // <-!!!
```
Of course the code is buggy (buffer too short), but my understanding is that this should be caught before it hits the vulkan API.

The validation error is:
```
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object 0: handle = 0x2630000000263, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x50363c8d | VkDescriptorSet 0x2630000000263[] bound as set #0 encountered the following validation error at vkCmdDraw() time: Dynamic descriptor in binding #0 index 0 uses buffer 0x2600000000260 with dynamic offset 27136 combined with offset 0 and range 65536 that oversteps the buffer size of 65536.
    object info: (type: DESCRIPTOR_SET, hndl: 671801604571747)

```

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Closes #756 

**Description**

Needed to store some basic info about all dynamic bindings in the bind group.

I wasn't exactly sure where to put the validation function, so I stuck it as an inherent function on the BindGroup. Can be moved if this isn't ideal.

I also moved offset alignment validation into the validation function to help reduce duplication between render/compute.

**Testing**

None of the examples use dynamic indexing, so it's hard to test this as is.

@FlorianUekermann could you possibly test this patch with your repro case?

### CODE REVIEW

File: wgpu-core/src/binding_model.rs [hunk 1]
```diff
@@ -122,6 +130,47 @@ pub struct BindGroup<B: hal::Backend> {
     pub(crate) life_guard: LifeGuard,
     pub(crate) used: TrackerSet,
     pub(crate) dynamic_count: usize,
```
Comment (kvark) [inline wgpu-core/src/binding_model.rs:132]: this should now be unnecessary, as one would just take `dynamic_binding_info.len()` instead

File: wgpu-core/src/binding_model.rs [hunk 2]
```diff
@@ -122,6 +130,47 @@ pub struct BindGroup<B: hal::Backend> {
...
+    pub(crate) dynamic_binding_info: Vec<BindGroupDynamicBindingData>,
+}
+
+impl<B: hal::Backend> BindGroup<B> {
+    pub(crate) fn validate_dynamic_bindings(&self, offsets: &[wgt::DynamicOffset]) {
```
Comment (kvark) [inline wgpu-core/src/binding_model.rs:137]: We are trying to migrate from assertions to error codes. Since this is new code, let's make this right from start and return a `Result<(), BindError>`

File: wgpu-core/src/binding_model.rs [hunk 3]
```diff
@@ -114,6 +114,14 @@ pub struct BindGroupDescriptor<'a> {
     pub bindings: &'a [BindGroupEntry<'a>],
 }
 
+#[derive(Debug)]
+pub struct BindGroupDynamicBindingData {
+    /// Total size of the buffer
+    pub(crate) buffer_size: wgt::BufferAddress,
+    /// The end of the binding. For a binding 16..32, this will be 32.
+    pub(crate) binding_end_offset: wgt::BufferAddress,
```
Comment (kvark) [inline wgpu-core/src/binding_model.rs:122]: why don't we just have a single `max_offset` field instead of these two?

**Comment by cwfitzgerald** [comment]
Should be good to go.

File: wgpu-core/src/binding_model.rs [hunk 4]
```diff
@@ -114,14 +114,79 @@ pub struct BindGroupDescriptor<'a> {
...
+                log::error!(
+                    "Dynamic buffer offset index {}: {} needs to be aligned as a multiple of {}",
+                    idx,
+                    offset,
+                    wgt::BIND_BUFFER_ALIGNMENT
+                );
+                return Err(BindError::UnalignedDynamicBinding { idx });
+            }
+
+            if offset as wgt::BufferAddress <= info.maximum_dynamic_offset {
```
Comment (kvark) [inline wgpu-core/src/binding_model.rs:177]: wrong comparison :)

File: wgpu-core/src/binding_model.rs [hunk 5]
```diff
@@ -114,14 +114,79 @@ pub struct BindGroupDescriptor<'a> {
...
 }
 
+#[derive(Debug)]
+pub enum BindError {
+    /// Number of dynamic offsets doesn't match the number of dynamic bindings
+    /// in the bind group layout.
+    MismatchedDynamicOffsetCount { actual: usize, expected: usize },
+    /// Expected dynamic binding alignment was not met.
+    UnalignedDynamicBinding { idx: usize },
+    /// Dynamic offset would cause buffer overrun
```
Comment (kvark) [inline wgpu-core/src/binding_model.rs:124]: nit: missing period
