### PR TITLE
Stop Vulkan generating validation error in build acceleration structures

### LINKED ISSUE #6278: Validation error when building acceleration structure without index buffer
**Description**
When building an acceleration structure on vulkan a vulkan validation layer error is printed
````cmd
Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03806 ] Object 0: handle = 0x2bae8c8dec0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x76173dcc | vkCmdBuildAccelerationStructuresKHR(): pInfos[0].pGeometries[0].geometry.tria
ngles.indexData.deviceAddress (0x0) is not an address belonging to an existing buffer. pInfos[0].pGeometries[0].geometry.triangles.indexType is VK_INDEX_TYPE_UINT16. The Vulkan spec states: For any element of pInfos[i].pGeometries or pInfos[i].ppGeometries wit
h a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.indexType is not VK_INDEX_TYPE_NONE_KHR, geometry.triangles.indexData.deviceAddress must be a valid device address obtained from vkGetBufferDeviceAddress (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03806)
````
this is because when calling `AccelerationStructureGeometryTrianglesDataKHR::default()` in
https://github.com/gfx-rs/wgpu/blob/2fac5e983e0f0d33f127bde04c2c3b0621faa685/wgpu-hal/src/vulkan/command.rs#L504-L506
IndexType is set to `UINT16` (because apart from when building acceleration structures `NONE_KHR` is not valid) therefore this needs to be set by the code.

**Repro steps**
Call `build_acceleration_structures` on a vulkan device without providing a index buffer (by setting `AccelerationStructureTriangles::indices to `None`)

**Expected vs observed behavior**
There should be no validation error but one is generated

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

**Platform**
N/a

**Proposed Fix**
```
impl crate::CommandEncoder for super::CommandEncoder {
                     for triangles in in_geometries {
                         let mut triangle_data =
                             vk::AccelerationStructureGeometryTrianglesDataKHR::default()
+                                .index_type(vk::IndexType::NONE_KHR)
                                 .vertex_data(vk::DeviceOrHostAddressConstKHR {
                                     device_address: get_device_address(triangles.vertex_buffer),
                                 })
```

### PR DESCRIPTION
**Pull request by Vecvec**
**Connections**
fixes #6278 

**Description**
This stops vulkan validation layers giving an error when index buffer is not specified, also updates ray-traced triangle to be configurable whether to use an index buffer.

**Testing**
run raytraced triangle without argument `index_buffer`, before:
````cmd
    Rgba8Unorm,
    Rgba8UnormSrgb,
]
[2024-09-16T05:12:41Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03806 (0x76173dcc)]
        Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03806 ] Object 0: handle = 0x1be9895ffa0, name = init, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x76173dcc | vkCmdBuildAccelerationStructuresKHR(): pInfos[0].pGeometries[0].
geometry.triangles.indexData.deviceAddress (0x0) is not an address belonging to an existing buffer. pInfos[0].pGeometries[0].geometry.triangles.indexType is VK_INDEX_TYPE_UINT16. The Vulkan spec states: For any element of pInfos[i].pGeometries or pInfos[i].ppG
eometries with a geometryType of VK_GEOMETRY_TYPE_TRIANGLES_KHR, if geometry.triangles.indexType is not VK_INDEX_TYPE_NONE_KHR, geometry.triangles.indexData.deviceAddress must be a valid device address obtained from vkGetBufferDeviceAddress (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03806)
[2024-09-16T05:12:41Z ERROR wgpu_hal::vulkan::instance]         objects: (type: COMMAND_BUFFER, hndl: 0x1be9895ffa0, name: init)
````
after:
````cmd
 Bgra8UnormSrgb,
    Rgba8Unorm,
    Rgba8UnormSrgb,
]

Process finished with exit code 0
````

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [] `--target wasm32-unknown-unknown` N/a
  - [] `--target wasm32-unknown-emscripten` N/a
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu-hal/src/vulkan/command.rs [hunk 1]
```diff
@@ -503,6 +503,8 @@ impl crate::CommandEncoder for super::CommandEncoder {
                     for triangles in in_geometries {
                         let mut triangle_data =
                             vk::AccelerationStructureGeometryTrianglesDataKHR::default()
+                                // by default this is IndexType::UINT16 because IndexType::NONE_KHR is only allowed here
```
Comment (JMS55) [inline wgpu-hal/src/vulkan/command.rs]: I don't really understand what this comment is saying, can you elaborate?

Comment (Vecvec) [reply wgpu-hal/src/vulkan/command.rs]: None_KHR is only provided by extension acceleration structures (for use while building) so it is by not the default, since it is not the default, but here if we don't have an index buffer we need to have None_KHR, so we need to set it here.

I've realized that the comment is confusing, I'll look at updating it

**Review by JMS55 — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -117,6 +117,7 @@ By @bradwerth [#6216](https://github.com/gfx-rs/wgpu/pull/6216).
 #### Vulkan
 
 - Vulkan debug labels assumed no interior nul byte. By @DJMcNab in [#6257](https://github.com/gfx-rs/wgpu/pull/6257)
+- Add `.index_type(vk::IndexType::NONE_KHR)` when creating `AccelerationStructureGeometryTrianglesDataKHR` to prevent a validation error. By @Vecvec in [#6282](https://github.com/gfx-rs/wgpu/pull/6282)
```
Comment (nical) [inline CHANGELOG.md]:
```suggestion
- Add `.index_type(vk::IndexType::NONE_KHR)` when creating `AccelerationStructureGeometryTrianglesDataKHR` in the raytraced triange example to prevent a validation error. By @Vecvec in [#6282](https://github.com/gfx-rs/wgpu/pull/6282)
```

**Review by nical — APPROVED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -117,6 +117,7 @@ By @bradwerth [#6216](https://github.com/gfx-rs/wgpu/pull/6216).
 #### Vulkan
 
 - Vulkan debug labels assumed no interior nul byte. By @DJMcNab in [#6257](https://github.com/gfx-rs/wgpu/pull/6257)
+- Add `.index_type(vk::IndexType::NONE_KHR)` when creating `AccelerationStructureGeometryTrianglesDataKHR` in the raytraced triange example to prevent a validation error. By @Vecvec in [#6282](https://github.com/gfx-rs/wgpu/pull/6282)
```
Comment (nical) [inline CHANGELOG.md]:
```suggestion
- Add `.index_type(vk::IndexType::NONE_KHR)` when creating `AccelerationStructureGeometryTrianglesDataKHR` in the raytraced triangle example to prevent a validation error. By @Vecvec in [#6282](https://github.com/gfx-rs/wgpu/pull/6282)
```
