### PR TITLE
Fix Android crash by setting `waitAll` to true in `vkWaitForFences`

### LINKED ISSUE #8553: Regression from wgpu-hal v26.0.6: Crash on Android
**Description**
Running any bevy examples (with render feature) on Android crashes since I updated to wgpu-hal v26.0.6 (may be due to #8420 according to the changelog).
It doesn't crash if I use `wgpu-hal = { version = "=26.0.5" }`.
~I'm not sure if this is fixed in v27 because bevy hasn't upgrade to wgpu v27~ v27 has the same issue.

**Repro steps**
Run the bevy mobile example on Android.

**Expected vs observed behavior**
It crashes with a segfault after a few frames.

**Platform**
Android, Mali G76

### PR DESCRIPTION
**Pull request by beicause**
**Connections**
Fixes #8553

**Description**
I can still reproduce the linked issue on https://github.com/jinleili/wgpu-in-app with wgpu v28 which doesn't depend on Bevy. But the good news is I found the crash no longer occurs once I set the `wait_all` parameter in `wait_for_fences` to true.

I only tested it on one Android device (Mali-G76) and have no idea why this works, but I believe this is a very safe change.

**Testing**
Tested this on my physical Android device with Mali-G76, api level 31.

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-hal/src/vulkan/swapchain/native.rs [hunk 1]
```diff
@@ -470,7 +470,7 @@ impl Swapchain for NativeSwapchain {
         unsafe {
             self.device
                 .raw
-                .wait_for_fences(&[self.fence], false, timeout_ns)
+                .wait_for_fences(&[self.fence], true, timeout_ns)
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/swapchain/native.rs:474]: Definitely need a comment here explaining why this is needs to be set true and linking back to the issue/PR. We'll never remember otherwise :)

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
G2G after comment. Will backport this to 28 and 27

**Comment by cwfitzgerald** [comment]
@AlbinBernhardssonARM Heyo! Do you know if this is a known issue? See this, #8553, and #8420 for more context.

**Review by cwfitzgerald — APPROVED** [review]

**Comment by AlbinBernhardssonARM** [comment]
> @AlbinBernhardssonARM Heyo! Do you know if this is a known issue? See this, #8553, and #8420 for more context.

The driver behaves very differently depending on `waitAll` (basically two entirely separate paths), but there shouldn't be any user-observable difference when `fenceCount` is 1 (beyond minor timing). I'm not aware of any issues that could cause this in the `waitAll=false` path, but I've raised this internally.

@beicause It would be useful to know the driver version you're on. A quick and easy way to find it is to open `chrome://gpu` in Chrome and find the `GL_VERSION` string.
Is there a reproducer I can run?

**Comment by beicause** [comment]
GL_VERSION is OpenGL ES 3.2 v1.r34p0-01eac0.25e2bb3c33faf61b5b59a4dc9253ba17 
[about-gpu-2026-01-06T15-56-40-432Z.txt](https://github.com/user-attachments/files/24455804/about-gpu-2026-01-06T15-56-40-432Z.txt)


It can be reproduced by running https://github.com/jinleili/wgpu-in-app or bevy mobile example.

**Comment by AlbinBernhardssonARM** [comment]
I ran the bevy Android example.
On Immortalis-G715 I did not reproduce any crashes (with or without the fence wait), but got rendering artifacts due to a missing barrier (#8853). The incorrect synchronization should not cause crashes, just rendering artifacts.
On a Mali-G68 I get crashes after a few frames with or without the fence wait (and with or without `waitAll`). I need to look into that more. There may be multiple issues or the "fence wait issue" is unrelated to fences and just hidden based on timing.

**Comment by cwfitzgerald** [comment]
Published in [v28.0.1!](https://github.com/gfx-rs/wgpu/releases/tag/v28.0.1)

**Comment by analytik** [comment]
Thank you for this! I backported it to 27.0.4 combined together with the early v27 version of #8924 and a manual version bump of codespan-reporting and tested on 4 different Mali Android devices and so far I got 0 crashes in 15+ minutes (while before I got crashes reliably under a minute).

I'm not confident enough to submit a PR for v27, but in case it's useful to some lost soul: https://github.com/analytik/wgpu/commit/07af396d122c5a050d03930147a23cd50ea10b1c#diff-786e4019ca344aeb5daa3e94848b7dac677e11d6d884f75d9c475a1beed7c0feR1157
