### PR TITLE
Don't implement `Send` or `Sync` on Wasm

### LINKED ISSUE #2884: wgpu calls `createBuffer` on an `undefined` from a worker thread on Wasm
**Description**
*wgpu* attempts to execute the `createBuffer` method on an `undefined` when running in a worker thread on the target `wasm32-unknown-unknown`. The instance, adapter, surface, and device were created on the main thread.

**Repro steps**
A runnable example is [here](https://norepimorphism.github.io), the source code for which is [here](https://github.com/norepimorphism/noctane); see [`wasm.rs`](https://github.com/norepimorphism/noctane/blob/a9f7e684785377acb230d39ef6b251f8c24c9589/core/examples/wasm.rs) and [`core/src/lib.rs`](https://github.com/norepimorphism/noctane/blob/a9f7e684785377acb230d39ef6b251f8c24c9589/core/src/lib.rs). More generic instructions are described below.

1. Create a new Rust crate targeting `wasm32-unknown-unknown`.
2. Export a `main` function using `#[wasm_bindgen]`.
3. In `main`, create a *wgpu* instance, adapter, device, and surface.
4. Create a new thread (e.g., using `wasm_thread`) in which a vertex buffer is created and initialized with the device returned by *wgpu*.
5. Observe the error.

**Expected vs observed behavior**
I expect the vertex buffer creation to be successful, after which render passes would occur, the command queue would be submitted, and the surface frame would ultimately be presented.

Instead, I observe that attempting to create the vertex buffer from a worker thread crashes the Wasm process.

**Extra materials**
On Microsoft Edge (Chromium-based), I receive the following error:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createBuffer')

On Firefox, I receive the following error:
TypeError: can't access property "createBuffer", getObject(...) is undefined

**Platform**
Windows 11. *wgpu* 0.13 (latest minor release). *naga* 0.9.

### PR DESCRIPTION
**Pull request by daxpedda**
**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
Fixes #2884.
Addresses #3026.

**Description**
Currently all types unsafely implement `Send` and `Sync` on the Wasm target under the assumption that Wasm doesn't support multi-threading. Which it actually does (on nightly).

This PR removes all these implementations and introduces `MaybeSend` and `MaybeSync` supertraits to continue implementing `Send` and `Sync` on non-Wasm targets.

**Testing**
It's not, maybe in the future we could add some Wasm multithreading examples/tests.

### CODE REVIEW

File: wgpu/src/lib.rs [hunk 1]
```diff
@@ -4531,3 +4581,51 @@ impl Display for Error {
         }
     }
 }
+
+use send_sync::*;
+
+mod send_sync {
```
Comment (cwfitzgerald) [inline wgpu/src/lib.rs:4977]: Could we just put this as a two modules in `wgpu-types` so that we don't to duplicate it across crates?

File: wgpu/src/lib.rs [hunk 2]
```diff
@@ -4531,3 +4581,51 @@ impl Display for Error {
...
+    use std::any::Any;
+    use std::fmt;
+
+    #[cfg(not(target_arch = "wasm32"))]
+    pub trait MaybeSend: Send {}
```
Comment (cwfitzgerald) [inline wgpu/src/lib.rs]: We probably should call it something other than `MaybeSend`, as users will need to use it too.`WasmNotSend` or so? Suggestions welcome

File: wgpu/src/lib.rs [hunk 3]
```diff
@@ -4502,16 +4543,25 @@ pub enum Error {
     /// Out of memory error
     OutOfMemory {
         /// Lower level source of the error.
+        #[cfg(not(target_arch = "wasm32"))]
         source: Box<dyn error::Error + Send + 'static>,
```
Comment (cwfitzgerald) [inline wgpu/src/lib.rs:4913]: These can't use `MaybeSend`?

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]

File: wgpu/src/lib.rs (hunk 3 above)
Comment (daxpedda) [reply wgpu/src/lib.rs:4913]: Unfortunately not, `dyn` has some serious limitations around that.
I could use a `Box<dyn ...>` type definition, but I thought it's a bit overkill in this case.

File: wgpu/src/lib.rs (hunk 1 above)
Comment (daxpedda) [reply wgpu/src/lib.rs:4977]: Right, I keep forgetting about this crate.

File: wgpu/src/lib.rs (hunk 2 above)
Comment (daxpedda) [reply wgpu/src/lib.rs]: I thought about this but honestly can't come up with a good name.
Also played around with re-exporting `Send` and `NoSend` under the same name and hoping that `rustdoc` would show it under it's actual name, but it didn't.

I will just use `WasmNotSend`.

File: wgpu/src/lib.rs (hunk 1 above)
Comment (daxpedda) [reply wgpu/src/lib.rs:4977]: Done.

File: wgpu/src/lib.rs (hunk 2 above)
Comment (daxpedda) [reply wgpu/src/lib.rs]: Done.

File: wgpu/src/lib.rs (hunk 3 above)
Comment (daxpedda) [reply wgpu/src/lib.rs:4913]: Done.

File: wgpu-types/src/lib.rs [hunk 4]
```diff
@@ -6165,3 +6160,26 @@ impl Default for InstanceDescriptor {
         }
     }
 }
+
+pub use send_sync::*;
+
+#[doc(hidden)]
```
Comment (daxpedda) [inline wgpu-types/src/lib.rs:6331]: I hope that's appropriate.

File: wgpu/src/lib.rs [hunk 5]
```diff
@@ -4531,3 +4582,35 @@ impl Display for Error {
...
+
+use send_sync::*;
+
+mod send_sync {
+    use std::any::Any;
+    use std::fmt;
+
+    use wgt::{WasmNotSend, WasmNotSync};
+
+    pub trait AnyWasmNotSendSync: Any + WasmNotSend + WasmNotSync {
```
Comment (daxpedda) [inline wgpu/src/lib.rs:4983]: I left this trait here because it's only used in this crate.
I hope the name isn't too awful.

File: wgpu-types/src/lib.rs (hunk 4 above)
Comment (cwfitzgerald) [reply wgpu-types/src/lib.rs:6331]: It won't show up in the docs as it's not a public module

**Comment by daxpedda** [comment]
@cwfitzgerald happy to rebase when this is ready to be merged, just hit me up.
Don't want to continuously rebase unnecessarily.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
I've had a comment queued up for the last 2 months....

The main change this needs is to have a feature to enable Send/Sync on wasm with a scary name like `unsound_send_sync_threadless_wasm32` or something

File: wgpu-types/src/lib.rs (hunk 4 above)
Comment (daxpedda) [reply wgpu-types/src/lib.rs:6331]: Right ... removed.

**Comment by daxpedda** [comment]
> The main change this needs is to have a feature to enable Send/Sync on wasm with a scary name like `unsound_send_sync_threadless_wasm32` or something

It's quite a big change actually, I removed a lot of those `Sendable`, I might almost rewrite the PR from scratch.
May I ask why this is necessary?

File: wgpu-types/src/lib.rs (hunk 4 above)
Comment (daxpedda) [reply wgpu-types/src/lib.rs:6331]: Right, I forgot the context here.
The reason why I had `#[doc(hidden)]` here was because this is a public module.
See https://github.com/gfx-rs/wgpu/pull/3691#discussion_r1171754933.

**Comment by daxpedda** [comment]
> > The main change this needs is to have a feature to enable Send/Sync on wasm with a scary name like `unsound_send_sync_threadless_wasm32` or something
> 
> It's quite a big change actually, I removed a lot of those `Sendable`, I might almost rewrite the PR from scratch. May I ask why this is necessary?

Just a suggestion, not less work, instead of a crate feature, we could just let `Send` and `Sync` be implemented if `not(feature = "atomics")`.

Another one, we could do that this feature only work on `not(feature = "atomics")` targets, which makes the most sense actually.

Though the disadvantage is that some libraries might rely on this and wouldn't be compatible with atomics then.

**Comment by daxpedda** [comment]
I added the crate feature. It's all very verbose and I should probably adjust the CI to cover it.
Some documentation of this feature would also be nice.

But before I continue, WDYT @cwfitzgerald?

**Comment by cwfitzgerald** [comment]
I think this situation is fine, though I'm not sure the feature is technically unsound in this case, as you require atomics to have threads at all. 

I'm torn as I think we probably should make it unconditional on atomics, as if someone enables this feature, you get in that same "downstream someone breaks it", but maybe that's a good thing if it would lead to unsoundness.

**Comment by daxpedda** [comment]
> I think this situation is fine, though I'm not sure the feature is technically unsound in this case, as you require atomics to have threads at all.

True, this isn't unsound then. Do you want me to rename the crate feature?

EDIT: I'm gonna deal with CI and docs tmrw.

**Comment by cwfitzgerald** [comment]
Maybe rename it fragile instead of unsound. Thoughts?

**Comment by daxpedda** [comment]
Yeah, that sounds fine!

**Comment by daxpedda** [comment]
I renamed the crate feature to `fragile-send-sync-non-atomic-wasm`.

File: .github/workflows/ci.yml [hunk 6]
```diff
@@ -138,6 +138,7 @@ jobs:
           set -e
 
           # build for WebGPU
+          cargo clippy --target ${{ matrix.target }} --tests --features glsl,spirv,fragile-send-sync-non-atomic-wasm
```
Comment (daxpedda) [inline .github/workflows/ci.yml:141]: I would like to add testing with `target-feature=+atomics` as well, but that would require Rust nightly.
Should I add another matrix entry for that?

**Comment by daxpedda** [comment]
I couldn't find a central place where all crate features were documented, would like some guidance on where to document this new crate feature.

File: .github/workflows/ci.yml (hunk 6 above)
Comment (cwfitzgerald) [reply .github/workflows/ci.yml:141]: I honestly wouldn't bother on it right now, we need a central place to document this, likely in the readme.

File: wgpu-core/src/command/bundle.rs [hunk 7]
```diff
@@ -746,7 +746,21 @@ pub struct RenderBundle<A: HalApi> {
     pub(crate) life_guard: LifeGuard,
 }
 
+#[cfg(any(
```
Comment (cwfitzgerald) [inline wgpu-core/src/command/bundle.rs:749]: Do we actually need to do this for wgpu-core and hal? Or would forcing things at the `wgpu` layer work?

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]

File: .github/workflows/ci.yml (hunk 6 above)
Comment (daxpedda) [reply .github/workflows/ci.yml:141]: Alright.

File: wgpu-core/src/command/bundle.rs (hunk 7 above)
Comment (daxpedda) [reply wgpu-core/src/command/bundle.rs:749]: Maybe? I assume it was implemented initially here for a reason.
I can try and play around with that idea.

Comment (daxpedda) [reply wgpu-core/src/command/bundle.rs:749]: Well, after scrolling through some of the places where this is done, there might be some types where this isn't necessary, but there are plenty of other implementations that require this, like callback types.

So I would say maybe, but we couldn't remove the crate feature from `core` or `hal` completely anyway.

Basically what I did in this PR is just gate the already existing `Send` and `Sync` implementations, I assumed they were there for a good reason. If they aren't then I would argue we can figure this out in a different PR, it takes me quite a bit of time to understand the internals enough to figure out if this was unnecessary or not.

Comment (cwfitzgerald) [reply wgpu-core/src/command/bundle.rs:749]: Alright, let's keep it as is then, was just trying to reduce conflicts with arcinization.

**Comment by daxpedda** [comment]
Rebased.

**Review by cwfitzgerald — APPROVED** [review]
Thanks so much for the persistence on this!

**Comment by expenses** [comment]
Thanks for adding the `fragile-send-sync-non-atomic-wasm` feature! I just tried this and it broke a ton of stuff as bevy components need to be send + sync: https://docs.rs/bevy_ecs/latest/bevy_ecs/component/trait.Component.html.

**Comment by daxpedda** [comment]
I guess bevy would need https://github.com/bevyengine/bevy/issues/6689 to support this properly.

FYI `fragile-send-sync-non-atomic-wasm` doesn't work with `target-feature = "+atomics"`, which requires nightly anyway.
