### PR TITLE
[naga wgsl-in] Allow explicit cast from AbstractFloat to integer types

### LINKED ISSUE #7312: [wgsl] `i32` constructor needs to support abstract floats
https://threejs.org/examples/?q=webgpu#webgpu_lights_tiled uses this functionality. naga currently errors with:

```
Shader 'fragment' parsing error: abstract floating-point values cannot be automatically converted to integers
    ┌─ wgsl:142:192
    │
142 │         nodeVar13 = textureLoad( nodeUniform13, vec2<i32>( ( lightIndexes.value[ u32( ( ( ( nodeVar2.x + ( nodeVar2.y * 46.0 ) ) * 2.0 ) + f32( ( ( i ) / 4 ) ) ) ) ][ u32( ( ( i ) % 4 ) ) ] - 1 ), i32( 0.0 ) ), u32( 0u ) );
    │                                                                                                                                                                                                      ^^^^^^^^^^ see msg
```

Part of https://bugzilla.mozilla.org/show_bug.cgi?id=1916072#c5.

### PR DESCRIPTION
**Pull request by jamienicol**
And from either AbstractFloat or AbstractInt to bool.

**Connections**
Fixes #7312 

**Description**
AbstractFloat to integer was presumably not implemented as *automatic* conversion between those types is not allowed. However, explicit conversions (for example `i32(1.0)`) are allowed, and are implemented during const evaluation using the same code path in ConstantEvaluator::cast().

The integer conversion constructors treat AbstractFloats as any other floating point type, meaning we must follow the scalar floating point to integral conversion algorithm [1]. This specifies:

    To convert a floating point scalar value X to an integer scalar
    type T:
    * If X is a NaN, the result is an indeterminate value in T.
    * If X is exactly representable in the target type T, then the result is that value.
    * Otherwise, the result is the value in T closest to truncate(X) and also exactly representable in the original floating point type.

Fortunately a rust cast satisfies all these conditions apart from the result being exactly representable in the original floating point type. However, as i32::MIN, i32::MAX, u32::MIN, and u32::MAX are all representable by f64 (the underlying type of AbstractFloat), this is not an issue.

For i64 and u64 using a rust cast will not meet that requirement, but as these types are not present in the WGSL spec we are free to ignore that.

[1] https://www.w3.org/TR/WGSL/#floating-point-conversion

**Testing**
Added snapshot tests

**Squash or Rebase?**

Doesn't matter

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy --tests`. If applicable, add:
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/proc/constant_evaluator.rs [hunk 1]
```diff
@@ -2533,13 +2529,19 @@ trait TryFromAbstract<T>: Sized {
...
+    /// - WGSL §15.7.6 Floating Point Conversion says that conversions
     ///   to floating point in constant expressions and override
     ///   expressions are errors if the value is out of range for the
     ///   destination type, but rounding is okay.
     ///
+    /// - WGSL §17.1.2 i32()/u32() constructors treat AbstractFloat as any
+    ///   other floating point type, following the scalar floating point to
+    ///   integral conversion algorithm (§15.7.6). There is no automatic
+    ///   conversion from AbstractFloat to integer types.
+    ///
```
Comment (ErichDonGubler) [inline naga/src/proc/constant_evaluator.rs:2544]: praise: Standards refs. 🤤

**Review by ErichDonGubler — APPROVED** [review]
ez
