### PR TITLE
[wgpu-tests] Use concrete error messages for failures

### LINKED ISSUE #5727: Good first issue: use concrete error messages for `wgpu-test` tests
After merging https://github.com/gfx-rs/wgpu/pull/5290, there are many tests in `tests/tests/` that do not specify the text of the expected validation error. This is actually a hole in coverage; if the reason for validation changes, it could potentially be a regression of coverage. We wouldn't be able to detect this without actually checking the content of the validation error!

We should narrow expected validation error texts for these tests.

@ErichDonGubler is happy to act as a mentor for whoever wants to take this on. 🙂

### PR DESCRIPTION
**Pull request by dv29**
Partially resolves #5727 (note: edited by @ErichDonGubler).

**Connections**
https://github.com/gfx-rs/wgpu/issues/5727

**Description**
Its adding better descriptions to failure tests to avoid breaking because of regression

**Testing**
`cargo xtask test`

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [x] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] ~~Add change to `CHANGELOG.md`. See simple instructions inside file.~~ EDIT from @ErichDonGubler: Not necessary. 🙂

### CODE REVIEW

File: xtask/src/test.rs [hunk 1]
```diff
@@ -18,12 +18,10 @@ pub fn run_tests(shell: Shell, mut args: Arguments) -> anyhow::Result<()> {
...
         &["llvm-cov", "--no-cfg-coverage", "--no-report", "nextest"]
+    } else if list {
+        &["nextest", "list"]
     } else {
-        if list {
-            &["nextest", "list"]
-        } else {
-            &["nextest", "run"]
-        }
+        &["nextest", "run"]
```
Comment (ErichDonGubler) [inline xtask/src/test.rs:24]: nitpick(non-blocking): This change looks like something that should be a separate commit, or maybe even a PR. I'm guessing `clippy` complained at you about this?

Comment (dv29) [reply xtask/src/test.rs:24]: Yup it was `clippy`, I'll revert this

Comment (ErichDonGubler) [reply xtask/src/test.rs:24]: You can even keep the change! It's good to apply `clippy` suggestions that fire for this code. 🙂 Just want to make sure individual commits have specific changes. Otherwise, it can be a hazard for source management operations like `git revert` if something needs to reverted.

**Comment by ErichDonGubler** [comment]
@dv29: Just seeing <https://github.com/gfx-rs/wgpu/issues/5727#issuecomment-2243931638> now. Did you want to convert this to a draft and add some more changes (for a re-review) before merging this?

**Comment by dv29** [comment]
> @dv29: Just seeing [#5727 (comment)](https://github.com/gfx-rs/wgpu/issues/5727#issuecomment-2243931638) now. Did you want to convert this to a draft and add some more changes (for a re-review) before merging this?

Yes it is Draft PR. Are the changes what you expected, if so I'll go ahead and do the other ones

**Comment by ErichDonGubler** [comment]
@dv29:

> Yes it is Draft PR. Are the changes what you expected, if so I'll go ahead and do the other ones

Ah, sorry, I wasn't very explicit in confirming this, was I? Yes, this direction looks good, overall. 🙂 I'm not sure how I feel about the entire message being lowercased, but then again, we _are_ doing a case-insensitive match against the provided message.

Don't feel the need to copy the entire diagnostic text into an expected message argument; if you can reduce it to something that guarantees that the error has _some_ sensible content, then that also works. This is, however, subjective, so copying the entire diagnostic text is safe for merging, even if maybe more prone to needing updating over time.

**Comment by ErichDonGubler** [comment]
@dv29: Looks like some messages are failing CI now. At least some of them are because the backend mentioned doesn't not apply on the tested platform.

🤔 Maybe we need a way of expressing expected message _patterns_, rather than dumb case-insensitive matches? CC @cwfitzgerald.

**Comment by ErichDonGubler** [comment]
@dv29: If nothing else, we could punt on the problematic cases where an ID is interspersed in critical portions of the error message to another PR where we figure out the right solution. I suggest extracting the problematic changes into a commit outside this PR's branch for now.

**Comment by ErichDonGubler** [comment]
Sorry, @JCapucho, I incorrectly clicked on your name in the `Assignees` list. 😓

**Comment by dv29** [comment]
> @dv29: If nothing else, we could punt on the problematic cases where an ID is interspersed in critical portions of the error message to another PR where we figure out the right solution. I suggest extracting the problematic changes into a commit outside this PR's branch for now.

Gotcha, I'll try to see if I can resolve them for the platform (with what we have right now). If not I'll move them to another PR.

**Comment by JCapucho** [comment]
> Sorry, @JCapucho, I incorrectly clicked on your name in the `Assignees` list. 😓

No problem, it happens :)

**Comment by dv29** [comment]
@ErichDonGubler do you think we could do a regex error matches? i.e pass in regex expression string and it tries to match portion of it?

**Comment by ErichDonGubler** [comment]
Hey @dv29! Sorry for taking so long to get back with you. I've been extremely heads-down on a large backlog of some WebGPU CTS work in Firefox that's been consuming all of my work time. 😅

I think case-sensitive regexes are a good idea, and certainly easier to understand than the current behavior. Any objections, @cwfitzgerald?

**Comment by cwfitzgerald** [comment]
Yeah regex would be fine (maybe lets use regex-lite?) but I think that should be opt in with a different method, so that people don't need to worry about escaping when just string matching.

**Comment by dv29** [comment]
> Yeah regex would be fine (maybe lets use regex-lite?) but I think that should be opt in with a different method, so that people don't need to worry about escaping when just string matching.

so we should support both string and regex input? and maybe convert the string to regex internally at the function level?

**Comment by teoxoy** [comment]
The IDs in errors will go away soon (with the removal of the registries), so I don't think we should complicate things with regexes.

**Comment by dv29** [comment]
Should I then undo the test cases that are failing and create another PR with a different solution for it and close this one?

**Comment by teoxoy** [comment]
I'm not seeing any CI failures in this PR, can't we just merge it as is?

**Comment by ErichDonGubler** [comment]
@teoxoy: I hadn't been paying much attention to the content of the PR and check status. I hadn't noticed that the question of platform-specific error messages had actually been resolved! 😅

I think we should be good with the current contents of this PR, and iterate further as we discover more pain points.

**Comment by ErichDonGubler** [comment]
Squashed the fixup commit at the tip of the PR into the first commit, so we can rebase-and-merge.

**Review by ErichDonGubler — APPROVED** [review]
Fixed up one nit (`s/Option::None/None`).
