### PR TITLE
[naga wgsl-in] Allow trailing comma in switch cases

### LINKED ISSUE #8126: Switch case not compiling
# Switch case not compiling

## Simplest example

The command ran is `naga bug.wgsl`
Output:

```
Could not parse WGSL:
error: expected expression, found "{"
   ┌─ bug.wgsl:23:20
   │
23 │         case 1, c, {
   │                    ^ expected expression
```

`bug.wgsl` contains:
```wgsl
struct Uniforms {
    values: vec4i,
}

@group(0) @binding(0) var<uniform> ub: Uniforms;


@vertex
fn vertexMain(@location(0) pos: vec2f) -> @builtin(position) vec4f {
    return vec4f(pos, 0, 1, );
}

@fragment
fn fragmentMain() -> @location(0) vec4f {
    // This should compile but does not as the case statements are supposedly invalid according to firefox.
    // On Chrome it correctly outputs red.
    // This was derived from a example in the wgsl specification: https://www.w3.org/TR/WGSL/#switch-statement
    const c = 2;
    switch ub.values.x {
        case 0: {
            return vec4(0, 0, 1, 1);
        }
        case 1, c, {
            return vec4(1, 0, 0, 1);
        }
        case 3, default {
            return vec4(0.5, 0.5, 0.5, 1);
        }
    }
    return vec4(0.5, 0, 0.5, 1);
}
```

Naga version: 26.0.0

## Expected output vs unexpected output

[bug.html](https://github.com/user-attachments/files/21918828/bug.html)

`expected.png`:
Image

`bug.html` contains some boilerplate and the `bug.wgsl` shader. `bug.html` should render `expected.png` and does on Chrome but on Firefox it does not.

Firefox produces this error:

```
Encountered one or more errors while creating shader module "Shader"
WebGPU compilation info for shader module "Shader" (1 error(s), 0 warning(s), 0 info)

Shader 'Shader' parsing error: expected expression, found "{"
   ┌─ wgsl:24:20
   │
24 │         case 1, c, {
   │                    ^ expected expression
```

## Platforms

This behaviour is observed on various platforms including a Laptop with an Intel GPU and a Laptop with an AMD GPU

This bug was found as part of the wgsl-fuzz project: https://github.com/mc-imperial/wgsl-fuzz

### PR DESCRIPTION
**Pull request by reima**
**Connections**
Fixes #8126.

**Description**
This change allows a trailing comma in the list of `case` values inside a `switch`.

It accomplishes this by checking if a comma is followed by a `:` (indicating the list of values ends here), or an attribute or `{` token (indicating that a compound statement follows).

**Testing**
I've extended `naga\tests\in\wgsl\control-flow.wgsl` to contain a `switch` with trailing commas.

**Squash or Rebase?**

Squash

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/front/wgsl/parse/mod.rs [hunk 1]
```diff
@@ -2287,11 +2287,17 @@ impl Parser {
...
                                             let value = this.switch_value(lexer, ctx)?;
                                             if lexer.skip(Token::Separator(',')) {
-                                                if lexer.skip(Token::Separator(':')) {
+                                                // list of values ends with ':' or a compound statement
+                                                // indicated by an attribute or '{'
+                                                if matches!(
+                                                    lexer.peek().0,
+                                                    Token::Separator(':')
+                                                        | Token::Attribute
+                                                        | Token::Paren('{')
```
Comment (andyleiserson) [inline naga/src/front/wgsl/parse/mod.rs]: I'd suggest making a helper `Token::is_start_of_compound_statement` for `matches!(token, Token::Attribute | Token::Paren('{'))`. It could be used here and on line 2124 where `fn statement` parses compound statements. This better encapsulates the sensitivity to a rule from elsewhere in the grammar and reduces the risk of bugs if the grammar changes in the future.

**Review by andyleiserson — APPROVED** [review]
One suggestion, but it's not critical and otherwise this looks good. Thanks for the PR!

File: naga/src/front/wgsl/parse/mod.rs (hunk 1 above)
Comment (reima) [reply naga/src/front/wgsl/parse/mod.rs]: That's a good idea! Adding the helper to `Token` didn't feel right to me, so I've added a free function instead.

**Comment by andyleiserson** [comment]
Sorry this waited so long, I lost track of it.

**Comment by reima** [comment]
No worries at all! Thanks for merging the PR.
