### PR TITLE
[wgpu-core] split command encoders from command buffers

### LINKED ISSUE #7812: [deno] Calling `CommandEncoder.finish` multiple times should raise a validation error
Many `wgpu-core` functions return both an object ID and an error when they fail. For typical functions that construct a new object, the returned ID when there is an error refers to a new, invalid object, which is fine. But in the case of `CommandEncoder.finish`, there is a problem, because `wgpu-core` does not have distinct object types for command encoders and command buffers. The returned ID (for a command buffer) is just the ID of the encoder being finished. This means that calling `CommandEncoder.finish` multiple times creates multiple command buffer objects with the same ID, which can cause problems if those objects are not dropped correctly.

According to the spec, calling `finish()` multiple times for the same encoder should result in a validation error. With the `wgpu` API, `finish()` consumes the encoder so it is not possible to call multiple times. In deno, as of #7808, calling `finish()` multiple times raises a `TypeError` immediately in order to avoid returning a duplicate command buffer. For Firefox, see the first comment.

### PR DESCRIPTION
**Pull request by teoxoy**
Fixes https://github.com/gfx-rs/wgpu/issues/7812 and partially [Bug 1972949](https://bugzilla.mozilla.org/show_bug.cgi?id=1972949).

### CODE REVIEW

File: player/src/lib.rs [hunk 1]
```diff
@@ -15,14 +15,22 @@ pub trait GlobalPlay {
         &self,
         encoder: wgc::id::CommandEncoderId,
         commands: Vec<trace::Command>,
+        command_buffer_id_manager: &mut wgc::identity::IdentityManager<
+            wgc::id::markers::CommandBuffer,
+        >,
```
Comment (andyleiserson) [inline player/src/lib.rs]: nit: since the type names are kind of unwieldy and are repeated a few times, maybe it's worth importing the components or defining type aliases for the two identity manager types?

File: wgpu-core/src/command/mod.rs [hunk 2]
```diff
@@ -145,6 +145,9 @@ impl CommandEncoderStatus {
             // Encoder is ended. Invalidate the encoder, do not record anything,
             // and return an immediate validation error.
             Self::Finished(_) => Err(self.invalidate(EncoderStateError::Ended)),
+            Self::Error(CommandEncoderError::State(EncoderStateError::Ended)) => {
+                Err(EncoderStateError::Ended)
+            }
```
Comment (andyleiserson) [inline wgpu-core/src/command/mod.rs]: Does it make sense to add a new `CommandEncoderStatus::Consumed` for the status of an encoder that has been finished? (vs. `Finished`, which after this change is the `CommandEncoderStatus` of a valid command buffer). Distinguishing it as a separate state makes it easier to distinguish "there's a bug in wgpu, I didn't expect to find this state here" from an application doing something illegal that results in objects being invalid.

File: wgpu-core/src/command/mod.rs [hunk 3]
```diff
@@ -254,6 +262,10 @@ impl CommandEncoderStatus {
                 *self = Self::Error(EncoderStateError::Unlocked.into());
                 Err(EncoderStateError::Unlocked)
             }
+            st @ Self::Error(CommandEncoderError::State(EncoderStateError::Ended)) => {
+                *self = st;
+                Err(EncoderStateError::Ended)
+            }
```
Comment (andyleiserson) [inline wgpu-core/src/command/mod.rs:269]: This is actually a comment about `CommandEncoderStatus::finish`, below. We could change the API to reflect that the operation is no longer a mutation of the common state of encoders/buffers, but is more like an update to the state of a command encoder that also returns some information that will be given to the new command buffer. (Eventually, we could even split the buffer states out of `CommandEncoderStatus` into `CommandBufferStatus`, but that's a bigger refactoring that is probably better not to combine with this PR.) 

Maybe something like:

```rust
    fn finish(&mut self) -> Self {
        // Replace our state with `Consumed`, and return either the inner
        // state or an error, to be transferred to the command buffer.
        match mem::replace(self, Self::Consumed) {
            Self::Recording(mut inner) => {
                if let Err(err) = inner.encoder.close_if_open() {
                    Self::Error(err.into())
                } else {
                    // Note: if we want to stop tracking the swapchain texture view,
                    // this is the place to do it.
                    Self::Finished(inner)
                }
            }
            Self::Consumed | Self::Finished(_) => Self::Error(EncoderStateError::Ended.into()),
            Self::Locked(_) => Self::Error(EncoderStateError::Locked.into()),
            st @ Self::Error(_) => st,
            Self::Transitioning => unreachable!(),
        }
    }
```

**Review by andyleiserson — APPROVED** [review]
Nice, thank you for taking care of this.

I left some minor comments but nothing that I see as blocking. I pushed a branch with all of my `CommandEncoderStatus::Consumed` changes [here](https://github.com/gfx-rs/wgpu/commit/41af9a21dc90fce4cf106e4eae0cd8f68c0c7fdd).

**Comment by teoxoy** [comment]
Adding a consumed variant sounds good! I will add your commit to the PR.

File: wgpu-core/src/command/mod.rs [hunk 4]
```diff
@@ -214,10 +215,7 @@ impl CommandEncoderStatus {
                 Err(EncoderStateError::Ended)
             }
             Self::Locked(_) => Err(self.invalidate(EncoderStateError::Locked)),
-            st @ Self::Error(CommandEncoderError::State(EncoderStateError::Ended)) => {
-                *self = st;
-                Err(EncoderStateError::Ended)
-            }
```
Comment (teoxoy) [inline wgpu-core/src/command/mod.rs]: Here and below in `unlock_and_record` we still need to set the state back or else it will remain as `Transitioning`. I will fixup the commit.

File: wgpu-core/src/command/mod.rs [hunk 5]
```diff
@@ -214,10 +215,7 @@ impl CommandEncoderStatus {
...
+            Self::Consumed => Err(EncoderStateError::Ended),
```
Comment (teoxoy) [inline wgpu-core/src/command/mod.rs]: Here and below in `unlock_and_record` we still need to set the state back or else it will remain as `Transitioning`. I will fixup the commit.

File: player/src/lib.rs (hunk 1 above)
Comment (teoxoy) [reply player/src/lib.rs]: Importing `IdentityManager` was enough to get those onto one line.

**Comment by andyleiserson** [comment]
Just in time to fix the new CTS test in https://github.com/gpuweb/cts/pull/4401!
