### PR TITLE
Simplify `WeakVec`

### LINKED ISSUE #6580: `WeakVec` should consider using `Vec::swap_remove` instead of a freelist
`wgpu_core::weak_vec::WeakVec` maintains a freelist, but it's not important that elements stay at their original indices, so it should be possible to use `std::vec::Vec::swap_remove` to remove broken weak references, thus keeping all live references contiguous at the start of the vector, making the freelist unnecessary.

### PR DESCRIPTION
**Pull request by teoxoy**
Resolves https://github.com/gfx-rs/wgpu/issues/6580.

Follow-up to https://github.com/gfx-rs/wgpu/pull/6419.
Related: https://github.com/bevyengine/bevy/issues/15893.
@DGriffin91 / @tychedelia could you give this PR a try?

### CODE REVIEW

File: wgpu-core/src/weak_vec.rs [hunk 1]
```diff
@@ -6,57 +6,44 @@ use std::sync::Weak;
...
-                        self.empty_slots.push(i);
-                    }
+        if self.inner.len() == self.inner.capacity() {
+            let mut i = 0;
+            while let Some(w) = self.inner.get(i) {
+                if w.strong_count() == 0 {
+                    self.inner.swap_remove(i);
+                } else {
+                    i += 1;
                 }
```
Comment (ErichDonGubler) [inline wgpu-core/src/weak_vec.rs]: suggestion(non-blocking): (CC @jimblandy):

```suggestion
            self.inner.retain(|w| w.strong_count() > 0);
```

It's not clear-cut that `swap_remove` is going to be faster, and this is a lot simpler code to read. See also discussion from <https://github.com/rust-lang/rust/issues/69043>.

I guess I'd suggest profiling, making sure folks are happy (or at least happier), and then trying `retain` as an iteration on top.

**Review by ErichDonGubler — APPROVED** [review]

File: wgpu-core/src/weak_vec.rs (hunk 1 above)
Comment (teoxoy) [reply wgpu-core/src/weak_vec.rs]: With `retain` I'm concerned about the nr of moves, if one of the elements close to the front gets dropped, all of the elements after it have to be moved. `retain` will take better advantage of caches though.

Ideally optimized apps don't create and destroy resources often but depending on how they create and destroy resources one solution might be faster than the other.

A perf cliff of `swap_remove` would be if all resources have been dropped...

Profiling multiple scenarios would be best.

Comment (ErichDonGubler) [reply wgpu-core/src/weak_vec.rs]: We don't have to block merging on profiling here, OFC, just wanted to note that profiling and _then_ applying the change seems even like a `good-first-issue` task.

**Comment by tychedelia** [comment]
Just tested in Bevy with our previously degenerate case and things look a lot better! Don't have concrete numbers but the remaining small but observable hang we saw post-fix in 0.23 is basically eliminated.

File: wgpu-core/src/weak_vec.rs [hunk 2]
```diff
@@ -6,57 +6,44 @@ use std::sync::Weak;
...
     /// no longer have strong references to them.
     pub(crate) fn push(&mut self, value: Weak<T>) {
-        if self.scan_slots_on_next_push {
-            for (i, value) in self.inner.iter_mut().enumerate() {
-                if let Some(w) = value {
-                    if w.strong_count() == 0 {
-                        *value = None;
-                        self.empty_slots.push(i);
-                    }
+        if self.inner.len() == self.inner.capacity() {
```
Comment (jimblandy) [inline wgpu-core/src/weak_vec.rs:30]: How will this behave if we have a large set that is at capacity, with one weak pointer broken each time a new one is pushed? It seems to me this would result in a full scan on every push.

**Comment by jimblandy** [comment]
GitHub won't let me make suggestions on deleted lines, but:

I think `push` should look like this:

```rust
    pub(crate) fn push(&mut self, value: Weak<T>) {
        let original_capacity = self.inner.capacity(); 

        self.inner.push(value);

        if self.inner.capacity() > original_capacity {
            for i in (0..self.inner.len()).rev() {
                if self.inner[i].strong_count() == 0 {
                    self.inner.swap_remove(i);
                }
            }

            // Make sure our spare capacity is not (much) more than
            // twice the number of live elements. Leaving some spare
            // capacity ensures that we won't re-scan immediately.
            self.inner.shrink_to(self.inner.len() * 2);
        }
    }
```

By iterating backwards, you avoid needing to do any index adjustment.

This ensures that successive scans are always separated by at least as many pushes as there are elements in the set after the earlier scan.

File: wgpu-core/src/weak_vec.rs (hunk 1 above)
Comment (jimblandy) [reply wgpu-core/src/weak_vec.rs]: I think it's good to bound the number of moves on the number of broken weak references, since we know work will be proportional to at least that in any implementation.

**Review by jimblandy — CHANGES_REQUESTED** [review]
I'm not certain my suggestions are good, but please take a look. If not, I'll approve this.

**Comment by jimblandy** [comment]
The most expensive operation within a single scan will be dropping the `Weak`, because that's what actually frees the `Arc`'s heap block, so it hits the heap allocator. I would expect the moves of the pointers within `WeakVec` are almost certainly negligible in comparison to that. So probably the difference between a `retain` and a `swap_remove` implementation is relatively unimportant.

File: wgpu-core/src/weak_vec.rs (hunk 2 above)
Comment (teoxoy) [reply wgpu-core/src/weak_vec.rs:30]: That's a good point.

**Comment by teoxoy** [comment]
That's a nice solution!

> I think it's good to bound the number of moves on the number of broken weak references, since we know work will be proportional to at least that in any implementation.

And it satisfies this nicely.

> By iterating backwards, you avoid needing to do any index adjustment.

It also avoids moving items from the back that haven't been checked yet (possibly having to be dropped). So it gets rid of this cliff as well:

> A perf cliff of `swap_remove` would be if all resources have been dropped...

**Comment by teoxoy** [comment]
One thing I changed from your proposal is instead of reallocating the whole Vec twice, we only reallocate it once.

**Review by jimblandy — APPROVED** [review]
Looks good to me!
