### PR TITLE
[vk] Don't request portability enumeration without the extension.

### LINKED ISSUE #4004: `VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR` Present When Portability Extension Is Not
Test the suppress-obs-vuid using the latest wgpu (wgpu-hal with Suppress validation error caused by OBS layer (#4002)):

`wgpu = { git = "https://github.com/gfx-rs/wgpu.git" }`

on Windows 11, Nvidia RTX 3060 with Vulkan backend. Still got a validation error:

`VUID-VkInstanceCreateInfo-flags-zerobitmask(ERROR / SPEC): msgNum: 1636402386 - Validation Error: [ VUID-VkInstanceCreateInfo-flags-zerobitmask ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x618984d2 | vkCreateInstance: parameter pCreateInfo->flags must be 0. The Vulkan spec states: flags must be 0 (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkInstanceCreateInfo-flags-zerobitmask)`

However, this error only occurs once, but not on every frame, which is different from the previous error that is logged every frame.

The app runs fine, but this error is still very annoying.

_Originally posted by @jack1232 in https://github.com/gfx-rs/wgpu/issues/4002#issuecomment-1664582002_

### PR DESCRIPTION
**Pull request by jimblandy**
VUID-VkInstanceCreateInfo-flags-06559 forbids us from passing `vk::InstanceCreateFlags::ENUMERATE_PORTABILITY_KHR` unless we actually found and requested the "VK_KHR_portability_enumeration" layer.

Fixes #4004.

**Checklist**

- [X] Run `cargo clippy`.
- [X] Run `cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Testing**
This is covered by `wgpu-test::wgpu-tests encoder::drop_encoder`.

### CODE REVIEW

File: wgpu-hal/src/vulkan/instance.rs [hunk 1]
```diff
@@ -609,6 +609,11 @@ impl crate::Instance<super::Api> for super::Instance {
         let obs_layer = CStr::from_bytes_with_nul(b"VK_LAYER_OBS_HOOK\0").unwrap();
         let has_obs_layer = find_layer(&instance_layers, obs_layer).is_some();
 
+        let portability_enumeration_layer =
+            CStr::from_bytes_with_nul(b"VK_KHR_portability_enumeration\0").unwrap();
+        let has_portability_enumeration_layer =
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/instance.rs]: We are looking for layer that is also an extension? Could you add some doc comments explaining why we're doing this/vk is set up like this

Comment (jimblandy) [reply wgpu-hal/src/vulkan/instance.rs]: D'oh - thanks for paying attention.

**Review by cwfitzgerald — APPROVED** [review]
Nice
