### PR TITLE
Fix metal feature detection

### LINKED ISSUE #8594: Metal feature detection is very broken
**Description**

See #8439

Related and for texture formats: #8654 

Many (most?) of the feature detection logic in the metal backend is completely incorrect. You usually need to check for a specific metal version, a feature family, or specific versions of different OSes. This is often not checked correctly. For example, I have seen checks that ignore the API version completely. Many checks also assume tvOS versions and iOS versions have the same feature support which isn't true.

Some examples: vertex amplficiation checks calls a function not available everywhere, barycentrics is the same.

**Repro steps**
Look at the feature detection code

**Expected vs observed behavior**
It should be correct

**Extra materials**
None

**Platform**
Metal

### LINKED ISSUE #8629: `primitive_id` being enabled on unsupported device
Discovered in https://github.com/gfx-rs/wgpu/issues/8610#issuecomment-3605006862

Failure in test `wgpu_gpu::shader_primitive_index`

Platform: iOS 15.8.2, Apple A9

```
2025-12-02 22:37:37.212 wgpu_gpu-6745f484ba67fbea[17894:138612] Metal API Validation Enabled
2025-12-02 22:37:37.212 wgpu_gpu-6745f484ba67fbea[17894:138612] Metal GPU Validation Enabled
[2025-12-03T03:37:37Z ERROR wgpu::backend::wgpu_core] Shader translation error for stage ShaderStages(VERTEX | FRAGMENT): new_render_pipeline_state: "primitive_id not supported for this device"
[2025-12-03T03:37:37Z ERROR wgpu::backend::wgpu_core] Please report it to https://github.com/gfx-rs/wgpu
[2025-12-03T03:37:37Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default     
```

### LINKED ISSUE #8632: Apple7 some tests fail due to Depth16unorm being unsupported
Discovered in https://github.com/gfx-rs/wgpu/issues/8610#issuecomment-3607956748

```
       ABORT [   1.401s] wgpu-test::wgpu-gpu [Executed] [Metal/Apple A7 GPU/0] wgpu_gpu::zero_init_texture_after_discard::discarding_depth_target_resets_texture_init_state_check_visible_on_copy_in_same_encoder
           - with code 0xffffffff: OS Error -268435457 (FormatMessageW() returned error 317) (os error -1)
  stdout ───

    running 1 test
  stderr ───
    validateMTLPixelFormat:174: failed assertion `pixelFormat (250) is not a valid MTLPixelFormat.'

    (test aborted)
```

This seems to be https://developer.apple.com/documentation/metal/mtlpixelformat/depth16unorm

### PR DESCRIPTION
**Pull request by inner-daemons**
**Connections**
Closes #8594
Closes #8629 
Closes #8632 

**Description**

Many (most?) of the feature detection logic in the metal backend is completely incorrect. You usually need to check for a specific metal version, a feature family, or specific versions of different OSes. This is often not checked correctly. For example, I have seen checks that ignore the API version completely. Many checks also assume tvOS versions and iOS versions have the same feature support which isn't true.

This addresses that by adjusting a TON of feature checks. This is not exhaustive.

@opstic confirms that this fixed all issues on their A7 (that's the one in the *iPhone 5*). So I'm thinking this is good enough for now 

**Testing**
None

**Squash or Rebase?**

Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by inner-daemons** [comment]
Due to my hatred of metal docs and the fact that they don't make any sense, and because it seems that feature set related docs have been removed, I'm not gonna look over most of the feature detection code, and just trust that it works well enough.

I will definitely take another few looks over all of this. Its kind of a nightmare to navigate, but I'll try to improve that a little and make sure that reviewers have to put in slightly less effort to follow what's going on.

File: wgpu-hal/src/metal/adapter.rs [hunk 1]
```diff
@@ -867,48 +919,64 @@ impl super::PrivateCapabilities {
...
+            shader_barycentrics: metal4
+                || (version.at_least((10, 15), (14, 0), (16, 0), (1, 0), os_type)
+                    && device.supports_shader_barycentric_coordinates()),
             // https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf#page=3
-            supports_memoryless_storage: if family_check {
-                device.supports_family(MTLGPUFamily::Apple2)
-            } else {
-                version.at_least((11, 0), (10, 0), os_is_mac)
-            },
+            supports_memoryless_storage: metal4 || device.supports_family(MTLGPUFamily::Apple2),
```
Comment (opstic) [inline wgpu-hal/src/metal/adapter.rs]: Are you sure about this logic? If a device under iOS 13 runs this, `metal4` would be false since `family_check` fails, and then `device.supports_family()` would be called. Since this API only became available after iOS 13, it would crash the app. (Past example: #5744) Ditto for the other usages of `metal3` and `metal4`.

Also can you please put the OS version check back since the A7 also supports memoryless storage and its last iOS version is [12.5.7](https://en.wikipedia.org/wiki/Apple_A7), so family checks wouldn't cover it.

Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs]: Happy to, this is a rough sketch, I went over tons of stuff, I'm gonna look at it more deeply in the future

Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs]: I messaged you about this on matrix since I still have concerns.

File: wgpu-hal/src/metal/adapter.rs [hunk 2]
```diff
@@ -262,12 +262,17 @@ impl crate::Adapter for super::Adapter {
                 all_caps | Tfc::DEPTH_STENCIL_ATTACHMENT | msaa_count | msaa_resolve_apple3x_if
             }
             Tf::Depth16Unorm => {
-                let mut flags =
-                    Tfc::DEPTH_STENCIL_ATTACHMENT | msaa_count | msaa_resolve_apple3x_if;
                 if pc.format_depth16unorm {
-                    flags |= Tfc::SAMPLED_LINEAR
+                    // TODO: what does SAMPLED_LINEAR mean?!?
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: Answer: able to sampled with a linear sampler.

File: wgpu-hal/src/metal/adapter.rs [hunk 3]
```diff
@@ -537,15 +542,17 @@ impl super::PrivateCapabilities {
...
-                    self.major > ios_version.0
-                        || (self.major == ios_version.0 && self.minor >= ios_version.1)
-                }
+                let required = match os_type {
+                    super::OsType::Macos => mac_version,
+                    super::OsType::Ios => ios_version,
+                    super::OsType::Tvos => tvos_version,
+                    super::OsType::VisionOs => visionos_version,
+                };
+                self.major > required.0 || (self.major == required.0 && self.minor >= required.1)
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: nit, this is `(self.major, self.minor) >= required`

File: wgpu-hal/src/metal/adapter.rs [hunk 4]
```diff
@@ -555,13 +562,27 @@ impl super::PrivateCapabilities {
...
-        // Therefore, the following conditions can be used to determine if it is visionOS.
-        // https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator
-        let os_is_xr = version.major < 8 && device.supports_family(MTLGPUFamily::Apple2);
-        let family_check = os_is_xr || version.at_least((10, 15), (13, 0), os_is_mac);
+        let os_type = {
+            // Metal was first introduced in OS X 10.11 and iOS 8. The current version number of visionOS is 1.0.0. Additionally,
+            // on the Simulator, Apple only provides the Apple2 GPU capability, and the Apple2+ GPU capability covers the capabilities of Apple2.
+            // Therefore, the following conditions can be used to determine if it is visionOS.
+            // https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator
+            let os_is_xr = version.major < 8 && device.supports_family(MTLGPUFamily::Apple2);
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: nit: while we're improving this, lets call this this `os_is_vision`.

File: wgpu-hal/src/metal/adapter.rs [hunk 5]
```diff
@@ -555,13 +562,27 @@ impl super::PrivateCapabilities {
...
+            if os_is_xr {
+                super::OsType::VisionOs
+            } else if os_is_mac {
+                super::OsType::Macos
+            } else if os_is_tvos {
+                super::OsType::Tvos
+            } else {
+                super::OsType::Ios
+            }
+        };
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: I think we should pull this all into a OsType::new or such. Seems to be well encapsulateable.

File: wgpu-hal/src/metal/adapter.rs [hunk 6]
```diff
@@ -605,46 +632,47 @@ impl super::PrivateCapabilities {
             // `TimestampQuerySupport::INSIDE_WGPU_PASSES` emerges from the other flags.
         }
 
-        let argument_buffers = device.argument_buffers_support();
+        // TODO: is this check something we can comfortably run?
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: What does this mean?

File: wgpu-hal/src/metal/adapter.rs [hunk 7]
```diff
@@ -605,46 +632,47 @@ impl super::PrivateCapabilities {
...
-                device.supports_feature_set(MTLFeatureSet::iOS_GPUFamily3_v4)
-            },
+            msaa_desktop: os_type == super::OsType::Macos,
+            msaa_apple3: (family_check && device.supports_family(MTLGPUFamily::Apple3))
+                || device.supports_feature_set(MTLFeatureSet::iOS_GPUFamily3_v4),
             msaa_apple7: family_check && device.supports_family(MTLGPUFamily::Apple7),
             resource_heaps: Self::supports_any(device, RESOURCE_HEAP_SUPPORT),
             argument_buffers,
-            shared_textures: !os_is_mac,
+            shared_textures: os_type != super::OsType::Macos,
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: Is this actually true, this seems weird.

File: wgpu-hal/src/metal/adapter.rs [hunk 8]
```diff
@@ -656,22 +684,26 @@ impl super::PrivateCapabilities {
...
+            format_min_srgb_channels: if os_type == super::OsType::Macos {
+                4
+            } else {
+                1
+            },
+            format_b5: os_type != super::OsType::Macos,
+            format_bc: os_type == super::OsType::Macos,
+            format_eac_etc: os_type != super::OsType::Macos
                 // M1 in macOS supports EAC/ETC2
                 || (family_check && device.supports_family(MTLGPUFamily::Apple7)),
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs:659]: This should be apple2. All apple devices support this. Similar to astc.

File: wgpu-hal/src/metal/adapter.rs [hunk 9]
```diff
@@ -744,13 +777,15 @@ impl super::PrivateCapabilities {
                 31
             },
             max_samplers_per_stage: 16,
-            max_binding_array_elements: if argument_buffers == MTLArgumentBuffersTier::Tier2 {
+            // TODO: check
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: Hum?

File: wgpu-hal/src/metal/adapter.rs [hunk 10]
```diff
@@ -759,18 +794,22 @@ impl super::PrivateCapabilities {
...
             },
-            buffer_alignment: if os_is_mac || os_is_xr { 256 } else { 64 },
-            max_buffer_size: if version.at_least((10, 14), (12, 0), os_is_mac) {
+            buffer_alignment: if matches!(os_type, super::OsType::Macos | super::OsType::VisionOs) {
+                256
+            } else {
+                64
+            },
+            max_buffer_size: if version.at_least((10, 14), (12, 0), (12, 0), (1, 0), os_type) {
                 // maxBufferLength available on macOS 10.14+ and iOS 12.0+
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: This comment is now redundant with the above check.

File: wgpu-hal/src/metal/adapter.rs [hunk 11]
```diff
@@ -854,79 +903,141 @@ impl super::PrivateCapabilities {
...
+                os_type,
+            ),
+            // This is just trusted blindly since docs referencing supports_any have been removed
+            // but we don't want to remove feature support.
             supports_arrays_of_textures: Self::supports_any(
                 device,
                 &[
                     MTLFeatureSet::iOS_GPUFamily3_v2,
+                    MTLFeatureSet::iOS_GPUFamily4_v1,
+                    MTLFeatureSet::iOS_GPUFamily5_v1,
```
Comment (cwfitzgerald) [inline wgpu-hal/src/metal/adapter.rs]: This is weird - doesn't all families imply the lower ones.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Thanks for tackling this!

File: wgpu-hal/src/metal/adapter.rs (hunk 7 above)
Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs]: I have no idea lol. I only looked at the bottom third of the capabilities in detail

File: wgpu-hal/src/metal/adapter.rs (hunk 6 above)
Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs]: Probably a relic from before I put it behind a version check. We previously assumed that argument buffers were always supported, which might be true on what we're targeting, but I put it behind a check here.

File: wgpu-hal/src/metal/adapter.rs (hunk 9 above)
Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs]: Idk, I put those as markers for what I didn't immediately understand and would come back to. At this point I'm inclined to assume the original author (you!!) were correct.

File: wgpu-hal/src/metal/adapter.rs (hunk 11 above)
Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs]: I have no recollection of writing this nor any idea how this came to be lol. I tried to avoid looking at MTLFeatureSet stuff because all the documentation for it has been scrubbed.

File: wgpu-hal/src/metal/adapter.rs (hunk 7 above)
Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs]: So it looks like this field isn't used anywhere. So I will just remove it as it doesn't make any sense lol.

File: wgpu-hal/src/metal/adapter.rs (hunk 8 above)
Comment (inner-daemons) [reply wgpu-hal/src/metal/adapter.rs:659]: THis isn't my doing. I hardly touched any texture formats in this PR, because that's outside its scope and outside my expertise. Also I don't love doing stuff like this so I'm not gonna pour tons of hours into making sure all our metal code is perfect lol.

Maybe this can be a followup PR, or you can suggest changes.

Comment (cwfitzgerald) [reply wgpu-hal/src/metal/adapter.rs:659]: Not wanting things to be perfect, but saw a thing while I was scrolling by and thought we could fix it while we're over here anyway.

**Review by cwfitzgerald — APPROVED** [review]
Nice!
