### PR TITLE
[naga wgsl-in] Reject vector constructors with incorrect number of components during const evaluation.

### LINKED ISSUE #6506: naga: index out of bound in constant_evaluator.rs:217
Translating the following wgsl with `naga a.wgsl a.hlsl` results in a panic on naga 23.0.0

```wgsl
fn a() {
    const b = vec4(f32(), f32());
    saturate(b);
}
```

```
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/naga-23.0.0/src/proc/constant_evaluator.rs:217:1:
index out of bounds: the len is 2 but the index is 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````

### PR DESCRIPTION
**Pull request by jamienicol**
**Connections**
Fixes #6506 

**Description**
A vector constructor with multiple arguments is represented in IR as a Compose expression. These can be nested, for example due to code such as this: `vec4(1, vec3(2, vec2(3, 4)))`. The total number of components of each argument must match the vector size, meaning `vec4(1, 2, 3, 4, 5)` is invalid. The validation pass already catches such occurences. However, validation runs after constant evaluation, meaning this can cause issues if the expression is evaluated as part of a const expression.

When applying an operation to a vector compose during const evaluation, we typically "flatten" the vector using the function `proc::flatten_compose()`. This silently truncates the list of components to the size implied by the type, meaning invalid code is accepted.

This patch validates that the total number of components in a Compose expression, once flattened, matches the size implied by the type. We do so once as each expression is registered to avoid needing to handle this each time the expression is used in a const expression.

For nested compose expressions, the inner expressions will be registed before the outer ones. This means we can trust that the size implied by the inner expression's type is correct, as it will have already been validated, and can therefore avoid recursing through each nested expression when registering the outer expression.

**Testing**
Added new tests

**Squash or Rebase?**

Either

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy --tests`. If applicable, add:
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/proc/constant_evaluator.rs [hunk 1]
```diff
@@ -2198,6 +2227,22 @@ impl<'a> ConstantEvaluator<'a> {
             crate::valid::check_literal_value(literal)?;
         }
 
+        // Ensure vector composes contain the correct number of components. We
```
Comment (andyleiserson) [inline naga/src/proc/constant_evaluator.rs:2284]: Maybe update the comment just above saying "It suffices to only check literals".

File: naga/src/proc/constant_evaluator.rs [hunk 2]
```diff
@@ -2186,6 +2190,31 @@ impl<'a> ConstantEvaluator<'a> {
...
+    ) -> Result<usize, ConstantEvaluatorError> {
+        components
+            .iter()
+            .try_fold(0, |acc, c| -> Result<_, ConstantEvaluatorError> {
+                let ty = self.resolve_type(*c)?;
+                let ty = match ty {
+                    super::TypeResolution::Handle(handle) => &self.types[handle].inner,
+                    super::TypeResolution::Value(ref inner) => inner,
+                };
+                let size = match *ty {
```
Comment (andyleiserson) [inline naga/src/proc/constant_evaluator.rs]:
```suggestion
                let size = match *ty.inner_with(&self.types) {
```

**Review by andyleiserson — APPROVED** [review]

File: naga/src/proc/constant_evaluator.rs (hunk 1 above)
Comment (jamienicol) [reply naga/src/proc/constant_evaluator.rs:2284]: yeah this is a bit confusing. The comment is still applicable, it's just referring specifically to the `check_literal_value()` check above, rather than all checks in this function (of which there are now multiple). I'll make it clear.

File: naga/src/proc/constant_evaluator.rs (hunk 2 above)
Comment (jamienicol) [reply naga/src/proc/constant_evaluator.rs]: I knew there was shortcut for this but my editor's autocomplete was letting me down :slightly_smiling_face:
