### PR TITLE
Fix Subgroup Ops on VK 1.2 Device

### LINKED ISSUE #5551: MoltenVK Subgroup Size Error
**Description**

When running basically any vulkan test on MoltenVK, I get:

```
[2024-04-17T21:26:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineShaderStageCreateInfo-flags-02784 (0xd65f4ec3)]
        Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-flags-02784 ] | MessageID = 0xd65f4ec3 | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[0].flags includes VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT, but the subgroupSizeControl feature was not enabled. The Vulkan spec states: If flags has the VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT flag set, the subgroupSizeControl feature must be enabled (https://vulkan.lunarg.com/doc/view/1.3.268.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-flags-02784)
[2024-04-17T21:26:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineShaderStageCreateInfo-flags-02784 (0xd65f4ec3)]
        Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-flags-02784 ] | MessageID = 0xd65f4ec3 | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1].flags includes VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT, but the subgroupSizeControl feature was not enabled. The Vulkan spec states: If flags has the VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT flag set, the subgroupSizeControl feature must be enabled (https://vulkan.lunarg.com/doc/view/1.3.268.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-flags-02784)
[2024-04-17T21:26:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineShaderStageCreateInfo-flags-02784 (0xd65f4ec3)]
        Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-flags-02784 ] | MessageID = 0xd65f4ec3 | vkCreateComputePipelines(): pCreateInfos[0].stage.flags includes VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT, but the subgroupSizeControl feature was not enabled. The Vulkan spec states: If flags has the VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT flag set, the subgroupSizeControl feature must be enabled (https://vulkan.lunarg.com/doc/view/1.3.268.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-flags-02784)
[2024-04-17T21:26:03Z ERROR wgpu_test::expectations] Validation Error: Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-flags-02784 ] | MessageID = 0xd65f4ec3 | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[0].flags includes VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT, but the subgroupSizeControl feature was not enabled. The Vulkan spec states: If flags has the VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT flag set, the subgroupSizeControl feature must be enabled (https://vulkan.lunarg.com/doc/view/1.3.268.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-flags-02784)
[2024-04-17T21:26:03Z ERROR wgpu_test::expectations] Validation Error: Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-flags-02784 ] | MessageID = 0xd65f4ec3 | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1].flags includes VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT, but the subgroupSizeControl feature was not enabled. The Vulkan spec states: If flags has the VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT flag set, the subgroupSizeControl feature must be enabled (https://vulkan.lunarg.com/doc/view/1.3.268.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-flags-02784)
[2024-04-17T21:26:03Z ERROR wgpu_test::expectations] Validation Error: Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-flags-02784 ] | MessageID = 0xd65f4ec3 | vkCreateComputePipelines(): pCreateInfos[0].stage.flags includes VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT, but the subgroupSizeControl feature was not enabled. The Vulkan spec states: If flags has the VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT flag set, the subgroupSizeControl feature must be enabled (https://vulkan.lunarg.com/doc/view/1.3.268.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-flags-02784)
thread '<unnamed>' panicked at tests/src/run.rs:119:9:
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

cc @Lichtso @exrook

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Closes #5551 

**Description**

Our subgroup code assumed that if the physical device supported it, we would enable the extension. However the extension enablement code checked if the user actually asked for subgroup ops.

### CODE REVIEW

File: wgpu-hal/src/vulkan/adapter.rs [hunk 1]
```diff
@@ -952,8 +952,8 @@ impl PhysicalDeviceProperties {
                 extensions.push(vk::ExtImageRobustnessFn::name());
             }
 
-            // Require `VK_EXT_subgroup_size_control` if the associated feature was requested
-            if requested_features.contains(wgt::Features::SUBGROUP) {
+            // Require `VK_EXT_subgroup_size_control` if it is available
+            if self.supports_extension(vk::ExtSubgroupSizeControlFn::name()) {
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/adapter.rs]: Note to reviewer, this is inside in a `vk_version < 1.3` block.

Comment (teoxoy) [reply wgpu-hal/src/vulkan/adapter.rs]: I think this was correct before, this change makes it so that the `VK_EXT_subgroup_size_control` extension is optional even if the user requested the feature.

Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/adapter.rs]: I'm not sure I follow.

The code for adding the varying subgroup size flag checks if the _adapter_ supports it, not if the user asked for it from the device. As such we need to always ask for the extension if it's available to us.

Comment (teoxoy) [reply wgpu-hal/src/vulkan/adapter.rs]: Ah, I see, I think we should fix it here then:

https://github.com/gfx-rs/wgpu/blob/08efa72a83d0acdf25177408150e4c87933c1cd7/wgpu-hal/src/vulkan/adapter.rs#L451-L458

It should be `.subgroup_size_control(requested_features.contains(wgt::Features::SUBGROUP))`.

This is how we deal with multiview as well.

Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/adapter.rs]: This doesn't actually fix it - that works for multi-view as multiview will only actually be used if the feature is enabled. Whereas the subgroup size bit will be used _always_ if the adapter supports it.

Comment (teoxoy) [reply wgpu-hal/src/vulkan/adapter.rs]: It wasn't intended that we always use the functionality if it's available.
We should only use it if the user asked for `Features::SUBGROUP`.

Comment (teoxoy) [reply wgpu-hal/src/vulkan/adapter.rs]: I think the fix I proposed above will work since we set `PrivateCapabilities.subgroup_size_control` based on the field in the `vk::PhysicalDeviceSubgroupSizeControlFeatures` struct.

https://github.com/gfx-rs/wgpu/blob/0f751b147ab72902bf76c291e9983d2f4fc39ec7/wgpu-hal/src/vulkan/adapter.rs#L1488-L1490

Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/adapter.rs]: Alright, I think I can check that, if we store the user's features in the vk DeviceShared in - the problem is https://github.com/cwfitzgerald/wgpu/blob/cdc67ff9222087494000696aa87b92dfb1de6748/wgpu-hal/src/vulkan/device.rs#L792-L794

Comment (teoxoy) [reply wgpu-hal/src/vulkan/adapter.rs]: I thought that if we pass `false` to `vk::PhysicalDeviceSubgroupSizeControlFeatures::builder().subgroup_size_control(false)`, `self.shared.private_caps.subgroup_size_control` should also end up being `false`.

Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/adapter.rs]: No, we pull that from the vulkan physical device features, so it's true if the device supports it.

Comment (teoxoy) [reply wgpu-hal/src/vulkan/adapter.rs]: I see, actually `PrivateCapabilities` sounds like the wrong place for that field.

Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/adapter.rs]: @teoxoy take a look at this, I think that should work now?

Comment (teoxoy) [reply wgpu-hal/src/vulkan/adapter.rs]: Looks good!

File: wgpu-hal/src/vulkan/adapter.rs [hunk 2]
```diff
@@ -918,7 +918,7 @@ impl PhysicalDeviceProperties {
                 extensions.push(ext::image_robustness::NAME);
             }
 
-            // Require `VK_EXT_subgroup_size_control` if the associated feature was requested
+            // Require `VK_EXT_subgroup_size_control` if it is available
```
Comment (teoxoy) [inline wgpu-hal/src/vulkan/adapter.rs]:
```suggestion
            // Require `VK_EXT_subgroup_size_control` if the associated feature was requested
```

**Review by teoxoy — APPROVED** [review]
