### PR TITLE
[naga wgsl-in] Attempt automatic conversion for arguments to user defined function calls

### LINKED ISSUE #5523: Abstract type coercion missing for function arguments
From [conversation](https://github.com/gfx-rs/wgpu/issues/5515#issuecomment-2048794750) in #5515:

> I think this works per the spec - the type of a literal is AbstractInt which should be coerced into whatever makes the most sense in context. I'm not sure how thorough our implementation is in 0.19 or trunk.

It works in a few spots (simple integer expressions, for example) but call a function that takes a u32 and pass a 0 and you get this beauty:

Shader validation error:
    ┌─ surface.wgsl:367:12
    │
367 │     return with_cond(vertex_ix, 0);
    │            ^^^^^^^^^^^^^^^^^^^^^^^
    │            │                    │
    │            │                    naga::Expression [2]
    │            invalid function call

    Entry point vs_main_cond at Vertex is invalid
    Call to [11] is invalid
    Argument 1 value [2] doesn't match the type [1]

It wants a 0u. Don't get me started on that error message... my goodness.

### PR DESCRIPTION
**Pull request by jamienicol**
**Connections**
Fixes #5523 

**Description**
When lowering arguments for a user-defined function call, avoid concretizing the argument types. Instead make use of the existing `try_automatic_conversions()` machinery to attempt to convert each argument to the type expected by the function. This is straightforward as user-defined functions only have a single overload.

This additionally changes an argument type in the test parse_pointers() from `ptr<private>` to `ptr<function>`. The former is invalid code which is indeed caught by the validator, but the test only asserts that parsing succeeds, not validation. With this patch, this error is now caught during parsing which caused the test to fail.

**Testing**
Test suite passes. Added new tests.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [x] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by jamienicol** [comment]
There may be a discussion to be had regarding how to handle conversion errors, which can either be addressed here or in a follow up. Note the change made to the `parse_pointers()` test. The old code was invalid WGSL which would be caught by the validator with this error message:

```
error: Function [1] 'bar' is invalid
  ┌─ in.wgsl:2:1
  │  
2 │ ╭ fn bar() {
3 │ │     var x: f32 = 1.0;
4 │ │     let px = &x;
5 │ │     let py = foo(px);
  │ │              ^^^^^^^ invalid function call
  │ ╰─────────────────────^ naga::Function [1]
  │  
  = Call to [0] is invalid
  = Argument 0 value [1] doesn't match the type [1]
```

However, the test only ensures that parsing succeeds, not validation. With this patch we now report an error during parsing (hence why we had to fix the shader code for the test to still pass):

```
Could not parse WGSL:
error: automatic conversions cannot convert `ptr<f32>` to `ptr<f32>`
  ┌─ in.wgsl:5:18
  │
5 │     let py = foo(px);
  │                  ^^ a value of type ptr<f32> is required here
```

Arguably the new error is more helpful as tells you the required type (though not printing the pointer's address space is unhelpful). Though of course the validator's error message could be improved. Additionally the "automatic conversions cannot convert..." line is a bit misleading, as we shouldn't really be attempting to automatically convert a ptr. 

FWIW I did try making us not attempt automatic conversions for non-abstract types, but that caused [this test assertion](https://github.com/gfx-rs/wgpu/blob/5ca92bf984ca1c019488f0a62f3f7129fb807901/naga/src/front/wgsl/tests.rs#L84) to fail. Again because it expects an error during parsing, but by not attempting to convert non-abstract types that shader parses successfully (but still fails validation)

**Comment by jamienicol** [comment]
For comparison, tint's error messages seem a bit more intuitive.

With the pointer example from above:
```wgsl
fn foo(a: ptr<private, f32>) -> f32 { return *a; }
fn bar() {
    var x: f32 = 1.0;
    let px = &x;
    let py = foo(px);
}
```
Tint outputs:
```
error: type mismatch for argument 1 in call to foo, expected ptr<private, f32, read_write>, got ptr<function, f32, read_write>
    let py = foo(px);
                 ^^
```

But in a case where an *abstract* type cannot convert correctly:
```wgsl
fn foo(a: u32) {}
fn bar() {
    foo(0.0);
}
```
```
error: cannot convert value of type abstract-float to type u32
    foo(0.0);
        ^^^
```

Note the distinction between a completely mismatched type, and an abstract type that cannot be converted correctly

**Review by ErichDonGubler — APPROVED** [review]
This LGTM, but I'm rather inexperienced with this part of Naga. Will give somebody from @gfx-rs/naga a (timeboxed) chance to look this over; holler if you'd like that, please!

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -2142,7 +2142,27 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
+                                    expr,
+                                    &crate::proc::TypeResolution::Handle(arg_ty),
+                                    ctx.ast_expressions.get_span(arg),
+                                )
+                            }
+                            // Wrong number of arguments... just concretize the type here
+                            // and let the validator report the error.
+                            None => self.expression(arg, ctx),
+                        }
+                    })
```
Comment (ErichDonGubler) [inline naga/src/front/wgsl/lower/mod.rs]: todo: Ah, one thing: gotta `CHANGELOG` entry? 🙂 This sounds like a nice item to highlight there!

Comment (jamienicol) [reply naga/src/front/wgsl/lower/mod.rs]: done 🙂

File: CHANGELOG.md [hunk 2]
```diff
@@ -100,6 +100,7 @@ By @ErichDonGubler in [#6456](https://github.com/gfx-rs/wgpu/pull/6456), [#6148]
 - Fix textureNumLevels in the GLSL backend. By @magcius in [#6483](https://github.com/gfx-rs/wgpu/pull/6483).
 - Implement `quantizeToF16()` for WGSL frontend, and WGSL, SPIR-V, HLSL, MSL, and GLSL backends. By @jamienicol in [#6519](https://github.com/gfx-rs/wgpu/pull/6519).
 - Add support for GLSL `usampler*` and `isampler*`. By @DavidPeicho in [#6513](https://github.com/gfx-rs/wgpu/pull/6513).
+- Implement type inference for abstract arguments to user-defined functions. By @jamienicol in [#6577](https://github.com/gfx-rs/wgpu/pull/6577).
```
Comment (ErichDonGubler) [inline CHANGELOG.md:118]: question: Doesn't this apply automatic type conversion, not just type inference?

Comment (jamienicol) [reply CHANGELOG.md:118]: I might not understand the distinction in terminology correctly. It will convert from `AbstractInt` or `AbstractFloat` to concrete types. It won’t convert from an already concrete type. I guess “conversion” is still a better word as “inference” relates to variable declaration?

Comment (ErichDonGubler) [reply CHANGELOG.md:118]: I guess the term of art of "feasible automatic conversion", according to the WGSL spec.: <https://www.w3.org/TR/WGSL/#feasible-automatic-conversion>.

So, I'd say "type conversion" here would be uncontroversial, while "inference" probably refers to the wrong thing (i.e., figuring out what the type of a binding is when it's not specified given a RHS on assignment).

**Comment by teoxoy** [comment]
This looks ok to me but @jimblandy might want to take a look.
