### PR TITLE
fix(naga): Validate invalid binary operations

### LINKED ISSUE #8868: Constant evaluation incorrectly allows some illegal combinations of binary operand types
Similar to #8790 but not the same issue.

A couple cases where constant evaluation incorrectly allows some illegal combinations of binary operand types:

1. Comparison operators are implemented as `BinaryOperator::Equal => Literal::Bool(left_value == right_value)`, which successfully performs the comparison even in cases where WGSL does not permit the given operand types.
2. Evaluation of arithmetic operations on compose expressions does not distinguish the case of a simple compose (i.e. a vector) from a nested compose (i.e. a matrix), which incorrectly allows some operations that should not be permitted on matrices.

There are relevant CTS tests in (at least) `webgpu:shader,validation,expression,matrix,*`.

### PR DESCRIPTION
**Pull request by ecoricemon**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/8868

**Description**
Added validation on invalid binary operations to cause errors
* Incompatible comparison: Added validation to prevent comparisons between different scalar types
  e.g. 42i == 42u.
* Compose-scalar operations: Added checks for unsupported binary operations between compose types and scalars
  e.g. mat2x2f(...) + 1.0f.

**Testing**
* Existing tests (cargo xtask test)
passed
* CTS pass ratio
webgpu:shader,validation,expression,matrix,* : 1570/1881 (83.47%) -> 1678/1881 (89.21%)
webgpu:shader,validation,expression,binary,* : 4635/4992 (92.85%) -> 4786/4992 (95.87%)

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/proc/constant_evaluator.rs [hunk 1]
```diff
@@ -2597,13 +2597,45 @@ impl<'a> ConstantEvaluator<'a> {
...
+                            return Err(ConstantEvaluatorError::InvalidBinaryOpArgs);
+                        }
+                        Literal::Bool(left_value > right_value)
+                    }
+                    BinaryOperator::GreaterEqual => {
+                        if discriminant(&left_value) != discriminant(&right_value) {
+                            return Err(ConstantEvaluatorError::InvalidBinaryOpArgs);
+                        }
+                        Literal::Bool(left_value >= right_value)
+                    }
```
Comment (teoxoy) [inline naga/src/proc/constant_evaluator.rs]: Instead of duplicating the check in every match arm, could you move it out?

**Comment by teoxoy** [comment]
Thanks for the PR!

> webgpu:shader,validation,expression,matrix,* : 1570/1881 (83.47%) -> 1678/1881 (89.21%)
> webgpu:shader,validation,expression,binary,* : 4635/4992 (92.85%) -> 4786/4992 (95.87%)

Do you know what it would take to get these to fully pass?

**Review by teoxoy — CHANGES_REQUESTED** [review]

**Comment by ecoricemon** [comment]
> Thanks for the PR!
> 
> > webgpu:shader,validation,expression,matrix,* : 1570/1881 (83.47%) -> 1678/1881 (89.21%)
> > webgpu:shader,validation,expression,binary,* : 4635/4992 (92.85%) -> 4786/4992 (95.87%)
> 
> Do you know what it would take to get these to fully pass?

The first thing that I could see was some binary operations between compose types were rejected. I'll look into it!

File: naga/src/proc/constant_evaluator.rs (hunk 1 above)
Comment (ecoricemon) [reply naga/src/proc/constant_evaluator.rs]: I've fixed it. Could you review it again

**Comment by teoxoy** [comment]
> The first thing that I could see was some binary operations between compose types were rejected. I'll look into it!

Sounds great, thanks!

**Review by teoxoy — APPROVED** [review]

**Comment by andyleiserson** [comment]
There are some notes about the issues with the matrix tests at https://github.com/andyleiserson/cts-triage/blob/main/README.md#matrix-expression-validation, and a few places in that file for `binary` tests -- issues include #5474, #8900. ("Do not fix" in those notes only means don't fix right away as part of the triage work. We do want to fix.)
