### PR TITLE
Remove hold of snatch write lock during present

### LINKED ISSUE #8597: `SurfaceTexture::present` blocks with lock if window is not visible
**Description**

When the window of my application (egui/eframe/wgpu) is not visible my compute shaders hang. 

(edit: to be clear: not the shader themself hang, but my code managing them. it is not related to compute shaders, but anything using certain wgpu resources will hang).

egui is run using eframe (wgpu backend) on main thread.
Compute shaders use the same wgpu device and queue but are managed by a separate thread.

I found the following related issues: #3283, #421, #1218. But they don't seem to point out this exact issue, so I thought to open this in case this is something that should be fixed.

**Repro steps**

Call `SurfaceTexture::present` on a surface of a window that is not visible. `PresentMode` should be `AutoVsync` (eframe default). `Mailbox` fixes this issue.

Then on another thread try to use device and queue. E.g. `BufferSlice::get_mapped_range_mut`, or `CommandEncoder::finish`. It will hang.

**Expected vs observed behavior**

Expected to still be able to use device and queue as normal with any blocking behavior documented.
Observed behavior: Many calls into wgpu will block while window is hidden.

**Extra materials**

To debug this I first sprayed log prints over the code running my compute shaders. It was hanging in multiple places. Then I ran the app with a debugger attached and inspected the main/compute threads' call stacks (window hidden, program then paused). I did this multiple times, so these stack traces reproduce. Only the exact point where the compute thread hangs changes, but it's always waiting for a lock in wgpu, while the main thread is blocked presenting the surface texture.

<details>
  <summary>Main thread (egui/eframe)</summary>
  
  ```
___lldb_unnamed_symbol3741 (@___lldb_unnamed_symbol3741:17)
___lldb_unnamed_symbol3665 (@___lldb_unnamed_symbol3665:28)
___lldb_unnamed_symbol3666 (@___lldb_unnamed_symbol3666:9)
__poll (@__poll:13)
wl_display_dispatch_queue (@wl_display_dispatch_queue:73)
___lldb_unnamed_symbol3111 (@___lldb_unnamed_symbol3111:54)
___lldb_unnamed_symbol2981 (@___lldb_unnamed_symbol2981:296)
___lldb_unnamed_symbol1590 (@___lldb_unnamed_symbol1590:35)
ash::extensions::khr::swapchain::<impl ash::extensions_generated::khr::swapchain::Device>::queue_present (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ash-0.38.0+1.3.281/src/extensions/khr/swapchain.rs:86)
<wgpu_hal::vulkan::Queue as wgpu_hal::Queue>::present (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-hal-27.0.4/src/vulkan/mod.rs:1631)
<Q as wgpu_hal::dynamic::queue::DynQueue>::present (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-hal-27.0.4/src/dynamic/queue.rs:50)
wgpu_core::present::<impl wgpu_core::instance::Surface>::present (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-27.0.3/src/present.rs:301)
wgpu_core::present::<impl wgpu_core::global::Global>::surface_present (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-27.0.3/src/present.rs:396)
<wgpu::backend::wgpu_core::CoreSurfaceOutputDetail as wgpu::dispatch::SurfaceOutputDetailInterface>::present (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-27.0.1/src/backend/wgpu_core.rs:3856)
wgpu::api::surface_texture::SurfaceTexture::present (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-27.0.1/src/api/surface_texture.rs:38)
egui_wgpu::winit::Painter::paint_and_update_textures (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/egui-wgpu/src/winit.rs:617)
eframe::native::wgpu_integration::WgpuWinitRunning::run_ui_and_paint (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/wgpu_integration.rs:690)
<eframe::native::wgpu_integration::WgpuWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/wgpu_integration.rs:395)
<eframe::native::run::WinitAppWrapper<T> as winit::application::ApplicationHandler<eframe::native::winit_integration::UserEvent>>::window_event::{{closure}} (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/run.rs:311)
eframe::native::event_loop_context::with_event_loop_context (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/event_loop_context.rs:53)
<eframe::native::run::WinitAppWrapper<T> as winit::application::ApplicationHandler<eframe::native::winit_integration::UserEvent>>::window_event (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/run.rs:308)
winit::event_loop::dispatch_event_for_app (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/event_loop.rs:642)
winit::platform::run_on_demand::EventLoopExtRunOnDemand::run_app_on_demand::{{closure}} (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform/run_on_demand.rs:76)
core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:298)
core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:298)
winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::single_iteration (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform_impl/linux/wayland/event_loop/mod.rs:502)
winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::poll_events_with_timeout (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform_impl/linux/wayland/event_loop/mod.rs:328)
winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::pump_events (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform_impl/linux/wayland/event_loop/mod.rs:226)
winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::run_on_demand (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform_impl/linux/wayland/event_loop/mod.rs:190)
winit::platform_impl::linux::EventLoop<T>::run_on_demand (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform_impl/linux/mod.rs:820)
<winit::event_loop::EventLoop<T> as winit::platform::run_on_demand::EventLoopExtRunOnDemand>::run_on_demand (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform/run_on_demand.rs:89)
winit::platform::run_on_demand::EventLoopExtRunOnDemand::run_app_on_demand (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform/run_on_demand.rs:75)
eframe::native::run::run_and_return (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/run.rs:328)
eframe::native::run::run_wgpu::{{closure}} (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/run.rs:398)
eframe::native::run::with_event_loop::{{closure}} (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/run.rs:62)
std::thread::local::LocalKey<T>::try_with (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:508)
std::thread::local::LocalKey<T>::with (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:472)
eframe::native::run::with_event_loop (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/run.rs:52)
eframe::native::run::run_wgpu (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/native/run.rs:396)
eframe::run_native (~/.cargo/git/checkouts/egui-5370533f5a2b2faf/fc06f6f/crates/eframe/src/lib.rs:274)
  ```
</details>

<details>
  <summary>Compute shader thread</summary>
  
  ```
syscall (@syscall:12)
parking_lot_core::thread_parker::imp::ThreadParker::futex_wait (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.12/src/thread_parker/linux.rs:112)
<parking_lot_core::thread_parker::imp::ThreadParker as parking_lot_core::thread_parker::ThreadParkerT>::park (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.12/src/thread_parker/linux.rs:66)
parking_lot_core::parking_lot::park::{{closure}} (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.12/src/parking_lot.rs:635)
parking_lot_core::parking_lot::with_thread_data (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.12/src/parking_lot.rs:207)
parking_lot_core::parking_lot::park (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.12/src/parking_lot.rs:600)
parking_lot::raw_rwlock::RawRwLock::lock_common (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.5/src/raw_rwlock.rs:1124)
parking_lot::raw_rwlock::RawRwLock::lock_shared_slow (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.5/src/raw_rwlock.rs:721)
<parking_lot::raw_rwlock::RawRwLock as lock_api::rwlock::RawRwLock>::lock_shared (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.5/src/raw_rwlock.rs:109)
lock_api::rwlock::RwLock<R,T>::read (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.14/src/rwlock.rs:458)
wgpu_core::lock::vanilla::RwLock<T>::read (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-27.0.3/src/lock/vanilla.rs:91)
wgpu_core::snatch::SnatchLock::read (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-27.0.3/src/snatch.rs:148)
wgpu_core::device::global::<impl wgpu_core::global::Global>::buffer_get_mapped_range (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-27.0.3/src/device/global.rs:2331)
<wgpu::backend::wgpu_core::CoreBuffer as wgpu::dispatch::BufferInterface>::get_mapped_range (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-27.0.1/src/backend/wgpu_core.rs:2160)
wgpu::api::buffer::BufferSlice::get_mapped_range_mut (~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-27.0.1/src/api/buffer.rs:637)
cem_util::wgpu::buffer::staging::write::WriteStagingTransaction<P>::view_mut_and_copy::{{closure}} (~/code/fdtd/cem-util/src/wgpu/buffer/staging/write.rs:65)
<cem_util::wgpu::buffer::staging::write::WriteStagingBelt as cem_util::wgpu::buffer::staging::write::StagingBufferProvider>::allocate (~/code/fdtd/cem-util/src/wgpu/buffer/staging/write.rs:373)
cem_util::wgpu::buffer::staging::write::WriteStagingTransaction<P>::view_mut_and_copy (~/code/fdtd/cem-util/src/wgpu/buffer/staging/write.rs:63)
cem_util::wgpu::buffer::staging::write::WriteStagingTransaction<P>::write_buffer (~/code/fdtd/cem-util/src/wgpu/buffer/staging/write.rs:82)
cem_util::wgpu::buffer::staging::write::WriteStagingTransaction<P>::write_buffer_from_slice (~/code/fdtd/cem-util/src/wgpu/buffer/staging/write.rs:99)
<cem_solver::fdtd::wgpu::FdtdWgpuUpdatePass as cem_solver::UpdatePass>::finish (~/code/fdtd/cem-solver/src/fdtd/wgpu/mod.rs:399)
cem_app::solver::runner::Solver::spawn::{{closure}} (~/code/fdtd/cem-app/src/solver/runner.rs:545)
std::sys::backtrace::__rust_begin_short_backtrace (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:158)
std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}} (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:562)
<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274)
std::panicking::catch_unwind::do_call (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:590)
__rust_try (@__rust_try:10)
std::panicking::catch_unwind (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:553)
std::panic::catch_unwind (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359)
std::thread::Builder::spawn_unchecked_::{{closure}} (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:560)
core::ops::function::FnOnce::call_once{{vtable.shim}} (~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250)
<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once (@std::sys::thread::unix::Thread::new::thread_start:19)
std::sys::thread::unix::Thread::new::thread_start (@std::sys::thread::unix::Thread::new::thread_start:17)
___lldb_unnamed_symbol3707 (@___lldb_unnamed_symbol3707:156)
___lldb_unnamed_symbol4140 (@___lldb_unnamed_symbol4140:6)
  ```
</details>

**Platform**

Arch Linux, Wayland, Sway
wgpu v27.0.1
Adapter: Intel(R) UHD Graphics 620 (WHL GT2) (8086:3ea0)
Backend: Vulkan
Driver: Intel open-source Mesa driver (Mesa 25.1.5-arch1.1)

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Closes #8597 

**Description**

By locking the snatch lock inline, we extended the lifetime of the snatch lock over the entire present operation, instead of snatching then presenting.

**Testing**

None.

**Squash or Rebase?**

Commit

### CODE REVIEW

File: wgpu-core/src/present.rs [hunk 1]
```diff
@@ -293,7 +293,11 @@ impl Surface {
             .take()
             .ok_or(SurfaceError::AlreadyAcquired)?;
 
-        let result = match texture.inner.snatch(&mut device.snatchable_lock.write()) {
+        let mut exclusive_snatch_guard = device.snatchable_lock.write();
+        let inner = texture.inner.snatch(&mut exclusive_snatch_guard);
+        drop(exclusive_snatch_guard);
```
Comment (kristoff3r) [inline wgpu-core/src/present.rs:298]: While this is very explicit (which might be desirable in this case), just moving the expression out of the match statement is equivalent to this code. The problem with the existing code is that temporaries aren't dropped before the entire match scope ends, so a good rule of thumb is to always assign stuff from inside locks to a variable before using them. https://fasterthanli.me/articles/a-rust-match-made-in-hell has a good deep dive about this.

Please excuse my rant if you were already aware of this :smile: 

```suggestion
        let inner = texture.inner.snatch(&mut device.snatchable_lock.write());
```

Comment (ErichDonGubler) [reply wgpu-core/src/present.rs:298]: As a reviewer, and not the author: This is interesting feedback. My counter to it (short-term) would be that most of the rest of the code base that handles resource tracking explicitly does this also to resolve deadlock conflicts, and it's important to be consistent.

If we wanted to move to this style in the long-term, though, that seems fine for a follow-up issue. 🙂

Comment (cwfitzgerald) [reply wgpu-core/src/present.rs:298]: Yup, am painfully aware :) In this case yeah I wanted to have the critical section be very clear as this is the write side of a very heavy lock in wgpu.

File: CHANGELOG.md [hunk 2]
```diff
@@ -175,6 +175,7 @@ By @cwfitzgerald in [#8579](https://github.com/gfx-rs/wgpu/pull/8579).
 - The `STORAGE_READ_ONLY` texture usage is now permitted to coexist with other read-only usages. By @andyleiserson in [#8490](https://github.com/gfx-rs/wgpu/pull/8490).
 - Validate that buffers are unmapped in `write_buffer` calls. By @ErichDonGubler in [#8454](https://github.com/gfx-rs/wgpu/pull/8454).
 - Add WGSL parsing for mesh shaders. By @inner-daemons in [#8370](https://github.com/gfx-rs/wgpu/pull/8370).
+- Shorten critical section inside present such that the snatch write lock is no longer held during present, preventing other work happening on other threads. By @cwfitzgerald in [#8608](https://github.com/gfx-rs/wgpu/pull/8608).
```
Comment (ErichDonGubler) [inline CHANGELOG.md:178]: suggestion: Maybe we should distinguish the different meanings of "present" here between a wgpu API call to present, and the _platform's_ API for presentation?

**Review by ErichDonGubler — APPROVED** [review]
LGTM!

**Comment by inner-daemons** [comment]
This is being blamed for #9003.
