### PR TITLE
[spirv] Stop naga causing undefined behavior in `rayQueryGet*Intersection`

### LINKED ISSUE #6731: Lavapipe causes access violation accessing `intersection.world_to_object`
**Description**
Since I got lavapipe installed I've been testing it with ray-tracing, and it seems that if a section of the intersection struct is accessed that needs a triangle to be hit (not done within the current examples) lavapipe dereferences a null pointer and crashes. I think this is actually our issue, as we gather these members without caring whether we have hit anything or not (this is technically undefined behavior). I think that the best way to deal with this is to emit a function for it for the three different blocks required. I am happy to do this.

**Repro steps**
add this line to any of the ray cube examples
````wgsl
color  = vec4f(intersection.world_to_object[0].x)
````
and run with lavapipe

**Expected vs observed behavior**
it should give an access violation

**Platform**
latest trunk wgpu w/ change

### PR DESCRIPTION
**Pull request by Vecvec**
**Connections**
fixes #6731 

**Description**
Naga previously unconditionally called operations that required the ray to hit something. This is undefined behavior according to the spirv raytracing spec. This caused seg-faults on lavapipe. This prevents that by separating the intersection getter into another function with conditional blocks.

**Testing**
added a test that previously failed (with a seg-fault) that now succeeds

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [n/a] `--target wasm32-unknown-unknown`
  - [n/a] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: tests/tests/ray_tracing/shader.rs [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+        mapped_at_creation: false,
+    });
+    //
+    // Create a clean `AsBuildContext`
+    //
+
+    let as_ctx = AsBuildContext::new(&ctx);
+
+    //
+    // Build in the right order, then rebuild the BLAS so the TLAS is invalid, then use the TLAS.
```
Comment (cwfitzgerald) [inline tests/tests/ray_tracing/shader.rs]: Comment is out of date

File: tests/tests/ray_tracing/shader.rs [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+    let mut encoder_tlas = ctx
+        .device
+        .create_command_encoder(&CommandEncoderDescriptor {
+            label: Some("TLAS 1"),
+        });
+
+    encoder_tlas.build_acceleration_structures([], [&as_ctx.tlas_package]);
+
+    ctx.queue
+        .submit([encoder_blas.finish(), encoder_tlas.finish()]);
```
Comment (cwfitzgerald) [inline tests/tests/ray_tracing/shader.rs]: If we're not testing anything funky, we can just do this in a single call, ja?

File: tests/tests/ray_tracing/shader.rs [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+        .device
+        .create_command_encoder(&CommandEncoderDescriptor::default());
+    {
+        let mut pass = encoder_compute.begin_compute_pass(&ComputePassDescriptor {
+            label: None,
+            timestamp_writes: None,
+        });
+        pass.set_pipeline(&compute_pipeline);
+        pass.set_bind_group(0, Some(&bind_group), &[]);
+        pass.dispatch_workgroups(1, 2, 1)
```
Comment (cwfitzgerald) [inline tests/tests/ray_tracing/shader.rs]: Two?

File: tests/tests/ray_tracing/shader.wgsl [hunk 4]
```diff
@@ -1,11 +1,51 @@
...
+        intersection.instance_custom_index,
+        intersection.instance_id,
+        intersection.sbt_record_offset,
+        intersection.geometry_index,
+        intersection.primitive_index,
+        intersection.barycentrics,
+        u32(intersection.front_face),
+        intersection.world_to_object,
+        intersection.object_to_world,
+    );
```
Comment (cwfitzgerald) [inline tests/tests/ray_tracing/shader.wgsl:50]: What values do these have if they are not valid to read? Similarly might it be useful to assert that the values are sane coming out of the api?

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Some comments on the tests

File: tests/tests/ray_tracing/shader.wgsl (hunk 4 above)
Comment (Vecvec) [reply tests/tests/ray_tracing/shader.wgsl:50]: The idea is these are always valid to read, it should just be zero.

Comment (Vecvec) [reply tests/tests/ray_tracing/shader.wgsl:50]: I'm not sure what happens on a mac though, it may still have undefined behavior.

Comment (Vecvec) [reply tests/tests/ray_tracing/shader.wgsl:50]: The way metal's API is designed seems to suggest that undefined behavior is unlikely (but I can't find anything in the specification that suggests this).

**Review by cwfitzgerald — APPROVED** [review]
Looks needfully verbose but fine.

I've done a pass on the naga side, would like a final lookover of the naga side before this lands.

@jimblandy

**Review by jimblandy — APPROVED** [review]
The Naga portion looks good. It's not pretty, but it's clean, and I don't see a better alternative.

**Comment by Vecvec** [comment]
I think the MacOS CI fail is unrelated - This doesn't change any code to do with MacOS.

**Comment by cwfitzgerald** [comment]
Ooo we have a spuriously failing test!
