### PR TITLE
Fix present synchronization

### LINKED ISSUE #9003: Crash on nvidia cards since wgpu 28
**Description**
The following code:

```
use std::sync::Arc;
use winit::{
    application::ApplicationHandler,
    event::WindowEvent,
    event_loop::{ActiveEventLoop, EventLoop},
    window::{Window, WindowId},
};

#[derive(Default)]
struct App {
    state: Option<State>,
}

struct State {
    window: Arc<Window>,
    surface: wgpu::Surface<'static>,
    queue: wgpu::Queue,
}

fn main() {
    let event_loop = EventLoop::new().unwrap();
    event_loop.set_control_flow(winit::event_loop::ControlFlow::Poll);

    let mut app = App::default();
    event_loop.run_app(&mut app).unwrap();
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        let window = Arc::new(
            event_loop
                .create_window(Window::default_attributes().with_title("wgpu crash test"))
                .unwrap(),
        );

        let instance = wgpu::Instance::new(&Default::default());

        let surface = instance.create_surface(window.clone()).unwrap();

        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            compatible_surface: Some(&surface),
            force_fallback_adapter: false,
        }))
        .unwrap();

        let (device, queue) = pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
            ..Default::default()
        }))
        .unwrap();

        let size = window.inner_size();
        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: surface.get_capabilities(&adapter).formats[0],
            width: size.width.max(1),
            height: size.height.max(1),
            present_mode: wgpu::PresentMode::Fifo,
            alpha_mode: wgpu::CompositeAlphaMode::Auto,
            view_formats: vec![],
            desired_maximum_frame_latency: 1,
        };
        surface.configure(&device, &config);

        let queue2 = queue.clone();
        std::thread::spawn(move || {
            loop {
                queue2.submit([]);
            }
        });

        self.state = Some(State {
            window,
            surface,
            queue,
        });
    }

    fn window_event(&mut self, _: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        let Some(state) = &mut self.state else {
            return;
        };

        if event == WindowEvent::RedrawRequested {
            // Just get and present - no rendering
            let frame = state.surface.get_current_texture().unwrap();
            state.queue.submit([]);
            frame.present();
            state.window.request_redraw();
        }
    }
}
```

```toml
[package]
name = "wgpu_repro"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "28"
# wgpu = "27"  # works! 
pollster = "0.4"
winit = "0.30"
```

Crashes on wgpu 28 when requesting my dedicated GPU. It does not crash on my integrated AMD card. On wgpu 27, neither my AMD or nvidia card crash.

**Platform**
Linux (Arch) and Windows reproduce the crash, on nvidia GPUs. macOS and my integrated AMD GPU do not.

### PR DESCRIPTION
**Pull request by inner-daemons**
**Connections**
Closes #9003
Closes #9024 

**Description**
This makes sure that the queue is effectively locked when presenting a texture, since this is still a queue operation and queue operations aren't threadsafe in vulkan.

**Testing**
Solves the issue

**Squash or Rebase?**
Squash pls, only commit name is dumb

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by SuchAFuriousDeath** [comment]
I'll be testing this today.

**Comment by SuchAFuriousDeath** [comment]
@inner-daemons I just tested and it does fix the issue.

**Comment by inner-daemons** [comment]
Ok so I'll add a changelog later. THen we can backport this

**Comment by ArthurBrussee** [comment]
Any chance to have another look at this? I'm blocked on upgrading some deps as they're on wgpu 28 which currently crashes without this fix. This PR does indeed solve it. Thanks a lot for finding the fix btw!

**Comment by SuchAFuriousDeath** [comment]
Yeah it would be nice for Ruffle too.

File: wgpu-core/src/present.rs [hunk 1]
```diff
@@ -302,6 +302,7 @@ impl Surface {
             Some(resource::TextureInner::Surface { raw }) => {
                 let raw_surface = self.raw(device.backend()).unwrap();
                 let raw_queue = queue.raw();
+                let _fence_lock = device.fence.write();
```
Comment (cwfitzgerald) [inline wgpu-core/src/present.rs:305]: Definitely need a comment about why this is needed as it's not obvious from the rest of the code. In the name of expediency, I will merge and backport this anyway, but @inner-daemons lets do this in a follow up.

**Review by cwfitzgerald — APPROVED** [review]

**Comment by cwfitzgerald** [comment]
Published in [v28.0.1!](https://github.com/gfx-rs/wgpu/releases/tag/v28.0.1)
