### PR TITLE
[wgpu-core] validate occlusion and pipeline statistics queries end

### LINKED ISSUE #7869: Validation missing for balancing of occlusion query begin and end in render passes
WGPU has incomplete coverage for validation. On macOS and Vulkan on Linux, this is allowed (!?), but on Windows' DirectX 12 and Vulkan backends, this results in a platform error we convert to an internal error. On DX12 specifically, we poorly handle this, and this becomes a panic; for example, using the MRE below yields:

```
[2025-07-01T18:31:37Z ERROR wgpu_hal::auxil::dxgi::result] GraphicsCommandList::close failed: Unspecified error (0x80004005)

thread 'main' panicked at C:\Users\Erich\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-core-25.0.2\src\resource.rs:1186:75:
thread 'main' attempted to acquire a snatch lock recursively.
- Currently trying to acquire a write lock at C:\Users\Erich\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-core-25.0.2\src\resource.rs:1186:75
disabled backtrace
- Previously acquired a read lock at C:\Users\Erich\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-core-25.0.2\src\command\render.rs:1632:52
```

Converting [`webgpu:api,validation,encoding,queries,begin_end:occlusion_query,begin_end_balance:*`](https://gpuweb.github.io/cts/standalone/?q=webgpu:api,validation,encoding,queries,begin_end:occlusion_query,begin_end_balance:*) into a Rust MRE:

```toml
[package]
name = "tmp-ovpsdi"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "*"
log = "*"
pollster = "*"
wgpu = "*"
```

```rust
use pollster::FutureExt as _;

fn main() {
    env_logger::init();

    let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
        backends: if cfg!(windows) {
            wgpu::Backends::DX12 
            // wgpu::Backends::VULKAN
        } else {
            wgpu::Backends::PRIMARY
        },
        ..Default::default()
    });

    let adapter = instance
        .request_adapter(&Default::default())
        .block_on()
        .unwrap();

    let (device, _queue) = adapter
        .request_device(&Default::default())
        .block_on()
        .unwrap();

    let num_query_sets = 2;

    let query_set = device.create_query_set(&wgpu::QuerySetDescriptor {
        label: None,
        ty: wgpu::QueryType::Occlusion,
        count: num_query_sets,
    });

    let color_attachment = device.create_texture(&wgpu::TextureDescriptor {
        label: None,
        size: wgpu::Extent3d {
            width: 16,
            height: 16,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
        view_formats: &[],
    });

    let color_attachment_view = color_attachment.create_view(&Default::default());

    // Cases stolen from
    // `webgpu:api,validation,encoding,queries,begin_end:occlusion_query,begin_end_balance:*` in
    // CTS:
    // <https://github.com/gpuweb/cts/blob/393b92882f3769cbcd8561dfbb4d3ff528a69afa/src/webgpu/api/validation/encoding/queries/begin_end.spec.ts#L20-L24>.
    let cases = [
        [0, 1],
        [1, 0],
        [1, 1], // control case
        [1, 2],
        [2, 1],
    ];
    for case @ [num_begin, num_end] in cases {
        log::debug!("testing case {case:?}");

        let valid = num_begin == num_end;

        if !valid {
            device.push_error_scope(wgpu::ErrorFilter::Validation);
        }

        let mut encoder = device.create_command_encoder(&Default::default());

        {
            let mut render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: None,
                occlusion_query_set: Some(&query_set),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &color_attachment_view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color::TRANSPARENT),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
            });

            for idx in 0..num_begin {
                render_pass.begin_occlusion_query(idx);
            }
            for _ in 0..num_end {
                render_pass.end_occlusion_query();
            }
        }

        let _buf = encoder.finish();

        if !valid {
            assert!(device.pop_error_scope().block_on().is_some());
        }
    }
}
```

### PR DESCRIPTION
**Pull request by teoxoy**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/7869.

**Description**
Validates that occlusion and pipeline statistics queries end.

**Testing**
Added new CTS test to list.

**Squash or Rebase?**
n/a

### CODE REVIEW

File: wgpu-core/src/command/query.rs [hunk 1]
```diff
@@ -150,6 +150,8 @@ pub enum QueryUseError {
         set_type: SimplifiedQueryType,
         query_type: SimplifiedQueryType,
     },
+    #[error("A query was not ended before the encoder was finished")]
+    MissingEnd,
```
Comment (cwfitzgerald) [inline wgpu-core/src/command/query.rs]: Could we add information about what kind of query it was to make this more actionable?

Comment (ErichDonGubler) [reply wgpu-core/src/command/query.rs]: Tried to address this with [34e1d20](https://github.com/gfx-rs/wgpu/pull/8684/commits/34e1d20143b6c2ab11e5076bb3c8b4b13556b6a9). What do you and @teoxoy think?

**Review by cwfitzgerald — APPROVED** [review]
LATM (Looks actionable to me)
