### PR TITLE
[naga wgsl-in] Handle struct types in error messages properly.

### LINKED ISSUE #7495: internal error: entered unreachable code: structs can only be referenced by name in WGSL
Some unreachable code is reachable. Since a contradiction has been proven, all propositions are now true, so I'm declaring WebGPU successfully shipped and myself a billionaire with my own private island.

... Well, that didn't work, so perhaps we should fix Naga instead.

When presented with the following WGSL:

```wgsl
alias f32_alias = f32;

@group(0) @binding(0) var s: sampler;
@group(0) @binding(1) var t: texture_2d<f32>;

var<workgroup> a: atomic<u32>;

struct A {
  i: u32,
}
struct B {
  arry: array<u32>,
}
@group(0) @binding(3) var<storage> k: B;

@vertex
fn main() -> @builtin(position) vec4<f32> {
  var a: A;
          _ = acosh(a);
  return vec4<f32>(.4, .2, .3, .1);
}
```

Naga says:

```
thread 'main' panicked at naga/src/common/wgsl/types.rs:372:13:
internal error: entered unreachable code: structs can only be referenced by name in WGSL
stack backtrace:
...
   2: naga::common::wgsl::types::try_write_type_inner
             at /home/jimb/rust/wgpu/naga/src/common/wgsl/types.rs:372:13
   3: naga::common::wgsl::types::TypeContext::write_type_inner
             at /home/jimb/rust/wgpu/naga/src/common/wgsl/types.rs:109:15
   4: <naga::common::diagnostic_display::DiagnosticDisplay<(&naga::ir::TypeInner,naga::proc::GlobalCtx)> as core::fmt::Display>::fmt
             at /home/jimb/rust/wgpu/naga/src/common/diagnostic_display.rs:74:9
   5: <T as alloc::string::ToString>::to_string
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/string.rs:2565:9
   6: naga::front::wgsl::lower::Lowerer::resolve_overloads
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:3056:30
   7: naga::front::wgsl::lower::Lowerer::math_function_helper
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:2964:20
   8: naga::front::wgsl::lower::Lowerer::call
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:2456:21
   9: naga::front::wgsl::lower::Lowerer::expression_for_reference
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:2142:30
  10: naga::front::wgsl::lower::Lowerer::expression_for_abstract
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:2019:20
  11: naga::front::wgsl::lower::Lowerer::expression
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:2010:20
  12: naga::front::wgsl::lower::Lowerer::statement
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:1985:29
  13: naga::front::wgsl::lower::Lowerer::block
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:1497:13
  14: naga::front::wgsl::lower::Lowerer::function
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:1404:24
  15: naga::front::wgsl::lower::Lowerer::lower
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/lower/mod.rs:1132:40
  16: naga::front::wgsl::Frontend::inner
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/mod.rs:50:22
  17: naga::front::wgsl::Frontend::parse
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/mod.rs:44:9
  18: naga::front::wgsl::parse_str
             at /home/jimb/rust/wgpu/naga/src/front/wgsl/mod.rs:68:5
...
```

### PR DESCRIPTION
**Pull request by jimblandy**
Don't try to use `&TypeInner` values to generate error messages, since `&TypeInner` cannot represent struct types in WGSL - they must be referred to by name, and only `Type` knows the type's name. Using `Handle<Type>` or `TypeResolution` works fine, so use that instead.

Add a new `Display` impl for `DiagnosticDisplay` for `TypeResolution`.

Fixes #7495.

### CODE REVIEW

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -3026,13 +3026,14 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
 
         for (arg_index, &arg) in arguments.iter().enumerate() {
-            let ty = ctx.typifier()[arg].inner_with(&ctx.module.types);
+            let arg_type_resolution = &ctx.typifier()[arg];
+            let arg_inner = arg_type_resolution.inner_with(&ctx.module.types);
             log::debug!(
-                "Supplying argument {arg_index} of type {}",
-                crate::common::DiagnosticDisplay((ty, ctx.module.to_ctx()))
+                "Supplying argument {arg_index} of type {:?}",
+                crate::common::DiagnosticDebug((arg_type_resolution, &ctx.module.types))
```
Comment (ErichDonGubler) [inline naga/src/front/wgsl/lower/mod.rs]: thought: What, no `for_debug` here? 👀

File: naga/src/common/diagnostic_display.rs [hunk 2]
```diff
@@ -49,6 +49,17 @@ use core::fmt;
...
+        let (resolution, ctx) = self.0;
+
+        match *resolution {
+            TypeResolution::Handle(handle) => DiagnosticDisplay((handle, ctx)).fmt(f),
+            TypeResolution::Value(ref inner) => DiagnosticDisplay((inner, ctx)).fmt(f),
+        }
+    }
+}
+
 impl fmt::Display for DiagnosticDisplay<(Handle<Type>, GlobalCtx<'_>)> {
```
Comment (ErichDonGubler) [inline naga/src/common/diagnostic_display.rs]: question: `DiagnosticDisplay` with a `Handle<Type>` has a footgun in that it can't handle `struct`s. Should we try to remove this `Display` implementation, and force other use sites to migrate?

**Review by ErichDonGubler — APPROVED** [review]
Fixes a crash, so you've got my vote! Just one question that need not block.

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (jimblandy) [reply naga/src/front/wgsl/lower/mod.rs]: I changed this to use `ForDebugWithTypes`. Thanks.

File: naga/src/common/diagnostic_display.rs (hunk 2 above)
Comment (jimblandy) [reply naga/src/common/diagnostic_display.rs]: It's `&TypeInner` that has the footgun, actually, not `Handle<Type>`.

Let me see if there are impls we can delete.

**Comment by jimblandy** [comment]
There are actually a lot of different places where this occurs, and I've been able to trigger crashes in most cases that I've found. I'm going to broaden the scope. I'll take it out of draft when I've taken care of all the cases I'm aware of.

File: naga/src/common/diagnostic_display.rs (hunk 2 above)
Comment (jimblandy) [reply naga/src/common/diagnostic_display.rs]: This was a serious problem. I've greatly expanded the PR.

**Comment by jimblandy** [comment]
@ErichDonGubler Okay, the new version of this patch goes much further. I've deleted all the `TypeInner` formatting paths except the ones used for logging, and added tests for a few more cases that would panic.

Could you take another look?

**Comment by jimblandy** [comment]
@ErichDonGubler Note that, aside from changing the original commit to use `for_debug` as you suggested, this leaves the original PR alone, and only adds commits. The new commits should be reviewable individually.

File: naga/src/back/wgsl/writer.rs [hunk 3]
```diff
@@ -481,15 +481,19 @@ impl<W: Write> Writer<W> {
...
+        resolution: &proc::TypeResolution,
+    ) -> BackendResult {
         // This actually can't be factored out into a nice constructor method,
         // because the borrow checker needs to be able to see that the borrows
         // of `self.names` and `self.out` are disjoint.
         let type_context = WriterTypeContext {
             module,
             names: &self.names,
         };
-        type_context.write_type_inner(inner, &mut self.out)?;
```
Comment (ErichDonGubler) [inline naga/src/back/wgsl/writer.rs:492]: question(non-blocking): Would it be possible to retire `write_type_inner` entirely at some point?

**Review by ErichDonGubler — APPROVED** [review]

File: naga/src/back/wgsl/writer.rs (hunk 3 above)
Comment (jimblandy) [reply naga/src/back/wgsl/writer.rs:492]: I started out with that as my goal. But one of the clienteles we need to serve is people doing debugging, and in some spots all you've got is a `TypeInner` and an arena.

Or at least I think so. Careful examination may show that, in every place we are currently dumping `TypeInner`, we actually have a `Handle<Type>` or a `TypeResolution` available as well. If that's the case, then we can totally make `write_type_inner` a private detail of `common::wgsl::types`.
