### PR TITLE
[naga wgsl-in] Handle automatic type conversions for switch selector and case expressions

### LINKED ISSUE #7225: WGSL: `switch` `case`s do not attempt automatic type conversion
**Repro steps**

1. Run the following against Naga, i.e., `cargo run -p naga ../in.wgsl`:

    ```wgsl
    const signedGlobalConst = 4;
    
    @compute @workgroup_size(1, 1, 1)
    fn main() {
        switch (1u) {
            case signedGlobalConst: {
                break;
            }
        }
    }
    ```

    Observe the following error message:

    ```
        Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.26s
         Running `target\debug\naga.exe ../in.wgsl`
    Could not parse WGSL:
    error: invalid switch value
      ┌─ ../in.wgsl:6:14
      │
    6 │         case signedGlobalConst: {
      │              ^^^^^^^^^^^^^^^^^ expected unsigned integer
      │
      = note: suffix the integer with a `u`: `signedGlobalConstu`
    
    
    error: process didn't exit successfully: `target\debug\naga.exe ../in.wgsl` (exit code: 1)
    ```

For an applied example in Firefox Nightly (latest build as of 2025-02-25) as a consumer of WGPU, we run into this at <https://webgpu.github.io/webgpu-samples/?sample=normalMap>:

```
18:29:36.993
WebGPU compilation info for shader module "NormalMappingRender.fragmentShader" (1 error(s), 0 warning(s), 0 info)
18:29:36.993

Shader 'NormalMappingRender.fragmentShader' parsing error: invalid switch value
   ┌─ wgsl:82:10
   │
82 │     case modeParallaxScale: {
   │          ^^^^^^^^^^^^^^^^^ expected unsigned integer
   │
   = note: suffix the integer with a `u`: `modeParallaxScaleu`
```

**Expected vs observed behavior**

I would instead expect that this code Just Works™, since official WebGPU examples obviously expect it to.

### PR DESCRIPTION
**Pull request by jamienicol**
**Connections**
Fixes #7225

Impacts #7226

**Description**
When lowering switch statements we weren't handling abstract types at all - we were simply concretizing them to i32. This PR makes us handle them correctly - find the (possibly abstract) type of the switch selector and all case selectors, find a consensus type they can be converted to, then attempt to convert them all to to that type. (concretizing to i32 if they are all abstract).

I've reworked the error handling slightly, differentiating between an invalid switch selector type (must be an int scalar), an invalid case expression (must be an int scalar constexpr), and a type mismatch between cases and the selector.

Note that this removed the note about adding/removing the `u` suffix, which we have #7226 filed about. We can keep that ticket open to potentially reinstate something similar. But for now I think it's better with no note at all rather than the misleading one. Especially as allowing abstract case expressions should greatly reduce the occurrence of this error in the first place: we will now accept shaders where the selector is a u32 and the case values are abstract.

**Testing**
Ran tests. Added new snapshot tests for code that should parse, and new wgsl_errors tests for code that should be rejected.

**Squash or Rebase?**

Surprise me

**Checklist**

- [x] Run `cargo fmt`.
~- [ ] Run `taplo format`.~
- [x] Run `cargo clippy`. If applicable, add:
  ~- [ ] `--target wasm32-unknown-unknown`~
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -1621,30 +1621,76 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
-                                        self.expression(expr, &mut ctx.as_global().as_const())?;
-                                    match ctx.module.to_ctx().eval_expr_to_literal(expr) {
-                                        Some(crate::Literal::I32(value)) if !uint => {
+                                    let expr = exprs.next().expect(
+                                        "Should yield expression for each SwitchValue::Expr case",
+                                    );
+                                    match ctx
+                                        .module
+                                        .to_ctx()
+                                        .eval_expr_to_literal_from(expr, &ctx.function.expressions)
```
Comment (sagudev) [inline naga/src/front/wgsl/lower/mod.rs:1693]: This also makes local const work in switch ❤️.

File: naga/src/front/wgsl/error.rs [hunk 2]
```diff
@@ -763,26 +768,32 @@ impl<'a> Error<'a> {
...
+            },
+            Error::SwitchCaseTypeMismatch { span } => ParseError {
+                message: "invalid switch case selector value".to_string(),
+                labels: vec![(
+                    span,
+                    "switch case selector must have the same type as the switch selector expression"
+                    .into(),
+                )],
+                notes: vec![],
             },
```
Comment (ErichDonGubler) [inline naga/src/front/wgsl/error.rs]: issue(non-blocking): As follow-up, we need to tell users _what_ the mismatched types are.

File: naga/src/front/wgsl/error.rs [hunk 3]
```diff
@@ -763,26 +768,32 @@ impl<'a> Error<'a> {
...
+                message: "invalid switch case value".to_string(),
+                labels: vec![(
+                    span,
+                    "switch case selector must be a scalar integer const expression"
+                    .into(),
+                )],
+                notes: vec![],
+            },
+            Error::SwitchCaseTypeMismatch { span } => ParseError {
+                message: "invalid switch case selector value".to_string(),
```
Comment (ErichDonGubler) [inline naga/src/front/wgsl/error.rs]: style: `` `switch` `` (with backticks) plz? 🥺

File: naga/src/front/wgsl/lower/mod.rs [hunk 4]
```diff
@@ -1621,30 +1621,76 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
+                                | crate::Scalar::U32
+                                | crate::Scalar::ABSTRACT_INT,
+                            ) => Ok((expr, span)),
+                            _ => match i {
+                                0 => Err(Error::InvalidSwitchSelector { span }),
+                                _ => Err(Error::InvalidSwitchCase { span }),
+                            },
+                        }
+                    })
+                    .collect::<Result<(Vec<_>, Vec<_>), _>>()?;
```
Comment (ErichDonGubler) [inline naga/src/front/wgsl/lower/mod.rs]: thought: The selection of the error case to remove seems like something we could capture with structure and a closure, rather. But…after trying the refactor locally, I'm not sure the code is substantially better:

```suggestion
                let helper = |expr| -> Result<_, Error<'source>> {
                    let span = ectx.ast_expressions.get_span(expr);
                    let expr = self.expression_for_abstract(expr, &mut ectx)?;
                    let ty = resolve_inner!(ectx, expr);
                    match *ty {
                        crate::TypeInner::Scalar(
                            crate::Scalar::I32 | crate::Scalar::U32 | crate::Scalar::ABSTRACT_INT,
                        ) => Ok(Ok((expr, span))),
                        _ => Ok(Err(span)),
                    }
                };
                let selector =
                    helper(selector)?.map_err(|span| Error::InvalidSwitchSelector { span })?;
                let cases = cases
                    .iter()
                    .filter_map(|case| match case.value {
                        ast::SwitchValue::Expr(expr) => Some(expr),
                        ast::SwitchValue::Default => None,
                    })
                    .map(|case| {
                        helper(case)?.map_err(|span| Error::InvalidSwitchSelector { span })
                    });
                std::iter::once(Ok(selector))
                    .chain(cases)
                    .collect::<Result<(Vec<_>, Vec<_>), _>>()?;
```


…especially because there's some code below that usefully consumes the set of them as a single iterable list and produces an index for diagnostics against that list.

**Review by ErichDonGubler — APPROVED** [review]
LGTM! Some diagnostic nitpicks, and that's it. 🙂 Excited to get this in.

File: naga/src/front/wgsl/error.rs (hunk 2 above)
Comment (jamienicol) [reply naga/src/front/wgsl/error.rs]: Yes this would be good. Agreed it's best suited as a follow up, as it's not as easy as you might think, to do it well at least. You might want to show the span of the incorrect case, and show correct type, and additionally the span indicating where the correct type came from. But if the `n`th case statement has the incorrect type, the correct type might be implied by the `n-1`th case statement. It wouldn't be as simple as showing the span of the selector, as that might be abstract.

File: naga/src/front/wgsl/lower/mod.rs (hunk 4 above)
Comment (jamienicol) [reply naga/src/front/wgsl/lower/mod.rs]: There either has to be a _"match `i`. if zero we're talking about the selector, else we're a case"_ block as written in the code here, or as you allude to when handling the error case of `automatic_conversion_consensus()` just below here.

I actually initially had it the way round you've suggested, but think I prefer it the way the PR currently has it

File: naga/src/front/wgsl/error.rs (hunk 3 above)
Comment (jamienicol) [reply naga/src/front/wgsl/error.rs]: done

File: naga/src/front/wgsl/error.rs (hunk 2 above)
Comment (ErichDonGubler) [reply naga/src/front/wgsl/error.rs]: Yep, that sounds similar to the domain of `match` statement arm type mismatches in Rust. Whee!

Comment (ErichDonGubler) [reply naga/src/front/wgsl/error.rs]: Filed <https://github.com/gfx-rs/wgpu/issues/7293>.
