### PR TITLE
Do texture init via clear passes when possible

### LINKED ISSUE #2149: WebGL2: panicked at 'Tex storage 2D multisample is not supported'
**Description**
When using wgpu master with WebGL2 and MSAA I'm getting: `panicked at 'Tex storage 2D multisample is not supported', C:\Users\super\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.11.0\src\web_sys.rs:2168:9`

**Repro steps**

See the attached zip of a wasm WebGL2 demo. Unpack, serve, browse, see panic.

**Expected vs observed behavior**
Expected: no panic. Observed: panic in both Chrome and Firefox. :)

**Extra materials**
[webgl2-multisample-panic.zip](https://github.com/gfx-rs/wgpu/files/7461193/webgl2-multisample-panic.zip)

**Platform**
wgpu master @ ca7ca749cdb2b5d88512be2b1ec4e44f5a88dfe0, WebGL2, Windows 10

### PR DESCRIPTION
**Pull request by Wumpf**
**Connections**
Should fix #2149 - haven't confirmed since I don't a repro at hand.
Changes clear extension semantics a bit as discussed on #2174

**Description**
Previously, render target/depth textures couldn't be initialized at all if they not also were COPY_DST, violating the spec.
Now, we always will use render passes when possible since it's expected to be faster.

All this comes with an overhaul of the texture clearing mechanisms as we tried to optimize things based on the assumption of texture-init == copy zero_buffer:
* Textures now know their `TextureClearMode` which may bring with it pre-created render views for clearing
* I consolidated all texture clears to go through more similar code paths. In some cases this trades performance against maintainability of the code, but imho it looks like a better starting point for optimizations now

Other smaller but important things in this PR:
* Rename CLEAR_COMMANDS to CLEAR_TEXTURE and change semantics a bit (see doc changes)
* creation of 3D depth texture will cause an error now, see also https://github.com/gpuweb/gpuweb/issues/2304

**Testing**
Tests in tests/clear_texture.rs clear now depth/stencil formats as well (this was not possible previously)
Ran `cargo test` locally (win10)

### CODE REVIEW

File: wgpu/src/lib.rs [hunk 1]
```diff
@@ -2388,12 +2388,16 @@ impl CommandEncoder {
 
     /// Clears texture to zero.
     ///
-    /// Where possible it may be significantly more efficient to perform clears via render passes!
+    /// Note that unlike with clear_buffer, `COPY_DST` usage is not required.
+    ///
+    /// # Implementation notes
```
Comment (kvark) [inline wgpu/src/lib.rs:2393]: nice to see these comments!

File: wgpu-core/src/command/clear.rs [hunk 2]
```diff
@@ -66,6 +60,12 @@ whereas subesource range specified start {subresource_base_array_layer} and coun
         subresource_base_array_layer: u32,
         subresource_array_layer_count: Option<NonZeroU32>,
     },
+    #[error("failed to create view for clearing texture {texture:?} at mip level {mip_level}, layer {layer}")]
+    FailedToCreateTextureViewForClear {
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs]: what are the possible reasons we could fail to create this view?

File: wgpu-core/src/command/clear.rs [hunk 3]
```diff
@@ -228,6 +220,23 @@ impl<G: GlobalIdentityHandlerFactory> Global<G> {
             });
         }
 
+        let clear_usage = if dst_texture
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs]: could be refactored slightly nicer with a list
```rust
const POSSIBLE_CLEAR_USAGES: &[hal::TextureUses] = [...];
let clear_usage = POSSIBLE_CLEAR_USAGES.iter().find(|&usage| dst_texture.hal_usage.contains(usage)).expect("...");
```

File: wgpu-core/src/command/clear.rs [hunk 4]
```diff
@@ -228,6 +220,23 @@ impl<G: GlobalIdentityHandlerFactory> Global<G> {
...
+            hal::TextureUses::DEPTH_STENCIL_WRITE
+        } else if dst_texture
+            .hal_usage
+            .contains(hal::TextureUses::COLOR_TARGET)
+        {
+            hal::TextureUses::COLOR_TARGET
+        } else if dst_texture.hal_usage.contains(hal::TextureUses::COPY_DST) {
+            hal::TextureUses::COPY_DST
+        } else {
+            panic!("Every texture must at least have one of hal::TextureUses::DEPTH_STENCIL_WRITE/COLOR_TARGET/COPY_DST.
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs]: The message here is not making it clear whose fault this is. I believe it's the fault of wgpu-core, since it controls how textures are created. So it's more like `unreachable!` here than a panic, although the panic is better if zero-initialization becomes optional. Anyway, if we refactor this into `expect()` like I suggested we can have a slightly better message.

File: wgpu-core/src/command/clear.rs [hunk 5]
```diff
@@ -5,24 +5,25 @@ use crate::device::trace::Command as TraceCommand;
...
     align_to,
     command::CommandBuffer,
+    device::Device,
     get_lowest_common_denom,
-    hub::{Global, GlobalIdentityHandlerFactory, HalApi, Token},
-    id::{BufferId, CommandEncoderId, DeviceId, TextureId},
-    init_tracker::MemoryInitKind,
-    track::TextureSelector,
+    hub::{Global, GlobalIdentityHandlerFactory, HalApi, Resource, Token},
+    id::{self, BufferId, CommandEncoderId, DeviceId, TextureId},
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs:11]: nit: if you are including `id`, then just write full path to the ids, i.e .`id::BufferId` everywhere.
this is how I was writing the rest of the code anyway. When there is only 1 or 2 things included, may include them directly. If more - just use the submodule qualified path.

**Comment by Wumpf** [comment]
there's apparently some DX12 test failures during tests that I need to look into

File: wgpu-core/src/command/clear.rs [hunk 6]
```diff
@@ -228,68 +221,126 @@ impl<G: GlobalIdentityHandlerFactory> Global<G> {
...
+    let dst_raw = dst_texture
+        .inner
+        .as_raw()
+        .ok_or(ClearError::InvalidTexture(dst_texture_id.value.0))?;
+
+    // Issue the right barrier.
+    let clear_usage = match dst_texture.clear_mode {
+        TextureClearMode::BufferCopy => hal::TextureUses::COPY_DST,
+        TextureClearMode::RenderPass(_) => {
+            if dst_texture
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs:278]: this may be a little be tricky in the future. Imagine a case where the texture is created in such a way that it has a depth format but can be reinterpret into R32F and rendered into. In this case, the texture itself may have both `COLOR_TARGET` and `DEPTH_STENCIL_WRITE` usages. We don't necessarily need to address this right here, since we don't know if the time will come for this to be possible.

Would it make sense to put that usage bit into `TextureClearMode::RenderPass`? Like `is_color: bool` or something like that.

File: wgpu-core/src/command/clear.rs [hunk 7]
```diff
@@ -305,23 +356,23 @@ pub(crate) fn collect_zero_buffer_copies_for_clear_texture(
         let max_rows_per_copy = max_rows_per_copy / format_desc.block_dimensions.1 as u32
             * format_desc.block_dimensions.1 as u32;
         assert!(max_rows_per_copy > 0, "Zero buffer size is too small to fill a single row of a texture with format {:?} and desc {:?}",
-                        texture_desc.format, texture_desc.size);
+                            texture_desc.format, texture_desc.size);
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs:359]: cargo fmt is needed?

File: wgpu-core/src/command/clear.rs [hunk 8]
```diff
@@ -349,4 +400,70 @@ pub(crate) fn collect_zero_buffer_copies_for_clear_texture(
...
+fn clear_texture_via_render_passes<A: hal::Api>(
+    dst_texture: &Texture<A>,
+    range: TextureInitRange,
+    clear_usage: hal::TextureUses,
+    encoder: &mut A::CommandEncoder,
+) -> Result<(), ClearError> {
+    let extent_base = wgt::Extent3d {
+        width: dst_texture.desc.size.width,
+        height: dst_texture.desc.size.height,
+        depth_or_array_layers: 1, // TODO: What about 3d textures? Only one slice a time, sure but how to select it?
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs:418]: the same way it's selected for 2D array textures

File: wgpu-core/src/command/clear.rs [hunk 9]
```diff
@@ -349,4 +400,70 @@ pub(crate) fn collect_zero_buffer_copies_for_clear_texture(
...
+        let extent = extent_base.mip_level_size(mip_level, is_3d_texture);
+        for layer in range.layer_range.clone() {
+            let target = hal::Attachment {
+                view: dst_texture.get_clear_view(mip_level, layer),
+                usage: clear_usage,
+            };
+
+            if clear_usage == hal::TextureUses::DEPTH_STENCIL_WRITE {
+                unsafe {
+                    encoder.begin_render_pass(&hal::RenderPassDescriptor {
```
Comment (kvark) [inline wgpu-core/src/command/clear.rs:432]: nit: we could probably merge those branches a little closer, i.e.
`let (color_attachments, depth-stencil_attachment) = if ... else ...;`

File: wgpu-core/src/command/clear.rs (hunk 2 above)
Comment (Wumpf) [reply wgpu-core/src/command/clear.rs]: whatever reason there was, it's gone now. Removing this value again

File: wgpu-core/src/command/memory_init.rs [hunk 10]
```diff
@@ -285,73 +261,36 @@ impl<A: hal::Api> BakedCommands<A> {
...
                 }
             }
+
+            // TODO: Could we attempt some range collapsing here?
+            for range in ranges.drain(..) {
+                clear_texture(
+                    &texture_use.id,
+                    &*texture,
+                    range,
+                    &mut self.encoder,
```
Comment (kvark) [inline wgpu-core/src/command/memory_init.rs:281]: given how the encoder is always passed mutably to clear texture, and that it's effectively an operation being encoded, like many other, would it make sense to put it as a method? i.e. `self.encoder.clear_texture(...)`. No strong preference here, just throwing unsolicited ideas around :)

File: wgpu-core/src/command/mod.rs [hunk 11]
```diff
@@ -9,8 +9,8 @@ mod render;
 mod transfer;
 
 pub use self::bundle::*;
-pub(crate) use self::clear::collect_zero_buffer_copies_for_clear_texture;
-pub use self::clear::ClearError;
+pub(crate) use self::clear::clear_texture_no_device;
+pub(crate) use self::clear::ClearError;
```
Comment (kvark) [inline wgpu-core/src/command/mod.rs:13]: lets merge these pub use statements per crate. I.e. `pub use self::{...};` or at least the 2 for clear :)

File: wgpu-core/src/command/render.rs [hunk 12]
```diff
@@ -568,7 +568,7 @@ impl<'a, A: HalApi> RenderPassInfo<'a, A> {
         if channel.load_op == LoadOp::Load {
             pending_discard_init_fixups.extend(texture_memory_actions.register_init_action(
                 &TextureInitTrackerAction {
-                    id: view.parent_id.value.0,
+                    id: view.parent_id.clone(),
```
Comment (kvark) [inline wgpu-core/src/command/render.rs:571]: So we are now copying the refcount in here. Is that a perf tradeoff you mentioned?

File: wgpu-core/src/command/transfer.rs [hunk 13]
```diff
@@ -1,18 +1,16 @@
...
-        collect_zero_buffer_copies_for_clear_texture, memory_init::fixup_discarded_surfaces,
-        CommandBuffer, CommandEncoderError,
-    },
+    command::{CommandBuffer, CommandEncoderError},
     conv,
     device::Device,
     error::{ErrorFormatter, PrettyError},
     hub::{Global, GlobalIdentityHandlerFactory, HalApi, Storage, Token},
-    id::{BufferId, CommandEncoderId, TextureId},
+    id::{self, BufferId, CommandEncoderId, TextureId},
```
Comment (kvark) [inline wgpu-core/src/command/transfer.rs:9]: similar nit about including `self`

File: wgpu-core/src/device/mod.rs [hunk 14]
```diff
@@ -677,13 +694,60 @@ impl<A: HalApi> Device<A> {
...
+        {
+            let usage = if desc.format.describe().sample_type == wgt::TextureSampleType::Depth {
+                hal::TextureUses::DEPTH_STENCIL_WRITE
+            } else {
+                hal::TextureUses::COLOR_TARGET
+            };
+            let dimension = match desc.dimension {
+                wgt::TextureDimension::D1 => wgt::TextureViewDimension::D1,
+                wgt::TextureDimension::D2 => wgt::TextureViewDimension::D2,
+                wgt::TextureDimension::D3 => wgt::TextureViewDimension::D2, // Todo? Is this even specified?
```
Comment (kvark) [inline wgpu-core/src/device/mod.rs:714]: I vaguely remember that not all Metal allows this. So WebGPU baseline probably forbids creation of such things at the API level. That doesn't mean we can't do it internally, but Metal may require a bit more specific code here. Let's defer to follow-ups and talk about this separately.

Ah, also, I think we are mostly agreeing with the group to make 3D textures non-renderable. So there is that :)

**Review by kvark — COMMENTED** [review]
Skimmed to the first half, a lot more to go!

File: wgpu-core/src/command/clear.rs (hunk 5 above)
Comment (Wumpf) [reply wgpu-core/src/command/clear.rs:11]: reason `self` gets into the mix is `id::Valid()`. Wouldn't mind replacing all the ids here with `id::ThingId`, but that would make this diff a bit messy

File: wgpu-core/src/command/clear.rs (hunk 7 above)
Comment (Wumpf) [reply wgpu-core/src/command/clear.rs:359]: cargo fmt doesn't seem to have an opinion on this oddly enough, must be a bug

File: wgpu-core/src/command/clear.rs (hunk 3 above)
Comment (Wumpf) [reply wgpu-core/src/command/clear.rs]: not applicable as final version first splits over clear-by-copy and clear-by-pass, making this a distinction between DEPTH_STENCIL_WRITE/COLOR_TARGET only

File: wgpu-core/src/command/clear.rs (hunk 6 above)
Comment (Wumpf) [reply wgpu-core/src/command/clear.rs:278]: I do like the idea of putting it on the clear_mode, makes this piece and one below more concise; going with that right away

File: wgpu-core/src/command/render.rs (hunk 12 above)
Comment (Wumpf) [reply wgpu-core/src/command/render.rs:571]: that is sure one issue, but I was mostly thinking about how setting up barriers no longer collapses (before we had less `cmd_buf_raw.transition_textures` calls) and how we resolve the texture from TextureId now in several places. Both is most prominent in `transfer.rs`

File: wgpu-core/src/command/clear.rs (hunk 9 above)
Comment (Wumpf) [reply wgpu-core/src/command/clear.rs:432]: I think I already tried this back when I wrote this because the problem I'm getting now again looks awfully familiar: It's not easily possible since the color attachment array has variable length!

```
            let (color_attachments, depth_stencil_attachment) = if is_color {
                (
                    [hal::ColorAttachment {
                        target: hal::Attachment {
                            view: dst_texture.get_clear_view(mip_level, layer),
                            usage: hal::TextureUses::COLOR_TARGET,
                        },
                        resolve_target: None,
                        ops: hal::AttachmentOps::STORE,
                        clear_value: wgt::Color::TRANSPARENT,
                    }],
                    None,
                )
            } else {
                (
                    [],
                    Some(hal::DepthStencilAttachment {
                        target: hal::Attachment {
                            view: dst_texture.get_clear_view(mip_level, layer),
                            usage: hal::TextureUses::DEPTH_STENCIL_WRITE,
                        },
                        depth_ops: hal::AttachmentOps::STORE,
                        stencil_ops: hal::AttachmentOps::STORE,
                        clear_value: (0.0, 0),
                    }),
                )
            };
```

Comment (kvark) [reply wgpu-core/src/command/clear.rs:420]: You can always work around this by moving a variable up:
```rust
let color_attachments_tmp;
let (color_attachments, depth_stencil_attachment) = if is_color {
  color_attachments_tmp = [hal::ColorAttachment {
                        target: hal::Attachment {
                            view: dst_texture.get_clear_view(mip_level, layer),
                            usage: hal::TextureUses::COLOR_TARGET,
                        },
                        resolve_target: None,
                        ops: hal::AttachmentOps::STORE,
                        clear_value: wgt::Color::TRANSPARENT,
                    }];
                (
                    &color_attachments_tmp[..],
                    None,
                )
            } else {
                (
                    &[][..],
                    Some(hal::DepthStencilAttachment {
                        target: hal::Attachment {
                            view: dst_texture.get_clear_view(mip_level, layer),
                            usage: hal::TextureUses::DEPTH_STENCIL_WRITE,
                        },
                        depth_ops: hal::AttachmentOps::STORE,
                        stencil_ops: hal::AttachmentOps::STORE,
                        clear_value: (0.0, 0),
                    }),
                )
            };
```

File: wgpu-core/src/command/memory_init.rs [hunk 15]
```diff
@@ -3,23 +3,22 @@ use std::{collections::hash_map::Entry, ops::Range, vec::Drain};
...
 
-use super::{BakedCommands, DestroyedBufferError, DestroyedTextureError};
+use super::{clear::clear_texture, BakedCommands, DestroyedBufferError, DestroyedTextureError};
 
 /// Surface that was discarded by `StoreOp::Discard` of a preceding renderpass.
 /// Any read access to this surface needs to be preceded by a texture initialization.
 #[derive(Clone)]
 pub(crate) struct TextureSurfaceDiscard {
-    pub texture: TextureId,
+    pub texture: Stored<TextureId>,
```
Comment (kvark) [inline wgpu-core/src/command/memory_init.rs:21]: where is this refcount used?

File: wgpu-core/src/command/memory_init.rs [hunk 16]
```diff
@@ -285,73 +261,36 @@ impl<A: hal::Api> BakedCommands<A> {
                     }
                 }
                 MemoryInitKind::NeedsInitializedMemory => {
-                    ranges.clear();
                     for (mip_level, mip_tracker) in affected_mip_trackers {
-                        for layer_range in mip_tracker.drain(use_range.layer_range.clone()) {
-                            ranges.push(TextureInitRange {
-                                mip_range: mip_level as u32..(mip_level as u32 + 1),
+                        ranges.extend(mip_tracker.drain(use_range.layer_range.clone()).map(
```
Comment (kvark) [inline wgpu-core/src/command/memory_init.rs:265]: Extensive use of functional chaining, like we are doing here, becomes an obstruction to reading and debugging the code. In this case, `extend()` doesn't really give us anything practical. But stepping through the loop would be nice.

File: wgpu-core/src/command/transfer.rs [hunk 17]
```diff
@@ -374,60 +376,110 @@ pub(crate) fn validate_texture_copy_range(
...
+    copy_size: &Extent3d,
+    texture_guard: &Storage<Texture<A>, TextureId>,
+) -> Result<(), TransferError> {
+    let texture = texture_guard
+        .get(destination.texture)
+        .map_err(|_| TransferError::InvalidTexture(destination.texture))?;
+
+    // Attention: If we don't write full texture subresources, we need to a full clear first since we don't track subrects.
+    // This means that in rare cases even a *destination* texture of a transfer may need an immediate texture init.
+    let dst_init_kind = if copy_size.width == texture.desc.size.width
```
Comment (kvark) [inline wgpu-core/src/command/transfer.rs:465]: This check is incorrect, it doesn't take into account the mip level size. Instead, it should use `texture.desc.mip_level_size(destination.mip_level)`

File: wgpu-core/src/device/mod.rs [hunk 18]
```diff
@@ -634,9 +636,24 @@ impl<A: HalApi> Device<A> {
...
+        }
+
+        // Enforce having COPY_DST/DEPTH_STENCIL_WRIT/COLOR_TARGET otherwise we wouldn't be able to initialize the texture.
+        let hal_usage = conv::map_texture_usage(desc.usage, desc.format.into())
+            | if format_desc.sample_type == wgt::TextureSampleType::Depth {
+                hal::TextureUses::DEPTH_STENCIL_WRITE
+            } else if desc.sample_count > 1 {
+                hal::TextureUses::COLOR_TARGET
+            } else {
+                hal::TextureUses::COPY_DST
```
Comment (kvark) [inline wgpu-core/src/device/mod.rs:655]: I think we need to change this. We don't want to add COPY_DST usage if the user didn't request it, since it may slow down the other operations on the texture. Therefore, this should look like:
```rust
} else if desc.usage.contains(wgt::TextureUsage::COPY_DST) {
  hal::TextureUses::COPY_DST
} else {
  hal::TextureUses::COLOR_TARGET
}
```

I don't even think this needs to check for MSAA, since MSAA textures shouldn't support COPY_DST at all.

File: wgpu-core/src/device/mod.rs [hunk 19]
```diff
@@ -677,13 +694,64 @@ impl<A: HalApi> Device<A> {
...
 
-        let raw = unsafe {
+        let raw_texture = unsafe {
             self.raw
                 .create_texture(&hal_desc)
                 .map_err(DeviceError::from)?
         };
 
-        let mut texture = self.create_texture_from_hal(raw, self_id, desc, format_features);
+        let clear_mode = if hal_usage.contains(hal::TextureUses::DEPTH_STENCIL_WRITE)
```
Comment (kvark) [inline wgpu-core/src/device/mod.rs:703]: `hal_usage.intersects(A | B)`

File: wgpu-core/src/device/mod.rs [hunk 20]
```diff
@@ -677,13 +694,64 @@ impl<A: HalApi> Device<A> {
...
+
+            let mut clear_views = SmallVec::new();
+            for layer in 0..desc.size.depth_or_array_layers {
+                for mip_level in 0..desc.mip_level_count {
+                    unsafe {
+                        clear_views.push(
+                            self.raw
+                                .create_texture_view(
+                                    &raw_texture,
+                                    &hal::TextureViewDescriptor {
```
Comment (kvark) [inline wgpu-core/src/device/mod.rs:726]: nit: can we move the creation of this descriptor out of `unsafe`? the less code in unsafe the better

File: wgpu-core/src/device/queue.rs [hunk 21]
```diff
@@ -418,7 +425,53 @@ impl<G: GlobalIdentityHandlerFactory> Global<G> {
...
+        // If the copy does not fully cover the layers, we need to initialize to zero *first* as we don't keep track of partial texture layer inits.
+        // Strictly speaking we only need to clear the areas of a layer untouched, but this would get increasingly messy.
+
+        let init_layer_range =
+            destination.origin.z..destination.origin.z + size.depth_or_array_layers;
+        if dst.initialization_status.mips[destination.mip_level as usize]
+            .check(init_layer_range.clone())
+            .is_some()
+        {
+            if size.width != dst.desc.size.width || size.height != dst.desc.size.height {
```
Comment (kvark) [inline wgpu-core/src/device/queue.rs:447]: similarly here we need to consider the size of the mipmap level, not the whole texture

**Review by kvark — CHANGES_REQUESTED** [review]
almost there!

File: wgpu-core/src/command/clear.rs (hunk 9 above)
Comment (Wumpf) [reply wgpu-core/src/command/clear.rs:420]: thx, makes sense! 👍

File: wgpu-core/src/command/memory_init.rs (hunk 15 above)
Comment (Wumpf) [reply wgpu-core/src/command/memory_init.rs]: while trying to elaborate why this is needed for the barrier in clear_texture_no_device I was able to remove it again :)
A tad bit messy though, see comment here https://github.com/Wumpf/wgpu/commit/5073b93b45d8e68b0e6f61a4e257a53591cb6257#diff-0935c4873f626097404cc18bab07ee4833b98c9fb868f1f30cce86d053b005bbR285-R290

File: wgpu-core/src/device/mod.rs (hunk 18 above)
Comment (Wumpf) [reply wgpu-core/src/device/mod.rs:655]: agreed, we should always use COLOR_TARGET over COPY_DST, but in any case where a user creates a texture that can not get COLOR_TARGET, we still need to enforce COPY_DST.
This would happen either when user intends to write via STORAGE or by error (or ofc banking on us not doing zero-init and trying to read uninitialized memory ;))

Comment (Wumpf) [reply wgpu-core/src/device/mod.rs:655]: this now made the volume textures in the clear_texture tests being cleared by via render target, making all sort of bugs visible now. Not the first time this test saved me, feels like we need more tests that grind through all permutations of a thing :)

**Review by kvark — APPROVED** [review]
please take care of CI failures

**Comment by niklaskorz** [comment]
Running this on https://github.com/niklaskorz/linon/tree/wgpu-0.12 gives me the following error instead of the current "Texture needs to have the COPY_DST flag":

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoValidTextureClearMode((5, 1, Metal))', /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu-core/src/command/memory_init.rs:284:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-12-27T12:24:28Z ERROR wgpu_hal::metal::device] No active command buffers for fence value 2
thread 'main' panicked at 'Error in Device::drop: parent device is lost', /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu/src/backend/direct.rs:214:9
[2021-12-27T12:24:28Z ERROR wgpu_hal::metal::device] No active command buffers for fence value 2
[2021-12-27T12:24:28Z ERROR wgpu_core::device] failed to wait for the device: Lost
```

<details>
  <summary>full stack trace</summary>
  
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoValidTextureClearMode((5, 1, Metal))', /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu-core/src/command/memory_init.rs:284:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: wgpu_core::command::memory_init::<impl wgpu_core::command::BakedCommands<A>>::initialize_texture_memory
             at /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu-core/src/command/memory_init.rs:276:17
   5: wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::queue_submit
             at /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu-core/src/device/queue.rs:785:25
   6: <wgpu::backend::direct::Context as wgpu::Context>::queue_submit
             at /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu/src/backend/direct.rs:2162:15
   7: wgpu::Queue::submit
             at /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu/src/lib.rs:3206:9
   8: linon::application::Application::render
             at ./src/application.rs:573:9
   9: linon::run::{{closure}}::{{closure}}
             at ./src/main.rs:111:33
  10: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/app_state.rs:101:13
  11: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/app_state.rs:79:13
  12: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/app_state.rs:100:9
  13: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/app_state.rs:206:21
  14: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/app_state.rs:389:13
  15: winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/observer.rs:180:21
  16: winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/observer.rs:142:57
  17: std::panicking::try::do_call
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  18: <unknown>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:312:14
  19: std::panicking::try
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  20: std::panic::catch_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  21: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/event_loop.rs:229:11
  22: winit::platform_impl::platform::observer::control_flow_handler
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/observer.rs:142:5
  23: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/observer.rs:175:9
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <() as objc::message::MessageArguments>::invoke
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  35: objc::message::platform::send_unverified
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  36: objc::message::send_message
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  37: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/event_loop.rs:188:22
  38: objc::rc::autorelease::autoreleasepool
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/rc/autorelease.rs:29:5
  39: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/event_loop.rs:178:9
  40: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/event_loop.rs:157:9
  41: winit::event_loop::EventLoop<T>::run
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/event_loop.rs:154:9
  42: linon::run::{{closure}}
             at ./src/main.rs:57:5
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  44: futures_executor::local_pool::block_on::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:315:23
  45: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:90:37
  46: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  47: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  48: futures_executor::local_pool::run_executor
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:86:5
  49: futures_executor::local_pool::block_on
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:315:5
  50: linon::main
             at ./src/main.rs:193:5
  51: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-12-27T12:26:55Z ERROR wgpu_hal::metal::device] No active command buffers for fence value 2
thread 'main' panicked at 'Error in Device::drop: parent device is lost', /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu/src/backend/direct.rs:214:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu/src/backend/direct.rs:214:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::device_drop
             at /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu/src/backend/direct.rs:1536:29
   4: <wgpu::Device as core::ops::drop::Drop>::drop
             at /Users/niklaskorz/.cargo/git/checkouts/wgpu-de6245268e4c8054/dc24f94/wgpu/src/lib.rs:1926:13
   5: core::ptr::drop_in_place<wgpu::Device>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
   6: core::ptr::drop_in_place<linon::application::Application>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
   7: core::ptr::drop_in_place<linon::run::{{closure}}::{{closure}}>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
   8: core::ptr::drop_in_place<core::cell::UnsafeCell<dyn core::ops::function::FnMut<(winit::event::Event<()>,&winit::event_loop::EventLoopWindowTarget<()>,&mut winit::event_loop::ControlFlow)>+Output = ()>>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
   9: core::ptr::drop_in_place<core::cell::RefCell<dyn core::ops::function::FnMut<(winit::event::Event<()>,&winit::event_loop::EventLoopWindowTarget<()>,&mut winit::event_loop::ControlFlow)>+Output = ()>>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
  10: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/rc.rs:1450:17
  11: core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<dyn core::ops::function::FnMut<(winit::event::Event<()>,&winit::event_loop::EventLoopWindowTarget<()>,&mut winit::event_loop::ControlFlow)>+Output = ()>>>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
  12: core::ptr::drop_in_place<core::option::Option<alloc::rc::Rc<core::cell::RefCell<dyn core::ops::function::FnMut<(winit::event::Event<()>,&winit::event_loop::EventLoopWindowTarget<()>,&mut winit::event_loop::ControlFlow)>+Output = ()>>>>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
  13: core::mem::drop
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/mem/mod.rs:898:24
  14: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/event_loop.rs:191:17
  15: objc::rc::autorelease::autoreleasepool
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/rc/autorelease.rs:29:5
  16: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/event_loop.rs:178:9
  17: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/macos/event_loop.rs:157:9
  18: winit::event_loop::EventLoop<T>::run
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/event_loop.rs:154:9
  19: linon::run::{{closure}}
             at ./src/main.rs:57:5
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  21: futures_executor::local_pool::block_on::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:315:23
  22: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:90:37
  23: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  24: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  25: futures_executor::local_pool::run_executor
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:86:5
  26: futures_executor::local_pool::block_on
             at /Users/niklaskorz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.17/src/local_pool.rs:315:5
  27: linon::main
             at ./src/main.rs:193:5
  28: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-12-27T12:26:55Z ERROR wgpu_hal::metal::device] No active command buffers for fence value 2
[2021-12-27T12:26:55Z ERROR wgpu_core::device] failed to wait for the device: Lost
```
</details>

**Comment by kvark** [comment]
@niklaskorz looks like this will be addressed by the very PR we are commenting on

**Comment by niklaskorz** [comment]
> @niklaskorz looks like this will be addressed by the very PR we are commenting on

That's what I was hoping :) The error I posted occurs when using this PR as wgpu crate, which is why I thought it relevant for the discussion here.

**Comment by Wumpf** [comment]
@niklaskorz reproed it and looking for a solution, I think I know what to do but looking for a nice way to add a test for this in wgpu. Meanwhile, you can fix/workaround this in your application by passing a clear color to egui in your application:
```
diff --git a/src/application.rs b/src/application.rs
index 9c3e96f..e380a94 100644
--- a/src/application.rs
+++ b/src/application.rs
@@ -567,7 +567,13 @@ impl Application {
             .update_buffers(&self.device, &self.queue, &paint_jobs, &screen_descriptor);

         self.rpass
-            .execute(&mut encoder, &view, &paint_jobs, &screen_descriptor, None)
+            .execute(
+                &mut encoder,
+                &view,
+                &paint_jobs,
+                &screen_descriptor,
+                Some(wgpu::Color::WHITE),
+            )
             .unwrap();

         self.queue.submit(Some(encoder.finish()));
```


@kvark please hold on with merging until I have this done as well. Meanwhile, you may want to complain about 
087145b which is needed to get Metal tests green pretty much like you anticipated in an earlier comment ;)

**Comment by Wumpf** [comment]
all done in f80a13d . Not pretty: For testing I needed to hijack an existing example so I didn't need to go through all the window creation stuff. Destruction of the new clear target every surface has is in two places and I'm actually not sure why this is ok to do it there (expecting it to be still in use, but neither DX12/Vulkan complain about this even under resize which causes discarded surfaces)

**Review by kvark — APPROVED** [review]
Thank you, LGTM, such grand piece!

**Comment by kvark** [comment]
#2327 is published in wgpu-core-0.12.1
