### PR TITLE
[msl-out] Fix `ReadZeroSkipWrite` bounds check mode for pointer arguments

### LINKED ISSUE #4541: [msl-out] `BoundsCheckPolicy::ReadZeroSkipWrite` produces invalid Metal when calling functions with pointers to array elements
Say you have a shader like this, which calls a function with a pointer to an array element:

```wgsl
fn takes_ptr(p: ptr<function, i32>) {}

fn foo(i: u32) {
    var arr = array(1, 2, 3, 4);
    takes_ptr(&arr[i]);
}
```

When `BoundsCheckPolicy::ReadZeroSkipWrite` is enabled, Naga produces this invalid Metal code:

```metal
// language: metal2.0
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;
struct DefaultConstructible {
    template<typename T>
    operator T() && {
        return T {};
    }
};

struct type_3 {
    int inner[4];
};

void takes_ptr(
    thread int& p
) {
    return;
}

void foo(
    uint i
) {
    type_3 arr = {};
    arr = type_3 {1, 2, 3, 4};
    takes_ptr(uint(i) < 4 ? arr.inner[i] : DefaultConstructible());
    return;
}
```

`DefaultConstructible()` isn't a valid reference, which Metal rightly complains about:

```
test.metal:28:5: error: no matching function for call to 'takes_ptr'
    takes_ptr(uint(i) < 4 ? arr.inner[i] : DefaultConstructible());
    ^~~~~~~~~
test.metal:17:6: note: candidate function not viable: expects an l-value for 1st argument
void takes_ptr(
     ^
1 error generated.
```

One solution to this that I could see would be to generate a variable containing the default value of the array element type, and pass a reference to that if the index is out of bounds. Something along the lines of this:

```metal
void foo(
    uint i
) {
    type_3 arr = {};
    arr = type_3 {1, 2, 3, 4};
    // I think this is equivalent to `DefaultConstructible()`, looking at its definition, but I don't know much about C++/Metal.
    int oob = {};
    takes_ptr(uint(i) < 4 ? arr.inner[i] : oob);
    return;
}
```

### PR DESCRIPTION
**Pull request by andyleiserson**
**Connections**
Fixes #4541

**Description**
See the description of #4541 for more detail and sample code, but in short, the ReadZeroSkipWrite bounds check policy didn't previously work when the result of the indexing operation was itself a pointer that then gets passed to a function. With this change, a dummy local variable is created for each type that may appear in this manner. If a bounds check fails, the address of the dummy variable is substituted as the argument value for the called function.

This change is based on https://github.com/gfx-rs/naga/pull/2451.

**Testing**
Added snapshot tests for the test case from the issue and a variety of other cases. I also ran the output from naga through the metal compiler to verify it is now accepted.

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by andyleiserson** [comment]
After spending more time with the spec, I think we'd be justified in disallowing this case (pointer to array element) just like pointer to matrix or vector component, at least until we want to claim support for `unrestricted_pointer_parameters`.

File: naga/src/back/msl/writer.rs [hunk 1]
```diff
@@ -679,6 +699,25 @@ impl<'a> ExpressionContext<'a> {
...
+    /// See docs for `proc::index::bounds_check_iter`.
+    fn bounds_check_iter(
+        &self,
+        chain: Handle<crate::Expression>,
+    ) -> impl Iterator<
+        Item = (
+            Handle<crate::Expression>,
+            index::GuardedIndex,
+            index::IndexableLength,
+        ),
```
Comment (ErichDonGubler) [inline naga/src/back/msl/writer.rs]: thought: This return type is complicated enough that some follow-up at some point to refactor to a named `struct` might be nice.

File: naga/src/back/msl/writer.rs [hunk 2]
```diff
@@ -885,6 +924,60 @@ impl<W: Write> Writer<W> {
...
     }
 
+    /// Writes the local variables of the given function, as well as any extra
+    /// out-of-bounds locals that are needed.
+    ///
+    /// The names of the OOB locals are also added to `self.names` at the same
+    /// time.
+    fn put_locals(&mut self, context: &ExpressionContext) -> BackendResult {
+        let oob_locals = context.oob_locals();
+        for &ty in oob_locals.iter() {
```
Comment (ErichDonGubler) [inline naga/src/back/msl/writer.rs]: style: Fun fact, you can shorten this to just a reference:

```suggestion
        for &ty in &oob_locals {
```

Comment (ErichDonGubler) [reply naga/src/back/msl/writer.rs]: Pushed as a `fixup!` with b5303f433f79ce888916d74837253b5bddea929a.

**Comment by ErichDonGubler** [comment]
Two things have been complicating my ability to get to this review:

1. Some protracted time during which I haven't felt like I could prioritize this against my other work. Despite this, I think this should have been reviewed much earlier, and I apologize for this; reviews from maintainers deserve a much faster turnaround than what I've done here (3 weeks!? 😱).
2. Actually understanding the different changes in this PR's single commit. It took me a few hours to peel apart the commit into multiple ones that can stand on their own, and I'm feeling confident enough that the changes are distinct enough for me to review meaningfully.

   I also pushed some `fixup!`s that came up in my review; I'll refer to the commits in my feedback that's soon to follow today.

File: naga/src/back/msl/writer.rs [hunk 3]
```diff
@@ -1741,7 +1768,39 @@ impl<W: Write> Writer<W> {
...
+                        // Instead, we create a dummy local variable to serve as pointer
+                        // target if the access is out of bounds.
+                        let result_ty = context.info[expr_handle]
+                            .ty
+                            .inner_with(&context.module.types)
+                            .pointer_base_type();
+                        let result_ty_handle = match result_ty {
+                            Some(TypeResolution::Handle(handle)) => handle,
+                            Some(TypeResolution::Value(_)) => {
+                                // I don't have a succinct argument why this is the case.
```
Comment (ErichDonGubler) [inline naga/src/back/msl/writer.rs]: nitpick: This is a collective artifact, so writing commentary in first person without a note of authorship is, at best, detail without context. Let's either get your name in here, or re-write this to simply acknowledge that this might not be correct (independent of trying to make this correct, which I'll address in a separate comment) and that we can collectively revise as needed.

File: naga/src/back/msl/writer.rs [hunk 4]
```diff
@@ -611,6 +611,13 @@ trait NameKeyExt {
             FunctionOrigin::EntryPoint(idx) => NameKey::EntryPointLocal(idx, local_handle),
         }
     }
+
+    fn oob_local(origin: FunctionOrigin, ty: Handle<crate::Type>) -> NameKey {
```
Comment (ErichDonGubler) [inline naga/src/back/msl/writer.rs]: question: It's rather confusing to only use the noun `local` when there are _types_ at play here rather than just local variables.

suggestion: Let's rename to something like `s/local/local_type`.

File: naga/src/back/msl/writer.rs [hunk 5]
```diff
@@ -721,6 +728,11 @@ impl<'a> ExpressionContext<'a> {
         index::bounds_check_iter(chain, self.module, self.function, self.info)
     }
 
+    /// See docs for `proc::index::oob_locals`.
```
Comment (ErichDonGubler) [inline naga/src/back/msl/writer.rs]: nitpick: Let's link where we can; `rustdoc` can take some of the load off in keeping this path correct.

Comment (ErichDonGubler) [reply naga/src/back/msl/writer.rs]: Pushed as a `fixup!` with [5208f4e](https://github.com/gfx-rs/wgpu/pull/7323/commits/5208f4ef0da934aebab43c08e39d357db3eefcac).

**Review by ErichDonGubler — CHANGES_REQUESTED** [review]
This mostly LGTM, with some minor issues.

---

<sub>I used [Conventional Comments](https://conventionalcomments.org/) in this review! I hope they help with clarity and tone. 🙂</sub>

**Comment by ErichDonGubler** [comment]
Rebased snapshots onto recent changes merged into `trunk` from <https://github.com/gfx-rs/wgpu/pull/7414>.

File: naga/src/back/msl/writer.rs (hunk 2 above)
Comment (andyleiserson) [reply naga/src/back/msl/writer.rs]: There's actually a clippy lint for this, if we wanted to turn it on: https://rust-lang.github.io/rust-clippy/master/index.html#explicit_iter_loop

File: naga/src/back/msl/writer.rs (hunk 3 above)
Comment (andyleiserson) [reply naga/src/back/msl/writer.rs]: I reworded the comment, although I'm also curious what your thoughts were on "trying to make this correct" -- I don't see another comment about it. I was hoping for some scrutiny on this from reviewers, so thank you for that.

File: naga/src/back/msl/writer.rs (hunk 1 above)
Comment (andyleiserson) [reply naga/src/back/msl/writer.rs]: I went ahead and did this, not hard and it's new (or at least newly more complicated) code.

File: naga/src/back/msl/writer.rs (hunk 4 above)
Comment (andyleiserson) [reply naga/src/back/msl/writer.rs]: I see how it is confusing, but I'm not sure that `oob_local_type` is better since the thing we're naming really is a local, not a type (it's just that there is one per type, and we name it based on the type it's for).

I added a bit more documentation that may help clarify this. If you still think the names are confusing, maybe `s/oob_locals/oob_local_types` and `s/oob_local/oob_local_for_type`?

File: naga/src/back/msl/mod.rs [hunk 6]
```diff
@@ -29,6 +29,20 @@ holding the result.
 [msl]: https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf
 [all-atom]: crate::valid::Capabilities::SHADER_INT64_ATOMIC_ALL_OPS
 
+## Pointer-typed bounds-checked expressions and OOB locals
+
+MSL (unlike HLSL and GLSL) has native support for pointer-typed function
+arguments. When the [`BoundsCheckPolicy`] is `ReadZeroSkipWrite` and an
```
Comment (ErichDonGubler) [inline naga/src/back/msl/mod.rs:35]: nitpick: It'd be nice to doc-link `ReadZeroSkipWrite` here, but I see that some existing commentary has also not linked it.

File: naga/src/back/msl/writer.rs (hunk 4 above)
Comment (ErichDonGubler) [reply naga/src/back/msl/writer.rs]: `oob_local_for_type` seems like a good option to me!

**Review by ErichDonGubler — APPROVED** [review]

**Comment by andyleiserson** [comment]
Github seems not to be triggering the CI jobs any more. I am going to try closing and reopening.
