### PR TITLE
Don't report violations of VUID-vkCmdEndDebugUtilsLabelEXT-commandBuffer-01912

### LINKED ISSUE #3733: Performing a `RenderPass` inside a debug group results in Vulkan validation errors
**Description**
When a `RenderPass` is performed inside of a `push_debug_group`/`pop_debug_group` pair, the following Vulkan validation error is emitted:

```
[2023-04-27T20:32:37Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkCmdEndDebugUtilsLabelEXT-commandBuffer-01912 (0x56146426)]
        Validation Error: [ VUID-vkCmdEndDebugUtilsLabelEXT-commandBuffer-01912 ] Object 0: handle = 0x563ee6e45520, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x56146426 | vkCmdEndDebugUtilsLabelEXT() called without a corresponding vkCmdBeginDebugUtilsLabelEXT first The Vulkan spec states: There must be an outstanding vkCmdBeginDebugUtilsLabelEXT command prior to the vkCmdEndDebugUtilsLabelEXT on the queue that commandBuffer is submitted to (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdEndDebugUtilsLabelEXT-commandBuffer-01912)
[2023-04-27T20:32:37Z ERROR wgpu_hal::vulkan::instance]         objects: (type: COMMAND_BUFFER, hndl: 0x563ee6e45520, name: ?)
```

**Repro steps**
Modify the `hello-triangle` example to add `encoder.push_debug_group("bla")` before and `encoder.pop_debug_group()` after the render pass.

**Expected vs observed behavior**
There should not be any validation errors.

**Extra materials**
I'm using the `vulkan-validation-layers` Arch Linux package at version 1.3.243.0-1 (recent versions add more validation, so this might not reproduce with a lower version, although I haven't tried).

**Platform**
Arch Linux, Vulkan, Wayland/X11 both repro.

### PR DESCRIPTION
**Pull request by jimblandy**
As described in [Vulkan-ValidationLayers#5671], the validation layers don't understand debug ranges paired across different command buffers on the same queue, even though the Vulkan spec says:

> An application may open a debug label region in one command buffer and close it in another, or otherwise split debug label regions across multiple command buffers or multiple queue submissions. When viewed from the linear series of submissions to a single queue, the calls to vkCmdBeginDebugUtilsLabelEXT and vkCmdEndDebugUtilsLabelEXT must be matched and balanced.

Until this is fixed, wgpu should ignore this validation error to reduce noise in test runs.

Fixes #3733.

[Vulkan-ValidationLayers#5671]: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5671

**Checklist**

- [X] Run `cargo clippy`.
- [X] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

### CODE REVIEW

**Comment by FrankenApps** [comment]
Here is the correct link to the Issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5671 in case anyone is interested.

**Comment by jimblandy** [comment]
> Here is the correct link to the Issue [KhronosGroup/Vulkan-ValidationLayers#5671](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5671) in case anyone is interested.

Fixed, thanks.

File: wgpu-hal/src/vulkan/instance.rs [hunk 1]
```diff
@@ -16,13 +16,30 @@ unsafe extern "system" fn debug_utils_messenger_callback(
...
+
+    const VUID_VKSWAPCHAINCREATEINFOKHR_IMAGEEXTENT_01274: i32 = 0x7cd0911d;
+    const VUID_VKCMDENDDEBUGUTILSLABELEXT_COMMANDBUFFER_01912: i32 = 0x56146426;
+
+    // Silence Vulkan Validation error " VUID-vkCmdEndDebugUtilsLabelEXT-commandBuffer-01912"
+    // This is a bug in the validation layer:
+    // https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5671
+    if cd.message_id_number == VUID_VKCMDENDDEBUGUTILSLABELEXT_COMMANDBUFFER_01912 {
+        return vk::FALSE;
+    }
```
Comment (teoxoy) [inline wgpu-hal/src/vulkan/instance.rs]: If we can get the version of the validation layers, it would be better to conditionally ignore it.

Comment (jimblandy) [reply wgpu-hal/src/vulkan/instance.rs]: To narrow down the affected Mesa versions: it seems like the validation was introduced in KhronosGroup/Vulkan-ValidationLayers#5277, merged 2023-2-16.

**Comment by jimblandy** [comment]
Layer properties in KhronosGroup/Vulkan-ValidationLayers@a90644606 (after introduction of 01912 test):

```
LayerProperties {
    layer_name: "VK_LAYER_KHRONOS_validation",
    spec_version: 4206832, // 1.3.240
    implementation_version: 1,
    description: "Khronos Validation Layer",
}
```

**Comment by jimblandy** [comment]
Layer properties in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/a54744d67 (current main):

```
JIMB: instance layer: LayerProperties {
    layer_name: "VK_LAYER_KHRONOS_validation",
    spec_version: 4206842, // 1.3.250
    implementation_version: 1,
    description: "Khronos Validation Layer",
}
```

**Comment by jimblandy** [comment]
Okay, this version of the PR supplies the validation layer description and version to the debug utils messenger callback, and checks them to ensure that we're only filtering out errors from affected versions of `Vulkan-ValidationLayers`.

But I think it does violence to the API of `vulkan::Instance::from_raw`, so I want to look at it again tomorrow.

File: wgpu-hal/src/vulkan/instance.rs [hunk 2]
```diff
@@ -236,48 +252,67 @@ impl super::Instance {
...
-            let mut severity = vk::DebugUtilsMessageSeverityFlagsEXT::ERROR;
-            if log::max_level() >= log::LevelFilter::Debug {
-                severity |= vk::DebugUtilsMessageSeverityFlagsEXT::VERBOSE;
-            }
-            if log::max_level() >= log::LevelFilter::Info {
-                severity |= vk::DebugUtilsMessageSeverityFlagsEXT::INFO;
-            }
-            if log::max_level() >= log::LevelFilter::Warn {
-                severity |= vk::DebugUtilsMessageSeverityFlagsEXT::WARNING;
+        eprintln!(
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/instance.rs]: Just putting a note on this println

File: wgpu-hal/src/vulkan/instance.rs [hunk 3]
```diff
@@ -236,48 +252,67 @@ impl super::Instance {
...
+            "JIMB: Instance::from_raw(debug_utils_user_data = {:?})",
+            debug_utils_user_data
+        );
+        let debug_utils = if let Some(debug_callback_user_data) = debug_utils_user_data {
+            if extensions.contains(&ext::DebugUtils::name()) {
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/instance.rs:273]: Would be nice to have an info level print about why debug callbacks are disabled.

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Would be great to get this in as #3830 is now hitting it.

File: wgpu-hal/src/vulkan/instance.rs (hunk 2 above)
Comment (jimblandy) [reply wgpu-hal/src/vulkan/instance.rs]: Yep, that's why it's a draft PR. :)

**Review by cwfitzgerald — APPROVED** [review]
Nice!
