### PR TITLE
Make links from `wgpu-types` to `wgpu` work in docs.rs.

### LINKED ISSUE #8199: Inter-crate links are broken on docs.rs
There are a bunch of links from hal, core, and types to `wgpu` documentation written like this:

https://github.com/gfx-rs/wgpu/blob/1791064a306881c7ddf218e69b4ffdafdae1be0d/wgpu-types/src/lib.rs#L101

I assume this works when the documentation is built and viewed locally. But on [docs.rs](https://docs.rs/wgpu-types/latest/wgpu_types/constant.MAP_ALIGNMENT.html), the relative link resolves to https://docs.rs/wgpu-types/latest/wgpu/struct.Buffer.html#method.map_async, which does not exist.

### PR DESCRIPTION
**Pull request by kpreid**
As a bonus, the macro now allows defining such links while writing the item name only once instead of twice.

**Connections**
Fixes #8199 (mostly).

**Description**
`../<other crate>` is not sufficient to link to another crate on docs.rs. This PR adds a macro which generates links that will work on docs.rs when `cfg(docsrs)` is set. The macro only applies to `wgpu-types`; it would be trickier to make it work for links in `wgpu-core` and `wgpu-hal`, but those links were fewer and less significant, so I figured it wasn't immediately worth doing.

~~I discovered a presumed bug in docs.rs, <https://github.com/rust-lang/docs.rs/issues/3036>, and this PR contains a workaround for it which will link to older documentation than ideal. The alternative would be to embed the latest version number of `wgpu` into `wgpu-types`, which seems worse.~~ Fixed!

**Testing**
* Clicked links in `cargo doc` to test local docs
* Ran `RUSTDOCFLAGS='--cfg=docsrs' cargo doc`, manually edited together the resulting URLs with `https://docs.rs/`, and verified they worked in docs.rs. 

**Squash or Rebase?**
One commit

**Checklist**

- [X] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [X] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [X] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-types/src/lib.rs [hunk 1]
```diff
@@ -51,25 +51,81 @@ pub use instance::*;
...
+    ($(../)? [$reference:expr]: $url_path:expr) => {
+        concat!(
+            "[",
+            $reference,
+            // URL path will have a base URL of https://docs.rs/
+            "]: /wgpu/",
+            // The version of wgpu-types is not necessarily the same as the version of wgpu,
+            // so we cannot use the full version number.
+            env!("CARGO_PKG_VERSION_MAJOR"),
+            // TODO: Workaround for <https://github.com/rust-lang/docs.rs/issues/3036>;
```
Comment (cwfitzgerald) [inline wgpu-types/src/lib.rs]: With this fixed upstream, (Amazing turnaround!) we can back this out again.

**Review by cwfitzgerald — APPROVED** [review]
Good stuff! Conditional approved on this one nit

File: wgpu-types/src/lib.rs (hunk 1 above)
Comment (kpreid) [reply wgpu-types/src/lib.rs]: Done.

Comment (kpreid) [reply wgpu-types/src/lib.rs]: I also added some further explanation about what is going on and the conditions under which this URL construction is correct.
