### PR TITLE
[naga] Handle phony statements properly by treating them as named expressions

### LINKED ISSUE #6095: get_bind_group_layout fails when layout is auto
**Description**
When layout is not explicitly provided when creating pipeline, `get_bind_group_layout` fails with `Error reflecting bind group 0: Invalid group index 0`, but explicitly providing it makes it work.

**Repro steps**
Relevant CTS test that fails in firefox (and servo): [webgpu:api,validation,getBindGroupLayout:index_range,auto_layout:*](https://gpuweb.github.io/cts/standalone/?debug=1&runnow=1&q=webgpu:api,validation,getBindGroupLayout:index_range,auto_layout:*
)

I also extracted relevant failing CTS subtest in rust/wgpu repro: https://github.com/sagudev/wgpu-problem/tree/get-auto-bind-group-layout (also contains explicit code that makes it work using `explicit` feature).

**Platform**
Happens on current trunk.

### PR DESCRIPTION
**Pull request by sagudev**
**Connections**
Alternative to https://github.com/gfx-rs/wgpu/pull/6308 that fixes https://github.com/gfx-rs/wgpu/issues/6095

**Description**
Currently phony statements get removed when compacting, we bypass this by making them named expressions with `phony` name.

**Testing**
New tests added and [CTS run in servo](https://github.com/sagudev/servo/actions/runs/11045854357/job/30685772542).

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by jimblandy** [comment]
Yeah, this is another reasonable approach.

File: naga/src/back/wgsl/writer.rs [hunk 1]
```diff
@@ -627,6 +627,12 @@ impl<W: Write> Writer<W> {
                 for handle in range.clone() {
                     let info = &func_ctx.info[handle];
                     let expr_name = if let Some(name) = func_ctx.named_expressions.get(&handle) {
+                        if name.starts_with("_naga_phony") {
```
Comment (jimblandy) [inline naga/src/back/wgsl/writer.rs]: What happens if we don't special-case this?

File: naga/src/front/wgsl/parse/ast.rs [hunk 2]
```diff
@@ -284,7 +284,7 @@ pub enum StatementKind<'a> {
     },
     Increment(Handle<Expression<'a>>),
     Decrement(Handle<Expression<'a>>),
-    Ignore(Handle<Expression<'a>>),
+    Phony(Handle<Expression<'a>>, Span),
```
Comment (jimblandy) [inline naga/src/front/wgsl/parse/ast.rs]: The rename is good: we should hew to the spec's terminology as much as possible.

Why does this need a Span when no other variant of `StatementKind` does? Why isn't the `Span` in `struct Statement` good enough?

File: naga/src/front/wgsl/lower/mod.rs [hunk 3]
```diff
@@ -1778,12 +1778,14 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
-            ast::StatementKind::Ignore(expr) => {
+            ast::StatementKind::Phony(expr, span) => {
                 let mut emitter = Emitter::default();
                 emitter.start(&ctx.function.expressions);
 
-                let _ = self.expression(expr, &mut ctx.as_expression(block, &mut emitter))?;
+                let value = self.expression(expr, &mut ctx.as_expression(block, &mut emitter))?;
                 block.extend(emitter.finish(&ctx.function.expressions));
+                ctx.named_expressions
+                    .insert(value, (format!("_naga_phony_{}", value.index()), span));
```
Comment (jimblandy) [inline naga/src/front/wgsl/lower/mod.rs]: I *think* if you just use the empty string for the name, everything will just work. Backends are supposed to apply the namer to everything from `naga::Function::named_expressions`, as done [here](https://github.com/gfx-rs/wgpu/blob/765c20235ea712fd14ad1b9e36bbb2071a86e319/naga/src/back/wgsl/writer.rs#L634), and that will return a fresh name for every string, including "".

Or, for legibility, just use "phony" as the name for all of them.

Please expand the snapshot test to show that these actually don't clash.

File: naga/tests/out/wgsl/phony_assignment.wgsl [hunk 4]
```diff
@@ -0,0 +1,7 @@
+@group(0) @binding(0) 
+var<uniform> binding: f32;
+
+@compute @workgroup_size(1, 1, 1) 
+fn main(@builtin(global_invocation_id) id: vec3<u32>) {
+    _ = binding;
```
Comment (jimblandy) [inline naga/tests/out/wgsl/phony_assignment.wgsl]: Whoa, how come `_ = a;` does away, but `_ = binding;` does not?

File: naga/src/back/wgsl/writer.rs (hunk 1 above)
Comment (sagudev) [reply naga/src/back/wgsl/writer.rs]: it gets emitted as `let` instead of `_`

File: naga/src/front/wgsl/parse/ast.rs (hunk 2 above)
Comment (sagudev) [reply naga/src/front/wgsl/parse/ast.rs]: This span refers to `_` and is used when adding named expressions where we usually add span of var name, but it would make sense for phony statements to use whole statement span (I didn't know we got it).

File: naga/tests/out/wgsl/phony_assignment.wgsl (hunk 4 above)
Comment (sagudev) [reply naga/tests/out/wgsl/phony_assignment.wgsl]: because `let x = a` would also get optimized away (by compat), because it's constant (and has no side effects so this is actually ok).

File: naga/src/back/wgsl/writer.rs (hunk 1 above)
Comment (sagudev) [reply naga/src/back/wgsl/writer.rs]: this is now removed

File: naga/src/front/wgsl/lower/mod.rs (hunk 3 above)
Comment (sagudev) [reply naga/src/front/wgsl/lower/mod.rs]: done in https://github.com/gfx-rs/wgpu/pull/6328/commits/0036482fe5993f3ab5f47eef10a7a720f8740861

File: naga/tests/out/wgsl/phony_assignment.wgsl [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+fn five() -> i32 {
+    return 5i;
+}
+
+@compute @workgroup_size(1, 1, 1) 
+fn main(@builtin(global_invocation_id) id: vec3<u32>) {
+    let phony = binding;
+    let phony_1 = binding;
+    let _e6 = five();
+    let _e7 = five();
```
Comment (jimblandy) [inline naga/tests/out/wgsl/phony_assignment.wgsl:13]: Okay, I think I see what's going on here: these are generated for the two `Statement::Call`s, but then the `_ = five();` and the `let b = five();` don't actually generate any code.

**Review by jimblandy — APPROVED** [review]
No IR or back end changes necessary! I love it.
