### PR TITLE
Fix multiview rendering

### LINKED ISSUE #3778: Add a feature gate to enable XR/Multiview rendering
As mentioned here https://github.com/gpuweb/gpuweb/issues/4109 the webgpu spec specifically does not allow for multiview rendering because of it's validation of 2D texture and 1 array layer of the render target texture. In order to be able to use WGPU to make XR applications I forked WGPU here with an example of how to resolve this issue. https://github.com/MalekiRe/wgpu and used it here in an openxr-wgpu example https://github.com/MalekiRe/wgpu-openxr-example

If we could have some form of disable for the validation as part of wgpu, because it seems like multiview *is* something eventually intended, that would be awesome.

### PR DESCRIPTION
**Pull request by MalekiRe**
**Checklist**

- [ x] Run `cargo clippy`.
- [ ] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
fixes https://github.com/gfx-rs/wgpu/issues/3778

**Description**
WGPU Multiview works again by disabling some validation of TextureViewDimension and ResolvedArrayLayerCount

**Testing**
Running WGPU with a multiview enabled and trying it with multiple views.

### CODE REVIEW

**Comment by MalekiRe** [comment]
@cwfitzgerald This is a PR to do the fix for the thing in the issue

**Review by Wumpf — APPROVED** [review]
lgtm!

File: wgpu-core/src/device/mod.rs [hunk 1]
```diff
@@ -1189,7 +1189,9 @@ impl<A: HalApi> Device<A> {
                 break 'b Err(TextureViewNotRenderableReason::Usage(texture.desc.usage));
             }
 
-            if resolved_dimension != TextureViewDimension::D2 {
+
+            if resolved_dimension != TextureViewDimension::D2
+                && !(self.features.contains(wgt::Features::MULTIVIEW)){
```
Comment (teoxoy) [inline wgpu-core/src/device/mod.rs]: I think this should still check that the view dimension is `D2Array` if the feature is available instead of allowing all through.

**Review by teoxoy — DISMISSED** [review]
Thanks for the PR! Besides the comment it looks good!

**Comment by MalekiRe** [comment]
@teoxoy Made the change

**Comment by MalekiRe** [comment]
Do not merge this yet! I messed up the logic with the 2DTextureView to be inverted with the fix

**Comment by MalekiRe** [comment]
Fixed, feel free to do checks, resolve the issue and merge

**Review by cwfitzgerald — APPROVED** [review]

**Review by teoxoy — APPROVED** [review]
