### PR TITLE
Fix framebuffers not always being cleaned up if invalid

### LINKED ISSUE #447: Framebuffers keep accumulating, degrading performance
Not sure how the lifecycle of framebuffers works right now or where it's coming from.

&borrowfan on Discord showed me a flame graph, showing that `.collect()` in `triage_framebuffers` takes increasingly long to complete. I added a `println` before it and that showed that framebuffers keep accumulating and aren't cleaned up until the `Surface` is destroyed.

### PR DESCRIPTION
**Pull request by LaylConway**
This changes framebuffers to be cleaned up if only one view is cleaned up, instead of if all views are cleaned up. This is necessary because currently, at least for me, swapchain images will have a different view every frame. This means that if other views continue to exist between frames, the resulting framebuffers will never be cleaned up.

Fixes #447

### CODE REVIEW

File: wgpu-core/src/device/life.rs [hunk 1]
```diff
@@ -419,10 +419,14 @@ impl<B: GfxBackend> LifetimeTracker<B> {
             .keys()
             .filter_map(|key| {
                 let mut last_submit: SubmissionIndex = 0;
+                let mut has_missing_view = false;
+
                 for &at in key.all() {
+                    // Clean the framebuffer up if at least one view it's referring to is gone
                     if texture_view_guard.contains(at) {
-                        return None;
+                        has_missing_view = true;
```
Comment (kvark) [inline wgpu-core/src/device/life.rs]: looks like the logic is all messed up here.

First of all, ` if texture_view_guard.contains(at)` means that the view is NOT gone, the opposite from the comment and the logic inside.

Secondly, the follow-up code says "This attachment is no longer registered.", it's only meant to run if the view is missing.

Comment (LaylConway) [reply wgpu-core/src/device/life.rs]: Oh! My bad yea you're completely right, I'll take another look over it.

**Comment by LaylConway** [comment]
Sorry for the rapid small commits, I fixed this while being a bit short on time and didn't pay enough attention to what I wrote in the comments

File: wgpu-core/src/device/life.rs [hunk 2]
```diff
@@ -418,20 +418,45 @@ impl<B: GfxBackend> LifetimeTracker<B> {
         let remove_list = framebuffers
             .keys()
             .filter_map(|key| {
-                let mut last_submit: SubmissionIndex = 0;
+                let mut last_submit = None;
+                let mut needs_cleanup = false;
```
Comment (kvark) [inline wgpu-core/src/device/life.rs]: these two flags are redundant, we could treat `last_submit.is_some()` as `needs_cleanup`

Comment (LaylConway) [reply wgpu-core/src/device/life.rs]: They are not redundant, the framebuffer can need cleanup without the views being in any submission, in that case the submission index will be considered "0" as previously, but this cannot be the default value because the loop tries to find the lowest one.

**Comment by kvark** [comment]
Please rebase so that there are no merge commits

**Comment by LaylConway** [comment]
Oh dang! I updated my local branch expecting things to already be merged, sorry about that

**Comment by LaylConway** [comment]
Sorry about that, should be fixed now
