### PR TITLE
macOS: Fix one-second delay when switching a wgpu app to the foreground

### LINKED ISSUE #8309: Mac/Metal: After alt-tab, `get_current_texture` locks for exactly one second
### Description
When alt-tabbing between applications I notice that sometimes (often, not always) the wgpu app will wait a full second before showing up after being hidden.

### Repro steps
1. On Mac, run `cargo r -p wgpu-example-02-hello-window`.
2. Use cmd-tab to switch to any other application that covers your entire screen (and more importantly: covers the wgpu-example).
3. Use cmd-tab to switch back to the wgpu-example
4. Observe that it takes exactly one second for the wgpu-example to show up

### Expected vs observed behavior
Instant switching

### Extra materials
Here's a screenshot of the stack trace after I added some extra `profiling` scopes:
Image

What is blocking is `MetalLayerRef::next_drawable`.

### Platform
macOS Tahoe 26.0.1
wgpu 27.0.0

### Related issues
* https://github.com/gfx-rs/wgpu/issues/5613 maybe?

### PR DESCRIPTION
**Pull request by emilk**
**Connections**
* Closes https://github.com/gfx-rs/wgpu/issues/8309
* Related to https://github.com/gfx-rs/wgpu/issues/5613

**Description**
  - Fix 1-second hang when switching to a wgpu application that was in the background on macOS
  - ⚠️ `get_current_texture` can now return `SurfaceError::Occluded` (only on Mac currently)
  - Change return type of `fn acquire_texture` to return timeouts as an error variant
                                                                                                                                                              
On macOS, when a window is occluded (minimized, behind other windows, or on another virtual desktop), `CAMetalLayer.nextDrawable()` can block for up to 1 second. This happens because presented drawables get stuck waiting for vsync that isn't happening while the window is hidden.                                                                                                                                                                                               
                                                                                                                                                                                                                                             
When switching back to a wgpu application that was in the background, users experience a noticeable 1-second delay before the application becomes responsive.       

This PR adds a fix: in the top of `aquire_texture` we first check if the window is occluded. If it is, we return a new `SurfaceError::Occluded` error right away, avoiding the 1 second delay.

This then requires users to actually handle this new error by attempting again later.

Thanks to Claude and @Wumpf for helping me with this PR!

**Testing**
I ran `cargo r -p wgpu-example-02-hello-window`, switching the app to be behind and then in front of another opaque window.

* [x] `cargo run --bin wgpu-examples cube`
* [x] `cargo run --bin wgpu-examples hello_triangle`
* [x] `cargo run --bin wgpu-examples uniform_values`
* [x] `cargo r -p wgpu-example-02-hello-window`

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [ ] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry. <!-- See instructions at the top of `CHANGELOG.md`. -->

### CODE REVIEW

File: examples/standalone/02_hello_window/src/main.rs [hunk 1]
```diff
@@ -78,11 +78,14 @@ impl State {
...
     fn render(&mut self) {
-        // Create texture view
-        let surface_texture = self
-            .surface
-            .get_current_texture()
-            .expect("failed to acquire next swapchain texture");
+        // Create texture view.
+        // NOTE: We must handle Timeout because the surface may be unavailable
+        // (e.g., when the window is occluded on macOS).
+        let surface_texture = match self.surface.get_current_texture() {
```
Comment (emilk) [inline examples/standalone/02_hello_window/src/main.rs:84]: Having to change this gives me pause. Should we treat this PR as a breaking change, or a bug fix? 🤷

Comment (Wumpf) [reply examples/standalone/02_hello_window/src/main.rs:84]: then again the fact that the sample didn't handle timeouts is a bug to begin with.

Have you checked whether other samples run into the same problem?

File: wgpu-hal/src/metal/surface.rs [hunk 2]
```diff
@@ -115,10 +115,49 @@ impl crate::Surface for super::Surface {
...
+                        let occlusion_state: usize =
+                            unsafe { objc2::msg_send![&*window, occlusionState] };
+                        let is_visible = (occlusion_state & NS_WINDOW_OCCLUSION_STATE_VISIBLE) != 0;
+
+                        if !is_visible {
+                            // Window is occluded. Skipping frame to avoid drawable stall
+                            return Ok(None);
+                        }
+                    }
+                    break;
```
Comment (Wumpf) [inline wgpu-hal/src/metal/surface.rs:154]: the way we use message sending and hardcoded constants here is a bit dubious, but avoids dragging in more dependencies

File: examples/standalone/02_hello_window/src/main.rs (hunk 1 above)
Comment (Wumpf) [reply examples/standalone/02_hello_window/src/main.rs:84]: I'll bring the question up on the maintainer's meeting. This PR for sure **will** make show timeouts a lot more often

**Comment by emilk** [comment]
I hear from @Wumpf (on other channels) that we should return a new error code instead of returning `None` (indicating timeout).

My plan is to change `acquire_texture` from returning a `Result<Option<Surface>, SurfaceError>` to returning `Result<Surface, SurfaceError>`, and add `Timeout` as an error variant in `SurfaceError` instead (mirroring `SurfaceStatus`). After that, add `Occluded` as an error variant both to `SurfaceError` and to `SurfaceStatus`.

File: wgpu/src/api/surface_texture.rs [hunk 3]
```diff
@@ -57,10 +57,22 @@ impl Drop for SurfaceTexture {
 #[derive(Clone, PartialEq, Eq, Debug)]
 pub enum SurfaceError {
     /// A timeout was encountered while trying to acquire the next frame.
+    ///
+    /// This can happen when the window is not visible (e.g., minimized, occluded,
+    /// or on another virtual desktop) on some platforms, particularly macOS.
+    /// Applications should handle this gracefully by skipping the frame.
```
Comment (Wumpf) [inline wgpu/src/api/surface_texture.rs]: this looks like we mixed it up with `Occluded`. In fact I don't think we know when this happens, but it surely ain't happening on MacOS since timeout isn't implemented there.

@cwfitzgerald do you know which cases we can hit `Timeout` realistically in the wild?

**Review by Wumpf — CHANGES_REQUESTED** [review]
looks good to me, except for the wrong comment I found. Much cleaner than before!

File: wgpu/src/api/surface_texture.rs (hunk 3 above)
Comment (emilk) [inline wgpu/src/api/surface_texture.rs]:
```suggestion
```

**Review by Wumpf — APPROVED** [review]
nice. Going to land that and further investigate correct reaction to inclusion events as part of https://github.com/gfx-rs/wgpu/pull/9089/
Which I want to review soonish; I'll then put some effort into learning about how to correctly process occluded events on winit and will transfer those learnings to eframe as well if it can be mitigated there

**Comment by emilk** [comment]
It actually looks like I accidentally counteracted the same problem in this PR:
* https://github.com/emilk/egui/pull/7950

On egui main now (without the fix in this wgpu PR), I get zero delay when moving the window to the front EXCEPT if I do so very quickly (switch back and forth within a single second).
