### PR TITLE
Try to fix occasional CI failures caused by #8345

### LINKED ISSUE #8345: Occasional CI failures on wgpu-examples [Executed] [Vulkan/llvmpipe (LLVM 18.1.3, 256 bits)/0] mipmap-query
**Description**
See [this CI failure](https://github.com/gfx-rs/wgpu/actions/runs/18475663343/job/52639502263). It was fixed by pushing an empty commit. @cwfitzgerald tells me this has been happening intermittently.

**Repro steps**
Idk

**Expected vs observed behavior**
Shouldn't crash

**Extra materials**

**Platform**
CI

### PR DESCRIPTION
**Pull request by inner-daemons**
**Connections**
Fixes #8345

**Description**
In both [this CI run](https://github.com/gfx-rs/wgpu/actions/runs/19045809424/job/54393600068) and [this one](https://github.com/gfx-rs/wgpu/actions/runs/18475663343/job/52639502263), we get the following logs (only differnet in timing)

```
    running 1 test
    Generating mip level 1 took 8811.895 μs and called the fragment shader 65536 times
    Generating mip level 2 took 1267.701 μs and called the fragment shader 16384 times
    Generating mip level 3 took 121.328 μs and called the fragment shader 4096 times
    Generating mip level 4 took 57.122 μs and called the fragment shader 1024 times
    Generating mip level 5 took 39.339 μs and called the fragment shader 256 times
    Generating mip level 6 took 35.281 μs and called the fragment shader 64 times
    Generating mip level 7 took 34.111 μs and called the fragment shader 16 times
    Generating mip level 8 took 33.486 μs and called the fragment shader 4 times
    Generating mip level 9 took 32.077 μs and called the fragment shader 1 times
    Starting image comparison test with reference image "/home/runner/work/wgpu/wgpu/examples/features/../..//examples/features/src/mipmap/screenshot_query.png"
    	Mean: 0.025341
    	Min Value: 0.000000
    	      25%: 0.031926
    	      50%: 0.042518
    	      75%: 0.042518
    	      95%: 0.051142
    	      99%: 0.058123
    	Max Value: 0.230251
    	Expected Mean (0.025341) to be under expected maximum (0.025): FAIL
    test [Executed] [Vulkan/llvmpipe (LLVM 18.1.3, 256 bits)/0] mipmap-query ... FAILED
```

The test requires the error to be under 0.025. This ups that limit to 0.04, hopefully preventing this CI failure in the future.

**Testing**

**Squash or Rebase?**
Either, CI is named horribly so probably squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: examples/features/src/mipmap/mod.rs [hunk 1]
```diff
@@ -530,6 +530,7 @@ pub static TEST_QUERY: crate::framework::ExampleTestParams = crate::framework::E
     height: 768,
     optional_features: QUERY_FEATURES,
     base_test_parameters: wgpu_test::TestParameters::default(),
-    comparisons: &[wgpu_test::ComparisonType::Mean(0.025)],
+    // Somehow, this test on CI lavapipe reasonably often gets error of 0.025341
+    comparisons: &[wgpu_test::ComparisonType::Mean(0.04)],
```
Comment (ErichDonGubler) [inline examples/features/src/mipmap/mod.rs]: thought: I wonder if we could conditionally use this value for the offending environment(s), instead of upping the tolerance for everything?

Comment (ErichDonGubler) [reply examples/features/src/mipmap/mod.rs]: question: Would using `0.26` also work?

**Review by ErichDonGubler — APPROVED** [review]
LGTM overall, but some refining thoughts before I hit `Merge`.

File: examples/features/src/mipmap/mod.rs (hunk 1 above)
Comment (inner-daemons) [reply examples/features/src/mipmap/mod.rs]: I'm not familiar enough with the testing infrastructure to know how to conditionally set the value, but thats probably worth looking into, since even the current value of 0.025 is 5 times higher than other tests.

I'm hesitant to up it only a little, it seems like if that is chosen then its a lot more likely that slight changes in the environment or in mesa will result in this failing again. I'm guessing 0.025 fixed issues over 0.005 when it was created for example, and then maybe some examples cropped up later pushing the error up to 0.0253

Comment (cwfitzgerald) [reply examples/features/src/mipmap/mod.rs]: Lets do Mean(0.03) and Percentile(99, 0.1) as there's some low level differences, but no real spikes. This should make the test sensitive if there's any big differences, but not if there's just small sampling differences.

Comment (inner-daemons) [reply examples/features/src/mipmap/mod.rs]: @cwfitzgerald Done, hopefully CI passes here
