### PR TITLE
fix(02_hello_window): drop texture if surface texture is suboptimal

### LINKED ISSUE #9360: examples/standalone/02_hello_window: `SurfaceOutput` must be dropped before a new `Surface` is made
**Description**
If I try to run the `examples/standalone/02_hello_window` example then I'm getting the following error message:

<details>

```
[2026-04-02T12:41:10Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default

thread 'main' (43066) panicked at wgpu/src/backend/wgpu_core.rs:3901:18:
wgpu error: Validation Error

Caused by:
  In Surface::configure
    `SurfaceOutput` must be dropped before a new `Surface` is made


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue "mesa vk display queue" 0x5555571b1cb0 destroyed while proxies still attached:
  wl_callback#86 still attached
  wp_linux_drm_syncobj_timeline_v1#94 still attached
  wp_linux_drm_syncobj_timeline_v1#93 still attached
  wl_buffer#92 still attached
  wp_linux_drm_syncobj_timeline_v1#73 still attached
  wp_linux_drm_syncobj_timeline_v1#57 still attached
  wl_buffer#61 still attached
  wp_linux_drm_syncobj_timeline_v1#72 still attached
  wp_linux_drm_syncobj_timeline_v1#77 still attached
  wl_buffer#81 still attached
  wp_linux_drm_syncobj_timeline_v1#55 still attached
  wp_linux_drm_syncobj_timeline_v1#56 still attached
  wl_buffer#54 still attached
```

</details>

**Repro steps**
Ideally, a runnable example we can check out.

1. `cd examples/standalone/02_hello_window`
2. `cargo run`

**Expected vs observed behavior**
No crash.

**Extra materials**

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
- NixOS

### PR DESCRIPTION
**Pull request by TornaxO7**
**Connections**
Closes https://github.com/gfx-rs/wgpu/issues/9360

**Description**
- Added the `drop` invokation for the `Suboptimal` case
- Changed the error message to make it easier to understand (in my opinion)

**Testing**
Ran the example.

**Squash or Rebase?**

I don't know tbh. Maybe squash? 

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [ ] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: examples/standalone/02_hello_window/src/main.rs [hunk 1]
```diff
@@ -86,7 +86,12 @@ impl State {
         let surface_texture = match self.surface.get_current_texture() {
             wgpu::CurrentSurfaceTexture::Success(texture) => texture,
             wgpu::CurrentSurfaceTexture::Occluded | wgpu::CurrentSurfaceTexture::Timeout => return,
-            wgpu::CurrentSurfaceTexture::Suboptimal(_) | wgpu::CurrentSurfaceTexture::Outdated => {
+            wgpu::CurrentSurfaceTexture::Suboptimal(texture) => {
+                drop(texture);
+                self.configure_surface();
+                return;
```
Comment (Wumpf) [inline examples/standalone/02_hello_window/src/main.rs:92]: nice catch. could you please also fix this in 
* `examples/features/src/hello_triangle/mod.rs`
* `examples/features/src/framework.rs`
* `examples/features/src/uniform_values/mod.rs`
* `examples/features/src/hello_windows/mod.rs`
* `examples/bug-repro/01_texture_atomic_bug/src/main.rs`

... I think that's all places where we have this bug

File: wgpu-core/src/present.rs [hunk 2]
```diff
@@ -76,7 +76,7 @@ pub enum ConfigureSurfaceError {
     InvalidViewFormat(wgt::TextureFormat, wgt::TextureFormat),
     #[error(transparent)]
     MissingDownlevelFlags(#[from] MissingDownlevelFlags),
-    #[error("`SurfaceOutput` must be dropped before a new `Surface` is made")]
+    #[error("The texture of the surface must be dropped before configuring the surface or a new texture of the surface is made.")]
```
Comment (Wumpf) [inline wgpu-core/src/present.rs]: How about keeping the accuracy of the old as well as the more readable proposal:

```suggestion
    #[error("The `SurfaceOutput` returned by `get_current_texture` must be dropped before re-configuring via `configure` or  retrieving a new texture via `get_current_texture`.")]
```

**Review by Wumpf — CHANGES_REQUESTED** [review]
thanks! let's fix this everywhere :)

**Comment by TornaxO7** [comment]
> thanks! let's fix this everywhere :)

Aye! 

I'll come back to this later (tomorrow at latest).

File: examples/standalone/02_hello_window/src/main.rs (hunk 1 above)
Comment (TornaxO7) [reply examples/standalone/02_hello_window/src/main.rs:92]: Should be done now.

**Review by Wumpf — APPROVED** [review]
thanks!
