### PR TITLE
[naga wgsl-in] Disallow named component expression for matrix types

### LINKED ISSUE #5496: [wgsl-in] Expression `some_matrix.x` should be rejected
**Description**
wgpu/naga accepts a named component expression to access columns of a matrix (`matrix.x`, `matrix.y`, etc), but this is not permitted by [the specification](https://www.w3.org/TR/WGSL/#composite-value-decomposition-expr); the `.` syntax applies to vectors and structures, but not matrices.

**Repro steps**
`naga-cli` accepts the following code:
```rust
fn foo(ip: mat4x4<f32>) -> f32 {
    return ip.z.z;
}
```

**Expected vs observed behavior**
Should be an error; is not.

**Platform**
wgpu 0.19.3; also tested at current git fb305b85f692f3fbbd9509b648dfbc97072f7465

### PR DESCRIPTION
**Pull request by jamienicol**
**Connections**
Fixes #5496

**Description**
The WGSL spec only allows named component expressions when the base type is a vector or a structure, so this patch removes support for it for matrices. Additionally tests which used this for matrices have been updated to use indexing expressions instead, and a test has been added to ensure a named component expression on a matrix results in an error.

**Testing**
Added a test to ensure the bad code errors during parsing

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -2060,11 +2060,9 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
 
                         lowered_base.map(|base| crate::Expression::AccessIndex { base, index })
                     }
-                    crate::TypeInner::Vector { .. } | crate::TypeInner::Matrix { .. } => {
+                    crate::TypeInner::Vector { .. } => {
                         match Components::new(field.name, field.span)? {
                             Components::Swizzle { size, pattern } => {
-                                // Swizzles aren't allowed on matrices, but
-                                // validation will catch that.
```
Comment (teoxoy) [inline naga/src/front/wgsl/lower/mod.rs:2067]: It does seem like we validate this already.

https://github.com/gfx-rs/wgpu/blob/f6f9233295f1bf49ada1da2d103db0ce087b9eda/naga/src/valid/expression.rs#L350-L362

Maybe the validator wasn't run in https://github.com/gfx-rs/wgpu/issues/5496, but this PR looks good either way.

**Review by teoxoy — APPROVED** [review]
