### PR TITLE
Disable suballocation on Iris(R) Xe gpu

### LINKED ISSUE #3552: Suballocation works incorrectly
**Description**
Related to #3544 

**Repro steps**
Uploading transparent pixel data

**Expected vs observed behavior**
Transparent pixels should be rendered correctly

**Extra materials**
图片

**Platform**
os: Win10
gpu: Intel iris xe
wgpu: 0.15 with dx12 backend

### PR DESCRIPTION
**Pull request by xiaopengli89**
**Checklist**

- [x] Run `cargo clippy`.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
Close #3552

### CODE REVIEW

**Comment by Elabajaba** [comment]
This technically invalidates the safety comments for the suballocated path, but I don't think that really matters.

Should probably also not create the allocator (just add an early return to the top of `create_allocator_wrapper()` in suballocation.rs if suballocation isn't supported).

Also should probably add a comment above each of the `if !device.private_caps.suballocation_supported {` blocks saying that it's a workaround for Intel Xe drivers.

**Comment by xiaopengli89** [comment]
Ok.

File: wgpu-hal/src/dx12/suballocation.rs [hunk 1]
```diff
@@ -111,6 +157,40 @@ mod allocation {
         raw_desc: d3d12_ty::D3D12_RESOURCE_DESC,
         resource: &mut WeakPtr<ID3D12Resource>,
     ) -> Result<(HRESULT, Option<AllocationWrapper>), crate::DeviceError> {
+        // It's a workaround for Intel Xe drivers.
+        if !device.private_caps.suballocation_supported {
```
Comment (cwfitzgerald) [inline wgpu-hal/src/dx12/suballocation.rs:127]: Can we re-configure the code in some way such that we can just call the other function instead of copy and pasting the body?

I would:
- Rename modules to `placed` and `committed`.
- Make `placed` conditional on windows_rs, but `committed` unconditional 
- Re-export the module based on the windows_rs cfg.
- If suballocation isn't supported, call the committed version of the function.

File: wgpu-hal/src/dx12/device.rs [hunk 2]
```diff
@@ -20,7 +20,10 @@ impl super::Device {
         library: &Arc<d3d12::D3D12Lib>,
         dx12_shader_compiler: wgt::Dx12Compiler,
     ) -> Result<Self, crate::DeviceError> {
-        let mem_allocator = super::suballocation::create_allocator_wrapper(&raw)?;
+        let mut mem_allocator = None;
+        if private_caps.suballocation_supported {
+            mem_allocator = super::suballocation::create_allocator_wrapper(&raw)?;
+        }
```
Comment (cwfitzgerald) [inline wgpu-hal/src/dx12/device.rs]:
```suggestion
        let mem_allocator = if private_caps.suballocation_supported {
            Some(super::suballocation::create_allocator_wrapper(&raw)?)
        } else {
            None
        }
```

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]

File: wgpu-hal/src/dx12/suballocation.rs (hunk 1 above)
Comment (Elabajaba) [reply wgpu-hal/src/dx12/suballocation.rs:127]: I originally did it this way to avoid having cfg blocks scattered through `device.rs`. We could move the inner part of the committed stuff out of the module and have the if blocks and the non-windows_rs path call those functions?

Comment (cwfitzgerald) [reply wgpu-hal/src/dx12/suballocation.rs:127]: I still thing that the suballocation module should automatically switch to the appropriate call, we just should _also_ have the committed functions available, just not re-exported.

Comment (Elabajaba) [reply wgpu-hal/src/dx12/suballocation.rs:127]: So having something like this?

```
#[cfg(windows_rs)]
pub(crate) use placed as allocation;
#[cfg(not(windows_rs))]
pub(crate) use committed as allocation;

#[cfg(windows_rs)]
mod placed {
    ...
}

pub(crate) mod committed {
    ...
}
```

File: wgpu-hal/src/dx12/suballocation.rs [hunk 3]
```diff
@@ -63,6 +68,13 @@ mod allocation {
     ) -> Result<(HRESULT, Option<AllocationWrapper>), crate::DeviceError> {
         let is_cpu_read = desc.usage.contains(crate::BufferUses::MAP_READ);
         let is_cpu_write = desc.usage.contains(crate::BufferUses::MAP_WRITE);
+
+        // It's a workaround for Intel Xe drivers.
+        if !device.private_caps.suballocation_supported {
+            return super::committed::create_buffer_resource(device, desc, raw_desc, resource)
+                .map(|(hr, _)| (hr, None));
```
Comment (Elabajaba) [inline wgpu-hal/src/dx12/suballocation.rs:75]: Is mapping this necessary? Committed creates will never return an allocation.

File: wgpu-hal/src/dx12/suballocation.rs [hunk 4]
```diff
@@ -111,6 +123,12 @@ mod allocation {
         raw_desc: d3d12_ty::D3D12_RESOURCE_DESC,
         resource: &mut WeakPtr<ID3D12Resource>,
     ) -> Result<(HRESULT, Option<AllocationWrapper>), crate::DeviceError> {
+        // It's a workaround for Intel Xe drivers.
+        if !device.private_caps.suballocation_supported {
+            return super::committed::create_texture_resource(device, desc, raw_desc, resource)
+                .map(|(hr, _)| (hr, None));
```
Comment (Elabajaba) [inline wgpu-hal/src/dx12/suballocation.rs:129]: Is mapping this necessary? Committed creates will never return an allocation.

File: wgpu-hal/src/dx12/suballocation.rs (hunk 3 above)
Comment (xiaopengli89) [reply wgpu-hal/src/dx12/suballocation.rs:75]: Because the allocation type is different.

Comment (Elabajaba) [reply wgpu-hal/src/dx12/suballocation.rs:75]: Makes sense. I don't think we can fix that until Mozilla finally gets around to allowing `windows-rs`.

File: wgpu-hal/src/dx12/suballocation.rs (hunk 1 above)
Comment (xiaopengli89) [reply wgpu-hal/src/dx12/suballocation.rs:127]: Done.

**Comment by Elabajaba** [comment]
I'm getting a test failure when I run this on my AMD 6800xt when I force it to use suballocation on the `wgpu::wgpu-tests zero_init_texture_after_discard::discarding_depth_target_resets_texture_init_state_check_visible_on_copy_in_same_encoder` test. It passes when suballocation is enabled, but it times out if it's disabled.

Does it pass that test on an Xe iGPU?

**Comment by xiaopengli89** [comment]
> I'm getting a test failure when I run this on my AMD 6800xt when I force it to use suballocation on the `wgpu::wgpu-tests zero_init_texture_after_discard::discarding_depth_target_resets_texture_init_state_check_visible_on_copy_in_same_encoder` test. It passes when suballocation is enabled, but it times out if it's disabled.
> 
> Does it pass that test on an Xe iGPU?

I ran the test on AMD Radeon(TM) Graphics with suballoction disabled and it pass `wgpu::wgpu-tests zero_init_texture_after_discard::discarding_depth_target_ resets_texture_init_state_check_visible_on_copy_in_same_encoder`.

But `texture_arrays_non_uniform` does not pass, the error is `Image data mismatch! Outlier count 768 over limit 0. Max difference 255`, even if suballoction is enabled, this should have nothing to do with this PR.

**Comment by xiaopengli89** [comment]
All tests passed on my Intel(R) Iris(R) Xe Graphics.

**Review by cwfitzgerald — APPROVED** [review]
Thanks so much!
