### PR TITLE
Fix compute pass barriers

### LINKED ISSUE #193: image in compute shader has vulkan validation errors
I'm seeing:
```
[2019-05-27T01:43:34Z ERROR gfx_backend_vulkan] 
VALIDATION [VUID-VkDescriptorImageInfo-imageLayout-00344 (0)] : vkCmdDispatch(): Cannot use image 0x48 (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL that doesn't match the previously used layout VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorImageInfo-imageLayout-00344)
object info: (type: COMMAND_BUFFER, hndl: 94377303160832)

[2019-05-27T01:43:34Z ERROR gfx_backend_vulkan] 
VALIDATION [UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated (0)] : Descriptor set 0x4f bound as set #0 encountered the following validation error at vkCmdDispatch() time: Image layout specified at vkUpdateDescriptorSet* or vkCmdPushDescriptorSet* time doesn't match actual image layout at time descriptor is used. See previous error callback for specific details.
object info: (type: DESCRIPTOR_SET, hndl: 79)
```

Basically this is the gist of the layout + setup; the image stuff was copied directly from the `cube.rs` example; i probably added DST in various places to usage flags to attempt to resolve it, so if there's a discrepancy in usage, that's why (though doesn't appear to affect anything):

```rust
        //////////////////////////////////
        // Image texture sampling
        /////////////////////////////////
        let texture_extent = wgpu::Extent3d {
            width: image_width,
            height: image_height,
            depth: 1,
        };
        let texture = device.create_texture(&wgpu::TextureDescriptor {
            size: texture_extent,
            array_layer_count: 1,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba8Unorm,
            usage: wgpu::TextureUsage::SAMPLED | wgpu::TextureUsage::TRANSFER_DST | wgpu::TextureUsage::TRANSFER_SRC,
        });
        let texture_view = texture.create_default_view();
        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Nearest,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::FilterMode::Nearest,
            lod_min_clamp: -100.0,
            lod_max_clamp: 100.0,
            compare_function: wgpu::CompareFunction::Always,
        });

        /////////////////////////////////
        // Layout data to the compute shader
        /////////////////////////////////
        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            bindings: &[
                wgpu::BindGroupLayoutBinding {
                    binding: 1,
                    visibility: wgpu::ShaderStage::COMPUTE,
                    ty: wgpu::BindingType::SampledTexture,
                },
                wgpu::BindGroupLayoutBinding {
                    binding: 2,
                    visibility: wgpu::ShaderStage::COMPUTE,
                    ty: wgpu::BindingType::Sampler,
                },
                wgpu::BindGroupLayoutBinding {
                    binding: 3,
                    visibility: wgpu::ShaderStage::COMPUTE,
                    ty: wgpu::BindingType::StorageBuffer,
                },
                wgpu::BindGroupLayoutBinding {
                    binding: 4,
                    visibility: wgpu::ShaderStage::COMPUTE,
                    ty: wgpu::BindingType::StorageBuffer,
                }
            ],
        });

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            layout: &bind_group_layout,
            bindings: &[
                wgpu::Binding {
                    binding: 1,
                    resource: wgpu::BindingResource::TextureView(&texture_view),
                },
                wgpu::Binding {
                    binding: 2,
                    resource: wgpu::BindingResource::Sampler(&sampler),
                },
                wgpu::Binding {
                    binding: 3,
                    resource: wgpu::BindingResource::Buffer {
                        buffer: &input_buffer,
                        range: 0..input_size as u64,
                    },
                },
                wgpu::Binding {
                    binding: 4,
                    resource: wgpu::BindingResource::Buffer {
                        buffer: &self.buf,
                        range: 0..output_size,
                    },
                }
            ],
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            bind_group_layouts: &[&bind_group_layout],
        });

        let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            layout: &pipeline_layout,
            compute_stage: wgpu::PipelineStageDescriptor {
                module: &self.cs,
                entry_point: "main",
            },
        });

        ////////////////////////////////
        // Encode commands
        ////////////////////////////////
        let image_buf = device
            .create_buffer_mapped(image_data.len(), wgpu::BufferUsage::TRANSFER_SRC | wgpu::BufferUsage::TRANSFER_DST)
            .fill_from_slice(image_data);
        encoder.copy_buffer_to_texture(
            wgpu::BufferCopyView {
                buffer: &image_buf,
                offset: 0,
                row_pitch: 4 * image_width,
                image_height,
            },
            wgpu::TextureCopyView {
                texture: &texture,
                mip_level: 0,
                array_layer: 0,
                origin: wgpu::Origin3d {
                    x: 0.0,
                    y: 0.0,
                    z: 0.0,
                },
            },
            texture_extent,
        );
```

shader layouts were also copied from cube.rs for the texture and sampler:
```glsl
layout(set = 0, binding = 1) uniform texture2D surface;
layout(set = 0, binding = 2) uniform sampler samp;

// this is a vec4 because otherwise we're unaligned
layout(set = 0, binding = 3) buffer VertexIn {
    vec4 data[];
} data_in;

layout(set = 0, binding = 4) buffer VertexOut {
    Vertex data[];
} data_out;
```

### PR DESCRIPTION
**Pull request by kvark**
Fixes #193 (supposedly)
@m4b would you be able to confirm?

Basic idea is that we treat commands inside a compute pass to follow the same rule as transfer commands. We could even go as far as alias `type ComputePassEncoderId = CommandEncoderId`, but I thought maybe we can still take advantage of a separate type. Currently it gets both the backend command buffer and the tracker from the primary encoder, only to return them back in place when the pass is done.

### CODE REVIEW

File: wgpu-native/src/command/compute.rs [hunk 1]
```diff
@@ -38,14 +42,14 @@ impl<B: hal::Backend> ComputePass<B> {
 
 #[no_mangle]
 pub extern "C" fn wgpu_compute_pass_end_pass(pass_id: ComputePassId) -> CommandBufferId {
-    let mut command_buffer_guard = HUB.command_buffers.write();
```
Comment (aloucks) [inline wgpu-native/src/command/compute.rs]: I think the original variable name is easier to digest.

**Comment by m4b** [comment]
Tried testing this, but:
1. patch in `Cargo.toml` doesn't seem to take effect
2. when i manually point to local checkouts in wgpu-native and wgpu-rs, i get:
```
   Compiling wgpu-native v0.2.6 (/home/m4b/git/wgpu/wgpu-native)
   Compiling wgpu v0.2.2 (/home/m4b/git/wgpu-rs)
error[E0308]: mismatched types
    --> /home/m4b/git/wgpu-rs/src/lib.rs:1071:13
     |
1071 |             offsets.as_ptr(),
     |             ^^^^^^^^^^^^^^^^ expected u64, found u32
     |
     = note: expected type `*const u64`
                found type `*const u32`
```

dunno what's going on here.

**Comment by rukai** [comment]
Its just a bit behind wgpu-rs is just a bit behind wgpu-native, this should fix it https://github.com/gfx-rs/wgpu-rs/pull/15

File: wgpu-native/src/command/compute.rs (hunk 1 above)
Comment (kvark) [reply wgpu-native/src/command/compute.rs]: Noted. I just made it consistent with the render pass code, will re-evaluate (and you are welcome to make a PR that changes names to be cleaner!)

**Comment by kvark** [comment]
Thanks everyone for having a look! It's such a joy to develop with a vibrant community :heart: 
Checking a patch here with wgpu-rs involves a few steps:
  1. Checking out the wgpu version that wgpu-rs currently relies upon
  2. Rebasing (or cherry-picking commits from) this PR on it
  3. Adjusting Cargo.toml in your local copy of wgpu-rs to point to the local path

I'm not aware of a simpler path.

**Comment by kvark** [comment]
Bors r=grovesNL

**Comment by m4b** [comment]
I'd like to test this, but I don't think its possible to cherry-pick this commit onto wgpu, and then have wgpu-rs use it; I'll just wait until wgpu-rs picks it up, and report back here or on the parent issue the results. Any eta when wgpu-rs will be updated to more recent stuff?

**Comment by rukai** [comment]
Done https://github.com/gfx-rs/wgpu-rs/pull/15
