### PR TITLE
fix(naga): don't crash on zero value of dynamically-sized array

### LINKED ISSUE #8442: [hlsl-out] `let a = array<f32>();` causes a crash
If one uses the following WGSL shader:

```wgsl
@compute @workgroup_size(1)
fn main() {
    let a = array<f32>(); // pretty sure this is invalid
}
```

…to emit HLSL via `naga-cli`, then the process crashes like this:

```
RUST_BACKTRACE=1 cargo run -p naga-cli --quiet -- ../in.wgsl ../out.hlsl

thread 'main' panicked at naga\src\back\hlsl\conv.rs:115:18:
internal error: entered unreachable code
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:697
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\panicking.rs:75
   2: core::panicking::panic
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\panicking.rs:145
   3: enum2$<naga::ir::TypeInner>::hlsl_type_id
             at .\naga\src\back\hlsl\conv.rs:115
   4: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_wrapped_zero_value_function_name<ref_mut$<alloc::string::String> >
             at .\naga\src\back\hlsl\help.rs:2251
   5: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_wrapped_zero_value_function<ref_mut$<alloc::string::String> >
             at .\naga\src\back\hlsl\help.rs:2283
   6: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_wrapped_zero_value_functions<ref_mut$<alloc::string::String> >
             at .\naga\src\back\hlsl\help.rs:1350
   7: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_wrapped_functions<ref_mut$<alloc::string::String> >
             at .\naga\src\back\hlsl\help.rs:1838
   8: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write<ref_mut$<alloc::string::String> >
             at .\naga\src\back\hlsl\writer.rs:508
   9: naga::write_output
             at .\naga-cli\src\bin\naga.rs:918
  10: naga::run
             at .\naga-cli\src\bin\naga.rs:648
  11: naga::main
             at .\naga-cli\src\bin\naga.rs:402
  12: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at C:\Users\<snip>\.rustup\toolchains\1.88-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
  13: core::hint::black_box
             at C:\Users\<snip>\.rustup\toolchains\1.88-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\hint.rs:482
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Originally reported by @stefnotch in [bug 1997070](https://bugzilla.mozilla.org/show_bug.cgi?id=1997070) in Mozilla's bug tracker.

### PR DESCRIPTION
**Pull request by mooori**
**Connections**

Fixes #8442 

**Description**

Usage of dynamically sized arrays is [restricted to a few special cases](https://github.com/gfx-rs/wgpu/blob/952d653835402dbff06477e1bd256dd505322e2b/naga/src/ir/mod.rs#L831). `let a = array<f32>()` is trying to construct the `ZeroValue` of a dynamically sized array, which is not allowed. With this PR, `ZeroValue` construction of dynamically sized arrays gets validated out.

Compiling the wgsl from #8442 doesn't crash naga anymore but instead throws an error:

```
$ RUST_BACKTRACE=1 cargo run -p naga-cli -- canary.wgsl canary.hlsl

[ERROR naga::valid::zero_value] Constructing zero value of runtime-sized array
error: Entry point main at Compute is invalid
  ┌─ canary.wgsl:3:13
  │
3 │     let a = array<f32>();
  │             ^^^^^^^^^^^ naga::ir::Expression [0]
  │
  = Expression [0] is invalid
  = ZeroValue construction of runtime-sized array is not allowed
```

**Testing**

Adds test `zero_value_dyn_array_error`.

**Squash or Rebase?**

Squash

**Checklist**

- [X] Run `cargo fmt`.
- [X] Run `taplo format`.
- [X] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [X] Run `cargo xtask test` to run tests.
- [X] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/valid/zero_value.rs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+use crate::arena::Handle;
+
+#[derive(Clone, Debug, thiserror::Error)]
+#[cfg_attr(test, derive(PartialEq))]
+pub enum ZeroValueError {
+    #[error("ZeroValue construction of dynamically-sized array is not allowed")]
+    DynamicallySizedArray,
```
Comment (andyleiserson) [inline naga/src/valid/zero_value.rs]: naga is inconsistent about the two terms, but I would prefer to call it runtime-sized array, rather than dynamically sized array, to match the spec's terminology.

File: naga/src/valid/expression/builtin.rs
Comment (andyleiserson) [inline naga/src/valid/expression/builtin.rs:1]: We definitely want to work on reducing the length of our files and functions, but this seems like it may slice things a little too finely? Not a strong opinion, and I'm open to more input here.

A different way of scoping it might be to create `naga/src/valid/expression/builtin.rs`.

**Review by andyleiserson — COMMENTED** [review]
There is a relevant CTS test `webgpu:shader,validation,expression,call,builtin,value_constructor:array_zero_value:case="invalid_rta"`, but it isn't failing, because it expects any validation error, and is getting one related to constructibility. (I'm looking at fixing this in the CTS.)

There are also some related CTS tests that expose other broken cases (atomics, override-sized arrays). Also see #4720.

Submitting as comments right now, but this is all nits, there's nothing here that is essential to fix before merging this.

**Comment by andyleiserson** [comment]
> There is a relevant CTS test `webgpu:shader,validation,expression,call,builtin,value_constructor:array_zero_value:case="invalid_rta"`, but it isn't failing, because it expects any validation error, and is getting one related to constructibility. (I'm looking at fixing this in the CTS.)

https://github.com/gpuweb/cts/pull/4550 has my proposed change to the CTS.

File: naga/src/valid/zero_value.rs (hunk 1 above)
Comment (mooori) [reply naga/src/valid/zero_value.rs]: Done.

File: naga/src/valid/expression/builtin.rs
Comment (mooori) [reply naga/src/valid/expression/builtin.rs:1]: Makes sense and I've moved it accordingly.

**Review by andyleiserson — APPROVED** [review]
Thanks for the contribution!
