### PR TITLE
Separate valid internal IDs from external ones

### LINKED ISSUE #638: Error model
Our current error model is a bunch of `assert!` calls in the function bodies. This *can* be made safe (in Rust's sense of safety), but it's not matching the upstream spec, and it's not desirable as a model exposed to users.

The upstream has a model like "internal contagious nullability", where things. at some point after they are used wrong, become internally invalid. They spread that invalid state onto things that use them, and so forth. The user would then get an error scope asynchronously with the exact problem.

I wonder if we can start reshaping the current model to propagate errors up to the user instead of asserting. This means the native users will get the errors right away, exactly in the way they expect a Rust library to error. This shouldn't block us in implementing the error scopes API for the Web specifically, it's just going to be unused (or underused) when compiling for native.

### PR DESCRIPTION
**Pull request by kvark**
**Connections**
Closes #638 
wgpu-rs update - https://github.com/gfx-rs/wgpu-rs/pull/494

**Description**
The core change here is to allow user-specified IDs to be in the "Error" state that was introduced in #776 .

This is done by defining an internal `Valid<I>` wrapper. Now, the hub storages can be indexed by this valid wrapper only. For regular IDs, we have to go through `storage.get(index)`, which returns a `Result`. It still panics if the ID is totally garbage though, we don't want to handle what can't be expected here.

All the other changes come mostly as a consequence of that:
  - new "Invalid*" error variants are added
  - the error types are undergone sever refactoring
  - new `command/draw.rs` module for stuff shared between render passes and bundles
  - functions to generate error IDs for all the types
  - various renames, e.g. `comb` -> `cmd_buf`

The expected use by wgpu-rs is unchanged. So far, I don't think we'd be generating Error IDs, but we can always reconsider.
For browsers though, if `device_create_xxx` failed, they would generate and error ID. It will occupy the slot up until the corresponding JS object is dropped.

**Testing**
Tested on wgpu-rs examples

### CODE REVIEW

File: wgpu-core/src/id.rs [hunk 1]
```diff
@@ -110,6 +110,14 @@ impl<T> Ord for Id<T> {
     }
 }
 
+/// An internal ID that has been checked to point to point to
```
Comment (kunalmohan) [inline wgpu-core/src/id.rs:113]: Remove the extra `point to`

File: player/src/bin/play.rs [hunk 2]
```diff
@@ -82,7 +82,7 @@ fn main() {
                 )
                 .expect("Unable to find an adapter for selected backend");
 
-            let info = gfx_select!(adapter => global.adapter_get_info(adapter));
+            let info = gfx_select!(adapter => global.adapter_get_info(adapter)).unwrap();
```
Comment (cwfitzgerald) [inline player/src/bin/play.rs:85]: Not in scope, but we likely want an `unwrap_pretty` type thing here too.

Comment (kvark) [reply player/src/bin/play.rs:85]: These are actually not expected to fail at all, unless we are hand-writing them.
I would be happy to accept such PR anyway though :)

**Comment by kvark** [comment]
bors r=cwfitzgerald
