### PR TITLE
Fix local_invocation_id and local_invocation_index handling

### LINKED ISSUE #8820: Naga HLSL writer treats thread index/thread id weirdly
**Description**
This might be a duplicate since I've explained this to @cwfitzgerald before at least but HLSL currently writes output variables with these builtins in multiple places, meaning multiple such variables can appear , which is illegal. Additionally, sometimes they are called `__local_invocation_id` or the like, which isn't a reserved keyword.

**Repro steps**
Try writing an HLSL shader that uses a workgroup variable that must be zero-initialized and that also takes an argument of `@builtin(local_invocation_id)`.

### PR DESCRIPTION
**Pull request by inner-daemons**
**Connections**
Closes #8820 

This is blocking #8752 and #8739, which I would rather not keep having to maintain. So speed would be appreciated here.

**Description**
Solves issue with builtins possibly being written multiple times in HLSL and MSL, and with naming conflicts when users name variables `__local_invocation_id` or `__local_invocation_index`.

**Testing**
Snapshots

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/back/hlsl/writer.rs [hunk 1]
```diff
@@ -845,8 +852,9 @@ impl<'a, W: fmt::Write> super::Writer<'a, W> {
             Some(crate::Binding::BuiltIn(crate::BuiltIn::SubgroupId)) => {
                 write!(
                     self.out,
-                    "{}.__local_invocation_index / WaveGetLaneCount()",
-                    ep_input.arg_name
+                    "{}.{} / WaveGetLaneCount()",
+                    ep_input.arg_name,
+                    ep_input.local_invocation_index_name.as_ref().unwrap()
```
Comment (Wumpf) [inline naga/src/back/hlsl/writer.rs:858]: don't like the unwrap here at all. Yes the invariant of (waaaay) above change is right now that if there's a subgroupid, then invocation index name will be `Some` but it's too easy to violate that via future iterations.

Why not just always set the invocation index name and overwrite only if a user specified one is there? The question of whether we expect it to be in use is a separate one then.

File: naga/src/back/hlsl/writer.rs [hunk 2]
```diff
@@ -1653,7 +1670,11 @@ impl<'a, W: fmt::Write> super::Writer<'a, W> {
         writeln!(self.out, "{{")?;
 
         if need_workgroup_variables_initialization {
-            self.write_workgroup_variables_initialization(func_ctx, module)?;
+            self.write_workgroup_variables_initialization(
+                func_ctx,
+                module,
+                local_invocation_id_name.unwrap(),
```
Comment (Wumpf) [inline naga/src/back/hlsl/writer.rs:1686]: as above, it's too hard to reason through these unwraps outside of this PR

File: naga/tests/in/wgsl/subgroup-operations.wgsl [hunk 3]
```diff
@@ -3,21 +3,25 @@ struct Structure {
...
     _ = subgroupAll(subgroup_invocation_id != 0u);
     _ = subgroupAny(subgroup_invocation_id == 0u);
-    _ = subgroupAdd(subgroup_invocation_id);
-    _ = subgroupMul(subgroup_invocation_id);
-    _ = subgroupMin(subgroup_invocation_id);
-    _ = subgroupMax(subgroup_invocation_id);
+    workgroup_var = subgroupAdd(subgroup_invocation_id);
+    _ = subgroupMul(workgroup_var);
+    _ = subgroupMin(local_invocation_id.x);
+    _ = subgroupMax(local_invocation_index);
```
Comment (Wumpf) [inline naga/tests/in/wgsl/subgroup-operations.wgsl]: variation of what function gets called with what seems totally arbitrary. It would be much cleaner to have a separate block that cleanly serves as a regression test for the fix here. Ideally also with a comment that it doesn't test any particular function but rather the use of invocation id/index

**Review by Wumpf — CHANGES_REQUESTED** [review]
some hygenie/maintainability things that need addressing, otherwise lgtm

File: naga/src/back/hlsl/writer.rs (hunk 1 above)
Comment (inner-daemons) [reply naga/src/back/hlsl/writer.rs:858]: I'm gonna add a comment. The problem there is that we always get this unused variable, even where it doesn't make sense (like in vertex shaders).

File: naga/src/back/hlsl/writer.rs (hunk 2 above)
Comment (inner-daemons) [reply naga/src/back/hlsl/writer.rs:1686]: Same comment as above.

File: naga/tests/in/wgsl/subgroup-operations.wgsl (hunk 3 above)
Comment (inner-daemons) [reply naga/tests/in/wgsl/subgroup-operations.wgsl]: Fixed

**Comment by inner-daemons** [comment]
@Wumpf Can you take another look

**Review by ChristopherBiscardi — APPROVED** [review]
Approving for the same reasons as the msl writer PR https://github.com/gfx-rs/wgpu/pull/8739#pullrequestreview-3933825701 which uses this code.

I've read through the code, ported bevy and a series of examples to use it, and it is working as expected.

**Review by Wumpf — APPROVED** [review]
still very much unhappy about the unwrapping :/. Testing looks _much_ nicer
But lgtm overall, so let's ship this.

Fixed changelog entry a bit though.

**Comment by Wumpf** [comment]
@ChristopherBiscardi thank you so much for giving those changes a spin here and on the other PRs!
