### PR TITLE
Report errors when `CommandEncoder.finish` is called

### LINKED ISSUE #7391: Command encoding validation should not emit errors before `CommandEncoder::finish`
Many WebGPU CTS tests exercise validation of command encoders with error scopes used this way:

1. Set up a device and a command encoder.
2. Do something invalid during command encoding, like using an occlusion query in a `GPURenderPassDescriptor.timestampWrites`.
3. Push an error scope, `finish` the command encoder, and pop an error scope to check if there was a validation error.

_**WGPU emits errors for validation during command encoding before calling `CommandEncoder::finish`, and it shouldn't.**_ It's difficult to cite spec. text that is _not_ present, but the easiest way to summarize is that "generate a validation error" does _not_ show up in the validation steps performed by the various methods of [`GPUCommandEncoder`](https://www.w3.org/TR/webgpu/#gpucommandencoder) and `{Compute,Render}PassEncoder` _except_ for `GPUCommandEncoder.finish`.

## Steps to reproduce

```toml
[package]
name = "wgpu-cmd-enc-finish-validation-bruh"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "1e172b2e1461724eb7ded00b6520732db1c5ae92" }
```

```rust
use pollster::FutureExt as _;

fn main() {
    let instance = wgpu::Instance::new(&Default::default());
    let adapter = instance
        .request_adapter(&Default::default())
        .block_on()
        .unwrap();
    let (device, queue) = adapter
        .request_device(&Default::default())
        .block_on()
        .unwrap();

    let occlusion_query = device.create_query_set(&wgpu::QuerySetDescriptor {
        label: None,
        ty: wgpu::QueryType::Occlusion,
        count: 1,
    });

    let mut command_encoder = device.create_command_encoder(&Default::default());

    {
        let mut _render_pass = command_encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
            timestamp_writes: Some(wgpu::RenderPassTimestampWrites {
                query_set: &occlusion_query,
                beginning_of_pass_write_index: Some(0),
                end_of_pass_write_index: Some(1),
            }),
            ..Default::default()
        });
    }

    device.push_error_scope(wgpu::ErrorFilter::Validation);
    let _cmd_buf = command_encoder.finish();
    device.pop_error_scope().block_on().unwrap();

    queue.submit([_cmd_buf]);
}
```

## Suggested implementation design

1. The MVP for this is to _stop_ emitting validation errors on `CommandEncoder`, `RenderPassEncoder`, and `ComputePassEncoder` methods. These methods already invalidate the associated `CommandEncoder` and other objects when failing validation, so no action should be needed there.
2. The above loses some significant diagnostic quality. We'll probably want to store the first validation error a command encoder encounters, to counter this.

This issue is likely to become a meta issue, since the API surface to which this issue applies is pretty broad.

### PR DESCRIPTION
**Pull request by andyleiserson**
This has the rest of the error reporting changes for #7391. I don't think there is urgency to get these changes in before the train leaves, but it's probably better to take either all of them or none of them than to take some of them, so here's a PR with all of them. It can be reviewed commit-by-commit if that's easier.

As in the other PRs, turning on the "hide whitespace" option will substantially reduce the diff.

**Testing**
Enables relevant CTS tests, and updates some wgpu tests that are sensitive to the timing of error reporting.

**Squash or Rebase?** Rebase, but check for fixups that should be squashed first.

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] Add a `CHANGELOG.md` entry.

### CODE REVIEW

File: wgpu-core/src/command/mod.rs [hunk 1]
```diff
@@ -854,6 +897,40 @@ impl<C: Clone> BasePass<C> {
...
+        match $res.map_pass_err($scope) {
+            Ok(val) => val,
+            Err(err) => {
+                $base.error.get_or_insert(err);
+                return Ok(());
+            }
+        }
+    };
+}
+pub(crate) use pass_try;
```
Comment (teoxoy) [inline wgpu-core/src/command/mod.rs]: Could these 2 macros be methods on the pass/base instead? Ideally we shouldn't have hidden control flow inside macros.

**Review by teoxoy — COMMENTED** [review]
Looks good overall!

File: wgpu-core/src/command/mod.rs (hunk 1 above)
Comment (andyleiserson) [reply wgpu-core/src/command/mod.rs]: There are two difficulties here, a major one and a minor one. The major difficulty is that we want early-return behavior with a return value of `Ok(())`. The minor difficulty is that implementing `pass_base!` as a helper on `BasePass` has borrow checker problems in some cases (when it's not done inline, `&mut pass.base` becomes `&mut pass` for purposes of conflicting mutable borrows).

I do appreciate the point about hidden control flow in macros though. The name `pass_try!` is a reference to `try!` which was the precursor to `?`, but perhaps that's too obscure to be useful documentation.

Before the current version I had a version where `base_mut` returned `Result<&mut BasePass, Result<(), Err>>`. Then the caller could do `if let Err(e) = ... { return e; }`. I dislike nested result/option types, but unlike control flow in a macro, at least the complexity is obvious. I'm not opposed to going back to that. Or it might be possible to do something with a closure here like I did for the encoder operations.

**Comment by andyleiserson** [comment]
I said in the meeting this morning that the change to report destroyed resources on submit was not in this PR, but it actually is. There's a helper [here](https://github.com/gfx-rs/wgpu/pull/7820/files#diff-1fe34f06c0c0bd67a41a9cb8aa26cae0a2a4b58028ce5e064abb6f8ad23b84cfR1007) that decides which errors will be deferred. It's a bit of a kludge and risks the match statement going stale, but on the other hand, I don't think anything catastrophic happens if it's wrong, we just report an error at the wrong time.

File: wgpu-core/src/command/mod.rs (hunk 1 above)
Comment (teoxoy) [reply wgpu-core/src/command/mod.rs]: I see, I think we can keep the macros then. It might be useful if they had some docs on them mentioning the hidden control flow and maybe the rationale for their existence (effectively copying the paragraph in your comment).

Leaving this up to you - I'll approve the PR!

**Review by teoxoy — APPROVED** [review]

File: wgpu-core/src/command/mod.rs (hunk 1 above)
Comment (andyleiserson) [reply wgpu-core/src/command/mod.rs]: Yes, these should definitely have comments, I've added some.
