### PR TITLE
Remove HashMaps from `wgpu` API

### LINKED ISSUE #7019: Conflict between type of `HashMap` in `PipelineCompilationOptions` and `HashMap` exposed by the surface API
**Description**

Currently, the type `PipelineCompilationOptions` has a field `constants` of type that is directly defined as `hashbrown::HashMap`.

However, that type is not exposed to the surface API, making it impossible for the user to declare an object of the same type and then pass to `constants` (unless I am missing how this type is re-exported from the WGPU crate).

Using `[FashHashMap](wgpu::naga::FastHashMap)` (which is an alias of `hashbrown::HashMap`) is also an error, as it uses a hasher different than the one that `constants` expects. Bellow is the case of using `wgpu::naga::FastHashMap<>`:

```rust
let mut vertex_hash_map_constant: wgpu::naga::FastHashMap<String, f64> = Default::default();
for /* ... */ {
    wgpu::naga::FastHashMap::insert(
        // ...
    );
}
let vertex_wgpu_pipeline_compilation_options = wgpu::PipelineCompilationOptions {
    constants: &vertex_hash_map_constant,
    // ...
};
```
Error (minus personal information in the output):
```sh
error[E0308]: mismatched types
    |
126 |                 constants: &vertex_hash_map_constant,
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&HashMap<String, f64>`, found `&HashMap<String, f64, BuildHasherDefault<FxHasher>>`
    |
    = note: expected reference `&hashbrown::map::HashMap<_, _, foldhash::seed::fast::RandomState>`
               found reference `&hashbrown::map::HashMap<_, _, BuildHasherDefault<rustc_hash::FxHasher>>`
```

**Expected vs observed behavior**
Either the hashmap type should be exposed in a way that will not cause confusion to the user, or `PipelineCompilationOptions` should use a generic type that then WGPU converts internally in whatever it uses.

**Platform**

WGPU version: https://github.com/gfx-rs/wgpu/commit/65d499f302fe3482207147d2c70892c12030b442

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Closes #7019 

This changes the surface apis over to arrays of key-value pairs.

### CODE REVIEW

File: wgpu/src/api/common_pipeline.rs [hunk 1]
```diff
@@ -24,14 +24,8 @@ pub struct PipelineCompilationOptions<'a> {
 
 impl Default for PipelineCompilationOptions<'_> {
     fn default() -> Self {
-        // HashMap doesn't have a const constructor, due to the use of RandomState
-        // This does introduce some synchronisation costs, but these should be minor,
-        // and might be cheaper than the alternative of getting new random state
-        static DEFAULT_CONSTANTS: std::sync::OnceLock<HashMap<String, f64>> =
-            std::sync::OnceLock::new();
-        let constants = DEFAULT_CONSTANTS.get_or_init(Default::default);
```
Comment (DJMcNab) [inline wgpu/src/api/common_pipeline.rs:32]: :fire: Glad to see this gone

File: wgpu/src/api/shader_module.rs [hunk 2]
```diff
@@ -186,8 +186,10 @@ pub enum ShaderSource<'a> {
         shader: Cow<'a, str>,
         /// The shader stage that the shader targets. For example, `naga::ShaderStage::Vertex`
         stage: naga::ShaderStage,
-        /// Defines to unlock configured shader features.
-        defines: naga::FastHashMap<String, String>,
+        /// Key-value pairs to represent defines sent to the glsl preprocessor.
+        ///
+        /// If the same name is defined multiple times, the last value is used.
+        defines: &'a [(String, String)],
```
Comment (DJMcNab) [inline wgpu/src/api/shader_module.rs]: Since we now clone these to make a map, I don't think there's any advantage to this being `String` over `&'a str`.

File: CHANGELOG.md [hunk 3]
```diff
@@ -40,6 +40,17 @@ Bottom level categories:
 
 ## Unreleased
 
+### Major Changes
+
+#### Hashmaps Removed from Apis
+
+Both `PipelineCompilationOptions::constants` and `ShaderSource::Glsl::defines` now take
+arrays with a list of key-value pairs instead of hashmaps. This is to prepare for no-std
```
Comment (DJMcNab) [inline CHANGELOG.md]: Maybe "slices containing key-value pairs"?

File: CHANGELOG.md [hunk 4]
```diff
@@ -40,6 +40,17 @@ Bottom level categories:
...
+support and allow us to keep which hashmap hasher and such as implementation details. It
```
Comment (ErichDonGubler) [inline CHANGELOG.md]: typo: 

```suggestion
support and allow us to keep which `hashmap` hasher and such as implementation details. It
```

File: CHANGELOG.md [hunk 5]
```diff
@@ -40,6 +40,17 @@ Bottom level categories:
 
 ## Unreleased
 
+### Major Changes
+
+#### Hashmaps Removed from Apis
```
Comment (ErichDonGubler) [inline CHANGELOG.md]: typo:

```suggestion
#### Hashmaps Removed from APIs
```

File: CHANGELOG.md (hunk 3 above)
Comment (ErichDonGubler) [inline CHANGELOG.md]: typo:

```suggestion
arrays with a list of key-value pairs instead of hashmaps. This is to prepare for `no_std`
```

Comment (ErichDonGubler) [reply CHANGELOG.md]: Third option: "slices _of_ key-value pairs", maybe?

File: wgpu/src/api/shader_module.rs (hunk 2 above)
Comment (ErichDonGubler) [reply wgpu/src/api/shader_module.rs]: Yeah, we should definitely take advantage to avoid allocations, if we can! 😀

**Review by ErichDonGubler — APPROVED** [review]
LGTM, minus some nits and other things raised by @DJMcNab. Conditionally approving based on these getting addressed.

File: wgpu/src/api/shader_module.rs (hunk 2 above)
Comment (cwfitzgerald) [reply wgpu/src/api/shader_module.rs]: There's some question if people are going to keep their list of defines around they need `[(String, String)]`, so they'd need to remake the array every time. Probably not a big enough problem in practice, this isn't hot code.
