### PR TITLE
[naga hlsl-out, glsl-out] Support atomicCompareExchangeWeak

### LINKED ISSUE #4364: Implement atomicCompareExchangeWeak
See https://github.com/gpuweb/gpuweb/pull/2113

### LINKED ISSUE #7578: Internal error in writing type when atomicCompareExchangeWeak is used in compute shader, on GL backend
**Description**
When `atomicCompareExchangeWeak` is called in compute shader, on a GL backend, `wgpu` will report internal error:
```
Caused by:
      In Device::create_compute_pipeline
        Internal error: Unable to write type Struct { members: [StructMember { name: Some("old_value"), ty: [3], binding: None, offset: 0 }, StructMember { name: Some("exchanged"), ty: [8], binding: None, offset: 4 }], span: 8 }
```

**Repro steps**
I'm reusing a repo I created for exploring other things: https://github.com/suguruwataru/wgsl-loop
The branch `atomic-compare-exchange-weak` contains a test that just runs a compute shader calling
`atomicCompareExchangeWeak`:
https://github.com/suguruwataru/wgsl-loop/tree/atomic-compare-exchange-weak

`cargo test` to run it, and you should see the internal error being reported.

**Expected vs observed behavior**
Expectation is `atomicCompareExchangeWeak` won't cause an internal error and be successfully translated.

**Platform**
I was running it on Linux without Vulkan driver. I have tried `wgpu 23.0.1` and `wgpu 25.0.0`.

### PR DESCRIPTION
**Pull request by cryvosh**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/7578
Fixes https://github.com/gfx-rs/wgpu/issues/4364

**Description**
Adds support for atomicCompareExchangeWeak translation to hlsl and glsl.

Note this does not implement the [allow_uav_condition] loop attribute mentioned [here](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/interlockedcompareexchange) and [here](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-for). 
Not sure the best way to check if the loop termination is based off a UAV read. 
Maybe can later borrow logic from the uniformity analyzer?
Dawn doesn't seem to do this either, though maybe it should?
There is a test with a while loop that depends on .exchanged which seems to pass hlsl validation.

**Testing**
Added / enabled some basic atomicCompareExchangeWeak tests to Naga.
My personal project using atomicCompareExchangeWeak runs fine now on Windows/Nvidia/DX12.
GL backend is untested outside the Naga tests / validation.

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by teoxoy** [comment]
> Note this does not implement the [allow_uav_condition] loop attribute mentioned [here](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/interlockedcompareexchange) and [here](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-for).
> Not sure the best way to check if the loop termination is based off a UAV read.
> Maybe can later borrow logic from the uniformity analyzer?
> Dawn doesn't seem to do this either, though maybe it should?
> There is a test with a while loop that depends on .exchanged which seems to pass hlsl validation.

I don't see DXC doing anything with the `[allow_uav_condition]` attribute https://github.com/search?q=repo%3Amicrosoft%2FDirectXShaderCompiler%20HLSLAllowUAVCondition&type=code, maybe it's legacy.

File: naga/src/back/hlsl/writer.rs [hunk 1]
```diff
@@ -4287,6 +4286,38 @@ impl<'a, W: fmt::Write> super::Writer<'a, W> {
...
+        value: Handle<crate::Expression>,
+        res_var_info: &Option<(Handle<crate::Expression>, String)>,
+    ) -> BackendResult {
+        if let Some(cmp) = compare_expr {
+            write!(self.out, ", ")?;
+            self.write_expr(module, cmp, func_ctx)?;
+        }
+        write!(self.out, ", ")?;
+        if let crate::AtomicFunction::Subtract = *fun {
+            write!(self.out, "-")?;
```
Comment (teoxoy) [inline naga/src/back/hlsl/writer.rs:4338]: I think we should keep the comment since it's unexpected that we use `InterlockedAdd` for `AtomicFunction::Subtract`.

File: naga/src/back/hlsl/writer.rs [hunk 2]
```diff
@@ -2358,79 +2358,78 @@ impl<'a, W: fmt::Write> super::Writer<'a, W> {
...
-                        return Err(Error::Unimplemented("atomic CompareExchange".to_string()));
+                if let Some(cmp) = compare_expr {
+                    if let Some(&(res_handle, ref res_name)) = res_var_info.as_ref() {
+                        write!(
+                            self.out,
+                            "{level}{res_name}.exchanged = ({res_name}.old_value == "
+                        )?;
+                        self.write_expr(module, cmp, func_ctx)?;
+                        writeln!(self.out, ");")?;
+                        self.named_expressions.insert(res_handle, res_name.clone());
```
Comment (teoxoy) [inline naga/src/back/hlsl/writer.rs]: We already register the named expression in `emit_hlsl_atomic_tail`.

File: naga/src/back/hlsl/writer.rs [hunk 3]
```diff
@@ -2358,79 +2358,78 @@ impl<'a, W: fmt::Write> super::Writer<'a, W> {
...
-
-                // Validation ensures that `pointer` has a `Pointer` type.
                 let pointer_space = func_ctx
                     .resolve_type(pointer, &module.types)
                     .pointer_space()
                     .unwrap();
-
                 let fun_str = fun.to_hlsl_suffix();
+                let compare_expr = match *fun {
+                    crate::AtomicFunction::Exchange { compare: Some(cmp) } => Some(cmp),
```
Comment (teoxoy) [inline naga/src/back/hlsl/writer.rs:2387]: We need to add `cmp` to `need_bake_expressions` to make sure that the expression chain doesn't get written multiple times. See `crate::Statement::SubgroupCollectiveOperation` for an example.

File: naga/src/back/glsl/mod.rs [hunk 4]
```diff
@@ -787,23 +791,36 @@ impl<'a, W: Write> Writer<'a, W> {
         // you can't make a struct without adding all of its members first.
         for (handle, ty) in self.module.types.iter() {
             if let TypeInner::Struct { ref members, .. } = ty.inner {
+                // Skip special atomic compare exchange result structs (generated in next loop)
+                let struct_name = &self.names[&NameKey::Type(handle)];
+                if struct_name.starts_with("_atomic_compare_exchange_result") {
+                    continue;
+                }
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs]: Why not allow the code below to generate them?

File: naga/src/back/glsl/mod.rs [hunk 5]
```diff
@@ -1118,6 +1140,17 @@ impl<'a, W: Write> Writer<'a, W> {
...
+        for (key, &handle) in self.module.special_types.predeclared_types.iter() {
+            if handle == ty {
+                if let crate::PredeclaredType::AtomicCompareExchangeWeakResult(_) = *key {
+                    let name = &self.names[&NameKey::Type(ty)];
+                    write!(self.out, "{name}")?;
+                    return Ok(());
+                }
+                break;
+            }
+        }
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs]: I think the code below should handle structs properly, is this needed?

File: naga/src/back/glsl/mod.rs [hunk 6]
```diff
@@ -2572,33 +2605,49 @@ impl<'a, W: Write> Writer<'a, W> {
...
-                write!(self.out, "atomic{fun_str}(")?;
-                self.write_expr(pointer, ctx)?;
-                write!(self.out, ", ")?;
-                // handle the special cases
                 match *fun {
-                    crate::AtomicFunction::Subtract => {
-                        // we just wrote `InterlockedAdd`, so negate the argument
-                        write!(self.out, "-")?;
+                    crate::AtomicFunction::Exchange {
+                        compare: Some(compare_expr),
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs:2593]: `compare_expr` needs to be added to `need_bake_expressions`.

File: naga/src/back/glsl/mod.rs [hunk 7]
```diff
@@ -2572,33 +2605,49 @@ impl<'a, W: Write> Writer<'a, W> {
...
+                            self.write_type(ctx.info[result].ty.handle().unwrap())?;
+                            write!(self.out, " {res_name} = ")?;
+                            self.named_expressions.insert(result, res_name);
+                        }
+                        let fun_str = fun.to_glsl();
+                        write!(self.out, "atomic{fun_str}(")?;
+                        self.write_expr(pointer, ctx)?;
+                        write!(self.out, ", ")?;
+                        if let crate::AtomicFunction::Subtract = *fun {
+                            write!(self.out, "-")?;
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs:2628]: It would be worth mentioning that we use `atomicAdd` for `crate::AtomicFunction::Subtract`.

**Review by teoxoy — CHANGES_REQUESTED** [review]

File: naga/src/back/glsl/mod.rs (hunk 6 above)
Comment (cryvosh) [reply naga/src/back/glsl/mod.rs:2593]: I added this logic directly here, but would it be better somewhere else like in `update_expressions_to_bake`?

File: naga/src/back/hlsl/writer.rs (hunk 2 above)
Comment (cryvosh) [reply naga/src/back/hlsl/writer.rs]: Removed redundant registration in `emit_hlsl_atomic_tail`

File: naga/src/back/hlsl/writer.rs (hunk 3 above)
Comment (cryvosh) [reply naga/src/back/hlsl/writer.rs:2387]: Inserted cmp immediately after but let me know if there's a better place to do it

File: naga/src/back/hlsl/writer.rs (hunk 1 above)
Comment (cryvosh) [reply naga/src/back/hlsl/writer.rs:4338]: Added a comment

File: naga/src/back/glsl/mod.rs (hunk 4 above)
Comment (cryvosh) [reply naga/src/back/glsl/mod.rs]: Removed redundant code

File: naga/src/back/glsl/mod.rs (hunk 5 above)
Comment (cryvosh) [reply naga/src/back/glsl/mod.rs]: Removed redundant code

File: naga/src/back/glsl/mod.rs (hunk 7 above)
Comment (cryvosh) [reply naga/src/back/glsl/mod.rs:2628]: Added a comment

File: naga/src/back/glsl/mod.rs (hunk 6 above)
Comment (teoxoy) [reply naga/src/back/glsl/mod.rs:2593]: Yeah it should go in `update_expressions_to_bake` since it might be too late to register it here.

File: naga/src/back/hlsl/writer.rs (hunk 3 above)
Comment (teoxoy) [reply naga/src/back/hlsl/writer.rs:2387]: Same comment as the GLSL backend, this should go in `update_expressions_to_bake`.

Comment (cryvosh) [reply naga/src/back/hlsl/writer.rs:2387]: Moved inside the loop over `statement in func.body` in `update_expressions_to_bake`

File: naga/src/back/glsl/mod.rs (hunk 6 above)
Comment (cryvosh) [reply naga/src/back/glsl/mod.rs:2593]: Added a loop over `statement in func.body` and moved this logic there

**Comment by teoxoy** [comment]
Thanks for addressing the comments, PR looks good - let's land it!

**Review by teoxoy — APPROVED** [review]
