### PR TITLE
[deno] Fix dropping of command encoders/buffers, and an enum typo

### LINKED ISSUE #7797: Intermittent `cannot remove a vacant resource` panics running in deno
This is reproducible for me (Mac M1) by running `cargo xtask cts 'webgpu:api,validation,encoding,cmds,copyTextureToTexture:texture_format_compatibility:*'`. It doesn't always panic at the same place. Without the #7391 fixes, the tests fail, but this problem is reproducible either with or without the error reporting changes.

I was not able to reproduce in Firefox, so I've tentatively marked this as a deno issue, although given the nature of the problem, that may or may not be accurate.

### PR DESCRIPTION
**Pull request by andyleiserson**
Fixes #7797, a double-free error in deno. Command encoders, since they are the same wgpu object as the command buffer they become, should not be dropped after a buffer has been created from that encoder. Separately, I think command buffers should be explicitly dropped, even after they have been submitted. 

Also fixes a typo in the GPUTextureFormat conversion.

This resolves a crash in the `copyTextureToTexture` tests, but they are still failing due to #7391, so they cannot be added to the regression until that is fixed.

**Testing**
Enables some CTS tests related to `Queue.submit`. As noted in a comment, the error reported if `CommandEncoder.finish` is called twice is not right, and I would not expect a CTS test for that to pass, but I also can't find one, so I made a note in https://github.com/gpuweb/cts/pull/4401 to add it.

**Squash or Rebase?** Squash

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [ ] Run `cargo xtask test` to run tests.
- [x] Run `cargo xtask cts`.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: deno_webgpu/command_encoder.rs [hunk 1]
```diff
@@ -407,23 +416,33 @@ impl GPUCommandEncoder {
     fn finish(
         &self,
         #[webidl] descriptor: crate::command_buffer::GPUCommandBufferDescriptor,
-    ) -> GPUCommandBuffer {
+    ) -> Result<GPUCommandBuffer, JsErrorBox> {
         let wgpu_descriptor = wgpu_types::CommandBufferDescriptor {
             label: crate::transform_label(descriptor.label.clone()),
         };
 
+        // TODO: This is not right, it should be a validation error, and it
```
Comment (andyleiserson) [inline deno_webgpu/command_encoder.rs]: This should be an issue but I'll hold off on making it in case there's an objection to leaving things in this state.

- [x] Create issue

**Review by crowlKats — APPROVED** [review]

File: deno_webgpu/command_encoder.rs (hunk 1 above)
Comment (andyleiserson) [reply deno_webgpu/command_encoder.rs]: https://github.com/gfx-rs/wgpu/issues/7812. I realized that it is not just a deno issue, wgpu also has the problem described here.
