### PR TITLE
Free command encoders' platform resources on drop on _all_ platforms

### LINKED ISSUE #3193: Early frees on CPU Implementations
Found in https://github.com/gfx-rs/wgpu/pull/3174#issuecomment-1305624133
Related: #3031, #2285

**Description**
Getting DX12 errors

```
[ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandAllocator::Reset: A command allocator 0x000001FD96C262F0:'Unnamed ID3D12CommandAllocator Object' is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]
[ERROR wgpu_hal::auxil::dxgi::exception] ID3D12Resource2::<final-release>: CORRUPTION: An ID3D12Resource object (0x000001FD96C25E80:'(wgpu internal) Staging') is referenced by GPU operations in-flight on Command Queue (0x000001FD96B64D10:'Unnamed ID3D12CommandQueue Object').  It is not safe to final-release objects that may have GPU operations pending.  This can result in application instability. [ EXECUTION ERROR #921: OBJECT_DELETED_WHILE_STILL_IN_USE]
```
or 
```
[ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandAllocator::Reset: The command allocator cannot be reset because a command list is currently being recorded with the allocator. [ EXECUTION ERROR #543: COMMAND_ALLOCATOR_CANNOT_RESET]
```
depending if `queue.submit` is called in the repro below.

This feels like a timing issue (also pointed out by @kvark in https://github.com/gfx-rs/wgpu/issues/2285#issuecomment-992769687) since I could only reproduce this locally by increasing `array_size` to `2048`. I also can't reproduce the issue on actual hardware (tried on an Nvidia dGPU and Intel iGPU).

**Repro steps**
```rust
use wgpu::{
    BindGroupDescriptor, BindGroupEntry, BindGroupLayoutDescriptor, BindGroupLayoutEntry,
    BindingType, BufferBindingType, BufferDescriptor, BufferUsages, CommandEncoderDescriptor,
    ComputePassDescriptor, ComputePipelineDescriptor, DownlevelFlags, Limits,
    PipelineLayoutDescriptor, ShaderModuleDescriptor, ShaderSource, ShaderStages,
};

use crate::common::{initialize_test, TestParameters, TestingContext};

#[test]
fn test() {
    initialize_test(
        TestParameters::default()
            .downlevel_flags(DownlevelFlags::COMPUTE_SHADERS)
            .limits(Limits::downlevel_defaults()),
        test_impl,
    );
}

const SRC: &'static str = r#"
let array_size = 2048u; // increase this if you can't reproduce

var<workgroup> w_mem: array<u32, array_size>;

@group(0) @binding(0)
var<storage, read_write> output: u32;

@compute @workgroup_size(1)
fn main() {
    w_mem = array<u32, array_size>();
    workgroupBarrier();

    var is_zero = true;
    for(var i = 0u; i < array_size; i++) {
        is_zero &= w_mem[i] == 0u;
    }
    output = u32(!is_zero);
}
"#;

fn test_impl(ctx: TestingContext) {
    let bgl = ctx
        .device
        .create_bind_group_layout(&BindGroupLayoutDescriptor {
            label: None,
            entries: &[BindGroupLayoutEntry {
                binding: 0,
                visibility: ShaderStages::COMPUTE,
                ty: BindingType::Buffer {
                    ty: BufferBindingType::Storage { read_only: false },
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            }],
        });

    let output_buffer = ctx.device.create_buffer(&BufferDescriptor {
        label: None,
        size: 4,
        usage: BufferUsages::COPY_DST | BufferUsages::STORAGE,
        mapped_at_creation: false,
    });

    let bg = ctx.device.create_bind_group(&BindGroupDescriptor {
        label: None,
        layout: &bgl,
        entries: &[BindGroupEntry {
            binding: 0,
            resource: output_buffer.as_entire_binding(),
        }],
    });

    let pll = ctx
        .device
        .create_pipeline_layout(&PipelineLayoutDescriptor {
            label: None,
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });

    let sm = ctx.device.create_shader_module(ShaderModuleDescriptor {
        label: None,
        source: ShaderSource::Wgsl(SRC.into()),
    });

    let pipeline = ctx
        .device
        .create_compute_pipeline(&ComputePipelineDescriptor {
            label: None,
            layout: Some(&pll),
            module: &sm,
            entry_point: "main",
        });

    ctx.queue
        .write_buffer(&output_buffer, 0, bytemuck::cast_slice(&[1])); // if this is here, we get OBJECT_DELETED_WHILE_STILL_IN_USE

    let mut encoder = ctx
        .device
        .create_command_encoder(&CommandEncoderDescriptor::default());

    let mut cpass = encoder.begin_compute_pass(&ComputePassDescriptor::default());
    cpass.set_pipeline(&pipeline);
    cpass.set_bind_group(0, &bg, &[]);
    cpass.dispatch_workgroups(1, 1, 1);
    drop(cpass);

    ctx.queue.submit(Some(encoder.finish())); // if this is removed, we get COMMAND_ALLOCATOR_CANNOT_RESET
}
```

**Expected vs observed behavior**
No errors.

**Platform**
Windows 11, wgpu master (08b160c2932a44adedd9411bd882bc7ef41ea270)

### PR DESCRIPTION
**Pull request by ErichDonGubler**
**Connections**
_Link to the issues addressed by this PR, or dependent PRs in other repositories_

This is my attempt to investigate and resolve <https://github.com/gfx-rs/wgpu/issues/3193>. ~I believe this code is ready to go, but have not yet confirmed internal details to my satisfaction. I'm leaving this as WIP for now because I will be unavailable to work on finalizing details until \~2024-02-21. If somebody wants to pick it up before then, great!~

**Description**
_Describe what problem this is solving, and how it's solved._

I believe that #3193 is caused by not freeing command encoders early enough. This is apparent on the DX12 backend, where the DX12 API actually emits an error to inform us of our mistake. This is likely causing issues in other backends (i.e., Vulkan), where the symptoms aren't as obvious. Metal has already been cared for by @bradwerth with #2077, so only the other backends need attention here.

Interestingly, we don't currently do any clean-up of command encoders when they are dropped, but we do when they're `finish`ed. This seems wrong. So, this change adds a `CommandEncoder::discard_encoding` call for command encoders within `wgpu_core::Global::command_encoder_drop`. This change also adds a similar call to the `Drop` implementation of backends that appear to be idempotent in their `CommandEncoder::discard_encoder` calls (N.B., this does not include Vulkan). This appears to resolve DX12 API errors.

To be completely clear about how each backend is changed here:

| Backend | Status before this PR     | Status after this PR |
| ------- | ------------------------- | -------------------- |
| Vulkan  | Possibly has issues       | ✅Fixed.             |
| DX12    | Reporting hard errors     | ✅No more errors!    |
| Metal   | Already handled by #2077. | -                    |
| GLES    | Possibly has issues       | ✅Fixed.             |

**Testing**
_Explain how this change is tested._

~A test (`wgpu_test::buffer::command_encoder_without_finish_fine`) has been added, demonstrating both the expected failure before the fix and resolution to "just" passing.~

This change changes numerous expected error cases for tests for `DX12`, most notably `wgpu_tests::encoder::drop_encoder_after_error`, to simply be passing.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [x] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: wgpu-core/src/device/global.rs [hunk 1]
```diff
@@ -1377,6 +1377,7 @@ impl Global {
             .command_buffers
             .unregister(command_encoder_id.transmute())
         {
+            cmd_buf.data.lock().as_mut().unwrap().encoder.discard();
```
Comment (ErichDonGubler) [inline wgpu-core/src/device/global.rs:1380]: This `wgpu-core`-centric change might be relevant to the issue that #4023 was trying to solve in Metal; ~~perhaps that fix is no longer necessary, with this in place~~? CC @bradwerth.

- [x] Investigate.

EDIT: Changed my mind, see below.

Comment (ErichDonGubler) [reply wgpu-core/src/device/global.rs:1380]: This also means that the test I had added before is redundant, woot!

Comment (ErichDonGubler) [reply wgpu-core/src/device/global.rs:1380]: I think the appropriate solution is actually to have every encoder for a specific back end discard itself on drop. That makes sense for _any_ stand-alone structure that can definitively conclude OS platform resource usage on `Drop` (minus maybe needing diagnostic context to report issues). We could also have the core abstraction discard the encoding—it would be redundant, technically, but I don't see that as a bad thing.

Comment (ErichDonGubler) [reply wgpu-core/src/device/global.rs:1380]: Added a `Drop` impl. for DX12. Also added one for GLES.

It seems that Vulkan specifically does not appear to track its current state, relying on correct usage from `wgpu-core`. I won't add a `Drop` call to `discard_encoding` for that backend.

**Review by nical — APPROVED** [review]

File: wgpu-core/src/device/global.rs (hunk 1 above)
Comment (ErichDonGubler) [reply wgpu-core/src/device/global.rs:1380]: Added a follow-up for Vulkan at <https://github.com/gfx-rs/wgpu/issues/5255> .

**Comment by torokati44** [comment]
*anxiously waiting for a release with this fix in, preferably in the `0.19` series*
https://github.com/ruffle-rs/ruffle/actions/runs/8046091966/job/21972653869

**Comment by ErichDonGubler** [comment]
@torokati44: Have you confirmed that this fix addresses an issue in Ruffle? It's unclear if the CI issue you're linking is caused by this fix, or fixed by this fix. 😅

**Comment by torokati44** [comment]
Since Ruffle is on `v0.19.1`, which was released before this got merged, the CI issue is definitely _not caused_ by this PR, but _hopefully fixed_ by it.
And, no, haven't verified it yet, but I'd give it more than 60% chance, just by gut feeling. :no_mouth:

**Comment by torokati44** [comment]
So this did not end up being backported into `0.19.2`? :face_with_spiral_eyes:

**Comment by ErichDonGubler** [comment]
@cwfitzgerald ☝🏻

**Comment by cwfitzgerald** [comment]
Agh - I honestly thought this PR was caught up in all the other internal work, I didn't realize it was so backportable. There will be a 0.19.3 decently soon, so I'll include this in that
