### PR TITLE
Move ordered usages to hals

### LINKED ISSUE #8853: Vulkan backend incorrectly skips barriers
[wgpu-core](https://github.com/gfx-rs/wgpu/blob/trunk/wgpu-core/src/track/mod.rs#L340) contains logic to skip unnecessary barriers if the usage hasn't changed and is "ordered". What uses count as ordered are defined in [wgpu-types](https://github.com/gfx-rs/wgpu/blob/trunk/wgpu-types/src/texture.rs#L258). This includes `Self::COLOR_TARGET.bits() | Self::DEPTH_STENCIL_WRITE.bits()`.

While this may be true for DX12 when using legacy barriers (no need to transition from `RENDER_TARGET` to `RENDER_TARGET` (I am not a DX12 expert)), this is _not true_ in Vulkan. [Vulkan makes very few execution ordering guarantees.](https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#synchronization-implicit) The only guarantees are: order of primitives in the graphics pipeline, the order of image layout transitions (relative to other image layout transitions) and the order of pipeline stages within one command (ie. fragment shading happens after vertex shading). _Everything else_ can execute out of order / in parallel unless an execution dependency is issued. For instance, on a tiled architecture, two render passes will execute in parallel, regardless of submission order, unless some synchronization primitive is used to ensure the order.

Additionally, for write-after-write and read-after-write hazards, ensuring correct execution order is not enough. Memory dependencies must also be expressed to ensure correct cache flushing/invalidation.

This is the case in Bevy's Android example, which contains two render passes:

1. Render pass 1 renders the 3D scene.
2. Render pass 2 renders a 2D overlay.

Both render passes render to the same color attachment. This is a write-after-write hazard, which requires a pipeline barrier from `COLOR_ATTACHMENT_OUTPUT_BIT` to `COLOR_ATTACHMENT_OUTPUT_BIT` with the associated image memory barrier. wgpu incorrectly skips the barrier since both uses of the color attachment are `COLOR_TARGET`, which is considered ordered. This leads to these rendering artifacts on Immortalis-G715:

https://github.com/user-attachments/assets/20f83932-05eb-43c1-ace3-8680d8cf7bab

Removing `Self::COLOR_TARGET.bits() | Self::DEPTH_STENCIL_WRITE.bits()` from `ORDERED` fixes the artifacts (remaining uses aren't "ordered" by Vulkan either but are read-only so ordering doesn't matter). However, removing them may negatively affect other backends (at least DX12). So I believe the proper solution is to move the barrier skipping logic from wgpu-core/wgpu-types to wgpu-hal on a per-backend basis as different backends have different synchronization requirements.

### PR DESCRIPTION
**Pull request by NiklasEi**
**Connections**
Resolves #8853 (and thus bevyengine/bevy#14710)

**Description**
Currently, ordered usage is defined globally for all hals. According to #8853 this is problematic and the current ordered usages are not correct for Vulkan.
This PR moves the ordered usages into the different hals. It also removes the two wrong ordered usages for Vulkan. 

**Testing**
I ran the standalone examples on my linux machine (NVIDIA RTX 2000 Ada).

**Squash or Rebase?**

Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [ ] Run `cargo xtask test` to run tests.
  - I have 15 failing tests, but the same are also failing on latest `trunk`
  - > 
        FAIL [   0.004s] naga::naga snapshots::convert_snapshots_spv
        FAIL [   1.680s] wgpu-examples [Executed Failure: BACKEND] [Vulkan/Intel(R) Graphics (RPL-S)/0] water
        FAIL [   1.790s] wgpu-examples [Executed Failure: BACKEND] [Vulkan/llvmpipe (LLVM 19.1.1, 256 bits)/2] water
        FAIL [   0.180s] wgpu-examples [Executed] [Vulkan/Intel(R) Graphics (RPL-S)/0] wgpu_examples::cooperative_matrix::tests::cooperative_matrix
        FAIL [   3.807s] wgpu-examples [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] multiple_render_targets
        FAIL [   3.638s] wgpu-examples [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] skybox-bc7
        FAIL [   3.726s] wgpu-examples [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] skybox-etc2
        FAIL [   5.871s] wgpu-test::wgpu-gpu [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] wgpu_gpu::clear_texture::clear_texture_uncompressed_gles
        FAIL [   5.571s] wgpu-examples [Executed Failure: BACKEND] [Vulkan/NVIDIA RTX 2000 Ada Generation Laptop GPU/1] water
        FAIL [   2.563s] wgpu-examples [Executed] [Vulkan/NVIDIA RTX 2000 Ada Generation Laptop GPU/1] wgpu_examples::cooperative_matrix::tests::cooperative_matrix
        FAIL [   2.107s] wgpu-test::wgpu-gpu [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] wgpu_gpu::render_target::draw_to_2d_view
        FAIL [   2.057s] wgpu-test::wgpu-gpu [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] wgpu_gpu::render_target::draw_to_3d_view
        FAIL [   2.259s] wgpu-test::wgpu-gpu [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] wgpu_gpu::render_target::draw_to_2d_array_view
        FAIL [   2.161s] wgpu-test::wgpu-gpu [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] wgpu_gpu::render_target::resolve_to_2d_array_view
        FAIL [   2.224s] wgpu-test::wgpu-gpu [Executed] [Gl/NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2/3] wgpu_gpu::render_target::resolve_to_2d_view
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by inner-daemons** [comment]
I'm interested in this so I'll take a look at some point, but I can't merge it myself.

File: wgpu-hal/src/dynamic/adapter.rs [hunk 1]
```diff
@@ -66,4 +70,12 @@ impl<A: Adapter + DynResource> DynAdapter for A {
...
         unsafe { A::get_presentation_timestamp(self) }
     }
+
+    fn get_buffer_ordered(&self) -> wgt::BufferUses {
+        A::get_buffer_ordered(self)
+    }
+
+    fn get_texture_ordered(&self) -> wgt::TextureUses {
+        A::get_texture_ordered(self)
+    }
```
Comment (inner-daemons) [inline wgpu-hal/src/dynamic/adapter.rs]: I like this approach!

**Comment by inner-daemons** [comment]
I'm just gonna let any future reviewer know than in [this comment](https://github.com/bevyengine/bevy/issues/14710#issuecomment-3796221522), this patch is confirmed to work. That makes multiple people with the bug completely going away so this is almost certainly the right fix.

Thanks for this @NiklasEi, we'll try to review & merge it soon-ish, plus I asked the maintainers about backporting this so it appears in a patch release like 28.0.1 rather than being pushed off until the next release in 2 months.

Valuable stuff!

File: wgpu-hal/src/vulkan/adapter.rs [hunk 2]
```diff
@@ -2789,6 +2789,14 @@ impl crate::Adapter for super::Adapter {
...
         }
     }
+
+    fn get_buffer_ordered(&self) -> wgt::BufferUses {
+        wgt::BufferUses::INCLUSIVE | wgt::BufferUses::MAP_WRITE
+    }
+
+    fn get_texture_ordered(&self) -> wgt::TextureUses {
+        wgt::TextureUses::INCLUSIVE | wgt::TextureUses::STORAGE_READ_ONLY
+    }
```
Comment (inner-daemons) [inline wgpu-hal/src/vulkan/adapter.rs]: I'd like to see docs for where this comes from, or explaining why this is correct

File: wgpu-hal/src/dx12/adapter.rs [hunk 3]
```diff
@@ -1220,6 +1220,17 @@ impl crate::Adapter for super::Adapter {
...
+    fn get_buffer_ordered(&self) -> wgt::BufferUses {
+        wgt::BufferUses::INCLUSIVE | wgt::BufferUses::MAP_WRITE
+    }
+
+    fn get_texture_ordered(&self) -> wgt::TextureUses {
+        wgt::TextureUses::INCLUSIVE
+            | wgt::TextureUses::COLOR_TARGET
+            | wgt::TextureUses::DEPTH_STENCIL_WRITE
+            | wgt::TextureUses::STORAGE_READ_ONLY
+    }
```
Comment (inner-daemons) [inline wgpu-hal/src/dx12/adapter.rs]: Same here, can you add a comment or link describing how you found these?

File: wgpu-core/src/track/texture.rs [hunk 4]
```diff
@@ -263,13 +259,18 @@ impl TextureStateSet {
...
 
 impl Default for TextureUsageScope {
     fn default() -> Self {
         Self {
             set: TextureStateSet::new(),
             metadata: ResourceMetadata::new(),
+            ordered_mask: TextureUses::INCLUSIVE
+                | TextureUses::COLOR_TARGET
+                | TextureUses::DEPTH_STENCIL_WRITE
+                | TextureUses::STORAGE_READ_ONLY,
```
Comment (inner-daemons) [inline wgpu-core/src/track/texture.rs]: These exact uses come up in many places, maybe you should put them somewhere and give them a name? Also, why couldn't we give this `TextureUses::empty()` and assume that it will be initialized later? Same goes for with the buffer usage scope thing.

Also, if the default doesn't matter, maybe initialize this to empty by default. This is a little unclear because you are assigning it an expression that has meaning but is never used.

**Review by inner-daemons — CHANGES_REQUESTED** [review]
A few comments/questions. Broadly LGTM! Also make sure to add a changelog entry

File: wgpu-hal/src/vulkan/adapter.rs (hunk 2 above)
Comment (NiklasEi) [reply wgpu-hal/src/vulkan/adapter.rs]: I have no experience with Vulkan (or any other graphics standards for that matter). This change is based on #8853 and the suggestion from @AlbinBernhardssonARM in that issue.

> Removing Self::COLOR_TARGET.bits() | Self::DEPTH_STENCIL_WRITE.bits() from ORDERED fixes the artifacts (remaining uses aren't "ordered" by Vulkan either but are read-only so ordering doesn't matter).

According to that comment, we might actually remove all of the ordered uses for Vulkan, but I was unsure if that has any consequences and they don't seem to hurt.

File: wgpu-hal/src/dx12/adapter.rs (hunk 3 above)
Comment (NiklasEi) [reply wgpu-hal/src/dx12/adapter.rs]: These values stayed the same, I just moved them here. I can certainly try to find sources, but this would probably be a lot faster if someone who knows the graphics APIs could point me to good sources for these values.

**Comment by NiklasEi** [comment]
> Also make sure to add a changelog entry

There are two entries now, one for the general move of ordered uses to the hals and one for the fix in Vulkan, I hope that is OK.

File: wgpu-hal/src/dx12/adapter.rs (hunk 3 above)
Comment (inner-daemons) [reply wgpu-hal/src/dx12/adapter.rs]: Maybe write a short comment that explains that `INCLUSIVE | STORAGE_READ_ONLY` are read-only and so don't cause any ordering hazards, while DX12 implicitly orders renderpasses on the same resources.

File: wgpu-hal/src/vulkan/adapter.rs (hunk 2 above)
Comment (inner-daemons) [reply wgpu-hal/src/vulkan/adapter.rs]: See my comment below. This looks right but I just want it to be explained :)

Comment (AlbinBernhardssonARM) [reply wgpu-hal/src/vulkan/adapter.rs]: We definitely still want to make sure we don't insert barriers between inclusive uses on Vulkan, as this would be unnecessary and have a performance impact. It's just the ordered/unorded naming and core/hal split that I find a bit confusing (the barrier skipping logic in core seems very much based around DX12 (without enhanced barriers)).

`STORAGE_READ_ONLY` is already in `INCLUSIVE`.

Comment (NiklasEi) [reply wgpu-hal/src/vulkan/adapter.rs]: > STORAGE_READ_ONLY is already in INCLUSIVE.

Thanks! I removed `STORAGE_READ_ONLY` everywhere.

File: wgpu-core/src/device/resource.rs [hunk 5]
```diff
@@ -259,6 +259,8 @@ pub struct Device {
     pub(crate) limits: wgt::Limits,
     pub(crate) features: wgt::Features,
     pub(crate) downlevel: wgt::DownlevelCapabilities,
+    pub(crate) buffer_ordered: wgt::BufferUses,
+    pub(crate) texture_ordered: wgt::TextureUses,
```
Comment (cwfitzgerald) [inline wgpu-core/src/device/resource.rs]:
```suggestion
    pub(crate) ordered_buffer_usages: wgt::BufferUses,
    pub(crate) ordered_texture_usages: wgt::TextureUses,
```

Naming nit, this feels clearer what it's trying to describe.

File: wgpu-core/src/track/buffer.rs [hunk 6]
```diff
@@ -81,13 +77,15 @@ impl BufferBindGroupState {
 pub(crate) struct BufferUsageScope {
     state: Vec<BufferUses>,
     metadata: ResourceMetadata<Arc<Buffer>>,
+    ordered_mask: BufferUses,
```
Comment (cwfitzgerald) [inline wgpu-core/src/track/buffer.rs]:
```suggestion
    ordered_uses_mask: BufferUses,
```

File: wgpu-core/src/track/texture.rs [hunk 7]
```diff
@@ -1290,14 +1307,19 @@ unsafe fn barrier(
...
     let new_state = unsafe { state_provider.get_state(Some(texture_selector), index) };
 
     match (current_state, new_state) {
         (SingleOrManyStates::Single(current_simple), SingleOrManyStates::Single(new_simple)) => {
-            if skip_barrier(current_simple, new_simple) {
+            if skip_barrier(
+                current_simple,
+                ordered_mask.contains(current_simple),
+                new_simple,
+            ) {
```
Comment (cwfitzgerald) [inline wgpu-core/src/track/texture.rs]: It feels cleaner to have skip_barrier take the ordered_mask directly, then internally call contains.

File: wgpu-hal/src/vulkan/adapter.rs [hunk 8]
```diff
@@ -2794,6 +2794,17 @@ impl crate::Adapter for super::Adapter {
             wgt::PresentationTimestamp::INVALID_TIMESTAMP
         }
     }
+
+    fn get_buffer_ordered(&self) -> wgt::BufferUses {
+        wgt::BufferUses::INCLUSIVE | wgt::BufferUses::MAP_WRITE
+    }
+
+    // Vulcan makes very few execution ordering guarantees
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/adapter.rs]:
```suggestion
    // Vulkan makes very few execution ordering guarantees
```

File: wgpu-hal/src/vulkan/adapter.rs [hunk 9]
```diff
@@ -2794,6 +2794,17 @@ impl crate::Adapter for super::Adapter {
...
+    // see https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#synchronization-implicit
+    // We just don't want to insert barriers between inclusive uses
+    fn get_texture_ordered(&self) -> wgt::TextureUses {
```
Comment (cwfitzgerald) [inline wgpu-hal/src/vulkan/adapter.rs]: We should link the issues that discuss the missing barriers.

File: wgpu-hal/src/lib.rs [hunk 10]
```diff
@@ -786,6 +786,12 @@ pub trait Adapter: WasmNotSendSync {
     ///
     /// [`PresentationTimestamp`]: wgt::PresentationTimestamp
     unsafe fn get_presentation_timestamp(&self) -> wgt::PresentationTimestamp;
+
+    /// Returns the buffer uses that are guaranteed to be ordered.
+    fn get_buffer_ordered(&self) -> wgt::BufferUses;
+
+    /// Returns the texture uses that are guaranteed to be ordered.
+    fn get_texture_ordered(&self) -> wgt::TextureUses;
```
Comment (cwfitzgerald) [inline wgpu-hal/src/lib.rs]: I think this should have a bit more of an explanation of what "ordered" means in this content. You can take from the comments on the old ordered usage masks.

File: wgpu-core/src/device/resource.rs (hunk 5 above)
Comment (cwfitzgerald) [reply wgpu-core/src/device/resource.rs]: These don't need comments explaining everything about Ordering, but should at least note where to find more information about what ordering is and maybe a brief summary

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Thank you for tackling this! Mostly comments about naming and docs. I have commented on a few names, though there are more places where the same pattern should be applied - I want to make sure that new readers of the code understand what exactly the members represent.

File: wgpu-core/src/track/texture.rs (hunk 7 above)
Comment (NiklasEi) [reply wgpu-core/src/track/texture.rs]: I moved the `contains` call into `skip_barrier`, but had to adapt the generic a bit to be able to pass both `TextureUses` and `BufferUses` in.

File: wgpu-hal/src/noop/mod.rs [hunk 11]
```diff
@@ -283,6 +283,17 @@ impl crate::Adapter for Context {
...
+
+    fn get_ordered_buffer_usages(&self) -> wgt::BufferUses {
+        wgt::BufferUses::INCLUSIVE | wgt::BufferUses::MAP_WRITE
+    }
+
+    fn get_ordered_texture_usages(&self) -> wgt::TextureUses {
+        wgt::TextureUses::INCLUSIVE
+            | wgt::TextureUses::COLOR_TARGET
+            | wgt::TextureUses::DEPTH_STENCIL_WRITE
+            | wgt::TextureUses::STORAGE_READ_ONLY
```
Comment (inner-daemons) [inline wgpu-hal/src/noop/mod.rs]: Can be removed

**Review by inner-daemons — APPROVED** [review]
Reading through the changes here gave me a headache, its 99% just passing around the same stuff. You couldn't pay me to spend another minute looking at this. Nothing controversial though, lets get this merged

**Review by cwfitzgerald — APPROVED** [review]
I have an idea for a different design for this, but lets land this and I'll file an issue about a potential different design

**Comment by cwfitzgerald** [comment]
Thank you!
