### PR TITLE
[naga wgsl-in] Apply automatic conversions to sampling arguments.

### LINKED ISSUE #7427: `textureSampleLevel` doesn't promote `level` argument correctly
Naga rejects the following correct WGSL:

```wgsl
@group(0) @binding(0)
var t: texture_2d<f32>;

@group(0) @binding(1)
var s: sampler;

fn f() -> vec4<f32> {
  return textureSampleLevel(t, s, vec2f(), 0);
}
```

The error message is:

```
error: Function [0] 'f' is invalid
  ┌─ textureSampleLevel.wgsl:7:1
  │  
7 │ ╭ fn f() -> vec4<f32> {
8 │ │   return textureSampleLevel(t, s, vec2f(), 0);
  │ │          ^^^^^^^^^^^^^^^^^^ naga::ir::Expression [4]
  │ ╰──────────────────────────────────────────────^ naga::ir::Function [0]
  │  
  = Expression [4] is invalid
  = Sample level (exact) type [3] has an invalid type
```

### PR DESCRIPTION
**Pull request by jimblandy**
Depends on #7547 (but could be rebased if that's rejected).

Properly apply WGSL's automatic conversions to the arguments
to texture sampling functions.

Introduce helper function `Lowerer::expression_with_leaf_scalar`.

Although this can't affect behavior, use
`Lowerer::expression_for_abstract` for the `image` and `sampler`
arguments, simply because we want to move away from
`Lower::expression`'s automatic concretization, and move towards
having callers say explicitly what sort of conversions they need.

Although this can't affect behavior, use
`Lowerer::expression_with_leaf_scalar` for the `offset` argument, so
that the code spells out that this requires an `i32` value, rather
than depending on blind concretization giving it that.

Continue to use `Lowerer::expression` for `gather` and `array_index`,
since those happen to behave correctly with blind concretization, and
can be cleaned up later.

Fixes #7427.

### CODE REVIEW

**Comment by jimblandy** [comment]
I started out trying to apply the overload database to this, but it seems not to be suitable, for a few reasons:

- The texture sampling overloads are extremely regular, so the `proc::overloads::list::List` representation seems a shame. But they're only regular in that the texture's type dictates what arguments can follow, so `Regular` doesn't work well either.

- Constructing an `Expression::ImageSample` really works much better when we statically know which operand is which.

- It's nice to generate custom diagnostics for the image operations, which `OverloadSet` doesn't really facilitate.

So it turns out this is just more ad-hoc code in the WGSL front end. But I don't think it's too bad.

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -3287,79 +3300,106 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
             Texture::SampleLevel => {
-                let level = self.expression(args.next()?, ctx)?;
-                (ir::SampleLevel::Exact(level), None)
+                let exact = match class {
+                    // When applied to depth textures, `textureSampleLevel`'s
+                    // `level` argument is an `i32` or `u32`.
+                    ir::ImageClass::Depth { .. } => self.expression(args.next()?, ctx)?,
+
+                    // When applied to other sampled types, its `level` argument
+                    // is an `i32` or `u32`.
```
Comment (teoxoy) [inline naga/src/front/wgsl/lower/mod.rs]:
```suggestion
                    // is an `f32`.
```

**Review by teoxoy — APPROVED** [review]
Looks good!

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (jimblandy) [reply naga/src/front/wgsl/lower/mod.rs]: d'oh
