### PR TITLE
Make examples work again

### LINKED ISSUE #295: Fix C examples to support uint32 SPIR-V
We recently updated `read_file` to return `WGPUU32Array`, however the assigned length is still the count of bytes in the file, but it should actually be the count of SPIR-V words (i.e. `bytes / 4`). This causes the pipeline creation to fail for the triangle example (probably for the compute example too).

We should also consider directly porting the existing Rust function so that we can ensure they handle reading SPIR-V consistently between both C and Rust examples (checking endianness, etc.).

### PR DESCRIPTION
**Pull request by GabrielMajeri**
This PR fixes the C example code to not crash and actually run.

I've also added a few assertions to ensure a warning is emitted next time somebody forgots to increase `max_bind_groups` to something non-zero on device creation.

To help with debugging the examples, I've configured CMake to include debug info in the builds. Some new Makefile targets for the examples have been added to automate running them.

### CODE REVIEW

File: wgpu-native/src/command/render.rs [hunk 1]
```diff
@@ -601,6 +604,10 @@ pub fn render_pass_set_pipeline<B: GfxBackend>(
     // Rebind resource
     if pass.binder.pipeline_layout_id != Some(pipeline.layout_id.clone()) {
         let pipeline_layout = &pipeline_layout_guard[pipeline.layout_id];
+
+        assert!(pipeline_layout.bind_group_layout_ids.len() <= pass.binder.entries.len(),
```
Comment (kvark) [inline wgpu-native/src/command/render.rs]: we should have this check at the bind group layout creation, not here

File: wgpu-native/src/command/transfer.rs [hunk 2]
```diff
@@ -86,7 +86,10 @@ pub fn command_encoder_copy_buffer_to_buffer<B: GfxBackend>(
         cmb.trackers
             .buffers
             .use_replace(&*buffer_guard, source, (), BufferUsage::COPY_SRC);
-    assert!(src_buffer.usage.contains(BufferUsage::COPY_SRC));
+    assert!(
+        src_buffer.usage.contains(BufferUsage::COPY_SRC),
+        "Source buffer does not have the `COPY_SRC` usage flag"
```
Comment (kvark) [inline wgpu-native/src/command/transfer.rs]: Do you think these messages are useful? It reads to me like a rewording of the same line `src_buffer.usage.contains(BufferUsage::COPY_SRC)`

File: examples/compute/main.c [hunk 3]
```diff
@@ -50,7 +51,7 @@ int main(
     WGPUBufferId storage_buffer = wgpu_device_create_buffer(device,
```
[the remark this answers is not in the document]
Comment (GabrielMajeri) [reply examples/compute/main.c]: Is it guaranteed that a compute shader can access a buffer which is also host visible/mappable?

File: wgpu-native/src/command/transfer.rs (hunk 2 above)
Comment (GabrielMajeri) [reply wgpu-native/src/command/transfer.rs]: As a Rust developer familiar with the `bitfields` crate, the line `src_buffer.usage.contains` is pretty understandable, but from the perspective of a C developer it wouldn't be (assuming they use wgpu-rs and don't understand its internals). IMO a language-agnostic message is more understandable.

Comment (kvark) [reply wgpu-native/src/command/transfer.rs]: It literally says "buffer usage contains COPY_SRC", I think it's clear even for non-rustaceans.
More importantly, the asserts are a stopgap, we'll need to change them into proper error handling, likely very soon. So we shouldn't invest in making the messages super clear, or at least not within this PR.

File: examples/compute/main.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (kvark) [reply examples/compute/main.c]: It can't access it *at the same time* as it's mappable, but that's not what we need anyway. It is guaranteed that a buffer *can* support both host mapping and any other usage flags.

**Comment by kvark** [comment]
Thank you for updating it!
TODO:
  - [ ] make CI happy
  - [ ] squash commits
  - [ ] revert the addition of assert messages, potentially move them into another PR

File: wgpu-native/src/command/transfer.rs (hunk 2 above)
Comment (GabrielMajeri) [reply wgpu-native/src/command/transfer.rs]: I've removed them from this PR

File: examples/compute/main.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (GabrielMajeri) [reply examples/compute/main.c]: I've simplified the compute example to only use one buffer now.

**Comment by GabrielMajeri** [comment]
I've reverted the added assert messages. I think the commits could be squashed on merge. 

I'm not exactly sure what to do about CI, it seems to be unrelated to my PR. Chocolatey fails to download `make` on Windows on Travis.

**Comment by kvark** [comment]
Thank you! We use bors, who doesn't know how to swuash commits.

**Comment by GabrielMajeri** [comment]
Alright, I've squashed the commits. CI issues also seem to have been fixed.

**Comment by kvark** [comment]
Thanks!
Bors r+
