### PR TITLE
Drop texture `clear_view`s in surface_texture_discard

### LINKED ISSUE #4056: Skipping `present()` on `SurfaceTexture` results in VUID-vkDestroyDevice-device-00378
**Description**
While exiting a program, vulkan validation errors VUID-vkDestroyDevice-device-00378 are emitted if the `SurfaceTexture` is dropped without `present()` being called on it.

```shell
   Compiling wgpu-hello-triangle-example v0.17.0 (/home/rajveer/Projects/wgpu/examples/hello-triangle)
    Finished dev [unoptimized + debuginfo] target(s) in 2.89s
     Running `target/debug/hello-triangle`
[2023-08-14T19:11:14Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkDestroyDevice-device-00378 (0x71500fba)]
        Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55ae308efd20, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x750000000075, name = (wgpu internal) clear surface texture view, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55ae308efd20[], VkImageView 0x750000000075[(wgpu internal) clear surface texture view] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
[2023-08-14T19:11:14Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x55ae308efd20, name: ?), (type: IMAGE_VIEW, hndl: 0x750000000075, name: (wgpu internal) clear surface texture view)
```

**Repro**
<details>
<summary>patched hello-triangle repro; press <kbd>T</kbd> to trigger frame skip</summary>

```rust
use std::borrow::Cow;
use winit::{
    event::{ElementState, Event, KeyboardInput, VirtualKeyCode, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::Window,
};

async fn run(event_loop: EventLoop<()>, window: Window) {
    let size = window.inner_size();

    let instance = wgpu::Instance::default();

    let surface = unsafe { instance.create_surface(&window) }.unwrap();
    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::default(),
            force_fallback_adapter: false,
            // Request an adapter which can render to our surface
            compatible_surface: Some(&surface),
        })
        .await
        .expect("Failed to find an appropriate adapter");

    // Create the logical device and command queue
    let (device, queue) = adapter
        .request_device(
            &wgpu::DeviceDescriptor {
                label: None,
                features: wgpu::Features::empty(),
                // Make sure we use the texture resolution limits from the adapter, so we can support images the size of the swapchain.
                limits: wgpu::Limits::downlevel_webgl2_defaults()
                    .using_resolution(adapter.limits()),
            },
            None,
        )
        .await
        .expect("Failed to create device");

    // Load the shaders from disk
    let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: None,
        source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(include_str!("shader.wgsl"))),
    });

    let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: None,
        bind_group_layouts: &[],
        push_constant_ranges: &[],
    });

    let swapchain_capabilities = surface.get_capabilities(&adapter);
    let swapchain_format = swapchain_capabilities.formats[0];

    let render_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: None,
        layout: Some(&pipeline_layout),
        vertex: wgpu::VertexState {
            module: &shader,
            entry_point: "vs_main",
            buffers: &[],
        },
        fragment: Some(wgpu::FragmentState {
            module: &shader,
            entry_point: "fs_main",
            targets: &[Some(swapchain_format.into())],
        }),
        primitive: wgpu::PrimitiveState::default(),
        depth_stencil: None,
        multisample: wgpu::MultisampleState::default(),
        multiview: None,
    });

    let mut config = wgpu::SurfaceConfiguration {
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
        format: swapchain_format,
        width: size.width,
        height: size.height,
        present_mode: wgpu::PresentMode::Fifo,
        alpha_mode: swapchain_capabilities.alpha_modes[0],
        view_formats: vec![],
    };

    surface.configure(&device, &config);

    let mut skip_frame = false;

    event_loop.run(move |event, _, control_flow| {
        // Have the closure take ownership of the resources.
        // `event_loop.run` never returns, therefore we must do this to ensure
        // the resources are properly cleaned up.
        let _ = (&instance, &adapter, &shader, &pipeline_layout);

        *control_flow = ControlFlow::Poll;
        match event {
            Event::WindowEvent {
                event: WindowEvent::Resized(size),
                ..
            } => {
                // Reconfigure the surface with the new size
                config.width = size.width;
                config.height = size.height;
                surface.configure(&device, &config);
            }
            Event::WindowEvent {
                event:
                    WindowEvent::KeyboardInput {
                        input:
                            KeyboardInput {
                                state: ElementState::Pressed,
                                virtual_keycode: Some(VirtualKeyCode::T),
                                ..
                            },
                        ..
                    },
                ..
            } => skip_frame = true,
            Event::MainEventsCleared => {
                let frame = surface
                    .get_current_texture()
                    .expect("Failed to acquire next swap chain texture");
                if skip_frame {
                    skip_frame = false;
                    return;
                }
                let view = frame
                    .texture
                    .create_view(&wgpu::TextureViewDescriptor::default());
                let mut encoder =
                    device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
                {
                    let mut rpass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                        label: None,
                        color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                            view: &view,
                            resolve_target: None,
                            ops: wgpu::Operations {
                                load: wgpu::LoadOp::Clear(wgpu::Color::GREEN),
                                store: true,
                            },
                        })],
                        depth_stencil_attachment: None,
                        timestamp_writes: None,
                        occlusion_query_set: None,
                    });
                    rpass.set_pipeline(&render_pipeline);
                    rpass.draw(0..3, 0..1);
                }

                queue.submit(Some(encoder.finish()));
                frame.present();
            }
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => {}
        }
    });
}

fn main() {
    let event_loop = EventLoop::new();
    let window = winit::window::Window::new(&event_loop).unwrap();
    #[cfg(not(target_arch = "wasm32"))]
    {
        env_logger::init();
        pollster::block_on(run(event_loop, window));
    }
    #[cfg(target_arch = "wasm32")]
    {
        std::panic::set_hook(Box::new(console_error_panic_hook::hook));
        console_log::init().expect("could not initialize logger");
        use winit::platform::web::WindowExtWebSys;
        // On wasm, append the canvas to the document body
        web_sys::window()
            .and_then(|win| win.document())
            .and_then(|doc| doc.body())
            .and_then(|body| {
                body.append_child(&web_sys::Element::from(window.canvas()))
                    .ok()
            })
            .expect("couldn't append canvas to document body");
        wasm_bindgen_futures::spawn_local(run(event_loop, window));
    }
}
```

</details>

**Expected vs observed behavior**
Should've exited normally instead of emitting vulkan validation errors.

**Platform**
OS: `Linux fedora 6.4.9-200.fc38.x86_64`
wgpu: f825ce4ac2cc15532a8141511d67c0d7a22f774e (trunk)

### PR DESCRIPTION
**Pull request by rajveermalviya**
Fixes #4056

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
#4056 

**Description**
The texture `clear_view`s weren't destroyed in `surface_texture_discard` and that resulted in dangling `VkImageView`s.

**Testing**
Tested locally (on Linux) with repro mentioned in #4056

### CODE REVIEW

**Comment by rajveermalviya** [comment]
This does fix the vulkan validation errors but still there is a weird behaviour, with the repro in #4056 if frame skip is triggered more than 3 times (not necessarily consecutive triggers): `get_current_texture` starts returning `SurfaceError::Timeout` unless the surface is reconfigured.

**Comment by cwfitzgerald** [comment]
That's because discard isn't implemented:

https://github.com/gfx-rs/wgpu/blob/50cfc541aace5c94c14fc390dda6d54dda5468db/wgpu-hal/src/vulkan/instance.rs#L912

**Comment by cwfitzgerald** [comment]
More specifically, I'm not sure there's a meaningful way to implement discard at the hal level - we likely need to keep the image around at the core level and reuse it next time acquire is called.

**Comment by rajveermalviya** [comment]
Hmm, in that case let's see how much I can grep.

**Comment by cwfitzgerald** [comment]
We can leave that to a follow up if that would be easier

File: wgpu-core/src/present.rs [hunk 1]
```diff
@@ -386,10 +386,24 @@ impl<G: GlobalIdentityHandlerFactory> Global<G> {
...
             // and now we are moving it away.
+            log::debug!(
+                "Removing swapchain texture {:?} from the device tracker",
+                texture_id.value
+            );
             device.trackers.lock().textures.remove(texture_id.value);
 
             let (texture, _) = hub.textures.unregister(texture_id.value.0, &mut token);
             if let Some(texture) = texture {
+                if let resource::TextureClearMode::RenderPass { clear_views, .. } =
```
Comment (cwfitzgerald) [inline wgpu-core/src/present.rs]: I think this would be better as a method on `TextureClearMode`

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]

**Comment by rajveermalviya** [comment]
> We can leave that to a follow up if that would be easier

Yeah, lets do that

File: wgpu-core/src/present.rs (hunk 1 above)
Comment (rajveermalviya) [reply wgpu-core/src/present.rs]: ack

**Review by cwfitzgerald — APPROVED** [review]
Noice
