### PR TITLE
[naga msl-out] Implement atomicCompareExchangeWeak for MSL backend

### LINKED ISSUE #5257: [msl-out] atomic CompareExchange is not implemented
Doesn't seem like there's any tracking issue for this currently, I just encountered this while trying to use `atomicCompareExchangeWeak`

```
[0216 14:17:07.454] [wgpu] [error] Device::create_render_pipeline error: Internal error in ShaderStages(VERTEX) shader: MSL: FeatureNotImplemented("atomic CompareExchange")
[0216 14:17:07.454] [wgpu] [error] Shader translation error for stage ShaderStages(VERTEX): MSL: FeatureNotImplemented("atomic CompareExchange")
[0216 14:17:07.454] [wgpu] [error] Please report it to https://github.com/gfx-rs/wgpu
[0216 14:17:07.454] [wgpu] [error] Validation Error

Caused by:
    In wgpuDeviceCreateRenderPipeline
    Internal error in ShaderStages(VERTEX) shader: MSL: FeatureNotImplemented("atomic CompareExchange")
 (1)
```

### PR DESCRIPTION
**Pull request by AsherJingkongChen**
**Connections**

Fixes https://github.com/gfx-rs/wgpu/issues/5257 and https://github.com/gfx-rs/wgpu/issues/4364 (partially).
Closes https://github.com/gfx-rs/wgpu/pull/5675.

**Description**

Implement `atomicCompareExchangeWeak` for MSL (Metal) backend.

Please see [Metal Specification 2024-06-06, Page 249](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#page=249) for support details.

**Testing**

I enabled and validated 2 snapshots for Metal.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by jimblandy** [comment]
See also #5675

**Comment by AsherJingkongChen** [comment]
> See also #5675

@jimblandy I understand that @9291Sam opened another similar PR, but the progress seems a bit slow. Since this branch is for my own project, I was hoping for quicker updates. That's why I decided to contribute.

**Comment by jimblandy** [comment]
> @jimblandy I understand that @9291Sam opened another similar PR, but the progress seems a bit slow. Since this branch is for my own project, I was hoping for quicker updates. That's why I decided to contribute.

Oh, definitely. I think we should probably review this PR instead. I just wanted to have the linkage there so that people could find the relationship if they wanted.

File: naga/src/back/msl/writer.rs [hunk 1]
```diff
@@ -3690,7 +3692,47 @@ impl<W: Write> Writer<W> {
...
+                    let arg_type_name = match width {
+                        1 => "bool",
+                        4 => match kind {
+                            crate::ScalarKind::Sint => "int",
+                            crate::ScalarKind::Uint => "uint",
+                            crate::ScalarKind::Float => "float",
+                            _ => return Err(Error::UnsupportedScalar(scalar)),
+                        },
+                        _ => return Err(Error::UnsupportedScalar(scalar)),
+                    };
```
Comment (teoxoy) [inline naga/src/back/msl/writer.rs]: We can use `scalar.to_msl_name()` instead.

File: naga/src/back/msl/writer.rs [hunk 2]
```diff
@@ -3690,7 +3692,47 @@ impl<W: Write> Writer<W> {
...
+                    writeln!(self.out)?;
+                    writeln!(self.out, "namespace {NAMESPACE} {{")?;
+
+                    for address_space_name in ["device", "threadgroup"] {
+                        writeln!(
+                            self.out,
+                            "    \
+    template <typename A>
+    {struct_name} atomic_{defined_func_key}_explicit(
+        volatile {address_space_name} A *atomic_ptr,
```
Comment (teoxoy) [inline naga/src/back/msl/writer.rs]: None of the variables are declared as `volatile`, I don't think it's necessary.

File: naga/src/back/msl/writer.rs [hunk 3]
```diff
@@ -3690,7 +3692,47 @@ impl<W: Write> Writer<W> {
...
+                        },
+                        _ => return Err(Error::UnsupportedScalar(scalar)),
+                    };
+
+                    let called_func_name = "atomic_compare_exchange_weak_explicit";
+                    let defined_func_key = ATOMIC_COMP_EXCH_FUNCTION_KEY;
+                    let struct_name = &self.names[&NameKey::Type(*struct_ty)];
+
+                    writeln!(self.out)?;
+                    writeln!(self.out, "namespace {NAMESPACE} {{")?;
```
Comment (teoxoy) [inline naga/src/back/msl/writer.rs]: We shouldn't declare things in the metal namespace, it could become problematic in the future.

**Review by teoxoy — CHANGES_REQUESTED** [review]

File: naga/src/back/msl/writer.rs (hunk 1 above)
Comment (AsherJingkongChen) [reply naga/src/back/msl/writer.rs:3706]: I got it.

Comment (AsherJingkongChen) [reply naga/src/back/msl/writer.rs]: I got it. It is better now.

File: naga/src/back/msl/writer.rs (hunk 3 above)
Comment (AsherJingkongChen) [reply naga/src/back/msl/writer.rs]: Sure. I changed it to global namespace.

File: naga/src/back/msl/writer.rs (hunk 2 above)
Comment (AsherJingkongChen) [reply naga/src/back/msl/writer.rs]: Yes, I removed `volatile`.

File: naga/src/back/msl/writer.rs (hunk 3 above)
Comment (AsherJingkongChen) [reply naga/src/back/msl/writer.rs]: BTW, the defined function name is `naga_atomic_compare_exchange_weak_explicit` now.

**Comment by AsherJingkongChen** [comment]
> > @jimblandy I understand that @9291Sam opened another similar PR, but the progress seems a bit slow. Since this branch is for my own project, I was hoping for quicker updates. That's why I decided to contribute.
> 
> Oh, definitely. I think we should probably review this PR instead. I just wanted to have the linkage there so that people could find the relationship if they wanted.

@jimblandy I understand. Thank you.

**Review by teoxoy — APPROVED** [review]
Looks good, thanks!

**Comment by teoxoy** [comment]
@AsherJingkongChen this needs a rebase + updating the msl snapshots due to https://github.com/gfx-rs/wgpu/pull/6285.

**Comment by AsherJingkongChen** [comment]
@teoxoy I had not squashed commits, would it matter? I see it was auto-squashed.

**Comment by teoxoy** [comment]
I squashed them when I merged the PR (see https://github.com/gfx-rs/wgpu/commit/bf33e481f32f1a656846f9d56e44ae4d3f0414df).
