### PR TITLE
[naga hlsl-out] Handle additional cases of Cx2 matrices

### LINKED ISSUE #4423: [hlsl-out] Stores of vec2-based matrix inside struct tries to access raw matrix directly
## WGSL

```rust
struct Ah {
    inner: mat2x2<f32>,
};
@group(0) @binding(0)
var<storage, write> ah: Ah;

@compute @workgroup_size(1)
fn cs_main() {
    ah = Ah(mat2x2<f32>(vec2<f32>(0.0), vec2<f32>(1.0)));
}
```

## HLSL

```hlsl
struct Ah {
    float2 inner_0; float2 inner_1;
};

RWByteAddressBuffer ah : register(u0);

Ah ConstructAh(float2x2 arg0) {
    Ah ret = (Ah)0;
    ret.inner_0 = arg0[0];
    ret.inner_1 = arg0[1];
    return ret;
}

[numthreads(1, 1, 1)]
void cs_main()
{
    {
        Ah _value2 = ConstructAh(float2x2((0.0).xx, (1.0).xx));
        {
            // ERROR: Inner doesn't exist
            float2x2 _value3 = _value2.inner;
            ah.Store2(0+0, asuint(_value3[0]));
            ah.Store2(0+8, asuint(_value3[1]));
        }
    }
    return;
}
```

### PR DESCRIPTION
**Pull request by andyleiserson**
**Connections**
Fixes #4423.

**Description**
Fixes the original issue in #4423, and a few more that I found while working on the fix. Because memory layouts differ between HLSL and WGSL in the case of _C_-column-by-2-row matrices, we store such matrices as _C_ separate vectors. There is a comment in `back::hlsl` describing this in more detail. There are a lot of different kinds of accesses to these matrices that need to be adjusted in code generation, and we missed some:

* Stores to struct in a storage buffer having a member `m` that is a Cx2 matrix, tried to obtain the value to be stored from member `m` in the source struct, but it is actually stored in _C_ separate members `m_0` ... `m_<C-1>`.
* Loads from a Cx2 matrix in a uniform buffer tried to index into the source value using the subscript operator, but it is actually a `__matCx2` struct with _C_ separate members.
* Stores to a struct-of-array-of-struct-of-matCx2 in a storage buffer tried to use `write_value_type` to declare a temporary for the value to be stored, but `write_value_type` does not support writing struct types.

The functional fixes are in the first commit. The second commit does some refactoring to use a helper method that I added in additional places, but it's just refactoring, and I'm not highly confident in any part of these changes, so I'd be fine to drop the refactoring commit if we decide it's not worth the risk.

**Testing**
Adds a snapshot test with a variety of Cx2 matrix cases.

**Squash or Rebase?**

If we keep the refactor commit, then rebase.

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/back/hlsl/writer.rs [hunk 1]
```diff
@@ -4355,10 +4434,10 @@ fn get_inner_matrix_of_global_uniform(
     base: Handle<crate::Expression>,
     func_ctx: &back::FunctionCtx<'_>,
 ) -> Option<MatrixType> {
+    let mut current_base = find_matrix_in_access_chain(module, base, func_ctx)?;
```
Comment (teoxoy) [inline naga/src/back/hlsl/writer.rs]: Could we merge the functionality of the new `find_matrix_in_access_chain` fn directly in the loop below?

I think all we need is to add `TypeInner::Scalar(_) | TypeInner::Vector { .. } => {}` to the `match`.

File: naga/src/back/hlsl/mod.rs [hunk 2]
```diff
@@ -448,6 +453,8 @@ pub enum Error {
     Override,
     #[error(transparent)]
     ResolveArraySizeError(#[from] proc::ResolveArraySizeError),
+    #[error("Internal error: reached unreachable code: {0}")]
+    Unreachable(String),
```
Comment (teoxoy) [inline naga/src/back/hlsl/mod.rs]: Nit: I don't think we have guidelines in naga on what should be errors vs panics but my feeling was that internal errors should be panics. cc @jimblandy

File: naga/src/back/hlsl/writer.rs [hunk 3]
```diff
@@ -2912,12 +2913,37 @@ impl<'a, W: fmt::Write> super::Writer<'a, W> {
...
+                                    rows: crate::VectorSize::Bi,
+                                    ..
+                                }),
+                            ) if module.global_variables[handle].space
+                                == crate::AddressSpace::Uniform =>
+                            {
+                                cx2_columns = Some(columns);
+                            }
+                            _ => cx2_columns = None,
+                        }
```
Comment (teoxoy) [inline naga/src/back/hlsl/writer.rs]: This new check (and the one in `Expression::Access`) are quite similar to `get_inner_matrix_of_global_uniform` but they don't peek through arrays. I'm not sure it would be clearer to merge them but I think we should at least extract the blocks out into their own fn.

File: naga/src/back/hlsl/writer.rs (hunk 1 above)
Comment (teoxoy) [reply naga/src/back/hlsl/writer.rs]: We should also update the docs on this fn and maybe even rename it?

Comment (teoxoy) [reply naga/src/back/hlsl/writer.rs]: Looking at the code some more, do we actually need this change? This fn is only used in `Expression::Load` to cast our custom struct to a native HLSL matrix, so we shouldn't need the cast if we started with expressions that resolve to scalars or vectors. You can also notice in the snapshot output that we cast when we don't need to.

**Review by teoxoy — CHANGES_REQUESTED** [review]

**Review by teoxoy — APPROVED** [review]
Looks great!
