### PR TITLE
[naga msl-out] Fix truncation of pulled vertices

### LINKED ISSUE #7410: Vertex-pulling transform generates invalid metal code in certain cases
This is from one of the demos in https://bugzilla.mozilla.org/show_bug.cgi?id=1866068. The render pipeline descriptor defines an input with format `float32x3`, but the shader consumes it as a `vec2f`. The naga-generated metal shader is invalid because it attempts to cast the `vec3f` return value from `unpackFloat32x3` (a helper function generated by the vertex-pulling transform) into a `vec2f` based on the declared type of `texcoord` in the shader:

```
7410-vertex-format-mismatch.metal:41:20: error:  from vector 'metal::float3' (aka 'float3') to vector 'metal::float2' (aka 'float2') of different size
        texcoord = metal::float2(unpackFloat32x3_(vb_1_elem.data[32], vb_1_elem.data[33], vb_1_elem.data[34], vb_1_elem.data[35], vb_1_elem.data[36], vb_1_elem.data[37], vb_1_elem.data[38], vb_1_elem.data[39], vb_1_elem.data[40], vb_1_elem.data[41], vb_1_elem.data[42], vb_1_elem.data[43]));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Test case: [7410.tar.gz](https://github.com/user-attachments/files/19451468/7410.tar.gz)

### PR DESCRIPTION
**Pull request by andyleiserson**
The [vertex pulling transform](https://github.com/gfx-rs/wgpu/blob/65fcacf683a23092279cebf23aa50aa2f4034017/naga/src/back/msl/mod.rs#L417) transforms vertex shaders:

> to receive the vertex buffers, lengths, and vertex id as args, and bounds-check the vertex id and use the index into the vertex buffers to access attributes, rather than using Metal's `[[stage-in]]` assembled attribute data

It is possible for the vertices to require truncation upon loading. For example, the vertex buffer could define the texture coordinate as a `vec3`, but the vertex shader might not care about the _z_ value and load the texture coordinate as a `vec2`. Before this change, the generated code would do this by casting, which seems to be allowed from `float4` to `float3`, but not from `float3` to `float2`. This PR changes the truncation to use a swizzle selector to select the appropriate number of components.

Fixes #7410

**Testing**
Adds more snapshot tests for the vertex pulling transform. I also tested that this fix does resolve the issue seen on the website linked from the original bugzilla issue.

Review note: there are four new snapshot tests, with suffixes `-x1` through `-x4`, for loading vertices into a scalar, `vec2`, `vec3`, or `vec4`. The TOML files for all four are identical since they are describing the source vertex formats. The WGSL files are the same except for the type of variable that the vertex is loaded to.

**Squash or Rebase?** Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/back/msl/writer.rs [hunk 1]
```diff
@@ -6403,36 +6402,60 @@ template <typename A>
...
                         // from a vec4(0, 0, 0, 1) of matching scalar type.
 
-                        let needs_truncate_or_padding = am.dimension != func.dimension;
-                        if needs_truncate_or_padding {
+                        let needs_padding_or_truncation = am.dimension.cmp(&func.dimension);
+
+                        if needs_padding_or_truncation != Ordering::Equal {
+                            writeln!(
+                                self.out,
+                                "{}// {attribute_ty_name} <- {:?}",
```
Comment (andyleiserson) [inline naga/src/back/msl/writer.rs:6416]: Since the swizzle selector tends to be buried at the end of a very long argument list, this comment helps to call out what's going on, but if it's preferred not to add anything extraneous to the generated shaders, I'd be fine removing it.

File: naga/src/back/msl/writer.rs [hunk 2]
```diff
@@ -6403,36 +6402,60 @@ template <typename A>
                             .expect("Should have generated this unpacking function earlier.");
                         let func_name = &func.name;
 
-                        write!(self.out, "{}{attribute_name} = ", back::Level(2),)?;
-
                         // Check dimensionality of the attribute compared to the unpacking
                         // function. If attribute dimension is < unpack dimension, then
                         // we need to explicitly cast down the result. Otherwise, if attribute
```
Comment (teoxoy) [inline naga/src/back/msl/writer.rs]: The doc is now out of date.

File: naga/src/back/msl/writer.rs (hunk 1 above)
Comment (teoxoy) [reply naga/src/back/msl/writer.rs:6416]: We sometimes add these sort of comments to help debugging - it should be fine.

**Review by teoxoy — APPROVED** [review]
Nice!

File: naga/src/back/msl/writer.rs (hunk 2 above)
Comment (andyleiserson) [reply naga/src/back/msl/writer.rs]: Thanks, updated.
