### PR TITLE
[spv-out] handle rayQueryTerminate correctly.

### LINKED ISSUE #8577: [spv-out] rayQueryTerminate is ignored.
**Description**
Currently, spirv out ignores `RayQueryFunction::Terminate`. On metal this is converted to `.abort`, Although there are no docs for this function (the reason I didn't realize this for ages), spirv-cross directly converts from glsl's `rayQueryTerminateEXT` (which is the same as spirv's). It also translates to `.Abort` on dx12, which has very similar documentation to spirv's `OpRayQueryTerminateKHR`, only it's allowed in more places. https://github.com/gfx-rs/wgpu/blob/3a157f74970dbee9b69d4b5221f2a42d515a8e64/naga/src/back/spv/ray.rs#L1866

**Repro steps**
Look at naga napshots (https://github.com/gfx-rs/wgpu/blob/3a157f74970dbee9b69d4b5221f2a42d515a8e64/naga/tests/out/hlsl/wgsl-ray-query.hlsl#L161 vs https://github.com/gfx-rs/wgpu/blob/3a157f74970dbee9b69d4b5221f2a42d515a8e64/naga/tests/out/spv/wgsl-ray-query.spvasm#L536-L537 (empty block)

**Expected vs observed behavior**
We should be outputting something that does the same thing as the other backends.

**Extra materials**
spirv-cross' glsl out (maybe glsl in, idk)
https://github.com/KhronosGroup/SPIRV-Cross/blob/8d838b4e2e1eb36deb292f89b8b5fc6ce84bf02c/shaders-msl/comp/ray-query.spv14.vk.ios.msl24..invalid.comp#L37
spirv-cross' msl out
https://github.com/KhronosGroup/SPIRV-Cross/blob/8d838b4e2e1eb36deb292f89b8b5fc6ce84bf02c/reference/shaders-msl/comp/ray-query.spv14.vk.ios.msl24..invalid.comp#L56

**Platform**
N/a

### PR DESCRIPTION
**Pull request by Vecvec**
**Connections**
fixes #8577 

**Description**
Outputs ray query terminate (and associated checking code) instead of just doing nothing, just like the other backends

**Testing**
Snapshot test  and invalid usages test.

**Squash or Rebase?**
squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy --tests`.
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/back/spv/ray.rs [hunk 1]
```diff
@@ -1781,6 +1781,98 @@ impl Writer {
...
+            );
+
+            let finished_proceed_id = write_ray_flags_contains_flags(
+                self,
+                &mut block,
+                initialized_tracker_id,
+                super::RayQueryPoint::FINISHED_TRAVERSAL.bits(),
+            );
+
+            // Can't find anything to suggest double calling this function is invalid.
```
Comment (cwfitzgerald) [inline naga/src/back/spv/ray.rs]: Stale comment? the following function is a unary not lol

**Review by cwfitzgerald — APPROVED** [review]
Approved with nit. Rebase/merge main to get latest CI.

File: naga/src/back/spv/ray.rs (hunk 1 above)
Comment (Vecvec) [reply naga/src/back/spv/ray.rs]: Possibly I meant it for the actual terminate but it got moved? Can't remember why though, so I've removed it.
