### PR TITLE
Fixed: enabling `PARTIALLY_BOUND_BINDING_ARRAY` does not get enabled on vulkan backend

### LINKED ISSUE #3522: Enabling the `PARTIALLY_BOUND_BINDING_ARRAY` feature causes Vulkan Validation Error
**Description**
Requesting a device with the `PARTIALLY_BOUND_BINDING_ARRAY` feature and creating a bind group causes a Vulkan validation error:

> VALIDATION [VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingPartiallyBound-03013 (0x95331f1c)]
        Validation Error: [ VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingPartiallyBound-03013 ] Object 0: handle = 0x18d7125fc20, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x95331f1c | vkCreateDescriptorSetLayout(): pBindings[11] can't have VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT for VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE since descriptorBindingPartiallyBound is not enabled. The Vulkan spec states: If VkPhysicalDeviceDescriptorIndexingFeatures::descriptorBindingPartiallyBound is not enabled, all elements of pBindingFlags must not include VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingPartiallyBound-03013)

**Repro steps**
Creating an adapter with `Features::TEXTURE_BINDING_ARRAY | Features::PARTIALLY_BOUND_BINDING_ARRAY` and then creating a `BindGroup` with a texture array appears to cause this validation error.

**Expected vs observed behavior**
wgpu should enable this Vulkan feature, but does not.

**Platform**
* wgpu 0.15.1
* Windows 10
* Vulkan SDK 1.3.216.0

### PR DESCRIPTION
**Pull request by 39ali**
**Checklist**

- [x] Run `cargo clippy`.
- [ ] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
resolves [3522](https://github.com/gfx-rs/wgpu/issues/3522).

**Description**
Fixed: enabling `PARTIALLY_BOUND_BINDING_ARRAY` does not enable `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT` on the Vulkan backend, I've also added `partially_bounded_array` test.

**Testing**
run the `partially_bounded_array` test.

### CODE REVIEW

File: wgpu/tests/partially_bounded_arrays/mod.rs [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+            .limits(wgpu::Limits {
+                ..wgpu::Limits::downlevel_defaults()
+            })
+            .backend_failure(
+                wgpu::Backends::GL
+                    | wgpu::Backends::DX11
+                    | wgpu::Backends::METAL
+                    | wgpu::Backends::DX12
+                    | wgpu::Backends::BROWSER_WEBGPU,
+            ),
```
Comment (cwfitzgerald) [inline wgpu/tests/partially_bounded_arrays/mod.rs]: This shouldn't be necessary - those backends will all be skipped as they don't have the required features

File: wgpu/tests/partially_bounded_arrays/mod.rs [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+        TestParameters::default()
+            .features(
+                wgpu::Features::TEXTURE_BINDING_ARRAY
+                    | wgpu::Features::STORAGE_RESOURCE_BINDING_ARRAY
+                    | wgpu::Features::PARTIALLY_BOUND_BINDING_ARRAY
+                    | wgpu::Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES,
+            )
+            .limits(wgpu::Limits {
+                ..wgpu::Limits::downlevel_defaults()
+            })
```
Comment (cwfitzgerald) [inline wgpu/tests/partially_bounded_arrays/mod.rs]:
```suggestion
            .limits(wgpu::Limits::downlevel_defaults())
```

File: wgpu/tests/partially_bounded_arrays/mod.rs [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+            if let Some(Ok(())) = pollster::block_on(receiver.receive()) {
+                let data = buffer_slice.get_mapped_range();
+                let result: Vec<f32> = bytemuck::cast_slice(&data).to_vec();
+                assert!(result.iter().eq(&[4.0, 3.0, 2.0, 1.0]));
+                // dropped before we unmap the buffer.
+                drop(data);
+                staging_buffer.unmap();
+            } else {
+                panic!("failed!")
+            }
```
Comment (cwfitzgerald) [inline wgpu/tests/partially_bounded_arrays/mod.rs]: I think most of this should be able to be replaced with the ReadbackBuffers here: https://github.com/gfx-rs/wgpu/blob/trunk/wgpu/tests/common/image.rs#L350-L355

**Review by cwfitzgerald — CHANGES_REQUESTED** [review]
Looking good, thank you for adding the test!

**Comment by cwfitzgerald** [comment]
Poke from triage

**Comment by 39ali** [comment]
**Pokes back**

File: CHANGELOG.md [hunk 4]
```diff
@@ -118,6 +118,7 @@ By @fornwall in [#3904](https://github.com/gfx-rs/wgpu/pull/3904) and [#3905](ht
 
 - Fix incorrect aspect in barriers when using emulated Stencil8 textures. By @cwfitzgerald in [#3833](https://github.com/gfx-rs/wgpu/pull/3833).
 - Implement depth-clip-control using depthClamp instead of VK_EXT_depth_clip_enable. By @AlbinBernhardssonARM [#3892](https://github.com/gfx-rs/wgpu/pull/3892).
+- Fix enabling `wgpu::Features::PARTIALLY_BOUND_BINDING_ARRAY` not being actually enabled in vulkan backend. By @39ali in[#3772](https://github.com/gfx-rs/wgpu/pull/3772).
```
Comment (cwfitzgerald) [inline CHANGELOG.md:126]: This entry is in 0.17, not a the new unreleased section. After that, g2g

**Review by cwfitzgerald — APPROVED** [review]
Poke received :)

File: CHANGELOG.md (hunk 4 above)
Comment (39ali) [reply CHANGELOG.md:126]: Woops!
