### PR TITLE
[naga] Make two structs with the same members not equivalent

### LINKED ISSUE #5796: Naga: Should not be a structural type system
**Description**
Currently naga will accept using a struct as another struct with the same layout.

Could it be that type checking only checks if the layout of a type is the same? And that aliases could be an issue, because they're represented as a copy of a given type in the naga::Module.

**Repro steps**

Add the following to `naga/tests/wgsl_errors.rs`. Naga creates a module and says it's valid, instead of throwing the expected error.
```
#[test]
fn different_types() {
    check_validation! {
        "@vertex
fn vtx_main() -> @builtin(position) vec4f {
  // I'm assigning a Foo to a Bar
  let x: Bar = Foo(1);
  return vec4f(f32(x.a));
}
 
struct Foo { a: u32 };
struct Bar { a: u32 }; // Same layout":
        Err(naga::valid::ValidationError::Type  {
            ..
        })
    }
}
```

**Expected vs observed behavior**
I expected it to match the Chrome behaviour of throwing an error.

**Platform**

- Windows 11
- WGSL trunk on commit 583cc6ab04796b8ab29a84920ff5bd42d9736e7a (one of the latest commits)

### PR DESCRIPTION
**Pull request by andyleiserson**
Fixes #5796

**Description**
Consider two structs with the same members, but different names:
```
struct Foo { a: u32 };
struct Bar { a: u32 };
```
An instance of `Bar` should not be accepted in a context where `Foo` is expected, and vice-versa. We were not previously enforcing this, because we compare `TypeInner`s, and the `TypeInner` for a struct only contains the list of members and the memory stride.

I took the strategy of adding a new mechanism for comparing types using `TypeResolution`s, which additionally have access to the type name (at least in the case of structs, which are always represented as `TypeResolution::Handle` rather than `TypeResolution::Value`). A different strategy would be to add something in the `TypeInner` that makes it possible to distinguish the structs. I briefly went down the path of putting the `Handle<Type>` (or a `usize` intended to come from `Handle<Type>`) in the `TypeInner`, but that seemed like a more involved change because each place that can add a struct to the arena needs to change to understand how to record handle information in the `TypeInner`. We could also put the name itself in the `TypeInner`, but that seemed undesirable.

There is some more work needed before this would be ready, that I deferred until there's agreement on the strategy. One issue is the signature of the `compare_types` method -- taking `TypeResolution`s by value seems not great, but being able to pass either `&TypeResolution` or `Handle` is hard to do generically.

Another issue is making sure that we properly distinguish between the built-in struct types and a user-defined struct type with the same name -- this may be difficult to properly test until we have support for shadowing the built-in types.

**Testing**
Adds several tests in wgsl_errors for various places where our type checking of structs was previously incorrect.

**Squash or Rebase?** Squash, unless there's desire to preserve the refactorings as separate commits.

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] Need to add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/tests/wgsl_errors.rs [hunk 1]
```diff
@@ -241,15 +241,15 @@ fn constructor_parameter_type_mismatch() {
...
             }
         "#,
-        r#"error: automatic conversions cannot convert `array<{AbstractInt}, 2>` to `vec2<f32>`
+        "error: automatic conversions cannot convert `array<{AbstractInt}, 2>` to `vec2<f32>`
   ┌─ wgsl:3:21
   │
 3 │                 _ = mat2x2<f32>(array(0, 1), vec2(2, 3));
   │                     ^^^^^^^^^^^ ^^^^^^^^^^^ this expression has type array<{AbstractInt}, 2>
-  │                     │            
+  │                     │\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
```
Comment (andyleiserson) [inline naga/tests/wgsl_errors.rs]: This has nothing to do with the rest of the change, but I got tired of fighting with my editor to preserve the trailing whitespace in this file.

**Comment by andyleiserson** [comment]
Split some renaming into separate commits to facilitate reviewing.

File: naga/src/front/wgsl/lower/conversion.rs [hunk 2]
```diff
@@ -46,7 +46,10 @@ impl<'source> super::ExpressionContext<'source, '_, '_> {
         }
 
         // If `expr` already has the requested type, we're done.
-        if expr_inner.equivalent(goal_inner, types) {
+        if self
+            .module
+            .compare_types(expr_resolution.clone(), goal_ty.clone())
```
Comment (teoxoy) [inline naga/src/front/wgsl/lower/conversion.rs]: Do we have to clone these? Could we pass them by reference instead? This also applies in all the other places we call `compare_types` and `clone` the args.

**Comment by teoxoy** [comment]
I think we can land this as is but:

> We could also put the name itself in the `TypeInner`, but that seemed undesirable.

I have been wondering for a while why `Type` has a `name` and a `TypeInner`, it feels more natural to have the name of the struct inside `TypeInner::Struct`, remove `Type` and rename `TypeInner` to `Type`.

cc @jimblandy

**Review by teoxoy — APPROVED** [review]

**Comment by jimblandy** [comment]
> I think we can land this as is but:
> 
> > We could also put the name itself in the `TypeInner`, but that seemed undesirable.
> 
> I have been wondering for a while why `Type` has a `name` and a `TypeInner`, it feels more natural to have the name of the struct inside `TypeInner::Struct`, remove `Type` and rename `TypeInner` to `Type`.

This is probably a good idea, but let's open a separate issue for that.

**Comment by teoxoy** [comment]
Looks good, @andyleiserson do you want to rebase this and merge? Since it looks like the commits are somewhat independent.
