### PR TITLE
fix(naga): Reject direct access to atomic variables

### LINKED ISSUE #5474: naga: Direct use of atomic types is not treated as an error
This issue was originally titled _Comparison-expressions on atomic types are not treated as an error_, and that is what is explained in this description. The title is broadened to reflect the scope of the underlying issue.

**Description**
According to the [WGSL Specification, Section 8.8](https://www.w3.org/TR/WGSL/#comparison-expr), comparison expressions are defined to operate on AbstractInt, AbstractFloat, bool, i32, u32, f32, or f16 (and apply component-wise on their vector equivalents). It looks like naga (0.19.2) permits an instance of `atomic<u32>` and a `u32` to be passed as the operands of a comparison operator and injects an atomic load before the comparison while translating the output. Tint treats this as an error and rejects the program.

I believe Tint's behavior matches the specification while Naga's behavior does not. Please see the details below.

## Details
The offending WGSL is from a compute program that applies comparison between two bindings (`// ...` denotes sections that are omitted from the rest of the program):

```wgsl
struct Config {
    // ...
    lines_size: u32,
    // ...
}

struct BumpAllocators {
    // ...
    lines: atomic<u32>,
    // ...
}

@group(0) @binding(0) var<uniform> config: Config;
@group(0) @binding(1) var<storage, read_write> bump: BumpAllocators;

var<workgroup> sh_previous_failed: u32;

@compute @workgroup_size(256)
fn main(@builtin(local_invocation_id) local_id: vec3<u32>) {
    // ...
    if local_id.x == 0u {
        let failed = bump.lines > config.lines_size;    // offending line
        sh_previous_failed = u32(failed);
    }
    // ...
}
```
### Tint Behavior:
Given the above, tint outputs the following error, which I believe matches the spec:
```
Errors:
line 243:22 no matching overload for 'operator > (atomic<u32>, u32)'

2 candidate operators:
 • 'operator > (T  ✗ , T  ✗ ) -> bool' where:
      ✗  'T' is 'abstract-float', 'abstract-int', 'f32', 'i32', 'u32' or 'f16'
 • 'operator > (vecN<T>  ✗ , vecN<T>  ✗ ) -> vecN<bool>' where:
      ✗  'T' is 'abstract-float', 'abstract-int', 'f32', 'i32', 'u32' or 'f16'
```

### Naga Behavior:
Naga accepts the program. Looking at the generated MSL, it looks like Naga inserts an atomic load and performs the comparison on the result of that. I haven't attempted to reproduce this on other backends:
```C++
    if (local_id.x == 0u) {
        uint _e22 = metal::atomic_load_explicit(&bump.lines, metal::memory_order_relaxed);
        uint _e25 = config.lines_size;
        bool failed = _e22 > _e25;
        sh_previous_failed = static_cast<uint>(failed);
    }
```

### PR DESCRIPTION
**Pull request by ecoricemon**
**Connections**
Fixes #5474
A follow-up PR for #9126

**Description**
This PR raises a WGSL front-end error in `apply_load_rule` when the load rule is applied to a reference whose pointee type is atomic.

* Test changes 
The existing `invalid_functions` test for return_atomic was slightly adjusted. The original test used a bare atomic<u32> return type; since the new front-end error fires during module lowering before the validator runs, the test was updated to use a struct  wrapping an atomic so that NonConstructibleReturnType is still exercised through the validator as originally intended.

* Affected CTS
webgpu:shader,validation,expression,binary,add_sub_mul:* : 901 -> 904 (100%)
webgpu:shader,validation,expression,binary,and_or_xor:* : 823 -> 826 (100%)
webgpu:shader,validation,expression,binary,comparison:* : 470 -> 476 (100%)
webgpu:shader,validation,expression,binary,bitwise_shift:invalid_types:* : 26 -> 28 (100%)
webgpu:shader,validation,expression,call,builtin,abs:* : 56 -> 57 (100%)
webgpu:shader,validation,expression,call,builtin,countLeadingZeros:* : 47 -> 48 (100%)
webgpu:shader,validation,expression,call,builtin,countOneBits:* : 47 -> 48 (100%)
webgpu:shader,validation,expression,call,builtin,countTrailingZeros:* : 47 -> 48 (100%)
webgpu:shader,validation,expression,call,builtin,firstLeadingBit:* : 47 -> 48 (100%)
webgpu:shader,validation,expression,call,builtin,firstTrailingBit:* : 47 -> 48 (100%)
webgpu:shader,validation,expression,call,builtin,reverseBits:* : 47 -> 48 (100%)
webgpu:shader,validation,expression,call,builtin,select:* : 842 -> 843 (100%)
webgpu:shader,validation,expression,matrix,* : 1863 -> 1881 (100%)
webgpu:shader,validation,expression,unary,* : 302 -> 304 (100%)
webgpu:shader,validation,statement,increment_decrement:* : 218 -> 222 (100%)
webgpu:shader,validation,statement,phony:* : 58 -> 62 (100%)
webgpu:shader,validation,statement,switch:* : 87 -> 88 (100%)
webgpu:shader,validation,expression,call,builtin,clamp:* : 161 -> 162 (71.68%)
webgpu:shader,validation,expression,call,builtin,extractBits:* : 29 -> 33 (62.26%)
webgpu:shader,validation,expression,call,builtin,insertBits:* : 85 -> 89 (76.07%)
webgpu:shader,validation,types,* : 1450 -> 1453 (95.22%)

<mark>**Uncertainty**</mark>
 I'm not fully confident this is the right approach. Please review. If the approach looks correct, I will identify any affected CTS tests and update them accordingly.    

**Testing**
Existing tests

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
I think this also needs to be validated against in the validator otherwise spirv and glsl will still have this problem. It may still be useful for error message purposes to keep the validation in the front end

**Comment by ecoricemon** [comment]
Thank you for the feedback. It sounds like the best path forward is to introduce a new expression variant, `Expression::AtomicLoad`, and then verify its pointee type during the validation stage. I’ll investigate this approach and update the PR accordingly.

**Comment by cwfitzgerald** [comment]
Oh I see, this is actually just a wgsl front end issue, an atomic load is expressed as an Expression::Load on an atomic type, so a non-atomic load is actually not even expressible in the IR as is.

So this PR is fine as is, sorry for the misunderstanding!

**Comment by ecoricemon** [comment]
No problem at all! I'll update affected CTS and the PR shortly. Please let me know if you spot any other potential issues with this approach.

**Comment by andyleiserson** [comment]
I ran the naga benchmark (`cargo bench --bench wgpu-benchmark -- naga::front`) just in case this affects performance, but any difference is within the noise.

**Comment by teoxoy** [comment]
This looks ok but I think we should really be moving atomic load/store into new variants of `AtomicFunction`. Should be done separately as this is a refactor that will touch lots of places.

**Comment by ecoricemon** [comment]
Thank you for the comments. I've resolved the conflicts.

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -901,8 +901,15 @@ impl<'source, 'temp, 'out> ExpressionContext<'source, 'temp, 'out> {
...
-                let load = ir::Expression::Load { pointer };
                 let span = self.get_expression_span(pointer);
+
+                // Reject direct access to atomic variables that does not go
+                // through a built-in function.
+                if resolve_inner!(self, pointer).is_atomic_pointer(&self.module.types) {
+                    return Err(Box::new(Error::InvalidAtomicAccess(span)));
+                }
+
+                let load = ir::Expression::Load { pointer };
```
Comment (teoxoy) [inline naga/src/front/wgsl/lower/mod.rs:912]: Could you check that `ast::StatementKind::Increment` `ast::StatementKind::Decrement` also do the right thing with regards to loading atomics? I took a quick look and it looked like we are allowing `atomic_var++`/`atomic_var--`.

File: cts_runner/fail.lst [hunk 2]
```diff
@@ -72,32 +72,24 @@ webgpu:shader,validation,decl,var:* // 99%, https://github.com/gfx-rs/wgpu/issue
 webgpu:shader,validation,expression,access,array:* // 97%, runtime indexing with compile-time-known values, https://github.com/gfx-rs/wgpu/issues/4390
 webgpu:shader,validation,expression,access,matrix:* // 93%, runtime OOB matrix access with literal indices incorrectly rejected
 webgpu:shader,validation,expression,access,vector:* // 52%, https://github.com/gfx-rs/wgpu/issues/4390, and missing swizzle validation
-webgpu:shader,validation,expression,binary,add_sub_mul:* // 95%, u32 const-eval overflow incorrectly rejected, f16 const-eval overflow not rejected, atomics #5474
-webgpu:shader,validation,expression,binary,and_or_xor:* // 96%, https://github.com/gfx-rs/wgpu/issues/5474
-webgpu:shader,validation,expression,binary,bitwise_shift:invalid_types:* // 93%, atomics #5474
-webgpu:shader,validation,expression,binary,comparison:* // 74%, https://github.com/gfx-rs/wgpu/issues/5474
+webgpu:shader,validation,expression,binary,and_or_xor:* // 99%, bool
+webgpu:shader,validation,expression,binary,comparison:* // 99%, bool
```
Comment (teoxoy) [inline cts_runner/fail.lst]: Did https://github.com/gfx-rs/wgpu/pull/9275 fix those?

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (ecoricemon) [reply naga/src/front/wgsl/lower/mod.rs:912]: Certainly! I'll check that out when I finish another task.

File: cts_runner/fail.lst (hunk 2 above)
Comment (ecoricemon) [reply cts_runner/fail.lst]: I'll update the CTS as well.

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (ecoricemon) [reply naga/src/front/wgsl/lower/mod.rs:912]: Those cases were already being rejected in [this](https://github.com/gfx-rs/wgpu/blob/9c5adb73a7792c45da742efd8572e75df0ed4e89/naga/src/front/wgsl/lower/mod.rs#L2217) and exercised by [this CTS test](https://github.com/gpuweb/cts/blob/9726cfe2893834c4bb42b435638c4e7362f4c258/src/webgpu/shader/validation/statement/increment_decrement.spec.ts#L205) included in `webgpu:shader,validation,statement,increment_decrement,*`

File: cts_runner/fail.lst (hunk 2 above)
Comment (ecoricemon) [reply cts_runner/fail.lst]: They have been fixed.

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (teoxoy) [reply naga/src/front/wgsl/lower/mod.rs:912]: I see, thanks for checking!

**Review by teoxoy — APPROVED** [review]
Thanks!
