### PR TITLE
Fix workgroupUniformLoad returning atomic types

### LINKED ISSUE #8785: `workgroupUniformLoad` specialization for `atomic<T>` is missing.
**Description**
When given an atomic pointer, [`workgroupUniformLoad`](https://www.w3.org/TR/WGSL/#workgroupUniformLoad-builtin) should return the inner `T`.

Image

This works in Chrome (presumably using the tint / Dawn backend), but fails with `naga` / `wgpu`, which returns the atomic type instead.

**Repro steps**
Here is a simple shader:
```wgsl
var<workgroup> wg_scratch: atomic<u32>;

@compute @workgroup_size(4, 4, 4)
fn interval_tile_main(
    @builtin(workgroup_id) workgroup_id: vec3u,
    @builtin(local_invocation_id) local_id: vec3u
) {
    let active_tile_index = workgroup_id.x + workgroup_id.y * 32768;
    atomicOr(&wg_scratch, u32(active_tile_index >= 64));
    workgroupBarrier();
    if workgroupUniformLoad(&wg_scratch) == 0 {
        return;
    }
}
```

It fails to parse in `naga`:
```console
$ naga --version
28.0.0
$ naga shader.wgsl
Could not parse WGSL:
error: Incompatible operands: Equal(Atomic(Scalar { kind: Uint, width: 4 }), _)
```

**Expected vs observed behavior**
This should be a valid WGSL program that `naga` can parse.

**Platform**
macOS 14.7.6 (23H626), `naga 28.0.0`

### PR DESCRIPTION
**Pull request by cryvosh**
**Connections**
FIxes https://github.com/gfx-rs/wgpu/issues/8785.

**Description**
`workgroupUniformLoad` now matches the spec and returns the inner type when called on an atomic.

**Testing**
Added a new snapshot test `workgroup-uniform-load-atomic.wgsl`

**Squash or Rebase?**
Squash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/tests/naga/wgsl_errors.rs [hunk 1]
```diff
@@ -47,6 +47,37 @@ fn check_success(input: &str) {
...
+        panic!(
+            "expected success, but parsing failed with:\n{}",
+            err.emit_to_string(input)
+        )
+    });
+
+    naga::valid::Validator::new(valid::ValidationFlags::default(), Capabilities::all())
+        .validate(&module)
+        .unwrap();
+}
```
Comment (inner-daemons) [inline naga/tests/naga/wgsl_errors.rs]: Given that this is just validating some WGSL, isn't it already covered by the snapshots? We shouldn't need a dedicated test in `wgsl_errors`.

File: naga/tests/in/wgsl/workgroup-uniform-load-atomic.wgsl
Comment (inner-daemons) [inline naga/tests/in/wgsl/workgroup-uniform-load-atomic.wgsl:1]: I appreciate the breadth of this test!

File: naga/src/front/wgsl/lower/mod.rs [hunk 2]
```diff
@@ -3059,7 +3059,32 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
+                                        name: None,
+                                        inner: match size {
+                                            Some(size) => ir::TypeInner::Vector { size, scalar },
+                                            None => ir::TypeInner::Scalar(scalar),
+                                        },
+                                    },
+                                    span,
+                                ),
                                 ref other => {
                                     log::error!("Type {other:?} passed to workgroupUniformLoad");
```
Comment (inner-daemons) [inline naga/src/front/wgsl/lower/mod.rs]: Not your fault but I think this log is unnecessary

File: naga/src/valid/function.rs [hunk 3]
```diff
@@ -1479,7 +1479,21 @@ impl super::Validator {
...
+                            base: pointer_base,
+                            space: AddressSpace::WorkGroup,
+                        } => match (&context.types[pointer_base].inner, &context.types[ty].inner) {
+                            (&Ti::Atomic(pointer_scalar), &Ti::Scalar(result_scalar)) => {
+                                pointer_scalar == result_scalar
+                            }
+                            _ => false,
+                        },
+                        _ => false,
+                    };
```
Comment (inner-daemons) [inline naga/src/valid/function.rs:1495]: Its mostly self-evident but I think this could use a short comment explaining what its doing

**Review by inner-daemons — CHANGES_REQUESTED** [review]
Thanks for this! Broadly LGTM, just a few suggestions

File: naga/src/front/wgsl/lower/mod.rs (hunk 2 above)
Comment (cryvosh) [reply naga/src/front/wgsl/lower/mod.rs]: The `log::error!("Type {other:?} passed to workgroupUniformLoad");`? Should I remove it?

File: naga/tests/naga/wgsl_errors.rs (hunk 1 above)
Comment (cryvosh) [reply naga/tests/naga/wgsl_errors.rs]: Good point, removed

File: naga/src/valid/function.rs (hunk 3 above)
Comment (cryvosh) [reply naga/src/valid/function.rs:1495]: Sure, added

File: naga/src/front/wgsl/lower/mod.rs (hunk 2 above)
Comment (inner-daemons) [reply naga/src/front/wgsl/lower/mod.rs]: Probably. It returns an error anyway.

Comment (cryvosh) [reply naga/src/front/wgsl/lower/mod.rs]: Done

File: naga/src/valid/function.rs [hunk 4]
```diff
@@ -1479,7 +1479,23 @@ impl super::Validator {
                         base: ty,
                         space: AddressSpace::WorkGroup,
                     };
-                    if !expected_pointer_inner.non_struct_equivalent(pointer_inner, context.types) {
+                    // workgroupUniformLoad on atomic<T> returns T, not atomic<T>.
+                    // Verify the pointer's atomic scalar matches the result scalar.
```
Comment (inner-daemons) [inline naga/src/valid/function.rs:1483]: Thanks!

**Review by inner-daemons — APPROVED** [review]
LGTM! Thanks for working on this. Probably it will get merged sometime around the 7th.

**Comment by ErichDonGubler** [comment]
This mostly LGTM! Thanks for the new snapshot test. 🙂 Just one nit: if the claim is that the spec. supports this change, let's also add some CTS tests to `cts_runner/test.lst`! In particular, the following seem interesting: 

- [`webgpu:shader,validation,expression,call,builtin,workgroupUniformLoad:*`](https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,validation,expression,call,builtin,workgroupUniformLoad:*)
- [`webgpu:shader,execution,expression,call,builtin,workgroupUniformLoad:*`](https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,execution,expression,call,builtin,workgroupUniformLoad:*)

I filed #8813 to establish a baseline. After that merges, let's rebase and uncomment the following, which start passing after changes here:

```
webgpu:shader,execution,expression,call,builtin,workgroupUniformLoad:types:type="atomic%3Cu32%3E";*
webgpu:shader,execution,expression,call,builtin,workgroupUniformLoad:types:type="atomic%3Ci32%3E";*
webgpu:shader,execution,expression,call,builtin,workgroupUniformLoad:types:type="AtomicInStruct";*
```

**Review by ErichDonGubler — DISMISSED** [review]
I intend to approve after we get CTS coverage, but also: I want a review from @teoxoy or @jimblandy to double-check me here, if they can provide one in the next day or so. If not, I'm okay with them taking a look post-merge.

**Review by teoxoy — APPROVED** [review]
LGTM, thanks!
