### PR TITLE
remove end pass return value and fix examples

### LINKED ISSUE #270: Dont return command encoders by the render_pass_end
The same applies to compute_pass_end()
This used to be in the spec, but it's not any more.

### PR DESCRIPTION
**Pull request by porky11**
closes #270

### CODE REVIEW

File: ffi/wgpu.h [hunk 1]
```diff
@@ -1,6 +1,6 @@
 #define WGPU_LOCAL
 
-/* Generated with cbindgen:0.9.0 */
+/* Generated with cbindgen:0.8.7 */
```
Comment (grovesNL) [inline ffi/wgpu.h]: nit: ideally we should try stay on the latest cbindgen version but it's not too important for this change

Comment (porky11) [reply ffi/wgpu.h]: right, I should have seen this
