### PR TITLE
Use EGL_KHR_gl_colorspace for srgb if available

### LINKED ISSUE #1667: sRGB Conversion Not Done for EGL < 1.5
**Description**
I think sRGB converison is not currently working for the GL backend with EGL < 1.6 on Linux. The issue was originally found in #1627.

( https://github.com/gfx-rs/wgpu/issues/1627#issuecomment-878602534 )

@cwfitzgerald said:
> Yeah my haswell rig has srgb issues on both vk and gl.

We have fixed the vulkan issue, but haven't done anything about GL yet.

**Repro steps**

**Expected vs observed behavior**
All of the examples appear darker in color than the vulkan ones. ( after we fixed vulkan in #1651 )

**Extra materials**

**Platform**
I was unable to reproduce this on my machine using `Mesa Intel(R) UHD Graphics (CML GT2)`, but @cwfitzgerald mentioned having issues on his haswell rig.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Connections**

Fixes #1667 

**Description**

Uses the extension to provide SRGB if needed relevant.

I also promoted the log message about missing robustness to a warning because it is a safety issue.

**Testing**

Tested on rpi and haswell.

### CODE REVIEW

File: wgpu-hal/src/gles/egl.rs [hunk 1]
```diff
@@ -543,11 +569,21 @@ impl crate::Instance<super::Api> for Instance {
...
+            SrgbFrameBufferKind::Core => {
+                attributes.push(egl::GL_COLORSPACE as usize);
+                attributes.push(egl::GL_COLORSPACE_SRGB as usize);
+            }
+            SrgbFrameBufferKind::Khr => {
+                attributes.push(EGL_GL_COLORSPACE_KHR as usize);
+                attributes.push(EGL_GL_COLORSPACE_SRGB_KHR as usize);
+            }
+            SrgbFrameBufferKind::None => {
+                // TODO: expose ot the user that srgb isn't supported
```
Comment (kvark) [inline wgpu-hal/src/gles/egl.rs:583]: do we need this TODO? let's just implement it here in the PR

File: wgpu-hal/src/gles/egl.rs [hunk 2]
```diff
@@ -543,11 +569,21 @@ impl crate::Instance<super::Api> for Instance {
...
+            }
         }
+        if inner.version >= (1, 5) {}
```
Comment (kvark) [inline wgpu-hal/src/gles/egl.rs:586]: leftover?

File: wgpu-hal/src/gles/egl.rs (hunk 1 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/gles/egl.rs:583]: I looked but couldn't find where I would change the list of supported backbuffer formats, so if you point me in the right direction I can do it.

File: wgpu-hal/src/gles/egl.rs (hunk 2 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/gles/egl.rs:586]: Oops!

File: wgpu-hal/src/gles/egl.rs (hunk 1 above)
Comment (kvark) [reply wgpu-hal/src/gles/egl.rs:583]: Sorry, I should have just posted the link right away - https://github.com/gfx-rs/wgpu/blob/22a81de6a99b25223f2fd9d6233f10fa16908ab6/wgpu-hal/src/gles/adapter.rs#L465

**Review by kvark — APPROVED** [review]
bors r+
