### PR TITLE
[naga] Retain unnamed constants' and overrides' types during compaction.

### LINKED ISSUE #7072: [naga] compaction may miss used constants' types
I think part of the compaction code is either wrong or redundant.

When `compact::compact` marks a name constants as used by definition, it also marks its initialization expression as used. But then later in that function, it marks the types of all used constants as used. I'm not sure why these two cases, type and initialization expression, should be handled differently. It seems to me that either the type marking can be moved up (removing that entire loop altogether) or the initializer marking must be moved down, because new constants are getting marked and we'd better include their initialization expressions.

Whatever the case, overrides deserve similar scrutiny.

(I'm not sure this is actually a bug, but there's an asymmetry to `naga::compact::compact` that seems wrong, and I'm afraid I'll forget about this doubt if I don't write it down.)

### PR DESCRIPTION
**Pull request by jimblandy**
Ensure that unnamed constants' types are retained, even when the
constants are used only by global expressions. Add a test case.

Similarly for overrides.

The old code marked all named constants as used; then processed
function bodies; and then marked the types of all used constants as
used. This ensured that, as long as a constant was used by a function,
its type would be retained, but didn't address the case where a
constant is used only by a global expression.

Fixes #7072.

### CODE REVIEW

File: naga/src/compact/mod.rs [hunk 1]
```diff
@@ -880,3 +934,75 @@ fn local_expression_override() {
...
+    );
+
+    let mut validator = super::valid::Validator::new(
+        super::valid::ValidationFlags::all(),
+        super::valid::Capabilities::all(),
+    );
+
+    assert!(validator.validate(&module).is_ok());
+    compact(&mut module);
+    assert!(validator.validate(&module).is_ok());
```
Comment (ErichDonGubler) [inline naga/src/compact/mod.rs:999]: nitpick: For this and the other test being added: Checking that the module still passes validation afterward is good, but I'm surprised that we're not snapshotting the contents of the module's arenas so we can enforce that certain things gets culled, and others don't, given the context of this PR. After all, the commits adding these tests are plugging a case where we were accidentally removing things, right?

**Review by ErichDonGubler — APPROVED** [review]
LGTM, minus a nit.

File: naga/src/compact/mod.rs (hunk 1 above)
Comment (jimblandy) [reply naga/src/compact/mod.rs:999]: The bug being addressed in this PR is that compaction was removing stuff that was being used, leaving dangling handles behind. So while it's true that we do know exactly what we expect the module to contain after compaction, meaning that a snapshot test wouldn't be wrong, checking validity should catch the failure reliably.

We agreed in chat that this wasn't a blocking concern.
