### PR TITLE
[naga] Use const ctx instead of global ctx for type resolution

### LINKED ISSUE #6720: WGSL: `const` declarations in function scope cannot be used as `const` expressions
**Description**

`const`-declared values in function scope (i.e., "local" `const mySize = 2` inside a `fn` declaration) cannot be used in contexts where values must be constant-evaluatable, like `array` sizes.

**Repro steps**

1. Observe that while this passes validation in WGSL:

	```wgsl
	const myArraySize = 2;
	@compute @workgroup_size(1, 1)
	fn main() {
		var myArray: array<f32, myArraySize>;
	}
	```

	…this does not:

	```wgsl
	@compute @workgroup_size(1, 1)
	fn main() {
		const myArraySize = 2; // Hello, I moved here!
		var myArray: array<f32, myArraySize>;
	}
	```

	…which returns an error from `naga-cli`:

	```
	error: this operation is not supported in a const context
	  ┌─ ../in.wgsl:4:26
	  │
	4 │     var myArray: array<f32, myArraySize>;
	  │                             ^^^^^^^^^^^ operation not supported here
	```

**Expected vs observed behavior**

I expect that values bound to `const` declarations should be usable as a `const` expression in the same contexts, independent of where they are declared (lexical scoping notwithstanding).

### PR DESCRIPTION
**Pull request by sagudev**
**Connections**
Fix #6720, depends on https://github.com/gfx-rs/wgpu/pull/6945

**Description**
Naga currently assumes constants are global and it passes global ctx to const needing functions. Instead we should pass const ctx (expr ctx) that can represents either local or global consts.

This PR only deals with using local const in types (array size). `ImageSample` and `Switch` will be handled as followups (both are pretty complex as this will require fixing validation and compaction).

Commits are not really standalone, but they should make reviewing easier.

**Testing**
Added new tests, weirdly enough there are no changes in CTS, so I guess this isn't exercised there.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

**Comment by sagudev** [comment]
I have a feeling we need to recheck evals and all arena invariants. Distinction between global const ctx and local const ctx is very blurry.

**Comment by sagudev** [comment]
Switch statement will be left off for follow up, based on https://github.com/gfx-rs/wgpu/pull/6935/commits/3d718ddf6bc8484c8793400c9c4e3ad8c4867356

**Comment by sagudev** [comment]
Hm, CTS run says no changes: https://github.com/sagudev/servo/actions/runs/13357425686/attempts/1#summary-37305026756

**Review by teoxoy — APPROVED** [review]
Looks good!

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -1101,9 +1101,10 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
                 ast::GlobalDeclKind::Const(ref c) => {
                     let mut ectx = ctx.as_const();
 
-                    let explicit_ty =
-                        c.ty.map(|ast| self.resolve_ast_type(ast, &mut ectx.as_global()))
-                            .transpose()?;
+                    let explicit_ty = c
+                        .ty
+                        .map(|ast| self.resolve_ast_type(ast, &mut ectx.as_global().as_const()))
+                        .transpose()?;
```
Comment (teoxoy) [inline naga/src/front/wgsl/lower/mod.rs]:
```suggestion
                    let explicit_ty =
                        c.ty.map(|ast| self.resolve_ast_type(ast, &mut ectx))
                            .transpose()?;
```
