### PR TITLE
[naga msl-out] invalid code emitted for minimum i32/i64 value literal.

### LINKED ISSUE #7435: [naga] [msl-out] Error: as_type cast from 'long' to 'metal::uint' (aka 'unsigned int') is not allowed
**Description**

When compiling [this code](https://github.com/LegNeato/rust-gpu-shadertoys/blob/update-deps/shaders/src/filtering_procedurals.rs) with `rust-gpu`, I get valid spirv asm. I then pass it to `naga` to translate to metal (as I am on macOS) and I get these errors:

```
                        float _e11563 = function_119(metal::float2(_e7495 * 7.6543, _e7496 * 7.6543));
                              ^
program_source:16276:67: error: as_type cast from 'long' to 'metal::uint' (aka 'unsigned int') is not allowed
                    int _e13236 = as_type<int>(as_type<uint>(1) + as_type<uint>((_e13226 == _e13226) ? ((_e13226 > as_type<float>(1325400063u)) ? 2147483647 : ((_e13226 < as_type<float>(3472883712u)) ? -2147483648 : naga_f2i32(_e13226))) : 0));
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:16304:67: error: as_type cast from 'long' to 'metal::uint' (aka 'unsigned int') is not allowed
                    int _e13273 = as_type<int>(as_type<uint>(1) + as_type<uint>((_e13263 == _e13263) ? ((_e13263 > as_type<float>(1325400063u)) ? 2147483647 : ((_e13263 < as_type<float>(3472883712u)) ? -2147483648 : naga_f2i32(_e13263))) : 0));
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Repro steps**
It's a bit convoluted...

1. Checkout https://github.com/Rust-GPU/rust-gpu-shadertoys/pull/33
2. Patch in https://github.com/gfx-rs/wgpu/pull/7425
3. In `build.rs`, remove the check that turns it off on macos or in `shaders/lib.rs`, delete everything in the match except `21 => filtering_procedurals::Inputs`

I'll work on getting the raw spirv.

Note I tested with the change from https://github.com/gfx-rs/wgpu/pull/7422 by @jamienicol and it still was not fixed.

**Expected vs observed behavior**
The shader to translate to metal code that compiles.

**Platform**
macOS, latest master of `wgpu`

### PR DESCRIPTION
**Pull request by LegNeato**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/7435.
Similar to https://github.com/gfx-rs/wgpu/issues/7423

**Description**
-2147483648 is parsed as "unary negation of 2147483648". 2147483648 is too large to fit in a 32 bit int, and is therefore inferred to be a long. Which promotes the rest of the expression to a long. Which then errors when trying to bitcast it to a uint because as_type() must keep the same bitwidth

**Testing**
I tried my repro from https://github.com/gfx-rs/wgpu/issues/7435 and saw it now works.

**Squash or Rebase?**

Rebase

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

**Comment by LegNeato** [comment]
The real change is in the 2nd commit...the first is the dep.

File: naga/src/back/msl/writer.rs [hunk 1]
```diff
@@ -1493,13 +1493,21 @@ impl<W: Write> Writer<W> {
...
+                } else {
+                    write!(self.out, "{value}")?;
+                }
             }
             crate::Literal::U64(value) => {
                 write!(self.out, "{value}uL")?;
             }
             crate::Literal::I64(value) => {
-                write!(self.out, "{value}L")?;
+                if value == i64::MIN {
```
Comment (jamienicol) [inline naga/src/back/msl/writer.rs:1517]: Sweet, this is exactly the fix I had in mind, too.

I think we should add a comment explaining exactly what's going on, like we have for the WGSL backend. It's a slightly different scenario though, so I can write that.

File: naga/tests/in/wgsl/int32.wgsl [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+var<storage> input_storage: UniformCompatible;
+@group(0) @binding(2)
+var<storage> input_arrays: StorageCompatible;
+@group(0) @binding(3)
+var<storage, read_write> output: UniformCompatible;
+@group(0) @binding(4)
+var<storage, read_write> output_arrays: StorageCompatible;
+
+fn int32_function(x: i32) -> i32 {
+    var min_val = bitcast<u32>(-2147483648);
```
Comment (jamienicol) [inline naga/tests/in/wgsl/int32.wgsl]: I don't think we need a whole int32.wgsl testcase. These should all be covered by the rest of the test suite.

(The reason we have an int64.wgsl / f64.wgsl etc is because those types are extensions)

We just want to make sure we test the i32::MIN and i64::MIN literals.

We can use the bitcast trick as you've done here for i32. AFAICT that's the only way to ensure we generate a compiler error rather than the accidentally-long value being implicitly converted to an int. Metal doesn't even appear to emit a compiler warning. The question is where to put it if not in a new int32.wgsl test. There's not really a great place but perhaps under arithmetic -> unary in operators.wgsl?

We should test the min int64 literal too. Unfortunately we cannot use the bitcast trick as the value is still a long. However, the metal compiler does emit a `constant-conversion` warning. So if we run our validation with `-Werror=constant-conversion` we will catch it.

**Review by jamienicol — COMMENTED** [review]
Looks good, thanks! Couple nits but I can make those changes for you.

I'm also going to rebase it to not depend on #7422 as that review might take slightly longer for someone to get to.

File: naga/tests/in/wgsl/int32.wgsl (hunk 2 above)
Comment (jamienicol) [reply naga/tests/in/wgsl/int32.wgsl]: Oh I though of another issue with relying on the bitcast to catch this bug: currently it works fine as we haven't implemented bitcasts during constant evaluation.

But when we do get round to that, the bitcast would be evaluated away, meaning the output MSL wouldn't contain the bitcast and the test would no longer do what it's meant to. So we need to ensure we add a non-const expression to the bitcast. Or we can even just use signed integer addition, as we wrap those in bitcasts to avoid signed overflow (again we'd have to prevent const evaluation removing the operation)

**Comment by jamienicol** [comment]
r+ from me for @LegNeato's changes, but would @ErichDonGubler mind having a quick look at my changes since I've now co-authored?

I've pushed an extra commit which improves the fix for #7424 so that we actually test the min i64 literal. And then I think the only controversial change I made to the patch was to pass `-Werror=constant-conversion` to metal so that validation would catch the bug

**Comment by jamienicol** [comment]
ha, #7422 got merged quicker than I expected. I'll rebase this again :laughing:

**Comment by LegNeato** [comment]
@ErichDonGubler any chance you can take a look?

**Comment by ErichDonGubler** [comment]
@LegNeato: Sorry, I'd forgotten to get this into my own task tracking. I'll take a look today!

**Comment by LegNeato** [comment]
No worries, I know you folks are busy!

**Review by ErichDonGubler — APPROVED** [review]

**Comment by LegNeato** [comment]
Thanks!
