### PR TITLE
Additional validation of texture copies

### LINKED ISSUE #7844: [dx12] Panic in `calc_subresource_for_copy` on texture aspect copy
The CTS test `webgpu:api,validation,encoding,cmds,copyTextureToTexture:copy_aspects:*` [panics on Windows in CI](https://github.com/gfx-rs/wgpu/actions/runs/15722178005/job/44305020480?pr=7820) with the following:

```
thread 'main' panicked at wgpu-hal\src\dx12\mod.rs:916:18:
internal error: entered unreachable code
stack backtrace:
...
  16:     0x7ff736a0ddcf - wgpu_hal::dx12::Texture::calc_subresource_for_copy
                               at C:\a\wgpu\wgpu\wgpu-hal\src\dx12\mod.rs:916
  17:     0x7ff736603d40 - wgpu_hal::dx12::command::impl$4::copy_texture_to_texture<core::iter::adapters::cloned::Cloned<core::slice::iter::Iter<wgpu_hal::TextureCopy> > >
                               at C:\a\wgpu\wgpu\wgpu-hal\src\dx12\command.rs:581
  18:     0x7ff7365ffd95 - wgpu_hal::dynamic::command::impl$0::copy_texture_to_texture<wgpu_hal::dx12::CommandEncoder>
                               at C:\a\wgpu\wgpu\wgpu-hal\src\dynamic\command.rs:283
  19:     0x7ff7366139f7 - wgpu_core::command::transfer::impl$0::command_encoder_copy_texture_to_texture::closure$0
                               at C:\a\wgpu\wgpu\wgpu-core\src\command\transfer.rs:1155
  20:     0x7ff736663c99 - wgpu_core::command::RecordingGuard::record<wgpu_core::command::transfer::impl$0::command_encoder_copy_texture_to_texture::closure_env$0,enum2$<wgpu_core::command::CommandEncoderError> >
                               at C:\a\wgpu\wgpu\wgpu-core\src\command\mod.rs:321
  21:     0x7ff7366624b1 - wgpu_core::command::CommandEncoderStatus::record_with<wgpu_core::command::transfer::impl$0::command_encoder_copy_texture_to_texture::closure_env$0,enum2$<wgpu_core::command::CommandEncoderError> >
                               at C:\a\wgpu\wgpu\wgpu-core\src\command\mod.rs:132
  22:     0x7ff73662a9c1 - wgpu_core::global::Global::command_encoder_copy_texture_to_texture
                               at C:\a\wgpu\wgpu\wgpu-core\src\command\transfer.rs:1013
...
```

The failure occurs after the following subtest:
```
[pass] webgpu:api,validation,encoding,cmds,copyTextureToTexture:copy_aspects:format="depth24plus" (30ms). Log:
  - (in subcase: sourceAspect="all";destinationAspect="all") INFO: subcase ran
  - (in subcase: sourceAspect="all";destinationAspect="depth-only") INFO: subcase ran
  - (in subcase: sourceAspect="all";destinationAspect="stencil-only") INFO: subcase ran
  - (in subcase: sourceAspect="depth-only";destinationAspect="all") INFO: subcase ran
  - (in subcase: sourceAspect="depth-only";destinationAspect="depth-only") INFO: subcase ran
  - (in subcase: sourceAspect="depth-only";destinationAspect="stencil-only") INFO: subcase ran
  - (in subcase: sourceAspect="stencil-only";destinationAspect="all") INFO: subcase ran
  - (in subcase: sourceAspect="stencil-only";destinationAspect="depth-only") INFO: subcase ran
  - (in subcase: sourceAspect="stencil-only";destinationAspect="stencil-only") INFO: subcase ran
```

I suspect that it is trying one of these (quoting `copyTextureToTexture.spec.ts`):
```
      'depth24plus-stencil8': ['all'],
      'depth32float-stencil8': ['all'],
```

### PR DESCRIPTION
**Pull request by andyleiserson**
In studying whether #2951 is still an issue, I identified some other texture validation that is missing. This adds it, and also fixes the issue where we skip parameter validation for zero-size copies. ~I suspect that this may fix #7844 by rejecting an illegal operation before dx12 panics.~ I've also included a fix for #7844 that splits depth+stencil copies into two operations, although I'm not sure if this is the right fix -- it appears that metal does support a combined copy in copyTextureToTexture (but not in copyBufferToTexture), so maybe this should be pushed to the backends. 

**Testing**
Enables all the `copyTextureToTexture` CTS tests. However, the CTS isn't complete coverage of the validation logic I added. In particular, it doesn't cover the logic that allows copies among different aspects of the same texture. I'm not sure if that even makes sense (copying between depth and stencil?), or if it's just the spec being thorough, but I would welcome a suggestion of an interesting test to add here. 

**Squash or Rebase?** Squash

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [ ] If this contains user-facing changes, add a `CHANGELOG.md` entry. _Maybe it's worth one overall changelog entry mentioning this, the vertex/index buffer offset change, and any other added validation that gets added._

### CODE REVIEW

**Comment by sagudev** [comment]
> However, the CTS isn't complete coverage of the validation logic I added

Sounds like we need to add more CTS tests.

File: wgpu-core/src/command/transfer.rs [hunk 1]
```diff
@@ -1115,6 +1209,16 @@ impl Global {
                 copy_size,
             )?;
 
+            if Arc::as_ptr(&src_texture) == Arc::as_ptr(&dst_texture) {
+                validate_copy_within_same_texture(
+                    source,
+                    src_texture.desc.format,
+                    destination,
+                    dst_texture.desc.format,
```
Comment (teoxoy) [inline wgpu-core/src/command/transfer.rs]: Nit: The format of the textures is the same since src = dst.

File: wgpu-core/src/command/transfer.rs [hunk 2]
```diff
@@ -431,6 +471,46 @@ pub(crate) fn validate_texture_copy_range<T>(
...
+///
+/// This implements the WebGPU requirement that the [sets of subresources for
+/// texture copy][srtc] of the source and destination be disjoint, i.e. that the
+/// source and destination do not overlap.
+///
+/// This function assumes that the copy ranges have already been validated with
+/// `validate_texture_copy_range`.
+///
+/// [srtc]: https://gpuweb.github.io/gpuweb/#abstract-opdef-set-of-subresources-for-texture-copy
+pub(crate) fn validate_copy_within_same_texture<T>(
```
Comment (teoxoy) [inline wgpu-core/src/command/transfer.rs:484]: This fn is not allowing disjoint mip levels but should, per spec.

File: wgpu-core/src/command/transfer.rs [hunk 3]
```diff
@@ -843,19 +922,40 @@ impl Global {
...
+                    },
+                    hal::BufferTextureCopy {
+                        texture_base: hal::TextureCopyBase {
+                            aspect: hal::FormatAspects::STENCIL,
+                            ..dst_base
+                        },
+                        buffer_layout: source.layout,
+                        size: hal_copy_size,
+                    },
+                ]
```
Comment (teoxoy) [inline wgpu-core/src/command/transfer.rs]: This case shouldn't be allowed by validation (same for `copyTextureToBuffer` and `writeTexture`).

> If texture.[format](https://gpuweb.github.io/gpuweb/#dom-gputexture-format) is a [depth-or-stencil format](https://gpuweb.github.io/gpuweb/#depth-or-stencil-format) format:
>    texelCopyTextureInfo.[aspect](https://gpuweb.github.io/gpuweb/#dom-gputexelcopytextureinfo-aspect) must refer to a single aspect of texture.[format](https://gpuweb.github.io/gpuweb/#dom-gputexture-format).

[from "validating texture buffer copy"](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-texture-buffer-copy)

**Review by teoxoy — CHANGES_REQUESTED** [review]

File: wgpu-core/src/command/transfer.rs (hunk 3 above)
Comment (andyleiserson) [reply wgpu-core/src/command/transfer.rs]: Good point, we only need this case for `copyTextureToTexture`.

File: wgpu-core/src/command/transfer.rs (hunk 2 above)
Comment (andyleiserson) [reply wgpu-core/src/command/transfer.rs:484]: Thanks, fixed. I'll also open a PR to add this to the CTS (it was noted as a TODO, but not implemented).

**Review by teoxoy — APPROVED** [review]
Nice!
