### PR TITLE
Fix crash on command buffer drop

### LINKED ISSUE #3724: `assertion failed: data.is::<T>()` on command buffer drop
**Description**
Intermittent assertion when dropping a command buffer when using **webgl** (not webgpu as in otherwise related #3710)
Haven't isolated yet which circumstances are necessary to trigger this:

```
panicked at 'assertion failed: data.is::<T>()', /Users/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.16.0/src/context.rs:1045:5

Stack:

getImports/imports.wbg.__wbg_new_abda76e883ba8a5f/<@http://127.0.0.1:9090/re_viewer.js:422:21
logError@http://127.0.0.1:9090/re_viewer.js:241:18
getImports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://127.0.0.1:9090/re_viewer.js:421:66
console_error_panic_hook::hook::h7085f0f35ae12a82@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[5590]:0x772074
core::ops::function::Fn::call::h4a4c198ad3cbb4af@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[20779]:0xa34346
eframe::web::backend::start_web::{{closure}}::{{closure}}::h2be874fa9b88f1af@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[11730]:0x98572b
std::panicking::rust_panic_with_hook::hbafe3e603d331223@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[11784]:0x98856d
std::panicking::begin_panic_handler::{{closure}}::h8ab6ee68d5b4c391@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[12896]:0x9bd960
std::sys_common::backtrace::__rust_end_short_backtrace::h008f69666d134159@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[16919]:0xa1fe05
rust_begin_unwind@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[15130]:0xa028b6
core::panicking::panic_fmt::h1d17fc068f528130@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[16212]:0xa166e0
core::panicking::panic::h27b5eefa3e4ff738@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[15333]:0xa06eb8
<T as wgpu::context::DynContext>::command_buffer_drop::ha1744d4f4947ce60@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[14681]:0x9f7a2b
<wgpu::CommandBuffer as core::ops::drop::Drop>::drop::ha2e55b23d296c66c@http://127.0.0.1:9090/re_viewer.js line 383 > WebAssembly.instantiate:wasm-function[12229]:0x99f2a2
```

**Platform**
Firefox, webgl backend

### PR DESCRIPTION
**Pull request by Wumpf**
**Checklist**

- [x] Run `cargo clippy`.
- [ ] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**

Fixes #3724

**Description**

Oversight in: #3657
Passed the wrong object was passed for `data` to `command_buffer_drop`, causing type conversion assertion to fail at runtime 😱 

**Testing**

Add minimal repro
```rust
let encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
drop(encoder.finish());
```
to hello triangle. Before: `thread 'main' panicked at 'assertion failed: data.is::<T>()', wgpu/src/context.rs:1045:5`

### CODE REVIEW

File: wgpu/src/lib.rs [hunk 1]
```diff
@@ -574,8 +574,9 @@ static_assertions::assert_impl_all!(CommandBuffer: Send, Sync);
 impl Drop for CommandBuffer {
     fn drop(&mut self) {
         if !thread::panicking() {
-            if let Some(ref id) = self.id {
-                self.context.command_buffer_drop(id, &self.data.take());
+            if let Some(id) = self.id.take() {
+                self.context
+                    .command_buffer_drop(&id, self.data.take().unwrap().as_ref());
```
Comment (emilk) [inline wgpu/src/lib.rs:579]: adding an `unwrap`, especially in a `drop`, seems unwise 😬

Comment (emilk) [inline wgpu/src/lib.rs:579]:
```suggestion
            if let (Some(id), Some(data)) = (self.id.take(), self.data.take()) {
                self.context
                    .command_buffer_drop(&id, &data);
```

**Comment by Wumpf** [comment]
@emilk I agree with the two comments, but I intentionally sticked with the pattern of the other drop implementations in this file to make it less confusing. If there is no data object but an id we are in an invalid state and should not continue either, so we need to handle this error in some way.
The actual issue here is that there’s two option fields that are in sync which is already pretty bad. But since this kind of check only id + unwrap is done in other places as well I decided to stick with it.

**Review by cwfitzgerald — APPROVED** [review]
Thanks!
