### PR TITLE
[naga wgsl-in] `vecN()` constructors and `let` type conversions

### LINKED ISSUE #7356: Initialiazing `var foo: vec4f = vec4()` fails with "type can't be inferred"
This failure is from https://martinlaxenaire.github.io/gpu-curtains/examples/shadow-mapping/ via https://bugzilla.mozilla.org/show_bug.cgi?id=1876519, although I think I also hit this problem writing test cases for an unrelated issue.

```
Shader 'Mesh 0 material render pipeline: fragment shader module' parsing error: type can't be inferred
    ┌─ wgsl:525:28
    │
525 │   var outputColor: vec4f = vec4();
    │                            ^^^^ type can't be inferred
```

### PR DESCRIPTION
**Pull request by andyleiserson**
**Connections**
Fix for #7356.

This pull request is on top of #7304, due to overlapping effects on naga output snapshots.

**Description**
Naga did not previously allow use of `vec4()` as a constructor, because it has no type information. However, the spec states that this constructor (and `vec2`/`vec3`) should return a vector of abstract ints. Depending on the context (e.g. the case of `var v: vec4f = vec()` from the associated issue), the vector of abstract ints may then be converted to another type. While writing test cases for this, I noticed that we weren't applying automatic conversions to the initializer of `let` declarations, so I fixed that as well, changing the code for handling `let` declarations to operate similarly to the code for `var` and `const`, which already handled conversions.

**Testing**
Added several snapshot tests to exercise various related cases, plus a few cases where a conversion is not possible in `wgsl_errors`. Type conversion for let declarations also fixes the CTS test `webgpu:shader,validation,decl,let:type:case="array_sized"`.

**Squash or Rebase?** Squash

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] Needs a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -1464,24 +1464,22 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
                         .map(|ty| self.resolve_ast_type(ty, &mut ctx.as_const(block, &mut emitter)))
                         .transpose()?;
 
-                    if let Some(ty) = explicit_ty {
-                        let mut ctx = ctx.as_expression(block, &mut emitter);
-                        let init_ty = ctx.register_type(value)?;
+                    let mut ectx = ctx.as_expression(block, &mut emitter);
+
+                    let value = if let Some(ty) = explicit_ty {
+                        let (init_ty, lowered_init) = self.type_and_init(
```
Comment (jamienicol) [inline naga/src/front/wgsl/lower/mod.rs]: Shouldn't unconditionally calling `type_and_init()` be okay? If `explicit_ty` is None the initializer will be concretized, which is equivalent to calling `expression()` as your patch does in the else block below.

File: naga/tests/in/wgsl/constructors.wgsl [hunk 2]
```diff
@@ -3,7 +3,7 @@ struct Foo {
     b: i32,
 }
 
-// const const1 = vec3<f32>(0.0); // TODO: this is now a splat and we need to const eval it
+const const1 = vec3<f32>(0.0);
```
Comment (jamienicol) [inline naga/tests/in/wgsl/constructors.wgsl:6]: was this fixed by this patch or something else?

File: naga/tests/in/wgsl/conversions.wgsl [hunk 3]
```diff
@@ -0,0 +1,99 @@
+// Conversion of initializer expressions
```
Comment (jamienicol) [inline naga/tests/in/wgsl/conversions.wgsl:1]: I think some of this duplicates abstract-types-var.wgsl and abstract-types-const.wgsl? Would it make sense to merge into those and add an abstract-types-let.wgsl too?

**Review by jamienicol — COMMENTED** [review]
Love the links to the spec and the thorough test coverage 🥇

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (andyleiserson) [reply naga/src/front/wgsl/lower/mod.rs]: Yes, I think it is. I will change it.

File: naga/tests/in/wgsl/constructors.wgsl (hunk 2 above)
Comment (andyleiserson) [reply naga/tests/in/wgsl/constructors.wgsl:6]: Something else... I'm not sure exactly what, but I had the impression that we const eval splats now, so I uncommented it, and it worked.

Comment (jamienicol) [reply naga/tests/in/wgsl/constructors.wgsl:6]: Awesome

**Review by jamienicol — APPROVED** [review]
Great, LGTM!

**Comment by ErichDonGubler** [comment]
Rebased to resolve conflicts.

**Comment by ErichDonGubler** [comment]
@andyleiserson, @sagudev: Should we just merge this, and close #7304? Or do we need to merge that first?

**Comment by andyleiserson** [comment]
I don't know if @jamienicol reviewed all the changes or just the ones that I added in this PR. And @jimblandy mentioned documenting `ImplConst`, which made me question whether there is some issue removing it.

**Comment by jamienicol** [comment]
I only reviewed your changes @andyleiserson

**Comment by cwfitzgerald** [comment]
This just needs to be rebased, then this can land.
