### PR TITLE
Override-expressions for Fixed Size Arrays

### LINKED ISSUE #5315: Allow override-expressions in element count of fixed-size arrays
**Description**

We don't appear to allow override-expressions within template parameters, though it is specified by the WebGPU spec.'s [`6.2.9 Array Types` section](https://gpuweb.github.io/gpuweb/wgsl/#array-types):

> The element count expression N of a fixed-size array is subject to the following constraints:
> 
> -   It [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) be an [override-expression](https://gpuweb.github.io/gpuweb/wgsl/#override-expressions).
>    
> -   It [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) evaluate to a [concrete](https://gpuweb.github.io/gpuweb/wgsl/#type-concrete) [integer scalar](https://gpuweb.github.io/gpuweb/wgsl/#integer-scalar).
>     
> -   It is a [pipeline-creation error](https://gpuweb.github.io/gpuweb/wgsl/#pipeline-creation-error) if N is not greater than zero.

**Repro steps**

I don't have _straightforward_ STR ATM (TODO), but this repros with WebGPU CTS' `webgpu:shader,execution,zero_init:compute,zero_init:*` test (see the source of the shader it submits here: https://github.com/mozilla/gpuweb-cts/blob/41f89e77b67e6b66cb017be4e00235a0a9429ca7/src/webgpu/shader/execution/zero_init.spec.ts#L413-L429). In particular, the `var<workgroup> wg_mem : array<u32, ${wg_memory_limits} / 4>;` line exercises this functionality, yielding an error like the following:

```
[ERROR wgpu_core::device::global] Device::create_shader_module error:
    Shader '' parsing error: expected '>', found '/'
      ┌─ wgsl:4:48
      │
    4 │       var<workgroup> wg_mem : array<u32, 16384 / 4>;
      │                                                ^ expected '>'
```

**Expected vs observed behavior**

Expected: Compilation Just Works™, and the shader module is usable in subsequently constructed pipelines.

Actual: We get a relatively unhelpful error diagnostic message, and the shader module is invalid.

**Extra materials**

None provided.

**Platform**

None provided.

### PR DESCRIPTION
**Pull request by kentslaney**
This pull request is still a work in progress, but is open to avoid others repeating work that's already been done.

**Connections**
Resolves #5315 

**Description**
The WebGPU spec allows for arrays to have a fixed size specified by an override-expression. This PR implements this by adding a `Pending` state to array sizes, which gets resolved with the rest of the override-expressions.

**Testing**
This change is tested by checking that a 1d spiral is correctly stored.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

### CODE REVIEW

File: naga/src/proc/mod.rs [hunk 1]
```diff
@@ -297,6 +297,9 @@ impl super::TypeInner {
             } => {
                 let count = match size {
                     super::ArraySize::Constant(count) => count.get(),
+                    // any struct member or array element needing a size at pipeline-creation time
+                    // must have a creation-fixed footprint
+                    super::ArraySize::Pending(_) => 0,
```
Comment (teoxoy) [inline naga/src/proc/mod.rs:302]: Ideally this would be `unreachable!();` to catch bugs early.

**Review by teoxoy — CHANGES_REQUESTED** [review]
We need to validate that arrays of this form are only declared on workgroup variables. They also can't be nested. I think this can be done via a new `TypeFlags` implementing the spec's distinction between "creation-fixed footprint" and "fixed footprint".

see https://www.w3.org/TR/WGSL/#fixed-footprint-types & https://www.w3.org/TR/WGSL/#example-workgroup-variables-sized-by-override

**Comment by teoxoy** [comment]
There is also this note in the spec:

> Note: To qualify for type-equivalency, any override expression that is not a const expression must be an identifier. See [Workgroup variables sized by overridable constants](https://www.w3.org/TR/WGSL/#example-workgroup-variables-sized-by-override)

I think to make this work we'd have to make `ArraySize::Pending` hold a new enum that is either a `Handle<Override>` or `Handle<Expression>`.

File: naga/src/proc/mod.rs (hunk 1 above)
Comment (kentslaney) [reply naga/src/proc/mod.rs:302]: This method is called even when the layouter doesn't need to determine struct member positioning, because it helps construct the `TypeLayout`, which is used for its `alignment` property. The comment is relevant because it explains why we can return zero, despite having a non-zero memory footprint: the result is never needed, which it could be if it was allowed to be part of a struct. I think that, like with the dynamically sized array below it, the consistent behavior is to let it be reachable, but return a placeholder default.

Comment (teoxoy) [reply naga/src/proc/mod.rs:302]: The dynamic case is reachable and valid, for the purposes of layout calculations dynamic arrays act as an array with a single element.

Comment (teoxoy) [reply naga/src/proc/mod.rs:302]: Hm, I do see that this might be hard to make `unreachable!();`, if it's too involved we can keep it as is.

**Comment by kentslaney** [comment]
> I think to make this work we'd have to make `ArraySize::Pending` hold a new enum that is either a `Handle<Override>` or `Handle<Expression>`.

You were right, that was much easier, sorry for the force push

File: naga/src/proc/mod.rs (hunk 1 above)
Comment (kentslaney) [reply naga/src/proc/mod.rs:302]: Oh, you're right about the dynamic arrays, Maybe the `BindingArray` option below that returning 0 is the better example? I think making it unreachable would mostly consist of pushing

https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/proc/layouter.rs#L170

into the match arms and not calling it for Array where the size is pending.

File: naga/src/valid/type.rs [hunk 2]
```diff
@@ -493,7 +512,16 @@ impl super::Validator {
...
+                    crate::ArraySize::Constant(_) => {
+                        TypeFlags::DATA
+                            | TypeFlags::SIZED
+                            | TypeFlags::COPY
+                            | TypeFlags::HOST_SHAREABLE
+                            | TypeFlags::ARGUMENT
+                            | TypeFlags::CONSTRUCTIBLE
+                            | TypeFlags::CREATION_RESOLVED
+                    }
+                    crate::ArraySize::Pending(_) => {
```
Comment (teoxoy) [inline naga/src/valid/type.rs:524]: Should not have `TypeFlags::CONSTRUCTIBLE`.

File: naga/src/valid/type.rs [hunk 3]
```diff
@@ -54,6 +54,10 @@ bitflags::bitflags! {
         /// Can be used for host-shareable structures.
         const HOST_SHAREABLE = 0x10;
 
+        /// The set of types with a fixed size at shader-creation time or a not-fixed size at
+        /// pipeline creation time (ie. everything except arrays sized by an override-expression)
+        const CREATION_RESOLVED = 0x20;
```
Comment (teoxoy) [inline naga/src/valid/type.rs]:
```suggestion
        /// The set of types with a fixed size at shader-creation time (ie. everything
        /// except arrays sized by an override-expression)
        const CREATION_RESOLVED = 0x20;
```

File: naga/src/proc/mod.rs (hunk 1 above)
Comment (teoxoy) [reply naga/src/proc/mod.rs:302]: Ah I see there is precedent for returning 0. Let's keep it as is.

**Review by teoxoy — APPROVED** [review]
Looks great, thanks!
