### PR TITLE
Fix D3D12 Surface Leak

### LINKED ISSUE #3967: Resize error on DX12 backend in wgpu 0.17
**Description** 

when attempting to run  wgpu examples using the DX12 backend in version 0.17 of wgpu, I encountered the following error:

[2023-07-23T20:02:29Z ERROR wgpu_hal::dx12] ResizeBuffers failed: 0x887A0001
[2023-07-23T20:02:29Z ERROR wgpu_core::device::global] surface configuration failed: window is in use
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Invalid surface
', C:\Users\****\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.17.0\src\backend\direct.rs:771:18

**Repro steps**

For example, in the "hello-triangle" example, simply replacing 

  `let instance = wgpu::Instance::default();`

by

```
 let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
        backends: wgpu::Backends::DX12,
        dx12_shader_compiler: Default::default(),
 });
```

this will generate the error when resizing the output window.

**Expected vs observed behavior**

This error only occurs in wgpu 0.17, while wgpu <= 0.16 never gives this error.

**Platform**

Windows 11, RTX 3060, wgpu 0.17.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**

Closes #3967
Found #4105

**Description**

Re-defines the wgpu-hal contract a bit, allowing proper destruction of resources before swap chain resize.

### CODE REVIEW

File: wgpu-hal/src/vulkan/instance.rs [hunk 1]
```diff
@@ -794,6 +793,7 @@ impl crate::Surface<super::Api> for super::Surface {
         device: &super::Device,
         config: &crate::SurfaceConfiguration,
     ) -> Result<(), crate::SurfaceError> {
+        // Safety: `configure`'s contract guarentees there is no resources derived from the swapchain in use.
```
Comment (Elabajaba) [inline wgpu-hal/src/vulkan/instance.rs]: *guarantees

File: wgpu-hal/src/vulkan/instance.rs [hunk 2]
```diff
@@ -807,6 +807,7 @@ impl crate::Surface<super::Api> for super::Surface {
 
     unsafe fn unconfigure(&mut self, device: &super::Device) {
         if let Some(sc) = self.swapchain.take() {
+            // Safety: `unconfigure`'s contract guarentees there is no resources derived from the swapchain in use.
```
Comment (Elabajaba) [inline wgpu-hal/src/vulkan/instance.rs]: *guarantees

**Review by Elabajaba — APPROVED** [review]
Tested and it works for me on amd+windows11+dx12 and vulkan.

File: wgpu-hal/src/vulkan/instance.rs (hunk 1 above)
Comment (cwfitzgerald) [reply wgpu-hal/src/vulkan/instance.rs]: Vowels are my kryptonite

File: wgpu-hal/src/vulkan/instance.rs [hunk 3]
```diff
@@ -794,6 +793,7 @@ impl crate::Surface<super::Api> for super::Surface {
         device: &super::Device,
         config: &crate::SurfaceConfiguration,
     ) -> Result<(), crate::SurfaceError> {
+        // Safety: `configure`'s contract guarantees there is no resources derived from the swapchain in use.
```
Comment (jimblandy) [inline wgpu-hal/src/vulkan/instance.rs]: "there are no resources", here and below

File: wgpu-hal/src/dx12/mod.rs [hunk 4]
```diff
@@ -614,18 +614,22 @@ impl crate::Surface<Api> for Surface {
         // We always set ALLOW_TEARING on the swapchain no matter
         // what kind of swapchain we want because ResizeBuffers
         // cannot change if ALLOW_TEARING is applied to the swapchain.
```
Comment (jimblandy) [inline wgpu-hal/src/dx12/mod.rs]: Pre-existing, but: 
```suggestion
        // cannot change the swapchain's ALLOW_TEARING flag.
```

The original text can easily be read as:

> if `ALLOW_TEARING` is appled to the swapchain, then `ResizeBuffers` cannot change

which is meaningless and confusing.

**Review by jimblandy — APPROVED** [review]
Looks good to me. Some suggestions and typos:
