### PR TITLE
[naga/spv-in] Remove unnecessary "gl_PerVertex" name check so unused builtins will always be skipped

### LINKED ISSUE #4915: [naga/spv-in] Naga seems unable to consume any simple vertex shader from glslc due to gl_PerVertex attributes.
**Description**
There seems to be something off when attempting to feed a simple vertex shader into naga, due to unused clip distance being present.

**Repro steps**

fullscreen.vert:
```
#version 450

void main()
{
    gl_Position = vec4(
        (gl_VertexIndex == 0) ? -4.0 : 1.0,
        (gl_VertexIndex == 2) ? 4.0 : -1.0,
        0.0,
        1.0
    );
}
```

Building:
```
glslc -O fullscreen.vert -o fullscreen.spv
naga fullscreen.spv fullscreen.wgsl
```

And the resulting error:
```
Entry point main at Vertex is invalid:
        Capability Capabilities(CLIP_DISTANCE) is not supported
Generating wgsl output requires validation to succeed, and it failed in a previous step
```

For reference here is the spirv-dis:
```
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 11
; Bound: 34
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %4 "main" %13 %gl_VertexIndex
               OpMemberDecorate %_struct_11 0 BuiltIn Position
               OpMemberDecorate %_struct_11 1 BuiltIn PointSize
               OpMemberDecorate %_struct_11 2 BuiltIn ClipDistance
               OpMemberDecorate %_struct_11 3 BuiltIn CullDistance
               OpDecorate %_struct_11 Block
               OpDecorate %gl_VertexIndex BuiltIn VertexIndex
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
 %_struct_11 = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output__struct_11 = OpTypePointer Output %_struct_11
         %13 = OpVariable %_ptr_Output__struct_11 Output
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%_ptr_Input_int = OpTypePointer Input %int
%gl_VertexIndex = OpVariable %_ptr_Input_int Input
       %bool = OpTypeBool
   %float_n4 = OpConstant %float -4
    %float_1 = OpConstant %float 1
      %int_2 = OpConstant %int 2
    %float_4 = OpConstant %float 4
   %float_n1 = OpConstant %float -1
    %float_0 = OpConstant %float 0
%_ptr_Output_v4float = OpTypePointer Output %v4float
          %4 = OpFunction %void None %3
          %5 = OpLabel
         %18 = OpLoad %int %gl_VertexIndex
         %20 = OpIEqual %bool %18 %int_0
         %23 = OpSelect %float %20 %float_n4 %float_1
         %26 = OpIEqual %bool %18 %int_2
         %29 = OpSelect %float %26 %float_4 %float_n1
         %31 = OpCompositeConstruct %v4float %23 %29 %float_0 %float_1
         %33 = OpAccessChain %_ptr_Output_v4float %13 %int_0
               OpStore %33 %31
               OpReturn
               OpFunctionEnd
```

There is a rather inconvenient workaround, which is to `spirv-cross` the spv back into glsl and feed that in.

**Platform**
On x64 Win10, using the latest naga and vulkansdk.

naga version: `0.14.0`

glslc version:
```
shaderc v2023.7 v2023.7
spirv-tools v2023.5 v2022.4-352-g360d469b
glslang 11.1.0-803-g48f9ed8b

Target: SPIR-V 1.0
```

### PR DESCRIPTION
**Pull request by Imberflur**
**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/4915

**Description**
Unused gl_PerVertex builtins need to be skipped since they my otherwise require capabilities that are not enabled. However, this was not being done when the input spirv didn't explicitly name this struct.

This just removes the check against the "gl_PerVertex" name as suggested in https://github.com/gfx-rs/wgpu/issues/4915#issuecomment-1926783047. Assuming valid SPIRV, this is technically equivalent to https://github.com/gfx-rs/wgpu/issues/4915#issuecomment-1873701825 because a struct with builtin members [must be decorated as a `Block`](https://github.com/KhronosGroup/SPIRV-Tools/commit/df2aad68b98279412494a6d449bd71b6756e699b) 

Would it be worth adding a test for this? If so, would that go under `naga/tests/in/spv`?

Also, I'm not very familiar with the overall structure of SPIRV nor with the spv frontend for naga. Can parse_function run more than once for a particular input? If so, is it possible that later functions will be using the builtin but we remove the builtin label after not seeing any uses when processing the first function?

**Testing**
I produced a .spv file using the method described in https://github.com/gfx-rs/wgpu/issues/4915 and confirmed that this change removes the error there. I also tested an application using `shaderc` to generate SPIRV for `wgpu` that was seeing this error with certain configurations of `shaderc` and confirmed that the issue was resolved (and that everything seemed to work).

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] ~~`--target wasm32-unknown-unknown`~~
  - [ ] ~~`--target wasm32-unknown-emscripten`~~
- [x] Run `cargo xtask test` to run tests.
  <details><summary>Some failures but they also fail on `trunk`</summary> 
  
  ```
  Summary [   6.158s] 411 tests run: 406 passed (5 flaky), 5 failed, 0 skipped
       FLAKY 2/3 [   0.251s] wgpu-examples [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_examples::hello_compute::tests::compute_1
       FLAKY 2/3 [   0.374s] wgpu-examples [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_examples::hello_compute::tests::compute_overflow
       FLAKY 2/3 [   0.271s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::occlusion_query::occlusion_query
       FLAKY 2/3 [   0.236s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::regression::issue_3457::pass_reset_vertex_buffer
       FLAKY 2/3 [   0.278s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::shader_primitive_index::draw_indexed
      TRY 3 SEGV [   0.727s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::mem_leaks::simple_draw_check_mem_leaks
      TRY 3 SEGV [   0.579s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::regression::issue_3349::multi_stage_data_binding
      TRY 3 SEGV [   0.552s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::scissor_tests::scissor_test_empty_rect
      TRY 3 SEGV [   0.504s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::scissor_tests::scissor_test_empty_rect_with_offset
      TRY 3 SEGV [   0.569s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)/1] wgpu_test::scissor_tests::scissor_test_full_rect
  ```
        
  </details>

- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

Edit:

**Additional changes**

* Removes perVertexStruct naming as requested below https://github.com/gfx-rs/wgpu/pull/5227#issuecomment-1936027091. For reference, this was originally added in https://github.com/gfx-rs/naga/pull/789.
 * Entry point specific code from `parse_function` was extracted and now runs after all functions are parsed. Since this includes the code that does gl_PerVertex builtin culling, we can be sure that any potential access has been registered.

### CODE REVIEW

File: naga/src/front/spv/function.rs [hunk 1]
```diff
@@ -376,34 +376,33 @@ impl<I: Iterator<Item = u32>> super::Frontend<I> {
...
-                                    {
-                                        if !self.gl_per_vertex_builtin_access.contains(&built_in) {
-                                            member.binding = None
-                                        }
+                        if let crate::TypeInner::Struct {
+                            members: ref original_members,
+                            span,
+                        } = ty.inner
+                        {
+                            let mut new_members = None;
```
Comment (Imberflur) [inline naga/src/front/spv/function.rs]: I refactored this a bit so that it only clones the members list if it is going to be modified

**Comment by teoxoy** [comment]
This looks good, could we also take out the block below? I don't think we should be naming things if they don't have a name in the input.

https://github.com/gfx-rs/wgpu/blob/665c075fa01a79859e92b64cfc66b5c42ab20769/naga/src/front/spv/mod.rs#L5130-L5139

**Comment by teoxoy** [comment]
> Would it be worth adding a test for this?

That would be great, thanks!

> If so, would that go under `naga/tests/in/spv`?

Yes.

> Also, I'm not very familiar with the overall structure of SPIRV nor with the spv frontend for naga. Can parse_function run more than once for a particular input?

SPIR-V does support multiple entry points per file but they are not common.

> If so, is it possible that later functions will be using the builtin but we remove the builtin label after not seeing any uses when processing the first function?

This is a good point, we might need to defer the removal.

**Comment by Imberflur** [comment]
> This is a good point, we might need to defer the removal.

This seems to be the case, I was able to get spv-in to remove the builtin from position by moving positing setting out of the main function:
```glsl
#version 450

out gl_PerVertex {
    vec4 gl_Position;
    float gl_ClipDistance[1];
};

void builtin_usage() {
    gl_ClipDistance[0] = 1.0;
    gl_Position = vec4(
        (gl_VertexIndex == 0) ? -4.0 : 1.0,
        (gl_VertexIndex == 2) ? 4.0 : -1.0,
        0.0,
        1.0
    );
}

void main()
{
    builtin_usage();
}
```
```sh
glslc test.vert -o test.spv
cargo r --bin naga test.spv
```
```
Entry point main at Vertex is invalid:
	Vertex shaders must return a `@builtin(position)` output value
```

**Comment by Imberflur** [comment]
> If so, is it possible that later functions will be using the builtin but we remove the builtin label after not seeing any uses when processing the first function?

I'm reading the code further and I realized that this section of code only runs for the entry point function, so the issue is not quite as bad as I make it seem here. It seems like it's only an issue if the entry point itself doesn't access the builtin while another function that the entry point calls does access it.

File: naga/src/front/spv/function.rs [hunk 2]
```diff
@@ -292,278 +292,286 @@ impl<I: Iterator<Item = u32>> super::Frontend<I> {
...
-            let mut function = crate::Function {
-                name: Some(format!("{}_wrap", ep.name)),
-                arguments: Vec::new(),
-                result: None,
-                local_variables: Arena::new(),
-                expressions: Arena::new(),
-                named_expressions: crate::NamedExpressions::default(),
-                body: crate::Block::new(),
-            };
+            self.deferred_entry_points.push((ep, fun_id));
```
Comment (Imberflur) [inline naga/src/front/spv/function.rs:295]: The diff here is a lot more readable with whitespace changes hidden:
image

I extracted the entry point processing from this `if let` block into a separate `process_entry_point` function and then deferred that to be called after all functions are parsed.

File: naga/tests/snapshots.rs [hunk 3]
```diff
@@ -886,6 +886,12 @@ fn convert_spv_all() {
         true,
         Targets::METAL | Targets::GLSL | Targets::HLSL | Targets::WGSL,
     );
+    convert_spv(
+        "unnamed-gl-per-vertex",
+        true,
```
Comment (Imberflur) [inline naga/tests/snapshots.rs:891]: Not sure if the `adjust_coordinate_space` should be `true`, but it might not matter either way for this test case?

File: naga/tests/in/spv/unnamed-gl-per-vertex.spvasm [hunk 4]
```diff
@@ -0,0 +1,72 @@
+;; Make sure that we don't have a validation error due to lacking capabilities
```
Comment (Imberflur) [inline naga/tests/in/spv/unnamed-gl-per-vertex.spvasm:1]: Trying to mimic the existing `.spvasm` files, I manually created this file with `spirv-dis unnamed-gl-per-vertex.spv > unnamed-gl-per-vertex.spvasm` and added some relevant comments in it. I don't know if there are any standard practices for adding naga tests here that I might have missed.

**Review by Imberflur — COMMENTED** [review]
Notes for additional context

**Comment by Imberflur** [comment]
> > Would it be worth adding a test for this?
>
> That would be great, thanks!

Added input spv to test for the original issue as well as another to test for the case of builtin's being accessed in a function parsed after the entry point.

>  This is a good point, we might need to defer the removal.

I ended up finding a way to defer this by postponing the entry point related processing to be after all function parsing. If this change is too much for this PR I can move it into a separate one.

> This looks good, could we also take out the block below? I don't think we should be naming things if they don't have a name in the input.

Removed this block.

File: naga/tests/snapshots.rs (hunk 3 above)
Comment (teoxoy) [reply naga/tests/snapshots.rs:891]: Yeah, I think any value should be fine.

File: naga/tests/in/spv/unnamed-gl-per-vertex.spvasm (hunk 4 above)
Comment (teoxoy) [reply naga/tests/in/spv/unnamed-gl-per-vertex.spvasm:1]: The tests look great, thanks for adding the comments as well!

**Review by teoxoy — APPROVED** [review]
Great stuff, thanks!

**Comment by teoxoy** [comment]
One last thing, I would like to "rebase and merge" this PR instead of squashing it. Could you include the changes in the last commit ("[fix typo](https://github.com/gfx-rs/wgpu/pull/5227/commits/4e346622a04df3297df4e39e7693336d5fc52611)") in the appropriate commits that introduced those?

**Comment by Imberflur** [comment]
> One last thing, I would like to "rebase and merge" this PR instead of squashing it. Could you include the changes in the last commit ("[fix typo](https://github.com/gfx-rs/wgpu/pull/5227/commits/4e346622a04df3297df4e39e7693336d5fc52611)") in the appropriate commits that introduced those?

done
