### PR TITLE
Polyfill unpackUnorm4x8 and friends on unsupported GLSL versions

### LINKED ISSUE #4525: [wgsl-in] 'unpackUnorm4x8' : no matching overloaded function found
Hi!

On wgpu 0.13 (naga 0.9), I receive the following panic message:

```
panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in VERTEX shader: ERROR: 0:52: 'unpackUnorm4x8' : no matching overloaded function found
ERROR: 0:52: '=' : dimension mismatch
ERROR: 0:52: 'assign' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'


'
```

Here's the offending code:

```rust
struct Output {
    @builtin(position)
    pos: vec4<f32>,
    @location(0) @interpolate(flat)
    flags: u32,
    @location(1) @interpolate(perspective, center)
    color: vec4<f32>,
    @location(2) @interpolate(perspective, center)
    tex_pos: vec2<f32>,
    @location(3) @interpolate(flat)
    pal_pos: vec2<u32>,
    @location(4) @interpolate(flat)
    tex_page_x: u32
}

fn make_tex_coord(coord: u32, max: f32) -> f32 {
    return f32(coord) / max;
}

fn make_tex_pos(pos: vec2<u32>, bounds: vec2<f32>) -> vec2<f32> {
    return vec2<f32>(
        make_tex_coord(pos.x, bounds.x),
        make_tex_coord(pos.y, bounds.y),
    );
}

fn make_ndc(coord: u32, max: f32) -> f32 {
    return (2.0 * make_tex_coord(coord, max)) - 1.0;
}

@vertex
fn main(
    @location(0) pos: vec2<u32>,
    @location(1) packed: vec2<u32>,
    @location(2) color: u32,
    @location(3) tex_pos: vec2<u32>,
    @location(4) pal_pos: vec2<u32>,
) -> Output {
    let vram_bounds = vec2<f32>(1024.0, 512.0);

    var out: Output;
    out.pos = vec4<f32>(
        // [0, 1024) -> [-1.0, 1.0].
        make_ndc(pos.x, vram_bounds.x),
        // [0, 512)  -> [-1.0, 1.0].
        make_ndc(pos.y, vram_bounds.y) * -1.0,
        0.0,
        1.0,
    );
    out.flags = packed.x;
    out.color = unpack4x8unorm(color);
    out.tex_pos = vec2<f32>(tex_pos);
    out.pal_pos = pal_pos;
    out.tex_page_x = packed.y;
    return out;
}
```

...of which line 52 is `out.tex_pos = vec2<f32>(tex_pos);`. That doesn't seem to be where the error is, though. (One-off bug?) Line 51 reads `out.color = unpack4x8unorm(color);`, which is where I think the error arises. I think my code is correct according to the spec, though; `color` is a `u32`, and `out.color` is a `vec4<f32>`, which matches [the `unpack4x8unorm` function signature](https://www.w3.org/TR/WGSL/#unpack4x8unorm-builtin).

For what it's worth, my shader code was previously validated correctly on wgpu 0.12 (naga 0.8).

### PR DESCRIPTION
**Pull request by DJMcNab**
**Connections**
Part of #4525 (other methods might be in scope, including stuff like `bitfieldExtract`, etc.)
See also https://github.com/linebender/vello/issues/876

**Description**
Adds a polyfill for the naga MathFunctions on the GLSL backend, when needed:
- `Unpack4x8snorm`
- `Unpack4x8unorm`
- `Unpack2x16snorm`
- `Unpack2x16unorm`

Also adds errors for:
- `Pack4x8snorm`
- `Pack4x8unorm`
- `Pack2x16snorm`
- `Pack2x16unorm`
- `Pack2x16float`
- `Unpack2x16float`

when those aren't actually supported by the backend. Those could also be polyfilled, but I don't need them, and so suggest that someone else do so.
There are still an awful lot of other functions which aren't supported, as can be seen in the commented out lines in the new tests.

**Testing**
Added "downlevel" web and desktop tests for these operations.
Also validated by removing the polyfill in https://github.com/linebender/vello/pull/872

**Squash or Rebase?**

Requires squashing, as the first commit adds failing tests

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`. N/A
- [x] Run `cargo clippy --tests`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] If this contains user-facing changes, add a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/back/glsl/mod.rs [hunk 1]
```diff
@@ -230,6 +230,31 @@ impl Version {
...
+    fn supports_pack_unpack_4x8(&self) -> bool {
+        *self >= Version::Desktop(400) || *self >= Version::new_gles(310)
+    }
+    fn supports_pack_unpack_snorm_2x16(&self) -> bool {
+        *self >= Version::Desktop(420) || *self >= Version::new_gles(310)
+    }
+    fn supports_pack_unpack_unorm_2x16(&self) -> bool {
+        // Same as `supports_pack_unpack_4x8`; different method for clarity in usage.
+        *self >= Version::Desktop(400) || *self >= Version::new_gles(310)
+    }
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs]: This and the one above are available in es 300.

File: naga/src/back/glsl/mod.rs [hunk 2]
```diff
@@ -1369,6 +1394,31 @@ impl<'a, W: Write> Writer<'a, W> {
...
+                    /* crate::MathFunction::Pack4x8unorm | */
+                    crate::MathFunction::Unpack4x8snorm
+                        if !self.options.version.supports_pack_unpack_4x8() =>
+                    {
+                        // We have a fallback if the platform doesn't natively support these
+                        self.need_bake_expressions.insert(arg);
+                    }
+                    /* crate::MathFunction::Pack2x16float | */
+                    crate::MathFunction::Unpack2x16float
+                        if !self.options.version.supports_pack_unpack_half_2x16() =>
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs]:
```suggestion
                    /* crate::MathFunction::Pack4x8unorm | */
                    crate::MathFunction::Unpack4x8unorm
                        if !self.options.version.supports_pack_unpack_4x8() =>
```

File: naga/src/back/glsl/mod.rs [hunk 3]
```diff
@@ -3756,11 +3806,37 @@ impl<'a, W: Write> Writer<'a, W> {
                     Mf::FirstTrailingBit => "findLSB",
                     Mf::FirstLeadingBit => "findMSB",
                     // data packing
-                    Mf::Pack4x8snorm => "packSnorm4x8",
-                    Mf::Pack4x8unorm => "packUnorm4x8",
-                    Mf::Pack2x16snorm => "packSnorm2x16",
-                    Mf::Pack2x16unorm => "packUnorm2x16",
-                    Mf::Pack2x16float => "packHalf2x16",
+                    Mf::Pack4x8snorm if self.options.version.supports_pack_unpack_4x8() => {
```
Comment (teoxoy) [inline naga/src/back/glsl/mod.rs]: Please match the variants once and move the `if`s inside each block, this is the existing style and I find it easier to read.

**Review by teoxoy — CHANGES_REQUESTED** [review]

File: naga/src/back/glsl/mod.rs (hunk 1 above)
Comment (DJMcNab) [reply naga/src/back/glsl/mod.rs]: Thanks! I'm glad I put the links in place so I could easily check. I'm not sure how I managed to get this wrong!

**Review by teoxoy — APPROVED** [review]
Looks good, thank you!
