### PR TITLE
Disallow taking the address of a vector component

### LINKED ISSUE #7271: Taking the address of a vector component should not be allowed
The spec states (https://gpuweb.github.io/gpuweb/wgsl/#address-of-expr):

> It is a shader-creation error if _r_ is a reference to a vector component.

In [naga#2451](https://github.com/gfx-rs/naga/pull/2451), which was a (never merged) fix for #4541, the concern was raised that passing pointers to vector components doesn't work in Metal and might need to be emulated. But if I am understanding the spec correctly, it should not be supported at all.

I would assume that the same treatment should apply to matrices. ~Tint appears to do so,~ but I don't see it stated explicitly in the spec. Edit: I must have messed something up or misinterpreted when I tested Tint's treatment of matrices before. Taking the address of a matrix column is allowed. Taking the address of a matrix element is disallowed, but that's implied by the vector component restriction.

The test case in #4541 is about pointers to array elements, that issue remains.

### PR DESCRIPTION
**Pull request by andyleiserson**
**Connections**
Fixes #7271

**Description**
The spec states that taking the address of a vector component is not allowed. This change rejects it (and also taking the address of a matrix component) in the WGSL front-end.

**Testing**
Added a test in wgsl_errors.

**Squash or Rebase?** Squash

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
- [x] Run `cargo xtask test` to run tests.
- [x] Added a `CHANGELOG.md` entry.

### CODE REVIEW

File: naga/src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -521,6 +521,16 @@ impl<'source, 'temp, 'out> ExpressionContext<'source, 'temp, 'out> {
         }
     }
 
+    fn get(&self, handle: Handle<crate::Expression>) -> &crate::Expression {
```
Comment (andyleiserson) [inline naga/src/front/wgsl/lower/mod.rs]: I'm not sure about this. Is this kind of direct access to the expressions something that was intentionally avoided, or was it just not needed before?

**Comment by ErichDonGubler** [comment]
> I am not sure what the threshold is for noting something in the changelog. This change rejects code that was previously accepted, does that qualify?

Yes please!

**Comment by andyleiserson** [comment]
A question here is whether the project is at a stage where a deprecation cycle is needed for things like this. Or maybe we could have a "strict WGSL" flag that applications can set depending on their individual preference for spec correctness at the cost of potential breakage.

**Comment by cwfitzgerald** [comment]
We're not really there yet, we just break things as needed.

File: naga/src/front/wgsl/lower/mod.rs [hunk 2]
```diff
@@ -2152,27 +2177,10 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
-                                ..
-                            } => {
-                                temp_inner = crate::TypeInner::Vector { size, scalar };
-                                &temp_inner
-                            }
-                            _ => unreachable!(
-                                "In Typed::Reference(handle), handle must be a Naga pointer"
-                            ),
-                        }
+                        temp_inner = resolve_inner!(ctx, handle)
```
Comment (teoxoy) [inline naga/src/front/wgsl/lower/mod.rs]: The name of the variable is now misleading as it's no longer `TypeInner`.

File: naga/src/front/wgsl/lower/mod.rs [hunk 3]
```diff
@@ -2077,6 +2087,21 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
                 // reference is required, the Load Rule is not applied.
                 match self.expression_for_reference(expr, ctx)? {
                     Typed::Reference(handle) => {
+                        if let &crate::Expression::Access { base, .. }
+                        | &crate::Expression::AccessIndex { base, .. } = ctx.get(handle)
+                        {
+                            if let Some(ty) = resolve_inner!(ctx, base).pointer_base_type() {
+                                if matches!(
+                                    *ty.inner_with(&ctx.module.types),
+                                    crate::TypeInner::Matrix { .. }
```
Comment (teoxoy) [inline naga/src/front/wgsl/lower/mod.rs]: I don't think this should apply to matrices. I don't know why Tint is also restricting matrices, the only mention of matrices in the spec discussion is:

> We have to determine what to do with matrices (which may or may not match what we're doing with vectors)

_from https://github.com/gpuweb/gpuweb/issues/1931#issuecomment-935180135_

Since it's not mentioned again, I assume someone checked and they were fine.

@jrprice did you guys find issues with matrices? If so, we should add the restriction to the spec.

**Review by teoxoy — CHANGES_REQUESTED** [review]

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (teoxoy) [reply naga/src/front/wgsl/lower/mod.rs]: I think it's a bit of both: It's easy to pass a `Handle` from an arena and try to index a different arena with it. It's also usually not necessary to have this since we usually know which arena to index.

Comment (teoxoy) [reply naga/src/front/wgsl/lower/mod.rs]: In this case, `self.expr_type` is always going to be `ExpressionContextType::Runtime` but if you think it's worth keeping the new method around, I'm not opposed to that.

File: naga/src/front/wgsl/lower/mod.rs (hunk 3 above)
Comment (jrprice) [reply naga/src/front/wgsl/lower/mod.rs]: Taking the address of a matrix component requires you to take the address of a vector component, since you have to go through a column vector to get there. So this case would also be covered by the existing WGSL spec restriction.

Comment (teoxoy) [reply naga/src/front/wgsl/lower/mod.rs]: That makes sense, I thought @andyleiserson meant that you couldn't take the address of a matrix component (a matrix component being a vector) at all (which is what the code in question is checking).

File: naga/src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (andyleiserson) [reply naga/src/front/wgsl/lower/mod.rs]: At the time I wrote it, I didn't appreciate that we could look it up directly via the runtime context. That does seem simpler, so I changed it to do that.

File: naga/src/front/wgsl/lower/mod.rs (hunk 3 above)
Comment (andyleiserson) [reply naga/src/front/wgsl/lower/mod.rs]: I must have messed something up when I was looking at the treatment of matrices before, maybe I wasn't careful enough to distinguish address-of-column from address-of-element.

In any case, I've changed it to disallow address-of vector component only.

**Review by teoxoy — APPROVED** [review]
LGTM
